In [1]:
from workspace.sources.local_datasets.preprocessing.tokenization import NLTKTokenizer
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction, Lemmatization, Stemming
from workspace.sources.local_datasets.preprocessing.encoders.encoders import BertBaseUncasedEncoder
from workspace.sources.experiments.metrics import Loss
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.models.transformers.bert_based_models import BERT
from workspace.sources.local_datasets.preprocessing.utils import truncate
from sklearn.model_selection import ParameterGrid
import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [2]:
experiment_name = 'prefinal-bert-base-uncased-v2'

In [4]:
def conduct_model_experiments(dataset_name,
                              dataset_path,
                              dataset_params_grid,
                              model_hparams_grid):
    for dataset_params in dataset_params_grid:
        for model_hparams in model_hparams_grid:
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = BERT(train_best_model_metric=Loss,
                         training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            recovery_experiment.run()

In [7]:
pipelines = [PreprocessingPipeline(name='minimal',
                                   iterable=[BertBaseUncasedEncoder()]),
             PreprocessingPipeline(name='noise_reduction',
                                   iterable=[NoiseReduction(),
                                             BertBaseUncasedEncoder()]),
             PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                   iterable=[NoiseReduction(), NLTKTokenizer(), Lemmatization(),
                                             BertBaseUncasedEncoder()]),
             PreprocessingPipeline(name='noise_reduction_with_stemming',
                                   iterable=[NoiseReduction(), NLTKTokenizer(), Stemming(),
                                             BertBaseUncasedEncoder()])
             ]
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(pipelines, fraction=0.05)

dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': pipelines})

print('Dataset Hyperparameters Grid Size: ', len(dataset_hparams_grid))

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16],
                                    'learning_rate': [1e-05, 5e-05],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [0.0, 1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})

print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(dataset_params_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  4
Total Hyperparameter Combinations:  16

### ReCOVery Dataset

In [ ]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_grid,
                          dataset_params_grid)

### EUvsDisinfo Dataset

In [ ]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

### ISOT Dataset

In [13]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

2025-05-14 17:15:51,348 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 17:15:51,349 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01)
2025-05-14 17:15:51,350 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:15:51,351 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:15:52,209 - Experiment - INFO - Run ID: 373bf99bb79c41adacac8934cb0dcea5
2025-05-14 17:15:52,209 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-15-52;rs=3086548351
2025-05-14 17:15:52,226 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:15:52,251 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:15:52,614 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8477E90>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A8BE0AA0>]>
2025-05-14 17:15:52,857 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:15:52,858 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:15:52,859 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:15:52,908 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:15:52,911 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:15:52,923 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:15:52,923 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:15:53,104 - Experiment - INFO - Preprocessing function 1: bert_base_uncased_encoder
2025-05-14 17:15:53,104 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:15:53,104 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:15:58,246 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:15:58,247 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:15:59,396 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:15:59,398 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:16:05,756 - Experiment - INFO - Model name: bert-base-uncased
2025-05-14 17:16:05,761 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 17:26:44,558 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 17:26:44,560 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 17:26:44,961 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.05934305489063263, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9873417721518988, 'eval_recall': 1.0, 'eval_f1_score': 0.9936305732484076, 'eval_roc_auc': 0.9897074756229686, 'eval_false_positives_rate': 0.014084507042253521, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 5.1453, 'eval_samples_per_second': 28.958, 'eval_steps_per_second': 3.693, 'epoch': 4.0, 'step': 352}
2025-05-14 17:26:44,962 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:26:50,163 - Experiment - INFO - Test metrics: {'test_loss': 0.22373878955841064, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9620253164556962, 'test_recall': 0.9743589743589743, 'test_f1_score': 0.9681528662420382, 'test_roc_auc': 0.9888710826210826, 'test_false_positives_rate': 0.041666666666666664, 'test_false_negatives_rate': 0.02564102564102564, 'test_runtime': 5.1954, 'test_samples_per_second': 28.872, 'test_steps_per_second': 3.657, 'test_epoch': 4.0}
2025-05-14 17:26:50,189 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:26:50,194 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:26:51,070 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:26:51,071 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 17:26:51,073 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 17:26:51,689 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.05934305489063263, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9873417721518988, 'eval_recall': 1.0, 'eval_f1_score': 0.9936305732484076, 'eval_roc_auc': 0.9897074756229686, 'eval_false_positives_rate': 0.014084507042253521, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 5.1453, 'eval_samples_per_second': 28.958, 'eval_steps_per_second': 3.693, 'epoch': 4.0, 'step': 352}
2025-05-14 17:26:51,690 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:26:56,859 - Experiment - INFO - Test metrics: {'test_loss': 0.22373878955841064, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9620253164556962, 'test_recall': 0.9743589743589743, 'test_f1_score': 0.9681528662420382, 'test_roc_auc': 0.9888710826210826, 'test_false_positives_rate': 0.041666666666666664, 'test_false_negatives_rate': 0.02564102564102564, 'test_runtime': 5.1634, 'test_samples_per_second': 29.051, 'test_steps_per_second': 3.68, 'test_epoch': 4.0}
2025-05-14 17:26:56,903 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:26:56,910 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:26:57,484 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:26:57,485 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 17:26:57,487 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 17:26:57,924 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.05934305489063263, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9873417721518988, 'eval_recall': 1.0, 'eval_f1_score': 0.9936305732484076, 'eval_roc_auc': 0.9897074756229686, 'eval_false_positives_rate': 0.014084507042253521, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 5.1453, 'eval_samples_per_second': 28.958, 'eval_steps_per_second': 3.693, 'epoch': 4.0, 'step': 352}
2025-05-14 17:26:57,925 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:27:03,103 - Experiment - INFO - Test metrics: {'test_loss': 0.22373878955841064, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9620253164556962, 'test_recall': 0.9743589743589743, 'test_f1_score': 0.9681528662420382, 'test_roc_auc': 0.9888710826210826, 'test_false_positives_rate': 0.041666666666666664, 'test_false_negatives_rate': 0.02564102564102564, 'test_runtime': 5.173, 'test_samples_per_second': 28.997, 'test_steps_per_second': 3.673, 'test_epoch': 4.0}
2025-05-14 17:27:03,131 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:27:03,137 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:27:03,631 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:27:03,632 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 17:27:03,634 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-264
2025-05-14 17:27:04,184 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.06944949924945831, 'eval_accuracy': 0.9865771812080537, 'eval_precision': 0.975, 'eval_recall': 1.0, 'eval_f1_score': 0.9873417721518988, 'eval_roc_auc': 0.9953051643192489, 'eval_false_positives_rate': 0.028169014084507043, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 5.205, 'eval_samples_per_second': 28.626, 'eval_steps_per_second': 3.65, 'epoch': 3.0, 'step': 264}
2025-05-14 17:27:04,185 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 17:27:09,452 - Experiment - INFO - Test metrics: {'test_loss': 0.21118049323558807, 'test_accuracy': 0.96, 'test_precision': 0.95, 'test_recall': 0.9743589743589743, 'test_f1_score': 0.9620253164556962, 'test_roc_auc': 0.988960113960114, 'test_false_positives_rate': 0.05555555555555555, 'test_false_negatives_rate': 0.02564102564102564, 'test_runtime': 5.2606, 'test_samples_per_second': 28.514, 'test_steps_per_second': 3.612, 'test_epoch': 3.0}
2025-05-14 17:27:09,474 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:27:09,480 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:27:10,176 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:27:10,178 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 17:27:10,178 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 17:27:10,679 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.05934305489063263, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9873417721518988, 'eval_recall': 1.0, 'eval_f1_score': 0.9936305732484076, 'eval_roc_auc': 0.9897074756229686, 'eval_false_positives_rate': 0.014084507042253521, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 5.1453, 'eval_samples_per_second': 28.958, 'eval_steps_per_second': 3.693, 'epoch': 4.0, 'step': 352}
2025-05-14 17:27:10,680 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:27:15,862 - Experiment - INFO - Test metrics: {'test_loss': 0.22373878955841064, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9620253164556962, 'test_recall': 0.9743589743589743, 'test_f1_score': 0.9681528662420382, 'test_roc_auc': 0.9888710826210826, 'test_false_positives_rate': 0.041666666666666664, 'test_false_negatives_rate': 0.02564102564102564, 'test_runtime': 5.1757, 'test_samples_per_second': 28.982, 'test_steps_per_second': 3.671, 'test_epoch': 4.0}
2025-05-14 17:27:15,893 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:27:15,899 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:27:16,309 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:27:16,311 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 17:27:17,018 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 17:27:17,018 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.01)
2025-05-14 17:27:17,019 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:27:17,019 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:27:18,218 - Experiment - INFO - Run ID: b8394529e8c543f8bec658e227cabe4a
2025-05-14 17:27:18,218 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-27-18;rs=3689455455
2025-05-14 17:27:18,229 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:27:18,253 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:27:18,604 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8477E90>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A8BE0AA0>]>
2025-05-14 17:27:18,833 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:27:18,834 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:27:18,835 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:27:18,887 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:27:18,889 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:27:18,911 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:27:18,912 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:27:19,137 - Experiment - INFO - Preprocessing function 1: bert_base_uncased_encoder
2025-05-14 17:27:19,138 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:27:19,139 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:27:25,304 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:27:25,305 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:27:26,472 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:27:26,473 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:27:32,727 - Experiment - INFO - Model name: bert-base-uncased
2025-05-14 17:27:32,733 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 17:38:07,084 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 17:38:07,087 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 17:38:07,829 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.16493073105812073, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.9879518072289156, 'eval_recall': 0.9761904761904762, 'eval_f1_score': 0.9820359281437125, 'eval_roc_auc': 0.9869963369963369, 'eval_false_positives_rate': 0.015384615384615385, 'eval_false_negatives_rate': 0.023809523809523808, 'eval_runtime': 5.0812, 'eval_samples_per_second': 29.324, 'eval_steps_per_second': 3.739, 'epoch': 4.0, 'step': 352}
2025-05-14 17:38:07,832 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:38:13,001 - Experiment - INFO - Test metrics: {'test_loss': 0.12289915978908539, 'test_accuracy': 0.98, 'test_precision': 0.974025974025974, 'test_recall': 0.9868421052631579, 'test_f1_score': 0.9803921568627451, 'test_roc_auc': 0.9886201991465149, 'test_false_positives_rate': 0.02702702702702703, 'test_false_negatives_rate': 0.013157894736842105, 'test_runtime': 5.1628, 'test_samples_per_second': 29.054, 'test_steps_per_second': 3.68, 'test_epoch': 4.0}
2025-05-14 17:38:13,025 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:38:13,030 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:38:13,451 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:38:13,451 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 17:38:13,451 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 17:38:13,916 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.16493073105812073, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.9879518072289156, 'eval_recall': 0.9761904761904762, 'eval_f1_score': 0.9820359281437125, 'eval_roc_auc': 0.9869963369963369, 'eval_false_positives_rate': 0.015384615384615385, 'eval_false_negatives_rate': 0.023809523809523808, 'eval_runtime': 5.0812, 'eval_samples_per_second': 29.324, 'eval_steps_per_second': 3.739, 'epoch': 4.0, 'step': 352}
2025-05-14 17:38:13,916 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:38:19,156 - Experiment - INFO - Test metrics: {'test_loss': 0.12289915978908539, 'test_accuracy': 0.98, 'test_precision': 0.974025974025974, 'test_recall': 0.9868421052631579, 'test_f1_score': 0.9803921568627451, 'test_roc_auc': 0.9886201991465149, 'test_false_positives_rate': 0.02702702702702703, 'test_false_negatives_rate': 0.013157894736842105, 'test_runtime': 5.2376, 'test_samples_per_second': 28.639, 'test_steps_per_second': 3.628, 'test_epoch': 4.0}
2025-05-14 17:38:19,186 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:38:19,193 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:38:19,642 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:38:19,643 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 17:38:19,645 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 17:38:20,094 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.16493073105812073, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.9879518072289156, 'eval_recall': 0.9761904761904762, 'eval_f1_score': 0.9820359281437125, 'eval_roc_auc': 0.9869963369963369, 'eval_false_positives_rate': 0.015384615384615385, 'eval_false_negatives_rate': 0.023809523809523808, 'eval_runtime': 5.0812, 'eval_samples_per_second': 29.324, 'eval_steps_per_second': 3.739, 'epoch': 4.0, 'step': 352}
2025-05-14 17:38:20,096 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:38:25,307 - Experiment - INFO - Test metrics: {'test_loss': 0.12289915978908539, 'test_accuracy': 0.98, 'test_precision': 0.974025974025974, 'test_recall': 0.9868421052631579, 'test_f1_score': 0.9803921568627451, 'test_roc_auc': 0.9886201991465149, 'test_false_positives_rate': 0.02702702702702703, 'test_false_negatives_rate': 0.013157894736842105, 'test_runtime': 5.2057, 'test_samples_per_second': 28.815, 'test_steps_per_second': 3.65, 'test_epoch': 4.0}
2025-05-14 17:38:25,332 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:38:25,336 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:38:25,913 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:38:25,913 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 17:38:25,913 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-616
2025-05-14 17:38:26,429 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.18110191822052002, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.9879518072289156, 'eval_recall': 0.9761904761904762, 'eval_f1_score': 0.9820359281437125, 'eval_roc_auc': 0.9890109890109889, 'eval_false_positives_rate': 0.015384615384615385, 'eval_false_negatives_rate': 0.023809523809523808, 'eval_runtime': 5.1396, 'eval_samples_per_second': 28.991, 'eval_steps_per_second': 3.697, 'epoch': 7.0, 'step': 616}
2025-05-14 17:38:26,429 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 17:38:31,558 - Experiment - INFO - Test metrics: {'test_loss': 0.1710508018732071, 'test_accuracy': 0.98, 'test_precision': 0.974025974025974, 'test_recall': 0.9868421052631579, 'test_f1_score': 0.9803921568627451, 'test_roc_auc': 0.9902204836415364, 'test_false_positives_rate': 0.02702702702702703, 'test_false_negatives_rate': 0.013157894736842105, 'test_runtime': 5.1155, 'test_samples_per_second': 29.323, 'test_steps_per_second': 3.714, 'test_epoch': 7.0}
2025-05-14 17:38:31,585 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:38:31,590 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:38:32,016 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:38:32,017 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 17:38:32,018 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 17:38:32,600 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.16493073105812073, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.9879518072289156, 'eval_recall': 0.9761904761904762, 'eval_f1_score': 0.9820359281437125, 'eval_roc_auc': 0.9869963369963369, 'eval_false_positives_rate': 0.015384615384615385, 'eval_false_negatives_rate': 0.023809523809523808, 'eval_runtime': 5.0812, 'eval_samples_per_second': 29.324, 'eval_steps_per_second': 3.739, 'epoch': 4.0, 'step': 352}
2025-05-14 17:38:32,602 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:38:37,731 - Experiment - INFO - Test metrics: {'test_loss': 0.12289915978908539, 'test_accuracy': 0.98, 'test_precision': 0.974025974025974, 'test_recall': 0.9868421052631579, 'test_f1_score': 0.9803921568627451, 'test_roc_auc': 0.9886201991465149, 'test_false_positives_rate': 0.02702702702702703, 'test_false_negatives_rate': 0.013157894736842105, 'test_runtime': 5.1244, 'test_samples_per_second': 29.272, 'test_steps_per_second': 3.708, 'test_epoch': 4.0}
2025-05-14 17:38:37,763 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:38:37,770 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:38:38,510 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:38:38,511 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 17:38:39,323 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 17:38:39,323 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01)
2025-05-14 17:38:39,323 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:38:39,323 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:38:40,219 - Experiment - INFO - Run ID: 743e1054e172408ea0466b0aa1a1947f
2025-05-14 17:38:40,219 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-38-40;rs=922503857
2025-05-14 17:38:40,230 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:38:40,258 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:38:40,595 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8BE0050>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000234A85C8860>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A83E15B0>]>
2025-05-14 17:38:40,791 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:38:40,791 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:38:40,791 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:38:40,845 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:38:40,846 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:38:40,862 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:38:40,863 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:38:40,879 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 17:38:40,880 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:38:40,880 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:38:41,105 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:38:41,107 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:38:41,157 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:38:41,158 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:38:41,378 - Experiment - INFO - Preprocessing function 2: bert_base_uncased_encoder
2025-05-14 17:38:41,379 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:38:41,380 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:38:46,405 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:38:46,406 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:38:47,615 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:38:47,617 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:38:54,212 - Experiment - INFO - Model name: bert-base-uncased
2025-05-14 17:38:54,216 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 18:00:47,431 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 18:00:47,432 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 18:00:47,879 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6580565571784973, 'eval_accuracy': 0.5838926174496645, 'eval_precision': 1.0, 'eval_recall': 0.10144927536231885, 'eval_f1_score': 0.18421052631578946, 'eval_roc_auc': 0.9113224637681159, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.8985507246376812, 'eval_runtime': 4.9626, 'eval_samples_per_second': 30.025, 'eval_steps_per_second': 3.829, 'epoch': 2.0, 'step': 176}
2025-05-14 18:00:47,880 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 18:00:52,812 - Experiment - INFO - Test metrics: {'test_loss': 0.6846456527709961, 'test_accuracy': 0.5666666666666667, 'test_precision': 1.0, 'test_recall': 0.015151515151515152, 'test_f1_score': 0.029850746268656716, 'test_roc_auc': 0.8732864357864357, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.9848484848484849, 'test_runtime': 4.9264, 'test_samples_per_second': 30.448, 'test_steps_per_second': 3.857, 'test_epoch': 2.0}
2025-05-14 18:00:52,844 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:00:52,852 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:00:53,818 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:00:53,820 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 18:00:53,821 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-616
2025-05-14 18:00:54,618 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.07372765988111496, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.9583333333333334, 'eval_recall': 1.0, 'eval_f1_score': 0.9787234042553191, 'eval_roc_auc': 0.9989130434782609, 'eval_false_positives_rate': 0.0375, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 4.8582, 'eval_samples_per_second': 30.67, 'eval_steps_per_second': 3.911, 'epoch': 7.0, 'step': 616}
2025-05-14 18:00:54,620 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 18:00:59,536 - Experiment - INFO - Test metrics: {'test_loss': 0.2123340368270874, 'test_accuracy': 0.9533333333333334, 'test_precision': 0.9402985074626866, 'test_recall': 0.9545454545454546, 'test_f1_score': 0.9473684210526315, 'test_roc_auc': 0.9891774891774892, 'test_false_positives_rate': 0.047619047619047616, 'test_false_negatives_rate': 0.045454545454545456, 'test_runtime': 4.9052, 'test_samples_per_second': 30.579, 'test_steps_per_second': 3.873, 'test_epoch': 7.0}
2025-05-14 18:00:59,567 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:00:59,574 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:01:00,119 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:01:00,120 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 18:01:00,121 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 18:01:00,745 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6580565571784973, 'eval_accuracy': 0.5838926174496645, 'eval_precision': 1.0, 'eval_recall': 0.10144927536231885, 'eval_f1_score': 0.18421052631578946, 'eval_roc_auc': 0.9113224637681159, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.8985507246376812, 'eval_runtime': 4.9626, 'eval_samples_per_second': 30.025, 'eval_steps_per_second': 3.829, 'epoch': 2.0, 'step': 176}
2025-05-14 18:01:00,747 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 18:01:05,676 - Experiment - INFO - Test metrics: {'test_loss': 0.6846456527709961, 'test_accuracy': 0.5666666666666667, 'test_precision': 1.0, 'test_recall': 0.015151515151515152, 'test_f1_score': 0.029850746268656716, 'test_roc_auc': 0.8732864357864357, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.9848484848484849, 'test_runtime': 4.9201, 'test_samples_per_second': 30.487, 'test_steps_per_second': 3.862, 'test_epoch': 2.0}
2025-05-14 18:01:05,713 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:01:05,721 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:01:06,593 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:01:06,594 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 18:01:06,595 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-792
2025-05-14 18:01:07,257 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.09619065374135971, 'eval_accuracy': 0.9664429530201343, 'eval_precision': 0.9324324324324325, 'eval_recall': 1.0, 'eval_f1_score': 0.965034965034965, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0625, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 4.817, 'eval_samples_per_second': 30.932, 'eval_steps_per_second': 3.944, 'epoch': 9.0, 'step': 792}
2025-05-14 18:01:07,259 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-14 18:01:12,139 - Experiment - INFO - Test metrics: {'test_loss': 0.2202991247177124, 'test_accuracy': 0.9533333333333334, 'test_precision': 0.927536231884058, 'test_recall': 0.9696969696969697, 'test_f1_score': 0.9481481481481482, 'test_roc_auc': 0.9797077922077921, 'test_false_positives_rate': 0.05952380952380952, 'test_false_negatives_rate': 0.030303030303030304, 'test_runtime': 4.8725, 'test_samples_per_second': 30.785, 'test_steps_per_second': 3.899, 'test_epoch': 9.0}
2025-05-14 18:01:12,173 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:01:12,182 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:01:12,757 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:01:12,759 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 18:01:12,761 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-616
2025-05-14 18:01:13,366 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.07372765988111496, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.9583333333333334, 'eval_recall': 1.0, 'eval_f1_score': 0.9787234042553191, 'eval_roc_auc': 0.9989130434782609, 'eval_false_positives_rate': 0.0375, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 4.8582, 'eval_samples_per_second': 30.67, 'eval_steps_per_second': 3.911, 'epoch': 7.0, 'step': 616}
2025-05-14 18:01:13,368 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 18:01:18,268 - Experiment - INFO - Test metrics: {'test_loss': 0.2123340368270874, 'test_accuracy': 0.9533333333333334, 'test_precision': 0.9402985074626866, 'test_recall': 0.9545454545454546, 'test_f1_score': 0.9473684210526315, 'test_roc_auc': 0.9891774891774892, 'test_false_positives_rate': 0.047619047619047616, 'test_false_negatives_rate': 0.045454545454545456, 'test_runtime': 4.8907, 'test_samples_per_second': 30.67, 'test_steps_per_second': 3.885, 'test_epoch': 7.0}
2025-05-14 18:01:18,301 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:01:18,307 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:01:19,041 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:01:19,043 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 18:01:19,962 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 18:01:19,964 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.01)
2025-05-14 18:01:19,965 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 18:01:19,966 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 18:01:21,690 - Experiment - INFO - Run ID: 5ab18520410c4e7ab95591ee9e6eff63
2025-05-14 18:01:21,691 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_18-01-21;rs=2228617686
2025-05-14 18:01:21,703 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 18:01:21,732 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 18:01:22,070 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8BE0050>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000234A85C8860>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A83E15B0>]>
2025-05-14 18:01:22,386 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 18:01:22,388 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 18:01:22,390 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 18:01:22,450 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 18:01:22,452 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 18:01:22,480 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 18:01:22,481 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 18:01:22,504 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 18:01:22,505 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 18:01:22,507 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 18:01:22,767 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 18:01:22,769 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 18:01:22,864 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 18:01:22,865 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 18:01:23,149 - Experiment - INFO - Preprocessing function 2: bert_base_uncased_encoder
2025-05-14 18:01:23,150 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 18:01:23,152 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 18:01:30,394 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 18:01:30,396 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 18:01:31,927 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 18:01:31,928 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 18:01:41,194 - Experiment - INFO - Model name: bert-base-uncased
2025-05-14 18:01:41,199 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 18:18:16,816 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 18:18:16,816 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 18:18:17,281 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3094053566455841, 'eval_accuracy': 0.959731543624161, 'eval_precision': 0.9866666666666667, 'eval_recall': 0.9367088607594937, 'eval_f1_score': 0.961038961038961, 'eval_roc_auc': 0.9909584086799277, 'eval_false_positives_rate': 0.014285714285714285, 'eval_false_negatives_rate': 0.06329113924050633, 'eval_runtime': 4.8577, 'eval_samples_per_second': 30.673, 'eval_steps_per_second': 3.911, 'epoch': 4.0, 'step': 352}
2025-05-14 18:18:17,281 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 18:18:22,148 - Experiment - INFO - Test metrics: {'test_loss': 0.266695499420166, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9857142857142858, 'test_recall': 0.9452054794520548, 'test_f1_score': 0.965034965034965, 'test_roc_auc': 0.9940402063689735, 'test_false_positives_rate': 0.012987012987012988, 'test_false_negatives_rate': 0.0547945205479452, 'test_runtime': 4.867, 'test_samples_per_second': 30.82, 'test_steps_per_second': 3.904, 'test_epoch': 4.0}
2025-05-14 18:18:22,169 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:18:22,169 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:18:22,588 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:18:22,590 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 18:18:22,592 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-264
2025-05-14 18:18:23,449 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.10521910339593887, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.975, 'eval_recall': 0.9873417721518988, 'eval_f1_score': 0.9811320754716981, 'eval_roc_auc': 0.9943942133815552, 'eval_false_positives_rate': 0.02857142857142857, 'eval_false_negatives_rate': 0.012658227848101266, 'eval_runtime': 4.8677, 'eval_samples_per_second': 30.61, 'eval_steps_per_second': 3.903, 'epoch': 3.0, 'step': 264}
2025-05-14 18:18:23,449 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 18:18:28,310 - Experiment - INFO - Test metrics: {'test_loss': 0.1827411651611328, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.9726027397260274, 'test_f1_score': 0.9659863945578231, 'test_roc_auc': 0.9925280199252802, 'test_false_positives_rate': 0.03896103896103896, 'test_false_negatives_rate': 0.0273972602739726, 'test_runtime': 4.8614, 'test_samples_per_second': 30.855, 'test_steps_per_second': 3.908, 'test_epoch': 3.0}
2025-05-14 18:18:28,326 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:18:28,342 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:18:28,678 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:18:28,678 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 18:18:28,678 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-352
2025-05-14 18:18:29,014 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3094053566455841, 'eval_accuracy': 0.959731543624161, 'eval_precision': 0.9866666666666667, 'eval_recall': 0.9367088607594937, 'eval_f1_score': 0.961038961038961, 'eval_roc_auc': 0.9909584086799277, 'eval_false_positives_rate': 0.014285714285714285, 'eval_false_negatives_rate': 0.06329113924050633, 'eval_runtime': 4.8577, 'eval_samples_per_second': 30.673, 'eval_steps_per_second': 3.911, 'epoch': 4.0, 'step': 352}
2025-05-14 18:18:29,014 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 18:18:33,901 - Experiment - INFO - Test metrics: {'test_loss': 0.266695499420166, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9857142857142858, 'test_recall': 0.9452054794520548, 'test_f1_score': 0.965034965034965, 'test_roc_auc': 0.9940402063689735, 'test_false_positives_rate': 0.012987012987012988, 'test_false_negatives_rate': 0.0547945205479452, 'test_runtime': 4.8868, 'test_samples_per_second': 30.695, 'test_steps_per_second': 3.888, 'test_epoch': 4.0}
2025-05-14 18:18:33,933 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:18:33,933 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:18:34,301 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:18:34,301 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 18:18:34,301 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-264
2025-05-14 18:18:34,637 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.10521910339593887, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.975, 'eval_recall': 0.9873417721518988, 'eval_f1_score': 0.9811320754716981, 'eval_roc_auc': 0.9943942133815552, 'eval_false_positives_rate': 0.02857142857142857, 'eval_false_negatives_rate': 0.012658227848101266, 'eval_runtime': 4.8677, 'eval_samples_per_second': 30.61, 'eval_steps_per_second': 3.903, 'epoch': 3.0, 'step': 264}
2025-05-14 18:18:34,637 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 18:18:39,524 - Experiment - INFO - Test metrics: {'test_loss': 0.1827411651611328, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.9726027397260274, 'test_f1_score': 0.9659863945578231, 'test_roc_auc': 0.9925280199252802, 'test_false_positives_rate': 0.03896103896103896, 'test_false_negatives_rate': 0.0273972602739726, 'test_runtime': 4.8874, 'test_samples_per_second': 30.691, 'test_steps_per_second': 3.888, 'test_epoch': 3.0}
2025-05-14 18:18:39,557 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:18:39,557 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:18:39,955 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:18:39,958 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 18:18:39,960 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-264
2025-05-14 18:18:40,352 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.10521910339593887, 'eval_accuracy': 0.9798657718120806, 'eval_precision': 0.975, 'eval_recall': 0.9873417721518988, 'eval_f1_score': 0.9811320754716981, 'eval_roc_auc': 0.9943942133815552, 'eval_false_positives_rate': 0.02857142857142857, 'eval_false_negatives_rate': 0.012658227848101266, 'eval_runtime': 4.8677, 'eval_samples_per_second': 30.61, 'eval_steps_per_second': 3.903, 'epoch': 3.0, 'step': 264}
2025-05-14 18:18:40,353 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 18:18:45,241 - Experiment - INFO - Test metrics: {'test_loss': 0.1827411651611328, 'test_accuracy': 0.9666666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.9726027397260274, 'test_f1_score': 0.9659863945578231, 'test_roc_auc': 0.9925280199252802, 'test_false_positives_rate': 0.03896103896103896, 'test_false_negatives_rate': 0.0273972602739726, 'test_runtime': 4.8832, 'test_samples_per_second': 30.717, 'test_steps_per_second': 3.891, 'test_epoch': 3.0}
2025-05-14 18:18:45,276 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 18:18:45,276 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 18:18:45,655 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 18:18:45,655 - Experiment - INFO - Finished model evaluations stage.

### CZ Dataset

In [ ]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)