In [9]:
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction
from workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased import BertBaseUncasedEncoder
from workspace.sources.experiments.metrics import Loss
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.local_datasets.preprocessing.transformations import Truncation
from workspace.sources.models.transformers.bert.bert_base_uncased import BertBaseUncased
from sklearn.model_selection import ParameterGrid
import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [10]:
experiment_name = 'prefinal-bert-base-uncased'

In [11]:
def conduct_model_experiments(dataset_name,
                              dataset_path,
                              dataset_params_dict,
                              model_hparams_dict):
    dataset_params_grid = ParameterGrid(dataset_params_dict)

    model_hparams_grid = ParameterGrid(model_hparams_dict)

    for dataset_params in dataset_params_grid:
        for model_hparams in model_hparams_grid:
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = BertBaseUncased(train_best_model_metric=Loss,
                                    training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            recovery_experiment.run()

In [12]:
pipelines = [PreprocessingPipeline(name='truncated_minimal_bert_pipeline',
                                   iterable=[Truncation(0.1),
                                             BertBaseUncasedEncoder()]),
             PreprocessingPipeline(name='truncated_noise_reduction_bert_pipeline',
                                   iterable=[Truncation(0.1), NoiseReduction(),
                                             BertBaseUncasedEncoder()])]
dataset_params_dict = {'preprocessings_pipeline': pipelines}

model_hparams_dict = {'epochs': [10],
                      'learning_rate': [1e-04, 5e-05],
                      'early_stopping_patience': [3],
                      'early_stopping_threshold': [0.01]}

### ReCOVery Dataset

In [7]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

2025-05-14 16:32:10,344 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 16:32:10,344 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:32:10,344 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:10,344 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:10,797 - Experiment - INFO - Found existing run with signature model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:10,797 - Experiment - INFO - Existing run ID: 095da1e8ed9f4da1bc451bf70b1f232f
2025-05-14 16:32:10,797 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-14 16:32:10,815 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 16:32:10,815 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:32:10,817 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:10,817 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:11,272 - Experiment - INFO - Found existing run with signature model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:11,272 - Experiment - INFO - Existing run ID: 38a83594ef494a419e718eb458e2ff50
2025-05-14 16:32:11,272 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-14 16:32:11,286 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 16:32:11,294 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:32:11,295 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:11,296 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:11,759 - Experiment - INFO - Found existing run with signature model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:11,759 - Experiment - INFO - Existing run ID: a0cbef192da54103a7512a73bf251e46
2025-05-14 16:32:11,759 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-14 16:32:11,759 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 16:32:11,759 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:32:11,775 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:11,775 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:12,241 - Experiment - INFO - Found existing run with signature model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:32:12,241 - Experiment - INFO - Existing run ID: 6f2203e122024994a38662bc2de11461
2025-05-14 16:32:12,241 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### EUvsDisinfo Dataset

In [5]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

2025-05-14 16:21:49,729 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 16:21:49,729 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:21:49,729 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:21:49,729 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:21:50,542 - Experiment - INFO - Run ID: bd7934115e444f2d9b753cb9595085cc
2025-05-14 16:21:50,542 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-21-50;rs=1405304350
2025-05-14 16:21:50,553 - Experiment - INFO - {'dataset_name': 'euvsdisinfo', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:21:50,585 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:21:50,617 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8660650>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A8A21910>]>
2025-05-14 16:21:50,778 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:21:50,778 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:21:50,778 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:21:50,795 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:21:50,795 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:21:50,812 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:21:50,812 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:21:51,008 - Experiment - INFO - Preprocessing function 1: bert_base_uncased_encoder
2025-05-14 16:21:51,008 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:21:51,008 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:21:51,810 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:21:51,810 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:21:52,041 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:21:52,044 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:21:53,157 - Experiment - INFO - Model name: bert-base-uncased
2025-05-14 16:21:53,168 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:23:46,904 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:23:46,905 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:23:47,264 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0001959682849701494, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0435, 'eval_samples_per_second': 30.667, 'eval_steps_per_second': 3.833, 'epoch': 2.0, 'step': 38}
2025-05-14 16:23:47,265 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:23:48,318 - Experiment - INFO - Test metrics: {'test_loss': 0.2600255608558655, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.048, 'test_samples_per_second': 30.533, 'test_steps_per_second': 3.817, 'test_epoch': 2.0}
2025-05-14 16:23:48,341 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:23:48,344 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:23:48,430 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:23:48,431 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:23:48,432 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:23:48,779 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0001959682849701494, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0435, 'eval_samples_per_second': 30.667, 'eval_steps_per_second': 3.833, 'epoch': 2.0, 'step': 38}
2025-05-14 16:23:48,779 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:23:49,813 - Experiment - INFO - Test metrics: {'test_loss': 0.2600255608558655, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.0203, 'test_samples_per_second': 31.363, 'test_steps_per_second': 3.92, 'test_epoch': 2.0}
2025-05-14 16:23:49,837 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:23:49,841 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:23:49,919 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:23:49,919 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:23:49,919 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:23:50,247 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0001959682849701494, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0435, 'eval_samples_per_second': 30.667, 'eval_steps_per_second': 3.833, 'epoch': 2.0, 'step': 38}
2025-05-14 16:23:50,247 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:23:51,280 - Experiment - INFO - Test metrics: {'test_loss': 0.2600255608558655, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.0326, 'test_samples_per_second': 30.99, 'test_steps_per_second': 3.874, 'test_epoch': 2.0}
2025-05-14 16:23:51,302 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:23:51,307 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:23:51,386 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:23:51,386 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:23:51,386 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:23:51,706 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0001959682849701494, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0435, 'eval_samples_per_second': 30.667, 'eval_steps_per_second': 3.833, 'epoch': 2.0, 'step': 38}
2025-05-14 16:23:51,706 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:23:52,747 - Experiment - INFO - Test metrics: {'test_loss': 0.2600255608558655, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.0366, 'test_samples_per_second': 30.871, 'test_steps_per_second': 3.859, 'test_epoch': 2.0}
2025-05-14 16:23:52,772 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:23:52,772 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:23:52,849 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:23:52,849 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:23:52,849 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:23:53,168 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0001959682849701494, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0435, 'eval_samples_per_second': 30.667, 'eval_steps_per_second': 3.833, 'epoch': 2.0, 'step': 38}
2025-05-14 16:23:53,168 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:23:54,207 - Experiment - INFO - Test metrics: {'test_loss': 0.2600255608558655, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.0325, 'test_samples_per_second': 30.993, 'test_steps_per_second': 3.874, 'test_epoch': 2.0}
2025-05-14 16:23:54,225 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:23:54,225 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:23:54,303 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:23:54,303 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:23:54,968 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 16:23:54,969 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:23:54,970 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:23:54,970 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:23:55,754 - Experiment - INFO - Run ID: bde23afb977649839863e3c780846de7
2025-05-14 16:23:55,754 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-23-55;rs=3131586544
2025-05-14 16:23:55,765 - Experiment - INFO - {'dataset_name': 'euvsdisinfo', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:23:55,785 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:23:55,818 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8660650>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A8A21910>]>
2025-05-14 16:23:55,985 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:23:55,985 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:23:55,985 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:23:56,006 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:23:56,006 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:23:56,018 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:23:56,019 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:23:56,191 - Experiment - INFO - Preprocessing function 1: bert_base_uncased_encoder
2025-05-14 16:23:56,191 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:23:56,191 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:23:56,992 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:23:56,992 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:23:57,231 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:23:57,231 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:23:58,346 - Experiment - INFO - Model name: bert-base-uncased
2025-05-14 16:23:58,355 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:26:07,748 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:26:07,748 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:26:08,194 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.00042416632641106844, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0531, 'eval_samples_per_second': 30.386, 'eval_steps_per_second': 3.798, 'epoch': 6.0, 'step': 114}
2025-05-14 16:26:08,194 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:26:10,129 - Experiment - INFO - Test metrics: {'test_loss': 0.000492728897370398, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.9353, 'test_samples_per_second': 16.535, 'test_steps_per_second': 2.067, 'test_epoch': 6.0}
2025-05-14 16:26:10,208 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:26:10,224 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:26:10,606 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:26:10,622 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:26:10,622 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:26:11,355 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.00042416632641106844, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0531, 'eval_samples_per_second': 30.386, 'eval_steps_per_second': 3.798, 'epoch': 6.0, 'step': 114}
2025-05-14 16:26:11,355 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:26:12,535 - Experiment - INFO - Test metrics: {'test_loss': 0.000492728897370398, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.1798, 'test_samples_per_second': 27.123, 'test_steps_per_second': 3.39, 'test_epoch': 6.0}
2025-05-14 16:26:12,554 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:26:12,554 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:26:12,640 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:26:12,640 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:26:12,640 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:26:12,993 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.00042416632641106844, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0531, 'eval_samples_per_second': 30.386, 'eval_steps_per_second': 3.798, 'epoch': 6.0, 'step': 114}
2025-05-14 16:26:12,993 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:26:14,044 - Experiment - INFO - Test metrics: {'test_loss': 0.000492728897370398, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.0508, 'test_samples_per_second': 30.452, 'test_steps_per_second': 3.806, 'test_epoch': 6.0}
2025-05-14 16:26:14,077 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:26:14,077 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:26:14,156 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:26:14,156 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:26:14,156 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:26:14,508 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.00042416632641106844, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0531, 'eval_samples_per_second': 30.386, 'eval_steps_per_second': 3.798, 'epoch': 6.0, 'step': 114}
2025-05-14 16:26:14,508 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:26:15,579 - Experiment - INFO - Test metrics: {'test_loss': 0.000492728897370398, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.0711, 'test_samples_per_second': 29.875, 'test_steps_per_second': 3.734, 'test_epoch': 6.0}
2025-05-14 16:26:15,590 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:26:15,590 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:26:15,679 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:26:15,679 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:26:15,679 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:26:16,040 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.00042416632641106844, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0531, 'eval_samples_per_second': 30.386, 'eval_steps_per_second': 3.798, 'epoch': 6.0, 'step': 114}
2025-05-14 16:26:16,040 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:26:17,112 - Experiment - INFO - Test metrics: {'test_loss': 0.000492728897370398, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.0719, 'test_samples_per_second': 29.854, 'test_steps_per_second': 3.732, 'test_epoch': 6.0}
2025-05-14 16:26:17,141 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:26:17,143 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:26:17,226 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:26:17,226 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:26:17,846 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 16:26:17,846 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:26:17,846 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:26:17,846 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:26:18,615 - Experiment - INFO - Run ID: e89aa7ed07e84c4ab775d12c11c2e9b8
2025-05-14 16:26:18,617 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-26-18;rs=436234055
2025-05-14 16:26:18,635 - Experiment - INFO - {'dataset_name': 'euvsdisinfo', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:26:18,667 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:26:18,708 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8A23E60>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000234A8A205C0>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A83E15B0>]>
2025-05-14 16:26:18,883 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:26:18,884 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:26:18,885 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:26:18,896 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:26:18,897 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:26:18,907 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:26:18,908 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:26:18,908 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 16:26:18,908 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:26:18,908 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:26:18,923 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:26:18,923 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:26:18,939 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:26:18,939 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:26:19,138 - Experiment - INFO - Preprocessing function 2: bert_base_uncased_encoder
2025-05-14 16:26:19,138 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:26:19,140 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:26:20,491 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:26:20,493 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:26:20,764 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:26:20,764 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:26:22,288 - Experiment - INFO - Model name: bert-base-uncased
2025-05-14 16:26:22,288 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:28:05,862 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:28:05,862 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:28:06,236 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001531902584247291, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0735, 'eval_samples_per_second': 29.809, 'eval_steps_per_second': 3.726, 'epoch': 2.0, 'step': 38}
2025-05-14 16:28:06,237 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:28:07,329 - Experiment - INFO - Test metrics: {'test_loss': 0.19295722246170044, 'test_accuracy': 0.9375, 'test_precision': 0.9375, 'test_recall': 0.9375, 'test_f1_score': 0.9375, 'test_roc_auc': 0.99609375, 'test_false_positives_rate': 0.0625, 'test_false_negatives_rate': 0.0625, 'test_runtime': 1.0872, 'test_samples_per_second': 29.434, 'test_steps_per_second': 3.679, 'test_epoch': 2.0}
2025-05-14 16:28:07,347 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:28:07,348 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:28:07,432 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:28:07,432 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:28:07,432 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:28:07,899 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001531902584247291, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0735, 'eval_samples_per_second': 29.809, 'eval_steps_per_second': 3.726, 'epoch': 2.0, 'step': 38}
2025-05-14 16:28:07,899 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:28:08,987 - Experiment - INFO - Test metrics: {'test_loss': 0.19295722246170044, 'test_accuracy': 0.9375, 'test_precision': 0.9375, 'test_recall': 0.9375, 'test_f1_score': 0.9375, 'test_roc_auc': 0.99609375, 'test_false_positives_rate': 0.0625, 'test_false_negatives_rate': 0.0625, 'test_runtime': 1.0868, 'test_samples_per_second': 29.444, 'test_steps_per_second': 3.681, 'test_epoch': 2.0}
2025-05-14 16:28:09,003 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:28:09,010 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:28:09,082 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:28:09,098 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:28:09,098 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:28:09,468 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001531902584247291, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0735, 'eval_samples_per_second': 29.809, 'eval_steps_per_second': 3.726, 'epoch': 2.0, 'step': 38}
2025-05-14 16:28:09,468 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:28:10,531 - Experiment - INFO - Test metrics: {'test_loss': 0.19295722246170044, 'test_accuracy': 0.9375, 'test_precision': 0.9375, 'test_recall': 0.9375, 'test_f1_score': 0.9375, 'test_roc_auc': 0.99609375, 'test_false_positives_rate': 0.0625, 'test_false_negatives_rate': 0.0625, 'test_runtime': 1.0602, 'test_samples_per_second': 30.184, 'test_steps_per_second': 3.773, 'test_epoch': 2.0}
2025-05-14 16:28:10,545 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:28:10,545 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:28:10,634 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:28:10,635 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:28:10,636 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:28:10,988 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001531902584247291, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0735, 'eval_samples_per_second': 29.809, 'eval_steps_per_second': 3.726, 'epoch': 2.0, 'step': 38}
2025-05-14 16:28:10,988 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:28:12,069 - Experiment - INFO - Test metrics: {'test_loss': 0.19295722246170044, 'test_accuracy': 0.9375, 'test_precision': 0.9375, 'test_recall': 0.9375, 'test_f1_score': 0.9375, 'test_roc_auc': 0.99609375, 'test_false_positives_rate': 0.0625, 'test_false_negatives_rate': 0.0625, 'test_runtime': 1.0651, 'test_samples_per_second': 30.043, 'test_steps_per_second': 3.755, 'test_epoch': 2.0}
2025-05-14 16:28:12,088 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:28:12,088 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:28:12,176 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:28:12,176 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:28:12,178 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-38
2025-05-14 16:28:12,530 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001531902584247291, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0735, 'eval_samples_per_second': 29.809, 'eval_steps_per_second': 3.726, 'epoch': 2.0, 'step': 38}
2025-05-14 16:28:12,530 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:28:13,616 - Experiment - INFO - Test metrics: {'test_loss': 0.19295722246170044, 'test_accuracy': 0.9375, 'test_precision': 0.9375, 'test_recall': 0.9375, 'test_f1_score': 0.9375, 'test_roc_auc': 0.99609375, 'test_false_positives_rate': 0.0625, 'test_false_negatives_rate': 0.0625, 'test_runtime': 1.0699, 'test_samples_per_second': 29.909, 'test_steps_per_second': 3.739, 'test_epoch': 2.0}
2025-05-14 16:28:13,637 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:28:13,639 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:28:13,718 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:28:13,718 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:28:13,974 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 16:28:13,974 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:28:13,974 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:28:13,974 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:28:14,593 - Experiment - INFO - Run ID: eb640078966f4f08bd82144e24c23422
2025-05-14 16:28:14,609 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-28-14;rs=508690901
2025-05-14 16:28:14,616 - Experiment - INFO - {'dataset_name': 'euvsdisinfo', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:28:14,636 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:28:14,668 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8A23E60>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000234A8A205C0>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A83E15B0>]>
2025-05-14 16:28:14,828 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:28:14,830 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:28:14,830 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:28:14,834 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:28:14,834 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:28:14,848 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:28:14,848 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:28:14,848 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 16:28:14,848 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:28:14,848 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:28:14,874 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:28:14,874 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:28:14,895 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:28:14,895 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:28:15,072 - Experiment - INFO - Preprocessing function 2: bert_base_uncased_encoder
2025-05-14 16:28:15,072 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:28:15,072 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:28:15,943 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:28:15,943 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:28:16,170 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:28:16,170 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:28:17,328 - Experiment - INFO - Model name: bert-base-uncased
2025-05-14 16:28:17,331 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:30:16,637 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:30:16,637 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-57
2025-05-14 16:30:18,442 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001992663834244013, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0972, 'eval_samples_per_second': 29.165, 'eval_steps_per_second': 3.646, 'epoch': 3.0, 'step': 57}
2025-05-14 16:30:18,445 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:30:19,757 - Experiment - INFO - Test metrics: {'test_loss': 0.19566211104393005, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 1.2976, 'test_samples_per_second': 24.66, 'test_steps_per_second': 3.083, 'test_epoch': 3.0}
2025-05-14 16:30:19,778 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:30:19,780 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:30:19,865 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:30:19,866 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:30:19,867 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-57
2025-05-14 16:30:20,239 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001992663834244013, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0972, 'eval_samples_per_second': 29.165, 'eval_steps_per_second': 3.646, 'epoch': 3.0, 'step': 57}
2025-05-14 16:30:20,239 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:30:21,379 - Experiment - INFO - Test metrics: {'test_loss': 0.19566211104393005, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 1.1211, 'test_samples_per_second': 28.543, 'test_steps_per_second': 3.568, 'test_epoch': 3.0}
2025-05-14 16:30:21,397 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:30:21,400 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:30:21,469 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:30:21,469 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:30:21,469 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-57
2025-05-14 16:30:21,869 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001992663834244013, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0972, 'eval_samples_per_second': 29.165, 'eval_steps_per_second': 3.646, 'epoch': 3.0, 'step': 57}
2025-05-14 16:30:21,869 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:30:22,977 - Experiment - INFO - Test metrics: {'test_loss': 0.19566211104393005, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 1.1062, 'test_samples_per_second': 28.929, 'test_steps_per_second': 3.616, 'test_epoch': 3.0}
2025-05-14 16:30:22,995 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:30:22,995 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:30:23,089 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:30:23,090 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:30:23,091 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-57
2025-05-14 16:30:23,497 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001992663834244013, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0972, 'eval_samples_per_second': 29.165, 'eval_steps_per_second': 3.646, 'epoch': 3.0, 'step': 57}
2025-05-14 16:30:23,498 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:30:24,616 - Experiment - INFO - Test metrics: {'test_loss': 0.19566211104393005, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 1.1128, 'test_samples_per_second': 28.757, 'test_steps_per_second': 3.595, 'test_epoch': 3.0}
2025-05-14 16:30:24,638 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:30:24,640 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:30:24,728 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:30:24,729 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:30:24,730 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-57
2025-05-14 16:30:25,156 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.001992663834244013, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.0972, 'eval_samples_per_second': 29.165, 'eval_steps_per_second': 3.646, 'epoch': 3.0, 'step': 57}
2025-05-14 16:30:25,157 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:30:26,239 - Experiment - INFO - Test metrics: {'test_loss': 0.19566211104393005, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 1.0794, 'test_samples_per_second': 29.647, 'test_steps_per_second': 3.706, 'test_epoch': 3.0}
2025-05-14 16:30:26,266 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:30:26,269 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:30:26,352 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:30:26,352 - Experiment - INFO - Finished model evaluations stage.

### ISOT Dataset

In [ ]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

2025-05-14 17:15:51,348 - Experiment - INFO - MLflow experiment initialized with ID: 847989095527904331
2025-05-14 17:15:51,349 - Experiment - INFO - Model signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01)
2025-05-14 17:15:51,350 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:15:51,351 - Experiment - INFO - Run signature: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:15:52,209 - Experiment - INFO - Run ID: 373bf99bb79c41adacac8934cb0dcea5
2025-05-14 17:15:52,209 - Experiment - INFO - Run name: model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-15-52;rs=3086548351
2025-05-14 17:15:52,226 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:15:52,251 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:15:52,614 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000234A8477E90>, <workspace.sources.local_datasets.preprocessing.encoders.bert_base_uncased.BertBaseUncasedEncoder object at 0x00000234A8BE0AA0>]>
2025-05-14 17:15:52,857 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:15:52,858 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:15:52,859 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:15:52,908 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:15:52,911 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:15:52,923 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:15:52,923 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:15:53,104 - Experiment - INFO - Preprocessing function 1: bert_base_uncased_encoder
2025-05-14 17:15:53,104 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:15:53,104 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

### CZ Dataset

In [ ]:
dataset_name = 'CzechDataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)