In [1]:
from workspace.sources.local_datasets.preprocessing.tokenization import NLTKTokenizer
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction, Lemmatization, Stemming
from workspace.sources.experiments.metrics import Loss
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.utils import class_name_to_str
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.local_datasets.preprocessing.utils import truncate
from sklearn.model_selection import ParameterGrid
from IPython.display import display, Markdown

from workspace.sources.local_datasets.preprocessing.encoders.encoders import BertBaseUncasedEncoder as Encoder
from workspace.sources.models.transformers.bert_based_models import BERT as Model

import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [2]:
experiment_name = f'prefinal-{class_name_to_str(Model.__name__)}-v2'
print('Experiment:', experiment_name)

Experiment: prefinal-bert-v2

In [3]:
def conduct_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid):
    total_runs = len(dataset_hparams_grid) * len(model_hparams_grid)
    for i, dataset_params in enumerate(dataset_hparams_grid):
        for j, model_hparams in enumerate(model_hparams_grid):
            run_number = i * len(model_hparams_grid) + j + 1
            display(Markdown(f'### Run {run_number} of {total_runs}'))
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = Model(train_best_model_metric=Loss,
                          training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            recovery_experiment.run()

In [4]:

# max_tokens_params = [128, 512]
max_tokens_params = [128]

pipelines = []

for max_tokens in max_tokens_params:
    pipelines.extend([PreprocessingPipeline(name='minimal',
                                            iterable=[Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction',
                                            iterable=[NoiseReduction(),
                                                      Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Lemmatization(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_stemming',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Stemming(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)])
                      ])
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(pipelines, fraction=0.05)

dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': pipelines})

print('Dataset Hyperparameters Grid Size: ', len(dataset_hparams_grid))

# model_hparams_grid = ParameterGrid({'epochs': [10],
#                                     'batch_size': [16],
#                                     'learning_rate': [1e-05, 5e-05],
#                                     'lr_scheduler': ['linear'],
#                                     'optimizer': ['adamw_torch'],
#                                     'weight_decay': [0.0, 1e-3],
#                                     'early_stopping_patience': [3],
#                                     'early_stopping_threshold': [0.01]})

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16],
                                    'learning_rate': [5e-05],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})

print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### ReCOVery Dataset

In [21]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 4

2025-05-16 00:15:29,413 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:15:29,413 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:15:29,415 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,416 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,537 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,539 - Experiment - INFO - Existing run ID: a83a87916b9c4334a422e12fa70fd542
2025-05-16 00:15:29,540 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 2 of 4

2025-05-16 00:15:29,556 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:15:29,557 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:15:29,558 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,558 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,688 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,690 - Experiment - INFO - Existing run ID: e228a0778d734eabaf636d09aeb59d61
2025-05-16 00:15:29,691 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 3 of 4

2025-05-16 00:15:29,711 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:15:29,712 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:15:29,713 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:15:29,713 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:15:29,923 - Experiment - INFO - Run ID: 457afb635d884616826d005a78056e8b
2025-05-16 00:15:29,924 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_00-15-29;rs=3681640104
2025-05-16 00:15:29,942 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 00:15:29,982 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 00:15:30,171 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000015DBDA5D100>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000015DBDA5FB90>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000015DBDA5DB20>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000015DBDA5D9A0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x0000015DBDA66FC0>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:15:30,357 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 00:15:30,358 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:30,359 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,375 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:30,376 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,386 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:30,387 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,396 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 00:15:30,397 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:30,398 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,463 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:30,464 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,480 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:30,481 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:15:30,500 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 00:15:30,501 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:30,503 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,760 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:30,762 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,812 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:30,812 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,853 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 00:15:30,855 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:30,857 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,929 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:30,930 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,949 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:30,951 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:31,136 - Experiment - INFO - Preprocessing function 4: bert_base_uncased_encoder
2025-05-16 00:15:31,137 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:31,138 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:15:31,970 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:31,970 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:15:32,180 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:32,181 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:15:32,946 - Experiment - INFO - Model name: BERT
2025-05-16 00:15:32,952 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 00:16:12,128 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 00:16:12,129 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-40
2025-05-16 00:16:12,550 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.32085272669792175, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 1.0, 'eval_recall': 0.9, 'eval_f1_score': 0.9473684210526315, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1239, 'eval_samples_per_second': 121.018, 'eval_steps_per_second': 8.068, 'epoch': 8.0, 'step': 40}
2025-05-16 00:16:12,551 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 00:16:12,696 - Experiment - INFO - Test metrics: {'test_loss': 0.640250563621521, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.1421, 'test_samples_per_second': 105.563, 'test_steps_per_second': 7.038, 'test_epoch': 8.0}
2025-05-16 00:16:12,713 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:12,716 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:12,762 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:12,764 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 00:16:12,765 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-40
2025-05-16 00:16:13,251 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.32085272669792175, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 1.0, 'eval_recall': 0.9, 'eval_f1_score': 0.9473684210526315, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1239, 'eval_samples_per_second': 121.018, 'eval_steps_per_second': 8.068, 'epoch': 8.0, 'step': 40}
2025-05-16 00:16:13,251 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 00:16:13,400 - Experiment - INFO - Test metrics: {'test_loss': 0.640250563621521, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.147, 'test_samples_per_second': 102.011, 'test_steps_per_second': 6.801, 'test_epoch': 8.0}
2025-05-16 00:16:13,416 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:13,418 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:13,456 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:13,456 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 00:16:13,458 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-40
2025-05-16 00:16:13,853 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.32085272669792175, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 1.0, 'eval_recall': 0.9, 'eval_f1_score': 0.9473684210526315, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1239, 'eval_samples_per_second': 121.018, 'eval_steps_per_second': 8.068, 'epoch': 8.0, 'step': 40}
2025-05-16 00:16:13,854 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 00:16:13,983 - Experiment - INFO - Test metrics: {'test_loss': 0.640250563621521, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.1252, 'test_samples_per_second': 119.827, 'test_steps_per_second': 7.988, 'test_epoch': 8.0}
2025-05-16 00:16:13,999 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:14,002 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:14,039 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:14,040 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 00:16:14,041 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 00:16:14,467 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.25702863931655884, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.9, 'eval_recall': 0.9, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1576, 'eval_samples_per_second': 95.148, 'eval_steps_per_second': 6.343, 'epoch': 7.0, 'step': 35}
2025-05-16 00:16:14,480 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 00:16:14,613 - Experiment - INFO - Test metrics: {'test_loss': 0.5816720724105835, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.7272727272727273, 'test_recall': 0.8, 'test_f1_score': 0.7619047619047619, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.6, 'test_false_negatives_rate': 0.2, 'test_runtime': 0.1293, 'test_samples_per_second': 116.043, 'test_steps_per_second': 7.736, 'test_epoch': 7.0}
2025-05-16 00:16:14,631 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:14,633 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:14,676 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:14,676 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 00:16:14,677 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 00:16:15,085 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.25702863931655884, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.9, 'eval_recall': 0.9, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1576, 'eval_samples_per_second': 95.148, 'eval_steps_per_second': 6.343, 'epoch': 7.0, 'step': 35}
2025-05-16 00:16:15,085 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 00:16:15,228 - Experiment - INFO - Test metrics: {'test_loss': 0.5816720724105835, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.7272727272727273, 'test_recall': 0.8, 'test_f1_score': 0.7619047619047619, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.6, 'test_false_negatives_rate': 0.2, 'test_runtime': 0.1368, 'test_samples_per_second': 109.63, 'test_steps_per_second': 7.309, 'test_epoch': 7.0}
2025-05-16 00:16:15,245 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:15,247 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:15,288 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:15,289 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 00:16:16,173 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:16:16,174 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:16:16,175 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:16:16,175 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:16:17,103 - Experiment - INFO - Run ID: f180219379a94e6e9a03c5eadf73183a
2025-05-16 00:16:17,103 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_00-16-17;rs=644145325
2025-05-16 00:16:17,115 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 00:16:17,155 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 00:16:17,331 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000015DBDA5DAC0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000015DBDA5FA40>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000015DBDA5ECC0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000015DBDA5CEF0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x0000015DBDA66F90>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:16:17,879 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 00:16:17,879 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:17,880 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,892 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:17,893 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,904 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:17,905 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,913 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 00:16:17,913 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:17,914 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,966 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:17,967 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,988 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:17,990 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:16:18,010 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 00:16:18,011 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:18,011 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,164 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:18,164 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,206 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:18,207 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,250 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 00:16:18,251 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:18,252 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,774 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:18,776 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,913 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:18,914 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:19,201 - Experiment - INFO - Preprocessing function 4: bert_base_uncased_encoder
2025-05-16 00:16:19,201 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:19,201 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:16:19,963 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:19,965 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:16:20,202 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:20,204 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:16:20,964 - Experiment - INFO - Model name: BERT
2025-05-16 00:16:20,969 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 00:16:43,153 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 00:16:43,168 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 00:16:43,697 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6907484531402588, 'eval_accuracy': 0.6, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.2857142857142857, 'eval_f1_score': 0.4, 'eval_roc_auc': 0.5357142857142857, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.7142857142857143, 'eval_runtime': 0.1345, 'eval_samples_per_second': 111.493, 'eval_steps_per_second': 7.433, 'epoch': 2.0, 'step': 10}
2025-05-16 00:16:43,699 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:16:43,841 - Experiment - INFO - Test metrics: {'test_loss': 0.745797872543335, 'test_accuracy': 0.2, 'test_precision': 0.0, 'test_recall': 0.0, 'test_f1_score': 0.0, 'test_roc_auc': 0.3928571428571429, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 1.0, 'test_runtime': 0.1368, 'test_samples_per_second': 109.614, 'test_steps_per_second': 7.308, 'test_epoch': 2.0}
2025-05-16 00:16:43,858 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:43,860 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:43,900 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:43,901 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 00:16:43,901 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:16:44,326 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6527726054191589, 'eval_accuracy': 0.6, 'eval_precision': 0.5454545454545454, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.6666666666666666, 'eval_roc_auc': 0.7142857142857143, 'eval_false_positives_rate': 0.625, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1543, 'eval_samples_per_second': 97.223, 'eval_steps_per_second': 6.482, 'epoch': 3.0, 'step': 15}
2025-05-16 00:16:44,327 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 00:16:44,469 - Experiment - INFO - Test metrics: {'test_loss': 0.7644299864768982, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.5384615384615384, 'test_recall': 0.875, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.44642857142857145, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.1359, 'test_samples_per_second': 110.357, 'test_steps_per_second': 7.357, 'test_epoch': 3.0}
2025-05-16 00:16:44,485 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:44,487 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:44,532 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:44,533 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 00:16:44,534 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 00:16:44,972 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6907484531402588, 'eval_accuracy': 0.6, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.2857142857142857, 'eval_f1_score': 0.4, 'eval_roc_auc': 0.5357142857142857, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.7142857142857143, 'eval_runtime': 0.1345, 'eval_samples_per_second': 111.493, 'eval_steps_per_second': 7.433, 'epoch': 2.0, 'step': 10}
2025-05-16 00:16:44,973 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:16:45,110 - Experiment - INFO - Test metrics: {'test_loss': 0.745797872543335, 'test_accuracy': 0.2, 'test_precision': 0.0, 'test_recall': 0.0, 'test_f1_score': 0.0, 'test_roc_auc': 0.3928571428571429, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 1.0, 'test_runtime': 0.1316, 'test_samples_per_second': 113.954, 'test_steps_per_second': 7.597, 'test_epoch': 2.0}
2025-05-16 00:16:45,131 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:45,133 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:45,173 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:45,174 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 00:16:45,174 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-5
2025-05-16 00:16:45,627 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7145585417747498, 'eval_accuracy': 0.4666666666666667, 'eval_precision': 0.4666666666666667, 'eval_recall': 1.0, 'eval_f1_score': 0.6363636363636364, 'eval_roc_auc': 0.7678571428571428, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1545, 'eval_samples_per_second': 97.116, 'eval_steps_per_second': 6.474, 'epoch': 1.0, 'step': 5}
2025-05-16 00:16:45,628 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 00:16:45,768 - Experiment - INFO - Test metrics: {'test_loss': 0.7016640901565552, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.5333333333333333, 'test_recall': 1.0, 'test_f1_score': 0.6956521739130435, 'test_roc_auc': 0.6071428571428571, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.134, 'test_samples_per_second': 111.906, 'test_steps_per_second': 7.46, 'test_epoch': 1.0}
2025-05-16 00:16:45,785 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:45,788 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:45,830 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:45,831 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 00:16:45,832 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:16:46,248 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6527726054191589, 'eval_accuracy': 0.6, 'eval_precision': 0.5454545454545454, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.6666666666666666, 'eval_roc_auc': 0.7142857142857143, 'eval_false_positives_rate': 0.625, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1543, 'eval_samples_per_second': 97.223, 'eval_steps_per_second': 6.482, 'epoch': 3.0, 'step': 15}
2025-05-16 00:16:46,248 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 00:16:46,382 - Experiment - INFO - Test metrics: {'test_loss': 0.7644299864768982, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.5384615384615384, 'test_recall': 0.875, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.44642857142857145, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.13, 'test_samples_per_second': 115.377, 'test_steps_per_second': 7.692, 'test_epoch': 3.0}
2025-05-16 00:16:46,398 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:46,399 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:46,440 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:46,441 - Experiment - INFO - Finished model evaluations stage.

### EUvsDisinfo Dataset

In [ ]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### ISOT Dataset

In [ ]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### CZ Dataset

In [5]:
cz_pipelines = []

for max_tokens in max_tokens_params:
    cz_pipelines.extend([PreprocessingPipeline(name='minimal',
                                               iterable=[Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction',
                                               iterable=[NoiseReduction(),
                                                         Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Lemmatization(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_stemming',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Stemming(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)])
                         ])
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(cz_pipelines, fraction=0.1)

cz_dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': cz_pipelines})
print('Dataset Hyperparameters Grid Size: ', len(cz_dataset_hparams_grid))
print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(cz_dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

In [6]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          cz_dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 4

2025-05-16 01:23:04,217 - Experiment - INFO - MLflow experiment initialized with ID: 102456789287063802
2025-05-16 01:23:04,218 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:23:04,219 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:23:04,220 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:23:05,092 - Experiment - INFO - Run ID: 1fe982d9e2884fb5b8a1f68edfc38268
2025-05-16 01:23:05,092 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_01-23-04;rs=3075290870
2025-05-16 01:23:05,108 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:23:05,132 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:23:05,235 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000002117834B500>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x000002117834B200>]>
2025-05-16 01:23:05,520 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:23:05,522 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:23:05,523 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:05,541 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:23:05,542 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:05,552 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:23:05,554 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:05,743 - Experiment - INFO - Preprocessing function 1: bert_base_uncased_encoder
2025-05-16 01:23:05,744 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:23:05,745 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:23:06,215 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:23:06,215 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:23:06,379 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:23:06,380 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:23:07,050 - Experiment - INFO - Model name: BERT
2025-05-16 01:23:07,053 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:23:32,433 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:23:32,433 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:23:32,838 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6017102599143982, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.7142857142857143, 'eval_recall': 1.0, 'eval_f1_score': 0.8333333333333334, 'eval_roc_auc': 0.42499999999999993, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1367, 'eval_samples_per_second': 102.412, 'eval_steps_per_second': 7.315, 'epoch': 2.0, 'step': 10}
2025-05-16 01:23:32,839 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:23:32,971 - Experiment - INFO - Test metrics: {'test_loss': 0.8591258525848389, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.4666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.6363636363636364, 'test_roc_auc': 0.5892857142857143, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1287, 'test_samples_per_second': 116.558, 'test_steps_per_second': 7.771, 'test_epoch': 2.0}
2025-05-16 01:23:32,988 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:23:32,990 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:23:33,030 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:23:33,032 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:23:33,032 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:23:33,443 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6017102599143982, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.7142857142857143, 'eval_recall': 1.0, 'eval_f1_score': 0.8333333333333334, 'eval_roc_auc': 0.42499999999999993, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1367, 'eval_samples_per_second': 102.412, 'eval_steps_per_second': 7.315, 'epoch': 2.0, 'step': 10}
2025-05-16 01:23:33,444 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:23:33,569 - Experiment - INFO - Test metrics: {'test_loss': 0.8591258525848389, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.4666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.6363636363636364, 'test_roc_auc': 0.5892857142857143, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1208, 'test_samples_per_second': 124.164, 'test_steps_per_second': 8.278, 'test_epoch': 2.0}
2025-05-16 01:23:33,586 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:23:33,587 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:23:33,626 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:23:33,627 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:23:33,628 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:23:34,039 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6017102599143982, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.7142857142857143, 'eval_recall': 1.0, 'eval_f1_score': 0.8333333333333334, 'eval_roc_auc': 0.42499999999999993, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1367, 'eval_samples_per_second': 102.412, 'eval_steps_per_second': 7.315, 'epoch': 2.0, 'step': 10}
2025-05-16 01:23:34,040 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:23:34,173 - Experiment - INFO - Test metrics: {'test_loss': 0.8591258525848389, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.4666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.6363636363636364, 'test_roc_auc': 0.5892857142857143, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1267, 'test_samples_per_second': 118.376, 'test_steps_per_second': 7.892, 'test_epoch': 2.0}
2025-05-16 01:23:34,189 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:23:34,191 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:23:34,235 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:23:34,237 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:23:34,238 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:23:34,618 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6030184030532837, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.7142857142857143, 'eval_recall': 1.0, 'eval_f1_score': 0.8333333333333334, 'eval_roc_auc': 0.825, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1325, 'eval_samples_per_second': 105.679, 'eval_steps_per_second': 7.549, 'epoch': 5.0, 'step': 25}
2025-05-16 01:23:34,619 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:23:34,741 - Experiment - INFO - Test metrics: {'test_loss': 0.9441301822662354, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.4666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.6363636363636364, 'test_roc_auc': 0.625, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1182, 'test_samples_per_second': 126.875, 'test_steps_per_second': 8.458, 'test_epoch': 5.0}
2025-05-16 01:23:34,755 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:23:34,756 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:23:34,797 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:23:34,798 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:23:34,799 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:23:35,175 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6017102599143982, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.7142857142857143, 'eval_recall': 1.0, 'eval_f1_score': 0.8333333333333334, 'eval_roc_auc': 0.42499999999999993, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1367, 'eval_samples_per_second': 102.412, 'eval_steps_per_second': 7.315, 'epoch': 2.0, 'step': 10}
2025-05-16 01:23:35,176 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:23:35,303 - Experiment - INFO - Test metrics: {'test_loss': 0.8591258525848389, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.4666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.6363636363636364, 'test_roc_auc': 0.5892857142857143, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1229, 'test_samples_per_second': 122.068, 'test_steps_per_second': 8.138, 'test_epoch': 2.0}
2025-05-16 01:23:35,319 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:23:35,320 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:23:35,357 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:23:35,359 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 4

2025-05-16 01:23:35,478 - Experiment - INFO - MLflow experiment initialized with ID: 102456789287063802
2025-05-16 01:23:35,479 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:23:35,479 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:23:35,480 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:23:36,250 - Experiment - INFO - Run ID: 2a6f065c437b4f439203c48548786bb2
2025-05-16 01:23:36,251 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_01-23-36;rs=1145886224
2025-05-16 01:23:36,260 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:23:36,278 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:23:36,376 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000002117834AAE0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000002117834B230>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x000002117834B260>]>
2025-05-16 01:23:36,534 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:23:36,535 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:23:36,536 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:36,549 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:23:36,550 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:36,559 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:23:36,560 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:36,568 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:23:36,569 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:23:36,570 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:36,617 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:23:36,618 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:36,632 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:23:36,632 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:23:36,801 - Experiment - INFO - Preprocessing function 2: bert_base_uncased_encoder
2025-05-16 01:23:36,802 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:23:36,803 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:23:37,168 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:23:37,168 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:23:37,277 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:23:37,278 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:23:37,686 - Experiment - INFO - Model name: BERT
2025-05-16 01:23:37,689 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:23:57,691 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:23:57,693 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:23:58,079 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6539859175682068, 'eval_accuracy': 0.6428571428571429, 'eval_precision': 0.6428571428571429, 'eval_recall': 1.0, 'eval_f1_score': 0.782608695652174, 'eval_roc_auc': 0.6666666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1227, 'eval_samples_per_second': 114.138, 'eval_steps_per_second': 8.153, 'epoch': 4.0, 'step': 20}
2025-05-16 01:23:58,080 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:23:58,238 - Experiment - INFO - Test metrics: {'test_loss': 0.519538402557373, 'test_accuracy': 0.8, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 0.861111111111111, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1542, 'test_samples_per_second': 97.251, 'test_steps_per_second': 6.483, 'test_epoch': 4.0}
2025-05-16 01:23:58,258 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:23:58,261 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:23:58,310 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:23:58,312 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:23:58,313 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:23:58,824 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6539859175682068, 'eval_accuracy': 0.6428571428571429, 'eval_precision': 0.6428571428571429, 'eval_recall': 1.0, 'eval_f1_score': 0.782608695652174, 'eval_roc_auc': 0.6666666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1227, 'eval_samples_per_second': 114.138, 'eval_steps_per_second': 8.153, 'epoch': 4.0, 'step': 20}
2025-05-16 01:23:58,825 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:23:58,970 - Experiment - INFO - Test metrics: {'test_loss': 0.519538402557373, 'test_accuracy': 0.8, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 0.861111111111111, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1391, 'test_samples_per_second': 107.836, 'test_steps_per_second': 7.189, 'test_epoch': 4.0}
2025-05-16 01:23:58,986 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:23:58,988 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:23:59,032 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:23:59,033 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:23:59,034 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:23:59,440 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6539859175682068, 'eval_accuracy': 0.6428571428571429, 'eval_precision': 0.6428571428571429, 'eval_recall': 1.0, 'eval_f1_score': 0.782608695652174, 'eval_roc_auc': 0.6666666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1227, 'eval_samples_per_second': 114.138, 'eval_steps_per_second': 8.153, 'epoch': 4.0, 'step': 20}
2025-05-16 01:23:59,441 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:23:59,570 - Experiment - INFO - Test metrics: {'test_loss': 0.519538402557373, 'test_accuracy': 0.8, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 0.861111111111111, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.125, 'test_samples_per_second': 120.021, 'test_steps_per_second': 8.001, 'test_epoch': 4.0}
2025-05-16 01:23:59,594 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:23:59,597 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:23:59,646 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:23:59,647 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:23:59,648 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:24:00,059 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6539859175682068, 'eval_accuracy': 0.6428571428571429, 'eval_precision': 0.6428571428571429, 'eval_recall': 1.0, 'eval_f1_score': 0.782608695652174, 'eval_roc_auc': 0.6666666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1227, 'eval_samples_per_second': 114.138, 'eval_steps_per_second': 8.153, 'epoch': 4.0, 'step': 20}
2025-05-16 01:24:00,060 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:24:00,200 - Experiment - INFO - Test metrics: {'test_loss': 0.519538402557373, 'test_accuracy': 0.8, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 0.861111111111111, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.134, 'test_samples_per_second': 111.932, 'test_steps_per_second': 7.462, 'test_epoch': 4.0}
2025-05-16 01:24:00,215 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:24:00,217 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:24:00,258 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:24:00,259 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:24:00,260 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:24:00,784 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6539859175682068, 'eval_accuracy': 0.6428571428571429, 'eval_precision': 0.6428571428571429, 'eval_recall': 1.0, 'eval_f1_score': 0.782608695652174, 'eval_roc_auc': 0.6666666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1227, 'eval_samples_per_second': 114.138, 'eval_steps_per_second': 8.153, 'epoch': 4.0, 'step': 20}
2025-05-16 01:24:00,785 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:24:00,913 - Experiment - INFO - Test metrics: {'test_loss': 0.519538402557373, 'test_accuracy': 0.8, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 0.861111111111111, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1238, 'test_samples_per_second': 121.138, 'test_steps_per_second': 8.076, 'test_epoch': 4.0}
2025-05-16 01:24:00,932 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:24:00,934 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:24:00,985 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:24:00,988 - Experiment - INFO - Finished model evaluations stage.

### Run 3 of 4

2025-05-16 01:24:01,742 - Experiment - INFO - MLflow experiment initialized with ID: 102456789287063802
2025-05-16 01:24:01,743 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:24:01,744 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:24:01,744 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:24:02,814 - Experiment - INFO - Run ID: af2efbaaa40142c38147b8f80dbc3bfa
2025-05-16 01:24:02,815 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_01-24-02;rs=1708032409
2025-05-16 01:24:02,824 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:24:02,853 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:24:02,956 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000002117834A6F0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000002117834B290>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x000002117834B2C0>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x000002117834B2F0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x000002117834B320>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:24:03,295 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:24:03,296 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:24:03,297 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:03,312 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:24:03,313 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:03,322 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:24:03,323 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:03,334 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:24:03,335 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:24:03,336 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:03,403 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:24:03,404 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:03,423 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:24:03,424 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:24:03,457 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:24:03,458 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:24:03,459 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:03,762 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:24:03,763 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:03,796 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:24:03,798 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:03,868 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 01:24:03,869 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:24:03,870 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:04,147 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:24:04,149 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:04,181 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:24:04,183 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:24:04,408 - Experiment - INFO - Preprocessing function 4: bert_base_uncased_encoder
2025-05-16 01:24:04,409 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:24:04,410 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:24:05,142 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:24:05,144 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:24:05,324 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:24:05,326 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:24:06,008 - Experiment - INFO - Model name: BERT
2025-05-16 01:24:06,013 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-16 01:24:56,230 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:24:56,230 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:24:56,651 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3878825604915619, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.8181818181818182, 'eval_recall': 1.0, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.8888888888888888, 'eval_false_positives_rate': 0.4, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1107, 'eval_samples_per_second': 126.523, 'eval_steps_per_second': 9.037, 'epoch': 10.0, 'step': 50}
2025-05-16 01:24:56,653 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:24:56,804 - Experiment - INFO - Test metrics: {'test_loss': 0.8526438474655151, 'test_accuracy': 0.6, 'test_precision': 0.4, 'test_recall': 1.0, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.8636363636363635, 'test_false_positives_rate': 0.5454545454545454, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1461, 'test_samples_per_second': 102.697, 'test_steps_per_second': 6.846, 'test_epoch': 10.0}
2025-05-16 01:24:56,818 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:24:56,820 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:24:56,860 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:24:56,861 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:24:56,861 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:24:57,217 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3878825604915619, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.8181818181818182, 'eval_recall': 1.0, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.8888888888888888, 'eval_false_positives_rate': 0.4, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1107, 'eval_samples_per_second': 126.523, 'eval_steps_per_second': 9.037, 'epoch': 10.0, 'step': 50}
2025-05-16 01:24:57,217 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:24:57,342 - Experiment - INFO - Test metrics: {'test_loss': 0.8526438474655151, 'test_accuracy': 0.6, 'test_precision': 0.4, 'test_recall': 1.0, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.8636363636363635, 'test_false_positives_rate': 0.5454545454545454, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1196, 'test_samples_per_second': 125.466, 'test_steps_per_second': 8.364, 'test_epoch': 10.0}
2025-05-16 01:24:57,562 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:24:57,564 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:24:57,616 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:24:57,617 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:24:57,618 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:24:58,091 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7358523607254028, 'eval_accuracy': 0.35714285714285715, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 0.42222222222222217, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.1403, 'eval_samples_per_second': 99.802, 'eval_steps_per_second': 7.129, 'epoch': 2.0, 'step': 10}
2025-05-16 01:24:58,092 - Experiment - INFO - Best model found at epoch 2.0.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-16 01:24:58,246 - Experiment - INFO - Test metrics: {'test_loss': 0.6623284220695496, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.0, 'test_recall': 0.0, 'test_f1_score': 0.0, 'test_roc_auc': 0.5909090909090909, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 1.0, 'test_runtime': 0.1479, 'test_samples_per_second': 101.406, 'test_steps_per_second': 6.76, 'test_epoch': 2.0}
2025-05-16 01:24:58,265 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:24:58,267 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:24:58,316 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:24:58,317 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:24:58,318 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-40
2025-05-16 01:24:58,822 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.40586379170417786, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.8181818181818182, 'eval_recall': 1.0, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.9333333333333333, 'eval_false_positives_rate': 0.4, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1217, 'eval_samples_per_second': 115.036, 'eval_steps_per_second': 8.217, 'epoch': 8.0, 'step': 40}
2025-05-16 01:24:58,824 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 01:24:58,961 - Experiment - INFO - Test metrics: {'test_loss': 0.9059239029884338, 'test_accuracy': 0.6, 'test_precision': 0.4, 'test_recall': 1.0, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.7954545454545454, 'test_false_positives_rate': 0.5454545454545454, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1317, 'test_samples_per_second': 113.938, 'test_steps_per_second': 7.596, 'test_epoch': 8.0}
2025-05-16 01:24:58,979 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:24:58,981 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:24:59,020 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:24:59,021 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:24:59,022 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:24:59,406 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3878825604915619, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.8181818181818182, 'eval_recall': 1.0, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.8888888888888888, 'eval_false_positives_rate': 0.4, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1107, 'eval_samples_per_second': 126.523, 'eval_steps_per_second': 9.037, 'epoch': 10.0, 'step': 50}
2025-05-16 01:24:59,407 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:24:59,532 - Experiment - INFO - Test metrics: {'test_loss': 0.8526438474655151, 'test_accuracy': 0.6, 'test_precision': 0.4, 'test_recall': 1.0, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.8636363636363635, 'test_false_positives_rate': 0.5454545454545454, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.121, 'test_samples_per_second': 123.972, 'test_steps_per_second': 8.265, 'test_epoch': 10.0}
2025-05-16 01:24:59,550 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:24:59,552 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:24:59,591 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:24:59,591 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 01:25:00,286 - Experiment - INFO - MLflow experiment initialized with ID: 102456789287063802
2025-05-16 01:25:00,286 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:25:00,287 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:25:00,288 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:25:01,243 - Experiment - INFO - Run ID: 31fe9869fc8f4bf19ec32316af796f51
2025-05-16 01:25:01,244 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_01-25-01;rs=3566234625
2025-05-16 01:25:01,255 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:25:01,287 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:25:01,386 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000002117834B530>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000002117834B440>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x000002117834B3E0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x000002117834B4A0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x000002117834B4D0>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:25:01,564 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:25:01,565 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:25:01,566 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:01,580 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:25:01,581 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:01,592 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:25:01,594 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:01,606 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:25:01,607 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:25:01,608 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:01,659 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:25:01,659 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:01,681 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:25:01,683 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:25:01,705 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:25:01,706 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:25:01,708 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:01,846 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:25:01,848 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:01,895 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:25:01,898 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:01,930 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 01:25:01,931 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:25:01,932 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: SPOLUobčané
warning: skipping word with mixed case: NATOsféry
warning: skipping word with mixed case: NATOsféry
warning: skipping word with mixed case: NATOstánu
warning: skipping word with mixed case: NATOstánu
warning: skipping word with mixed case: NATOstán
warning: skipping word with mixed case: NATOsféře
warning: skipping word with mixed case: NATOstánu
warning: skipping word with mixed case: oCxcRRwKl
warning: skipping word with mixed case: iZTdGDa
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: PolitRussia
warning: skipping word with mixed case: WeChat
warning: skipping word with mixed case: WeChat
warning: skipping word with mixed case: HIMARSy
warning: skipping word with mixed case: LightRocket
warning: skipping word with mixed case: MaxxPro
warning: skipping word with mixed case: mírUkrajině
warning: skipping word with mixed case: vícTo
warning: skipping word with mixed case: líbíOkomentovatSdílet
warning: skipping word with mixed case: DShK
2025-05-16 01:25:02,035 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:25:02,037 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: NLujLXkmQ
warning: skipping word with mixed case: FACs
warning: skipping word with mixed case: UAVs
2025-05-16 01:25:02,073 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:25:02,074 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: QsRsXmnJ
warning: skipping word with mixed case: mMztqsJRQT
warning: skipping word with mixed case: MiG
2025-05-16 01:25:02,277 - Experiment - INFO - Preprocessing function 4: bert_base_uncased_encoder
2025-05-16 01:25:02,277 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:25:02,279 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:25:02,856 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:25:02,857 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:25:03,066 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:25:03,067 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:25:03,593 - Experiment - INFO - Model name: BERT
2025-05-16 01:25:03,597 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:25:19,800 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:25:19,802 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:25:20,205 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.656831681728363, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.836734693877551, 'eval_false_positives_rate': 0.42857142857142855, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1319, 'eval_samples_per_second': 106.135, 'eval_steps_per_second': 7.581, 'epoch': 3.0, 'step': 15}
2025-05-16 01:25:20,206 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:25:20,364 - Experiment - INFO - Test metrics: {'test_loss': 0.6642666459083557, 'test_accuracy': 0.6666666666666666, 'test_precision': 1.0, 'test_recall': 0.5454545454545454, 'test_f1_score': 0.7058823529411765, 'test_roc_auc': 0.9772727272727273, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.45454545454545453, 'test_runtime': 0.1551, 'test_samples_per_second': 96.693, 'test_steps_per_second': 6.446, 'test_epoch': 3.0}
2025-05-16 01:25:20,378 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:25:20,381 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:25:20,419 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:25:20,420 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:25:20,421 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:25:20,857 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.656831681728363, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.836734693877551, 'eval_false_positives_rate': 0.42857142857142855, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1319, 'eval_samples_per_second': 106.135, 'eval_steps_per_second': 7.581, 'epoch': 3.0, 'step': 15}
2025-05-16 01:25:20,858 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:25:21,013 - Experiment - INFO - Test metrics: {'test_loss': 0.6642666459083557, 'test_accuracy': 0.6666666666666666, 'test_precision': 1.0, 'test_recall': 0.5454545454545454, 'test_f1_score': 0.7058823529411765, 'test_roc_auc': 0.9772727272727273, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.45454545454545453, 'test_runtime': 0.1485, 'test_samples_per_second': 101.02, 'test_steps_per_second': 6.735, 'test_epoch': 3.0}
2025-05-16 01:25:21,031 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:25:21,033 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:25:21,086 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:25:21,087 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:25:21,088 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:25:21,594 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.656831681728363, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.836734693877551, 'eval_false_positives_rate': 0.42857142857142855, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1319, 'eval_samples_per_second': 106.135, 'eval_steps_per_second': 7.581, 'epoch': 3.0, 'step': 15}
2025-05-16 01:25:21,595 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:25:21,733 - Experiment - INFO - Test metrics: {'test_loss': 0.6642666459083557, 'test_accuracy': 0.6666666666666666, 'test_precision': 1.0, 'test_recall': 0.5454545454545454, 'test_f1_score': 0.7058823529411765, 'test_roc_auc': 0.9772727272727273, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.45454545454545453, 'test_runtime': 0.1293, 'test_samples_per_second': 115.982, 'test_steps_per_second': 7.732, 'test_epoch': 3.0}
2025-05-16 01:25:21,759 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:25:21,763 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:25:21,817 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:25:21,818 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:25:21,819 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:25:22,229 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.656831681728363, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.836734693877551, 'eval_false_positives_rate': 0.42857142857142855, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1319, 'eval_samples_per_second': 106.135, 'eval_steps_per_second': 7.581, 'epoch': 3.0, 'step': 15}
2025-05-16 01:25:22,230 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:25:22,355 - Experiment - INFO - Test metrics: {'test_loss': 0.6642666459083557, 'test_accuracy': 0.6666666666666666, 'test_precision': 1.0, 'test_recall': 0.5454545454545454, 'test_f1_score': 0.7058823529411765, 'test_roc_auc': 0.9772727272727273, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.45454545454545453, 'test_runtime': 0.1209, 'test_samples_per_second': 124.08, 'test_steps_per_second': 8.272, 'test_epoch': 3.0}
2025-05-16 01:25:22,369 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:25:22,371 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:25:22,409 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:25:22,410 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:25:22,410 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:25:22,812 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.656831681728363, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.836734693877551, 'eval_false_positives_rate': 0.42857142857142855, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1319, 'eval_samples_per_second': 106.135, 'eval_steps_per_second': 7.581, 'epoch': 3.0, 'step': 15}
2025-05-16 01:25:22,814 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:25:22,950 - Experiment - INFO - Test metrics: {'test_loss': 0.6642666459083557, 'test_accuracy': 0.6666666666666666, 'test_precision': 1.0, 'test_recall': 0.5454545454545454, 'test_f1_score': 0.7058823529411765, 'test_roc_auc': 0.9772727272727273, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.45454545454545453, 'test_runtime': 0.1291, 'test_samples_per_second': 116.209, 'test_steps_per_second': 7.747, 'test_epoch': 3.0}
2025-05-16 01:25:22,974 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:25:22,977 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:25:23,035 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:25:23,036 - Experiment - INFO - Finished model evaluations stage.