In [24]:
from workspace.sources.local_datasets.preprocessing.tokenization import NLTKTokenizer
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction, Lemmatization, Stemming
from workspace.sources.local_datasets.preprocessing.encoders.encoders import BertBaseUncasedEncoder
from workspace.sources.experiments.metrics import Loss
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.models.transformers.bert_based_models import BERT
from workspace.sources.local_datasets.preprocessing.utils import truncate
from sklearn.model_selection import ParameterGrid
from IPython.display import display, Markdown
import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [8]:
experiment_name = 'prefinal-bert-base-uncased-v2'
model = BERT
encoder = BertBaseUncasedEncoder

In [19]:
def conduct_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid):
    total_runs = len(dataset_hparams_grid) * len(model_hparams_grid)
    for i, dataset_params in enumerate(dataset_hparams_grid):
        for j, model_hparams in enumerate(model_hparams_grid):
            run_number = i * len(model_hparams_grid) + j + 1
            display(Markdown(f'### Run {run_number} of {total_runs}'))
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model_ = model(train_best_model_metric=Loss,
                         training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model_)
            recovery_experiment.run()

In [20]:

# max_tokens_params = [128, 512]
max_tokens_params = [128]

pipelines = []

for max_tokens in max_tokens_params:
    pipelines.extend([PreprocessingPipeline(name='minimal',
                                            iterable=[encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction',
                                            iterable=[NoiseReduction(),
                                                      encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Lemmatization(),
                                                      encoder(is_split_into_words=True,
                                                                             truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_stemming',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Stemming(),
                                                      encoder(is_split_into_words=True,
                                                                             truncation_max_length=max_tokens)])
                      ])
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(pipelines, fraction=0.05)

dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': pipelines})

print('Dataset Hyperparameters Grid Size: ', len(dataset_hparams_grid))

# model_hparams_grid = ParameterGrid({'epochs': [10],
#                                     'batch_size': [16],
#                                     'learning_rate': [1e-05, 5e-05],
#                                     'lr_scheduler': ['linear'],
#                                     'optimizer': ['adamw_torch'],
#                                     'weight_decay': [0.0, 1e-3],
#                                     'early_stopping_patience': [3],
#                                     'early_stopping_threshold': [0.01]})

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16],
                                    'learning_rate': [5e-05],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})

print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### ReCOVery Dataset

In [21]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 4

2025-05-16 00:15:29,413 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:15:29,413 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:15:29,415 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,416 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,537 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,539 - Experiment - INFO - Existing run ID: a83a87916b9c4334a422e12fa70fd542
2025-05-16 00:15:29,540 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 2 of 4

2025-05-16 00:15:29,556 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:15:29,557 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:15:29,558 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,558 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,688 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:15:29,690 - Experiment - INFO - Existing run ID: e228a0778d734eabaf636d09aeb59d61
2025-05-16 00:15:29,691 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 3 of 4

2025-05-16 00:15:29,711 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:15:29,712 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:15:29,713 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:15:29,713 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:15:29,923 - Experiment - INFO - Run ID: 457afb635d884616826d005a78056e8b
2025-05-16 00:15:29,924 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_00-15-29;rs=3681640104
2025-05-16 00:15:29,942 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 00:15:29,982 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 00:15:30,171 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000015DBDA5D100>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000015DBDA5FB90>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000015DBDA5DB20>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000015DBDA5D9A0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x0000015DBDA66FC0>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:15:30,357 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 00:15:30,358 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:30,359 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,375 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:30,376 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,386 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:30,387 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,396 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 00:15:30,397 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:30,398 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,463 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:30,464 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,480 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:30,481 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:15:30,500 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 00:15:30,501 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:30,503 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,760 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:30,762 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,812 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:30,812 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,853 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 00:15:30,855 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:30,857 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,929 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:30,930 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:30,949 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:30,951 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:15:31,136 - Experiment - INFO - Preprocessing function 4: bert_base_uncased_encoder
2025-05-16 00:15:31,137 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:15:31,138 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:15:31,970 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:15:31,970 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:15:32,180 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:15:32,181 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:15:32,946 - Experiment - INFO - Model name: BERT
2025-05-16 00:15:32,952 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 00:16:12,128 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 00:16:12,129 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-40
2025-05-16 00:16:12,550 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.32085272669792175, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 1.0, 'eval_recall': 0.9, 'eval_f1_score': 0.9473684210526315, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1239, 'eval_samples_per_second': 121.018, 'eval_steps_per_second': 8.068, 'epoch': 8.0, 'step': 40}
2025-05-16 00:16:12,551 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 00:16:12,696 - Experiment - INFO - Test metrics: {'test_loss': 0.640250563621521, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.1421, 'test_samples_per_second': 105.563, 'test_steps_per_second': 7.038, 'test_epoch': 8.0}
2025-05-16 00:16:12,713 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:12,716 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:12,762 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:12,764 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 00:16:12,765 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-40
2025-05-16 00:16:13,251 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.32085272669792175, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 1.0, 'eval_recall': 0.9, 'eval_f1_score': 0.9473684210526315, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1239, 'eval_samples_per_second': 121.018, 'eval_steps_per_second': 8.068, 'epoch': 8.0, 'step': 40}
2025-05-16 00:16:13,251 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 00:16:13,400 - Experiment - INFO - Test metrics: {'test_loss': 0.640250563621521, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.147, 'test_samples_per_second': 102.011, 'test_steps_per_second': 6.801, 'test_epoch': 8.0}
2025-05-16 00:16:13,416 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:13,418 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:13,456 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:13,456 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 00:16:13,458 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-40
2025-05-16 00:16:13,853 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.32085272669792175, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 1.0, 'eval_recall': 0.9, 'eval_f1_score': 0.9473684210526315, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1239, 'eval_samples_per_second': 121.018, 'eval_steps_per_second': 8.068, 'epoch': 8.0, 'step': 40}
2025-05-16 00:16:13,854 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 00:16:13,983 - Experiment - INFO - Test metrics: {'test_loss': 0.640250563621521, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.1252, 'test_samples_per_second': 119.827, 'test_steps_per_second': 7.988, 'test_epoch': 8.0}
2025-05-16 00:16:13,999 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:14,002 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:14,039 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:14,040 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 00:16:14,041 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 00:16:14,467 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.25702863931655884, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.9, 'eval_recall': 0.9, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1576, 'eval_samples_per_second': 95.148, 'eval_steps_per_second': 6.343, 'epoch': 7.0, 'step': 35}
2025-05-16 00:16:14,480 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 00:16:14,613 - Experiment - INFO - Test metrics: {'test_loss': 0.5816720724105835, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.7272727272727273, 'test_recall': 0.8, 'test_f1_score': 0.7619047619047619, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.6, 'test_false_negatives_rate': 0.2, 'test_runtime': 0.1293, 'test_samples_per_second': 116.043, 'test_steps_per_second': 7.736, 'test_epoch': 7.0}
2025-05-16 00:16:14,631 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:14,633 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:14,676 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:14,676 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 00:16:14,677 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 00:16:15,085 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.25702863931655884, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.9, 'eval_recall': 0.9, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.96, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1576, 'eval_samples_per_second': 95.148, 'eval_steps_per_second': 6.343, 'epoch': 7.0, 'step': 35}
2025-05-16 00:16:15,085 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 00:16:15,228 - Experiment - INFO - Test metrics: {'test_loss': 0.5816720724105835, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.7272727272727273, 'test_recall': 0.8, 'test_f1_score': 0.7619047619047619, 'test_roc_auc': 0.8200000000000001, 'test_false_positives_rate': 0.6, 'test_false_negatives_rate': 0.2, 'test_runtime': 0.1368, 'test_samples_per_second': 109.63, 'test_steps_per_second': 7.309, 'test_epoch': 7.0}
2025-05-16 00:16:15,245 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:15,247 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:15,288 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:15,289 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 00:16:16,173 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:16:16,174 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:16:16,175 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:16:16,175 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:16:17,103 - Experiment - INFO - Run ID: f180219379a94e6e9a03c5eadf73183a
2025-05-16 00:16:17,103 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_00-16-17;rs=644145325
2025-05-16 00:16:17,115 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 00:16:17,155 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 00:16:17,331 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000015DBDA5DAC0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000015DBDA5FA40>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000015DBDA5ECC0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000015DBDA5CEF0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x0000015DBDA66F90>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:16:17,879 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 00:16:17,879 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:17,880 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,892 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:17,893 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,904 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:17,905 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,913 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 00:16:17,913 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:17,914 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,966 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:17,967 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:17,988 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:17,990 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:16:18,010 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 00:16:18,011 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:18,011 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,164 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:18,164 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,206 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:18,207 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,250 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 00:16:18,251 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:18,252 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,774 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:18,776 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:18,913 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:18,914 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:16:19,201 - Experiment - INFO - Preprocessing function 4: bert_base_uncased_encoder
2025-05-16 00:16:19,201 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:16:19,201 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:16:19,963 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:16:19,965 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:16:20,202 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:16:20,204 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:16:20,964 - Experiment - INFO - Model name: BERT
2025-05-16 00:16:20,969 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 00:16:43,153 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 00:16:43,168 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 00:16:43,697 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6907484531402588, 'eval_accuracy': 0.6, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.2857142857142857, 'eval_f1_score': 0.4, 'eval_roc_auc': 0.5357142857142857, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.7142857142857143, 'eval_runtime': 0.1345, 'eval_samples_per_second': 111.493, 'eval_steps_per_second': 7.433, 'epoch': 2.0, 'step': 10}
2025-05-16 00:16:43,699 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:16:43,841 - Experiment - INFO - Test metrics: {'test_loss': 0.745797872543335, 'test_accuracy': 0.2, 'test_precision': 0.0, 'test_recall': 0.0, 'test_f1_score': 0.0, 'test_roc_auc': 0.3928571428571429, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 1.0, 'test_runtime': 0.1368, 'test_samples_per_second': 109.614, 'test_steps_per_second': 7.308, 'test_epoch': 2.0}
2025-05-16 00:16:43,858 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:43,860 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:43,900 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:43,901 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 00:16:43,901 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:16:44,326 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6527726054191589, 'eval_accuracy': 0.6, 'eval_precision': 0.5454545454545454, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.6666666666666666, 'eval_roc_auc': 0.7142857142857143, 'eval_false_positives_rate': 0.625, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1543, 'eval_samples_per_second': 97.223, 'eval_steps_per_second': 6.482, 'epoch': 3.0, 'step': 15}
2025-05-16 00:16:44,327 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 00:16:44,469 - Experiment - INFO - Test metrics: {'test_loss': 0.7644299864768982, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.5384615384615384, 'test_recall': 0.875, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.44642857142857145, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.1359, 'test_samples_per_second': 110.357, 'test_steps_per_second': 7.357, 'test_epoch': 3.0}
2025-05-16 00:16:44,485 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:44,487 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:44,532 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:44,533 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 00:16:44,534 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 00:16:44,972 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6907484531402588, 'eval_accuracy': 0.6, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.2857142857142857, 'eval_f1_score': 0.4, 'eval_roc_auc': 0.5357142857142857, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.7142857142857143, 'eval_runtime': 0.1345, 'eval_samples_per_second': 111.493, 'eval_steps_per_second': 7.433, 'epoch': 2.0, 'step': 10}
2025-05-16 00:16:44,973 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:16:45,110 - Experiment - INFO - Test metrics: {'test_loss': 0.745797872543335, 'test_accuracy': 0.2, 'test_precision': 0.0, 'test_recall': 0.0, 'test_f1_score': 0.0, 'test_roc_auc': 0.3928571428571429, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 1.0, 'test_runtime': 0.1316, 'test_samples_per_second': 113.954, 'test_steps_per_second': 7.597, 'test_epoch': 2.0}
2025-05-16 00:16:45,131 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:45,133 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:45,173 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:45,174 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 00:16:45,174 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-5
2025-05-16 00:16:45,627 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7145585417747498, 'eval_accuracy': 0.4666666666666667, 'eval_precision': 0.4666666666666667, 'eval_recall': 1.0, 'eval_f1_score': 0.6363636363636364, 'eval_roc_auc': 0.7678571428571428, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1545, 'eval_samples_per_second': 97.116, 'eval_steps_per_second': 6.474, 'epoch': 1.0, 'step': 5}
2025-05-16 00:16:45,628 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 00:16:45,768 - Experiment - INFO - Test metrics: {'test_loss': 0.7016640901565552, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.5333333333333333, 'test_recall': 1.0, 'test_f1_score': 0.6956521739130435, 'test_roc_auc': 0.6071428571428571, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.134, 'test_samples_per_second': 111.906, 'test_steps_per_second': 7.46, 'test_epoch': 1.0}
2025-05-16 00:16:45,785 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:45,788 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:45,830 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:45,831 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 00:16:45,832 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:16:46,248 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6527726054191589, 'eval_accuracy': 0.6, 'eval_precision': 0.5454545454545454, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.6666666666666666, 'eval_roc_auc': 0.7142857142857143, 'eval_false_positives_rate': 0.625, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.1543, 'eval_samples_per_second': 97.223, 'eval_steps_per_second': 6.482, 'epoch': 3.0, 'step': 15}
2025-05-16 00:16:46,248 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 00:16:46,382 - Experiment - INFO - Test metrics: {'test_loss': 0.7644299864768982, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.5384615384615384, 'test_recall': 0.875, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.44642857142857145, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.13, 'test_samples_per_second': 115.377, 'test_steps_per_second': 7.692, 'test_epoch': 3.0}
2025-05-16 00:16:46,398 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:16:46,399 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:16:46,440 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:16:46,441 - Experiment - INFO - Finished model evaluations stage.

### EUvsDisinfo Dataset

In [ ]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### ISOT Dataset

In [ ]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### CZ Dataset

In [22]:
cz_pipelines = []

for max_tokens in max_tokens_params:
    cz_pipelines.extend([PreprocessingPipeline(name='minimal',
                                               iterable=[BertBaseUncasedEncoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction',
                                               iterable=[NoiseReduction(),
                                                         BertBaseUncasedEncoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Lemmatization(language='czech'),
                                                         BertBaseUncasedEncoder(is_split_into_words=True,
                                                                                truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_stemming',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Stemming(language='czech'),
                                                         BertBaseUncasedEncoder(is_split_into_words=True,
                                                                                truncation_max_length=max_tokens)])
                         ])
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(cz_pipelines, fraction=0.05)

cz_dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': cz_pipelines})
print('Dataset Hyperparameters Grid Size: ', len(cz_dataset_hparams_grid))
print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(cz_dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

In [23]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 4

2025-05-16 00:17:02,343 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:17:02,344 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:17:02,344 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:17:02,345 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:17:03,320 - Experiment - INFO - Run ID: 480312c7e8f144d88d5d5f824f019cac
2025-05-16 00:17:03,321 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_00-17-03;rs=1254734001
2025-05-16 00:17:03,335 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 00:17:03,369 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 00:17:03,481 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000015DBDA5C590>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x0000015DBDA67740>]>
2025-05-16 00:17:03,638 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 00:17:03,638 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:03,638 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:03,653 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:03,654 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:03,665 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:03,666 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:03,847 - Experiment - INFO - Preprocessing function 1: bert_base_uncased_encoder
2025-05-16 00:17:03,848 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:03,849 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/34 [00:00<?, ? examples/s]

Map:   0%|          | 0/34 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:04,233 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:04,234 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:04,373 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:04,375 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:04,725 - Experiment - INFO - Model name: BERT
2025-05-16 00:17:04,731 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 00:17:29,274 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 00:17:29,275 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-12
2025-05-16 00:17:29,622 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5446491837501526, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 1.0, 'eval_recall': 0.8, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.9, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.0882, 'eval_samples_per_second': 79.377, 'eval_steps_per_second': 11.34, 'epoch': 4.0, 'step': 12}
2025-05-16 00:17:29,622 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 00:17:29,692 - Experiment - INFO - Test metrics: {'test_loss': 0.5293641686439514, 'test_accuracy': 0.8571428571428571, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0667, 'test_samples_per_second': 105.02, 'test_steps_per_second': 15.003, 'test_epoch': 4.0}
2025-05-16 00:17:29,713 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:29,715 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:29,737 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:29,738 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 00:17:29,739 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:17:30,281 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4429023563861847, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.8333333333333334, 'eval_recall': 1.0, 'eval_f1_score': 0.9090909090909091, 'eval_roc_auc': 0.8, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0883, 'eval_samples_per_second': 79.237, 'eval_steps_per_second': 11.32, 'epoch': 5.0, 'step': 15}
2025-05-16 00:17:30,282 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 00:17:30,363 - Experiment - INFO - Test metrics: {'test_loss': 0.5285859107971191, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0754, 'test_samples_per_second': 92.851, 'test_steps_per_second': 13.264, 'test_epoch': 5.0}
2025-05-16 00:17:30,382 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:30,383 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:30,406 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:30,407 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 00:17:30,408 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-12
2025-05-16 00:17:30,778 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5446491837501526, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 1.0, 'eval_recall': 0.8, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.9, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.0882, 'eval_samples_per_second': 79.377, 'eval_steps_per_second': 11.34, 'epoch': 4.0, 'step': 12}
2025-05-16 00:17:30,779 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 00:17:30,863 - Experiment - INFO - Test metrics: {'test_loss': 0.5293641686439514, 'test_accuracy': 0.8571428571428571, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0777, 'test_samples_per_second': 90.065, 'test_steps_per_second': 12.866, 'test_epoch': 4.0}
2025-05-16 00:17:30,885 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:30,887 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:30,910 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:30,911 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 00:17:30,912 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-12
2025-05-16 00:17:31,330 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5446491837501526, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 1.0, 'eval_recall': 0.8, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.9, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.0882, 'eval_samples_per_second': 79.377, 'eval_steps_per_second': 11.34, 'epoch': 4.0, 'step': 12}
2025-05-16 00:17:31,331 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 00:17:31,417 - Experiment - INFO - Test metrics: {'test_loss': 0.5293641686439514, 'test_accuracy': 0.8571428571428571, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0816, 'test_samples_per_second': 85.757, 'test_steps_per_second': 12.251, 'test_epoch': 4.0}
2025-05-16 00:17:31,443 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:31,446 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:31,474 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:31,476 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 00:17:31,477 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:17:31,992 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4429023563861847, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.8333333333333334, 'eval_recall': 1.0, 'eval_f1_score': 0.9090909090909091, 'eval_roc_auc': 0.8, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0883, 'eval_samples_per_second': 79.237, 'eval_steps_per_second': 11.32, 'epoch': 5.0, 'step': 15}
2025-05-16 00:17:31,993 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 00:17:32,072 - Experiment - INFO - Test metrics: {'test_loss': 0.5285859107971191, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0741, 'test_samples_per_second': 94.526, 'test_steps_per_second': 13.504, 'test_epoch': 5.0}
2025-05-16 00:17:32,095 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:32,096 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:32,117 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:32,118 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 4

2025-05-16 00:17:32,360 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:17:32,361 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:17:32,362 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:17:32,363 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 00:17:33,526 - Experiment - INFO - Run ID: 463cd3c6f84b415eb13100f9ec97efeb
2025-05-16 00:17:33,527 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_00-17-33;rs=2665967258
2025-05-16 00:17:33,540 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 00:17:33,565 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 00:17:33,678 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000015DBDA5E510>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000015DBB2A4E30>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x0000015DBDA66F60>]>
2025-05-16 00:17:33,846 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 00:17:33,846 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:33,847 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:33,858 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:33,859 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:33,871 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:33,872 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:33,881 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 00:17:33,882 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:33,884 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:33,926 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:33,928 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:33,941 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:33,942 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:34,141 - Experiment - INFO - Preprocessing function 2: bert_base_uncased_encoder
2025-05-16 00:17:34,143 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:34,144 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/34 [00:00<?, ? examples/s]

Map:   0%|          | 0/34 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:34,480 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:34,481 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:34,567 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:34,568 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:34,950 - Experiment - INFO - Model name: BERT
2025-05-16 00:17:34,955 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-16 00:17:51,491 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 00:17:51,491 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-6
2025-05-16 00:17:51,998 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6978102922439575, 'eval_accuracy': 0.2857142857142857, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.0873, 'eval_samples_per_second': 80.163, 'eval_steps_per_second': 11.452, 'epoch': 2.0, 'step': 6}
2025-05-16 00:17:51,999 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:17:52,133 - Experiment - INFO - Test metrics: {'test_loss': 0.6765390038490295, 'test_accuracy': 0.7142857142857143, 'test_precision': 1.0, 'test_recall': 0.3333333333333333, 'test_f1_score': 0.5, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.6666666666666666, 'test_runtime': 0.1291, 'test_samples_per_second': 54.211, 'test_steps_per_second': 7.744, 'test_epoch': 2.0}
2025-05-16 00:17:52,154 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:52,156 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:52,184 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:52,185 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 00:17:52,186 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-6
2025-05-16 00:17:52,563 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6978102922439575, 'eval_accuracy': 0.2857142857142857, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.0873, 'eval_samples_per_second': 80.163, 'eval_steps_per_second': 11.452, 'epoch': 2.0, 'step': 6}
2025-05-16 00:17:52,564 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:17:52,687 - Experiment - INFO - Test metrics: {'test_loss': 0.6765390038490295, 'test_accuracy': 0.7142857142857143, 'test_precision': 1.0, 'test_recall': 0.3333333333333333, 'test_f1_score': 0.5, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.6666666666666666, 'test_runtime': 0.1196, 'test_samples_per_second': 58.505, 'test_steps_per_second': 8.358, 'test_epoch': 2.0}
2025-05-16 00:17:52,704 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:52,705 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:52,726 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:52,727 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 00:17:52,728 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-6
2025-05-16 00:17:53,128 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6978102922439575, 'eval_accuracy': 0.2857142857142857, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.0873, 'eval_samples_per_second': 80.163, 'eval_steps_per_second': 11.452, 'epoch': 2.0, 'step': 6}
2025-05-16 00:17:53,129 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:17:53,239 - Experiment - INFO - Test metrics: {'test_loss': 0.6765390038490295, 'test_accuracy': 0.7142857142857143, 'test_precision': 1.0, 'test_recall': 0.3333333333333333, 'test_f1_score': 0.5, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.6666666666666666, 'test_runtime': 0.1064, 'test_samples_per_second': 65.771, 'test_steps_per_second': 9.396, 'test_epoch': 2.0}
2025-05-16 00:17:53,260 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:53,262 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:53,282 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:53,283 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 00:17:53,284 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-6
2025-05-16 00:17:53,681 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6978102922439575, 'eval_accuracy': 0.2857142857142857, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.0873, 'eval_samples_per_second': 80.163, 'eval_steps_per_second': 11.452, 'epoch': 2.0, 'step': 6}
2025-05-16 00:17:53,682 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:17:53,773 - Experiment - INFO - Test metrics: {'test_loss': 0.6765390038490295, 'test_accuracy': 0.7142857142857143, 'test_precision': 1.0, 'test_recall': 0.3333333333333333, 'test_f1_score': 0.5, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.6666666666666666, 'test_runtime': 0.0864, 'test_samples_per_second': 80.993, 'test_steps_per_second': 11.57, 'test_epoch': 2.0}
2025-05-16 00:17:53,793 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:53,795 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:53,816 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:53,817 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 00:17:53,818 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-6
2025-05-16 00:17:54,223 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6978102922439575, 'eval_accuracy': 0.2857142857142857, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.0873, 'eval_samples_per_second': 80.163, 'eval_steps_per_second': 11.452, 'epoch': 2.0, 'step': 6}
2025-05-16 00:17:54,223 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:17:54,309 - Experiment - INFO - Test metrics: {'test_loss': 0.6765390038490295, 'test_accuracy': 0.7142857142857143, 'test_precision': 1.0, 'test_recall': 0.3333333333333333, 'test_f1_score': 0.5, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.6666666666666666, 'test_runtime': 0.0815, 'test_samples_per_second': 85.847, 'test_steps_per_second': 12.264, 'test_epoch': 2.0}
2025-05-16 00:17:54,329 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:17:54,331 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:17:54,351 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:17:54,352 - Experiment - INFO - Finished model evaluations stage.

### Run 3 of 4

2025-05-16 00:17:54,546 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:17:54,547 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:17:54,548 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:17:54,548 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:17:55,679 - Experiment - INFO - Run ID: 4439a4e3b2474276adeccd1b3a5c5f46
2025-05-16 00:17:55,679 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_00-17-55;rs=4166636162
2025-05-16 00:17:55,691 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 00:17:55,731 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 00:17:55,848 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000015DBDA5D100>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000015DBDA5FB90>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000015DBDA5DB20>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000015DBDA5D9A0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x0000015DBDA66FC0>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:17:56,022 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 00:17:56,023 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:56,024 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,035 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:56,036 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,044 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:56,045 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,053 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 00:17:56,054 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:56,055 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,090 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:56,091 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,105 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:56,106 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:17:56,120 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 00:17:56,121 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:56,122 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,210 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:56,211 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,234 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:56,236 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,252 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 00:17:56,252 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:56,254 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,338 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:56,340 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,357 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:56,359 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:17:56,553 - Experiment - INFO - Preprocessing function 4: bert_base_uncased_encoder
2025-05-16 00:17:56,554 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:17:56,555 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/34 [00:00<?, ? examples/s]

Map:   0%|          | 0/34 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:57,005 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:17:57,006 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:57,147 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:17:57,148 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:17:57,528 - Experiment - INFO - Model name: BERT
2025-05-16 00:17:57,532 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 00:18:13,664 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 00:18:13,665 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:18:14,150 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6796679496765137, 'eval_accuracy': 0.5714285714285714, 'eval_precision': 0.5714285714285714, 'eval_recall': 1.0, 'eval_f1_score': 0.7272727272727273, 'eval_roc_auc': 0.6666666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0898, 'eval_samples_per_second': 77.984, 'eval_steps_per_second': 11.141, 'epoch': 5.0, 'step': 15}
2025-05-16 00:18:14,151 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 00:18:14,306 - Experiment - INFO - Test metrics: {'test_loss': 0.645183265209198, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.4, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1508, 'test_samples_per_second': 46.426, 'test_steps_per_second': 6.632, 'test_epoch': 5.0}
2025-05-16 00:18:14,323 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:14,326 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:14,345 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:14,346 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 00:18:14,347 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:18:14,754 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6796679496765137, 'eval_accuracy': 0.5714285714285714, 'eval_precision': 0.5714285714285714, 'eval_recall': 1.0, 'eval_f1_score': 0.7272727272727273, 'eval_roc_auc': 0.6666666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0898, 'eval_samples_per_second': 77.984, 'eval_steps_per_second': 11.141, 'epoch': 5.0, 'step': 15}
2025-05-16 00:18:14,755 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 00:18:14,889 - Experiment - INFO - Test metrics: {'test_loss': 0.645183265209198, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.4, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.13, 'test_samples_per_second': 53.864, 'test_steps_per_second': 7.695, 'test_epoch': 5.0}
2025-05-16 00:18:14,904 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:14,906 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:14,927 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:14,928 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 00:18:14,928 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-12
2025-05-16 00:18:15,396 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7140750288963318, 'eval_accuracy': 0.2857142857142857, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 0.5, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.0871, 'eval_samples_per_second': 80.366, 'eval_steps_per_second': 11.481, 'epoch': 4.0, 'step': 12}
2025-05-16 00:18:15,397 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 00:18:15,530 - Experiment - INFO - Test metrics: {'test_loss': 0.7506799697875977, 'test_accuracy': 0.2857142857142857, 'test_precision': 0.5, 'test_recall': 0.2, 'test_f1_score': 0.2857142857142857, 'test_roc_auc': 0.2, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.8, 'test_runtime': 0.1283, 'test_samples_per_second': 54.544, 'test_steps_per_second': 7.792, 'test_epoch': 4.0}
2025-05-16 00:18:15,550 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:15,552 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:15,575 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:15,576 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 00:18:15,577 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-6
2025-05-16 00:18:16,007 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6859517693519592, 'eval_accuracy': 0.5714285714285714, 'eval_precision': 0.5714285714285714, 'eval_recall': 1.0, 'eval_f1_score': 0.7272727272727273, 'eval_roc_auc': 0.75, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.097, 'eval_samples_per_second': 72.148, 'eval_steps_per_second': 10.307, 'epoch': 2.0, 'step': 6}
2025-05-16 00:18:16,007 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 00:18:16,107 - Experiment - INFO - Test metrics: {'test_loss': 0.6138582825660706, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.7, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0954, 'test_samples_per_second': 73.37, 'test_steps_per_second': 10.481, 'test_epoch': 2.0}
2025-05-16 00:18:16,129 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:16,132 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:16,156 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:16,157 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 00:18:16,157 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 00:18:16,612 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6796679496765137, 'eval_accuracy': 0.5714285714285714, 'eval_precision': 0.5714285714285714, 'eval_recall': 1.0, 'eval_f1_score': 0.7272727272727273, 'eval_roc_auc': 0.6666666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0898, 'eval_samples_per_second': 77.984, 'eval_steps_per_second': 11.141, 'epoch': 5.0, 'step': 15}
2025-05-16 00:18:16,613 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 00:18:16,706 - Experiment - INFO - Test metrics: {'test_loss': 0.645183265209198, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.4, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0898, 'test_samples_per_second': 77.96, 'test_steps_per_second': 11.137, 'test_epoch': 5.0}
2025-05-16 00:18:16,726 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:16,728 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:16,751 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:16,752 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 00:18:17,695 - Experiment - INFO - MLflow experiment initialized with ID: 237384892919634716
2025-05-16 00:18:17,695 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 00:18:17,696 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:18:17,697 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 00:18:18,801 - Experiment - INFO - Run ID: 0b1a6b922621463682c7403524109da4
2025-05-16 00:18:18,802 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_00-18-18;rs=2456544178
2025-05-16 00:18:18,812 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 00:18:18,850 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 00:18:18,956 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000015DBDA5DAC0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000015DBDA5FA40>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000015DBDA5ECC0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000015DBDA5CEF0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x0000015DBDA66F90>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:18:19,145 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 00:18:19,147 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:18:19,148 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,161 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:18:19,161 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,169 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:18:19,170 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,178 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 00:18:19,179 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:18:19,179 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,223 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:18:19,224 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,237 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:18:19,239 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 00:18:19,253 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 00:18:19,254 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:18:19,255 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,359 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:18:19,360 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,376 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:18:19,377 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,399 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 00:18:19,400 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:18:19,401 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,714 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:18:19,717 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,749 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:18:19,750 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 00:18:19,974 - Experiment - INFO - Preprocessing function 4: bert_base_uncased_encoder
2025-05-16 00:18:19,975 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 00:18:19,976 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/34 [00:00<?, ? examples/s]

Map:   0%|          | 0/34 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:18:20,474 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 00:18:20,476 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:18:20,598 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 00:18:20,600 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Map:   0%|          | 0/7 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 00:18:20,988 - Experiment - INFO - Model name: BERT
2025-05-16 00:18:20,991 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 00:18:33,932 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 00:18:33,933 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-12
2025-05-16 00:18:34,410 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6081066131591797, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 1.0, 'eval_recall': 0.8, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.0906, 'eval_samples_per_second': 77.254, 'eval_steps_per_second': 11.036, 'epoch': 4.0, 'step': 12}
2025-05-16 00:18:34,411 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 00:18:34,493 - Experiment - INFO - Test metrics: {'test_loss': 0.644078254699707, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.6666666666666666, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.75, 'test_false_positives_rate': 0.25, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.0746, 'test_samples_per_second': 93.775, 'test_steps_per_second': 13.396, 'test_epoch': 4.0}
2025-05-16 00:18:34,519 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:34,521 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:34,552 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:34,554 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 00:18:34,555 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-12
2025-05-16 00:18:35,059 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6081066131591797, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 1.0, 'eval_recall': 0.8, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.0906, 'eval_samples_per_second': 77.254, 'eval_steps_per_second': 11.036, 'epoch': 4.0, 'step': 12}
2025-05-16 00:18:35,060 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 00:18:35,148 - Experiment - INFO - Test metrics: {'test_loss': 0.644078254699707, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.6666666666666666, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.75, 'test_false_positives_rate': 0.25, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.0829, 'test_samples_per_second': 84.422, 'test_steps_per_second': 12.06, 'test_epoch': 4.0}
2025-05-16 00:18:35,163 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:35,165 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:35,187 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:35,188 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 00:18:35,189 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-12
2025-05-16 00:18:35,581 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6081066131591797, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 1.0, 'eval_recall': 0.8, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.0906, 'eval_samples_per_second': 77.254, 'eval_steps_per_second': 11.036, 'epoch': 4.0, 'step': 12}
2025-05-16 00:18:35,582 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 00:18:35,660 - Experiment - INFO - Test metrics: {'test_loss': 0.644078254699707, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.6666666666666666, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.75, 'test_false_positives_rate': 0.25, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.0742, 'test_samples_per_second': 94.374, 'test_steps_per_second': 13.482, 'test_epoch': 4.0}
2025-05-16 00:18:35,678 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:35,679 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:35,700 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:35,701 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 00:18:35,702 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-12
2025-05-16 00:18:36,068 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6081066131591797, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 1.0, 'eval_recall': 0.8, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.0906, 'eval_samples_per_second': 77.254, 'eval_steps_per_second': 11.036, 'epoch': 4.0, 'step': 12}
2025-05-16 00:18:36,068 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 00:18:36,159 - Experiment - INFO - Test metrics: {'test_loss': 0.644078254699707, 'test_accuracy': 0.7142857142857143, 'test_precision': 0.6666666666666666, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.75, 'test_false_positives_rate': 0.25, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.0838, 'test_samples_per_second': 83.56, 'test_steps_per_second': 11.937, 'test_epoch': 4.0}
2025-05-16 00:18:36,189 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:36,193 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:36,226 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:36,227 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 00:18:36,228 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-3
2025-05-16 00:18:36,666 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6015368103981018, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.7142857142857143, 'eval_recall': 1.0, 'eval_f1_score': 0.8333333333333334, 'eval_roc_auc': 0.6, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.3262, 'eval_samples_per_second': 21.458, 'eval_steps_per_second': 3.065, 'epoch': 1.0, 'step': 3}
2025-05-16 00:18:36,667 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 00:18:36,747 - Experiment - INFO - Test metrics: {'test_loss': 0.7971214652061462, 'test_accuracy': 0.42857142857142855, 'test_precision': 0.42857142857142855, 'test_recall': 1.0, 'test_f1_score': 0.6, 'test_roc_auc': 0.41666666666666663, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0746, 'test_samples_per_second': 93.883, 'test_steps_per_second': 13.412, 'test_epoch': 1.0}
2025-05-16 00:18:36,767 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 00:18:36,769 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 00:18:36,791 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 00:18:36,792 - Experiment - INFO - Finished model evaluations stage.