In [1]:
from workspace.sources.local_datasets.preprocessing.tokenization import NLTKTokenizer
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction, Lemmatization, Stemming
from workspace.sources.experiments.metrics import Loss
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.utils import class_name_to_str
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.local_datasets.preprocessing.utils import truncate
from sklearn.model_selection import ParameterGrid
from IPython.display import display, Markdown

from workspace.sources.local_datasets.preprocessing.encoders.encoders import BertBaseUncasedEncoder as Encoder
from workspace.sources.models.transformers.bert_based_models import BERT as Model

import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [2]:
experiment_name = f'{class_name_to_str(Model.__name__)}'
print('Experiment:', experiment_name)

Experiment: bert

In [3]:
def conduct_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid):
    total_runs = len(dataset_hparams_grid) * len(model_hparams_grid)
    for i, dataset_params in enumerate(dataset_hparams_grid):
        for j, model_hparams in enumerate(model_hparams_grid):
            run_number = i * len(model_hparams_grid) + j + 1
            display(Markdown(f'### Run {run_number} of {total_runs}'))
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = Model(train_best_model_metric=Loss,
                          training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            recovery_experiment.run()

In [4]:

# max_tokens_params = [128, 512]
max_tokens_params = [128, 256]

pipelines = []

for max_tokens in max_tokens_params:
    pipelines.extend([PreprocessingPipeline(name='minimal',
                                            iterable=[Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction',
                                            iterable=[NoiseReduction(),
                                                      Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Lemmatization(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_stemming',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Stemming(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)])
                      ])
# optional - for testing purposes, if you want to run fast test on very small datasets
# truncate(pipelines, fraction=0.05)

dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': pipelines})

print('Dataset Hyperparameters Grid Size: ', len(dataset_hparams_grid))

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16],
                                    'learning_rate': [1e-05, 5e-05],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [0.0, 1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})


print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  8
Model Hyperparameters Grid Size:  4
Total Hyperparameter Combinations:  32

### ReCOVery Dataset

In [5]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 32

2025-05-16 05:54:07,207 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:07,208 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:07,209 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:07,210 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:07,998 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:07,999 - Experiment - INFO - Existing run ID: 8751084f751c4ef5b96c751f401fc4f9
2025-05-16 05:54:08,000 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 2 of 32

2025-05-16 05:54:08,009 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:08,010 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:08,011 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:08,011 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:08,773 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:08,774 - Experiment - INFO - Existing run ID: ec01891a90ee42a7803d858cc50a0655
2025-05-16 05:54:08,775 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 3 of 32

2025-05-16 05:54:08,783 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:08,784 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:08,785 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:08,786 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:09,560 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:09,561 - Experiment - INFO - Existing run ID: e0e9d47106e24b25983bfaa1aacccc81
2025-05-16 05:54:09,562 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 4 of 32

2025-05-16 05:54:09,571 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:09,572 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:09,573 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:09,574 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:10,347 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:10,348 - Experiment - INFO - Existing run ID: 0d1076534448495c8e8a32a08245bb35
2025-05-16 05:54:10,348 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 5 of 32

2025-05-16 05:54:10,358 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:10,359 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:10,360 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:10,360 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:11,118 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:11,119 - Experiment - INFO - Existing run ID: 4f6684bb38e7469fb121f0bb87a02af4
2025-05-16 05:54:11,119 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 6 of 32

2025-05-16 05:54:11,128 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:11,129 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:11,130 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:11,131 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:11,898 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:11,899 - Experiment - INFO - Existing run ID: 7897d3cceebb4c078be532ed9f463d50
2025-05-16 05:54:11,900 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 7 of 32

2025-05-16 05:54:11,908 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:11,909 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:11,910 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:11,911 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:12,687 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:12,687 - Experiment - INFO - Existing run ID: 4fd37b75afe344a18caafeb7245fdcd9
2025-05-16 05:54:12,688 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 8 of 32

2025-05-16 05:54:12,696 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:12,696 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:12,697 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:12,698 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:13,453 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 05:54:13,454 - Experiment - INFO - Existing run ID: 4c1a9dec1d604610975856ce5c9293c0
2025-05-16 05:54:13,455 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 9 of 32

2025-05-16 05:54:13,463 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:13,464 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:13,464 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:13,465 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:14,222 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:14,223 - Experiment - INFO - Existing run ID: f8c7b8dcf7584a579b219b82e0fbb99b
2025-05-16 05:54:14,223 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 10 of 32

2025-05-16 05:54:14,231 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:14,232 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:14,233 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:14,234 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:15,000 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:15,002 - Experiment - INFO - Existing run ID: b4cc7f1938764b2d8c2d36e21d7c797f
2025-05-16 05:54:15,003 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 11 of 32

2025-05-16 05:54:15,012 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:15,012 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:15,013 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:15,013 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:15,771 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:15,771 - Experiment - INFO - Existing run ID: 5fc670bd6369404ea6948454df4a0451
2025-05-16 05:54:15,772 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 12 of 32

2025-05-16 05:54:15,781 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:15,782 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:15,783 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:15,784 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:16,569 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:16,570 - Experiment - INFO - Existing run ID: 2cdc850c9aa64b52951452d067d7fd81
2025-05-16 05:54:16,570 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 13 of 32

2025-05-16 05:54:16,579 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:16,580 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:16,581 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:16,581 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:17,350 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:17,351 - Experiment - INFO - Existing run ID: 773778483d734c7da3b7bb211db36bb5
2025-05-16 05:54:17,351 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 14 of 32

2025-05-16 05:54:17,360 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:17,361 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:17,361 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:17,362 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:18,157 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:18,157 - Experiment - INFO - Existing run ID: 68a0aa05cf624b4791a13aa7f9686e46
2025-05-16 05:54:18,158 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 15 of 32

2025-05-16 05:54:18,166 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:54:18,167 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:54:18,168 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:18,168 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:54:19,145 - Experiment - INFO - Run ID: 91c12ced2d5640e2b09f19e96f1ae340
2025-05-16 05:54:19,146 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_05-54-18;rs=3250434509
2025-05-16 05:54:19,158 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 05:54:19,189 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 05:54:19,340 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000180B3AD7050>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x00000180B3AD75F0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x00000180B3AD7620>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x00000180B3AD7650>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 05:54:19,625 - Experiment - INFO - Preprocessing function 0: noise_reduction
2025-05-16 05:54:19,625 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 05:54:19,626 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:54:20,637 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 05:54:20,638 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:54:20,861 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 05:54:20,862 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 05:54:21,112 - Experiment - INFO - Preprocessing function 1: nltk_tokenizer
2025-05-16 05:54:21,112 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 05:54:21,113 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:54:24,371 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 05:54:24,372 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:54:25,052 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 05:54:25,053 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:54:25,776 - Experiment - INFO - Preprocessing function 2: stemming
2025-05-16 05:54:25,776 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 05:54:25,777 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:54:36,150 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 05:54:36,170 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:54:38,365 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 05:54:38,370 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:54:40,864 - Experiment - INFO - Preprocessing function 3: bert_base_uncased_encoder
2025-05-16 05:54:40,865 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 05:54:40,872 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

2025-05-16 05:54:55,290 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 05:54:55,312 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 05:54:58,293 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 05:54:58,298 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 05:55:04,938 - Experiment - INFO - Model name: BERT
2025-05-16 05:55:04,941 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.0, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 05:59:17,950 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 05:59:17,952 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 05:59:18,344 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6358242630958557, 'eval_accuracy': 0.8585526315789473, 'eval_precision': 0.9135135135135135, 'eval_recall': 0.8622448979591837, 'eval_f1_score': 0.8871391076115486, 'eval_roc_auc': 0.9246031746031746, 'eval_false_positives_rate': 0.14814814814814814, 'eval_false_negatives_rate': 0.1377551020408163, 'eval_runtime': 2.3116, 'eval_samples_per_second': 131.51, 'eval_steps_per_second': 8.219, 'epoch': 4.0, 'step': 356}
2025-05-16 05:59:18,345 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 05:59:22,381 - Experiment - INFO - Test metrics: {'test_loss': 0.48609745502471924, 'test_accuracy': 0.8819672131147541, 'test_precision': 0.9292929292929293, 'test_recall': 0.8932038834951457, 'test_f1_score': 0.9108910891089109, 'test_roc_auc': 0.9484652348730018, 'test_false_positives_rate': 0.1414141414141414, 'test_false_negatives_rate': 0.10679611650485436, 'test_runtime': 4.0312, 'test_samples_per_second': 75.66, 'test_steps_per_second': 4.961, 'test_epoch': 4.0}
2025-05-16 05:59:22,407 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 05:59:22,415 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 05:59:23,080 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 05:59:23,080 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 05:59:23,081 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-178
2025-05-16 05:59:23,411 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.359281986951828, 'eval_accuracy': 0.8552631578947368, 'eval_precision': 0.88, 'eval_recall': 0.8979591836734694, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.9163359788359787, 'eval_false_positives_rate': 0.2222222222222222, 'eval_false_negatives_rate': 0.10204081632653061, 'eval_runtime': 2.2549, 'eval_samples_per_second': 134.816, 'eval_steps_per_second': 8.426, 'epoch': 2.0, 'step': 178}
2025-05-16 05:59:23,412 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 05:59:25,782 - Experiment - INFO - Test metrics: {'test_loss': 0.30948469042778015, 'test_accuracy': 0.8852459016393442, 'test_precision': 0.9170731707317074, 'test_recall': 0.912621359223301, 'test_f1_score': 0.9148418491484185, 'test_roc_auc': 0.9381680886535255, 'test_false_positives_rate': 0.1717171717171717, 'test_false_negatives_rate': 0.08737864077669903, 'test_runtime': 2.3648, 'test_samples_per_second': 128.974, 'test_steps_per_second': 8.457, 'test_epoch': 2.0}
2025-05-16 05:59:25,809 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 05:59:25,816 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 05:59:26,518 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 05:59:26,518 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 05:59:26,519 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 05:59:26,849 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6358242630958557, 'eval_accuracy': 0.8585526315789473, 'eval_precision': 0.9135135135135135, 'eval_recall': 0.8622448979591837, 'eval_f1_score': 0.8871391076115486, 'eval_roc_auc': 0.9246031746031746, 'eval_false_positives_rate': 0.14814814814814814, 'eval_false_negatives_rate': 0.1377551020408163, 'eval_runtime': 2.3116, 'eval_samples_per_second': 131.51, 'eval_steps_per_second': 8.219, 'epoch': 4.0, 'step': 356}
2025-05-16 05:59:26,850 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 05:59:29,223 - Experiment - INFO - Test metrics: {'test_loss': 0.48609745502471924, 'test_accuracy': 0.8819672131147541, 'test_precision': 0.9292929292929293, 'test_recall': 0.8932038834951457, 'test_f1_score': 0.9108910891089109, 'test_roc_auc': 0.9484652348730018, 'test_false_positives_rate': 0.1414141414141414, 'test_false_negatives_rate': 0.10679611650485436, 'test_runtime': 2.368, 'test_samples_per_second': 128.798, 'test_steps_per_second': 8.446, 'test_epoch': 4.0}
2025-05-16 05:59:29,250 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 05:59:29,258 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 05:59:29,931 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 05:59:29,931 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 05:59:29,932 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 05:59:30,256 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6358242630958557, 'eval_accuracy': 0.8585526315789473, 'eval_precision': 0.9135135135135135, 'eval_recall': 0.8622448979591837, 'eval_f1_score': 0.8871391076115486, 'eval_roc_auc': 0.9246031746031746, 'eval_false_positives_rate': 0.14814814814814814, 'eval_false_negatives_rate': 0.1377551020408163, 'eval_runtime': 2.3116, 'eval_samples_per_second': 131.51, 'eval_steps_per_second': 8.219, 'epoch': 4.0, 'step': 356}
2025-05-16 05:59:30,256 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 05:59:32,658 - Experiment - INFO - Test metrics: {'test_loss': 0.48609745502471924, 'test_accuracy': 0.8819672131147541, 'test_precision': 0.9292929292929293, 'test_recall': 0.8932038834951457, 'test_f1_score': 0.9108910891089109, 'test_roc_auc': 0.9484652348730018, 'test_false_positives_rate': 0.1414141414141414, 'test_false_negatives_rate': 0.10679611650485436, 'test_runtime': 2.3954, 'test_samples_per_second': 127.33, 'test_steps_per_second': 8.349, 'test_epoch': 4.0}
2025-05-16 05:59:32,683 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 05:59:32,690 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 05:59:33,367 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 05:59:33,367 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 05:59:33,368 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-178
2025-05-16 05:59:33,707 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.359281986951828, 'eval_accuracy': 0.8552631578947368, 'eval_precision': 0.88, 'eval_recall': 0.8979591836734694, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.9163359788359787, 'eval_false_positives_rate': 0.2222222222222222, 'eval_false_negatives_rate': 0.10204081632653061, 'eval_runtime': 2.2549, 'eval_samples_per_second': 134.816, 'eval_steps_per_second': 8.426, 'epoch': 2.0, 'step': 178}
2025-05-16 05:59:33,707 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 05:59:37,806 - Experiment - INFO - Test metrics: {'test_loss': 0.30948469042778015, 'test_accuracy': 0.8852459016393442, 'test_precision': 0.9170731707317074, 'test_recall': 0.912621359223301, 'test_f1_score': 0.9148418491484185, 'test_roc_auc': 0.9381680886535255, 'test_false_positives_rate': 0.1717171717171717, 'test_false_negatives_rate': 0.08737864077669903, 'test_runtime': 4.0907, 'test_samples_per_second': 74.56, 'test_steps_per_second': 4.889, 'test_epoch': 2.0}
2025-05-16 05:59:37,895 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 05:59:37,924 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 05:59:39,100 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 05:59:39,101 - Experiment - INFO - Finished model evaluations stage.

### Run 16 of 32

2025-05-16 05:59:39,184 - Experiment - INFO - MLflow experiment initialized with ID: 826745395964684280
2025-05-16 05:59:39,185 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 05:59:39,186 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:59:39,187 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 05:59:40,435 - Experiment - INFO - Run ID: 40d7cf5f0efe4b53b530363a0c3a542a
2025-05-16 05:59:40,436 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_05-59-40;rs=1609913082
2025-05-16 05:59:40,447 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 05:59:40,482 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 05:59:40,638 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000180B3AD7050>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x00000180B3AD75F0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x00000180B3AD7620>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x00000180B3AD7650>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 05:59:40,852 - Experiment - INFO - Preprocessing function 0: noise_reduction
2025-05-16 05:59:40,853 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 05:59:40,855 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:59:41,858 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 05:59:41,859 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:59:42,107 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 05:59:42,108 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 05:59:42,360 - Experiment - INFO - Preprocessing function 1: nltk_tokenizer
2025-05-16 05:59:42,361 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 05:59:42,361 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:59:45,429 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 05:59:45,430 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:59:46,185 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 05:59:46,186 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:59:46,953 - Experiment - INFO - Preprocessing function 2: stemming
2025-05-16 05:59:46,953 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 05:59:46,954 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:59:57,269 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 05:59:57,290 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 05:59:59,673 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 05:59:59,678 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 06:00:02,402 - Experiment - INFO - Preprocessing function 3: bert_base_uncased_encoder
2025-05-16 06:00:02,403 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 06:00:02,409 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

2025-05-16 06:00:15,015 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 06:00:15,040 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 06:00:17,985 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 06:00:17,990 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 06:00:24,404 - Experiment - INFO - Model name: BERT
2025-05-16 06:00:24,408 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

KeyboardInterrupt:

### EUvsDisinfo Dataset

In [ ]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### ISOT Dataset

In [ ]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### CZ Dataset

In [ ]:
cz_pipelines = []

for max_tokens in max_tokens_params:
    cz_pipelines.extend([PreprocessingPipeline(name='minimal',
                                               iterable=[Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction',
                                               iterable=[NoiseReduction(),
                                                         Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Lemmatization(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_stemming',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Stemming(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)])
                         ])
# optional - for testing purposes, if you want to run fast test on very small datasets
# truncate(cz_pipelines, fraction=0.1)

cz_dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': cz_pipelines})
print('Dataset Hyperparameters Grid Size: ', len(cz_dataset_hparams_grid))
print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(cz_dataset_hparams_grid) * len(model_hparams_grid))

In [ ]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          cz_dataset_hparams_grid,
                          model_hparams_grid)