In [2]:
from workspace.sources.local_datasets.preprocessing.tokenization import NLTKTokenizer
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction, Lemmatization, Stemming
from workspace.sources.experiments.metrics import Loss
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.utils import class_name_to_str
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.local_datasets.preprocessing.utils import truncate
from sklearn.model_selection import ParameterGrid
from IPython.display import display, Markdown

from workspace.sources.local_datasets.preprocessing.encoders.encoders import DistilliBERT_Encoder as Encoder
from workspace.sources.models.transformers.bert_based_models import DistilliBERT as Model

import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [3]:
experiment_name = f'prefinal-{class_name_to_str(Model.__name__)}-v2'
print('Experiment:', experiment_name)

Experiment: prefinal-distilli_bert-v2

In [4]:
def conduct_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid):
    total_runs = len(dataset_hparams_grid) * len(model_hparams_grid)
    for i, dataset_params in enumerate(dataset_hparams_grid):
        for j, model_hparams in enumerate(model_hparams_grid):
            run_number = i * len(model_hparams_grid) + j + 1
            display(Markdown(f'### Run {run_number} of {total_runs}'))
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = Model(train_best_model_metric=Loss,
                           training_arguments=model_hparams)

            experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            experiment.run()
            experiment.prune_artifacts()

In [5]:

# max_tokens_params = [128, 512]
max_tokens_params = [128, 256]

pipelines = []

for max_tokens in max_tokens_params:
    pipelines.extend([PreprocessingPipeline(name='minimal',
                                            iterable=[Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction',
                                            iterable=[NoiseReduction(),
                                                      Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Lemmatization(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_stemming',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Stemming(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)])
                      ])
# optional - for testing purposes, if you want to run fast test on very small datasets
# truncate(pipelines, fraction=0.05)

dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': pipelines})

print('Dataset Hyperparameters Grid Size: ', len(dataset_hparams_grid))

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16],
                                    'learning_rate': [5e-05],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})


print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### ReCOVery Dataset

In [13]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 4

2025/05/16 01:02:48 INFO mlflow.tracking.fluent: Experiment with name 'prefinal-distilli_bert-v2' does not exist. Creating a new experiment.
2025-05-16 01:02:48,992 - Experiment - INFO - MLflow experiment initialized with ID: 701195748125061381
2025-05-16 01:02:48,993 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:02:48,994 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:02:48,994 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:02:49,051 - Experiment - INFO - Run ID: 53f0f085b3824bb39f82ce1063e8edcf
2025-05-16 01:02:49,052 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_01-02-48;rs=2836665775
2025-05-16 01:02:49,064 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:02:49,086 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:02:49,252 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001CAA819B6B0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x000001CA922BD2E0>]>
2025-05-16 01:02:49,494 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:02:49,495 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:02:49,496 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:02:49,520 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:02:49,522 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:02:49,535 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:02:49,536 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:02:49,731 - Experiment - INFO - Preprocessing function 1: distilli_bert__encoder
2025-05-16 01:02:49,733 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:02:49,734 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:02:50,222 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:02:50,223 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:02:50,390 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:02:50,392 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:02:51,268 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 01:02:51,272 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:03:05,405 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:03:05,406 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:03:05,729 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4768519699573517, 'eval_accuracy': 0.8, 'eval_precision': 0.8333333333333334, 'eval_recall': 0.9090909090909091, 'eval_f1_score': 0.8695652173913043, 'eval_roc_auc': 0.8409090909090909, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.09090909090909091, 'eval_runtime': 0.0663, 'eval_samples_per_second': 226.168, 'eval_steps_per_second': 15.078, 'epoch': 4.0, 'step': 20}
2025-05-16 01:03:05,730 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:03:05,801 - Experiment - INFO - Test metrics: {'test_loss': 0.6357678771018982, 'test_accuracy': 0.6, 'test_precision': 0.5454545454545454, 'test_recall': 0.8571428571428571, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.7857142857142857, 'test_false_positives_rate': 0.625, 'test_false_negatives_rate': 0.14285714285714285, 'test_runtime': 0.0704, 'test_samples_per_second': 213.065, 'test_steps_per_second': 14.204, 'test_epoch': 4.0}
2025-05-16 01:03:05,827 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:05,830 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:05,872 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:05,873 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:03:05,873 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:03:06,118 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4769511818885803, 'eval_accuracy': 0.8, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9090909090909091, 'eval_false_positives_rate': 0.75, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.082, 'eval_samples_per_second': 182.944, 'eval_steps_per_second': 12.196, 'epoch': 5.0, 'step': 25}
2025-05-16 01:03:06,119 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:03:06,187 - Experiment - INFO - Test metrics: {'test_loss': 0.9866457581520081, 'test_accuracy': 0.6, 'test_precision': 0.5384615384615384, 'test_recall': 1.0, 'test_f1_score': 0.7, 'test_roc_auc': 0.8392857142857142, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0638, 'test_samples_per_second': 235.176, 'test_steps_per_second': 15.678, 'test_epoch': 5.0}
2025-05-16 01:03:06,206 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:06,208 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:06,247 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:06,247 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:03:06,248 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:03:06,495 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4768519699573517, 'eval_accuracy': 0.8, 'eval_precision': 0.8333333333333334, 'eval_recall': 0.9090909090909091, 'eval_f1_score': 0.8695652173913043, 'eval_roc_auc': 0.8409090909090909, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.09090909090909091, 'eval_runtime': 0.0663, 'eval_samples_per_second': 226.168, 'eval_steps_per_second': 15.078, 'epoch': 4.0, 'step': 20}
2025-05-16 01:03:06,495 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:03:06,569 - Experiment - INFO - Test metrics: {'test_loss': 0.6357678771018982, 'test_accuracy': 0.6, 'test_precision': 0.5454545454545454, 'test_recall': 0.8571428571428571, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.7857142857142857, 'test_false_positives_rate': 0.625, 'test_false_negatives_rate': 0.14285714285714285, 'test_runtime': 0.0684, 'test_samples_per_second': 219.179, 'test_steps_per_second': 14.612, 'test_epoch': 4.0}
2025-05-16 01:03:06,586 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:06,588 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:06,629 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:06,631 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:03:06,632 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:03:06,914 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4769511818885803, 'eval_accuracy': 0.8, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9090909090909091, 'eval_false_positives_rate': 0.75, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.082, 'eval_samples_per_second': 182.944, 'eval_steps_per_second': 12.196, 'epoch': 5.0, 'step': 25}
2025-05-16 01:03:06,915 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:03:06,985 - Experiment - INFO - Test metrics: {'test_loss': 0.9866457581520081, 'test_accuracy': 0.6, 'test_precision': 0.5384615384615384, 'test_recall': 1.0, 'test_f1_score': 0.7, 'test_roc_auc': 0.8392857142857142, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0646, 'test_samples_per_second': 232.06, 'test_steps_per_second': 15.471, 'test_epoch': 5.0}
2025-05-16 01:03:07,003 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:07,004 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:07,079 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:07,080 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:03:07,080 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:03:07,294 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4768519699573517, 'eval_accuracy': 0.8, 'eval_precision': 0.8333333333333334, 'eval_recall': 0.9090909090909091, 'eval_f1_score': 0.8695652173913043, 'eval_roc_auc': 0.8409090909090909, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.09090909090909091, 'eval_runtime': 0.0663, 'eval_samples_per_second': 226.168, 'eval_steps_per_second': 15.078, 'epoch': 4.0, 'step': 20}
2025-05-16 01:03:07,295 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:03:07,375 - Experiment - INFO - Test metrics: {'test_loss': 0.6357678771018982, 'test_accuracy': 0.6, 'test_precision': 0.5454545454545454, 'test_recall': 0.8571428571428571, 'test_f1_score': 0.6666666666666666, 'test_roc_auc': 0.7857142857142857, 'test_false_positives_rate': 0.625, 'test_false_negatives_rate': 0.14285714285714285, 'test_runtime': 0.0749, 'test_samples_per_second': 200.289, 'test_steps_per_second': 13.353, 'test_epoch': 4.0}
2025-05-16 01:03:07,399 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:07,401 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:07,441 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:07,442 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 4

2025-05-16 01:03:08,450 - Experiment - INFO - MLflow experiment initialized with ID: 701195748125061381
2025-05-16 01:03:08,451 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:03:08,451 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:03:08,452 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:03:09,263 - Experiment - INFO - Run ID: 6a44460c17804c24a8b1d036d53eeace
2025-05-16 01:03:09,264 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_01-03-09;rs=4005228123
2025-05-16 01:03:09,287 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:03:09,319 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:03:09,494 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001CAA819BD40>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001CAA819B7A0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x000001CAA819A300>]>
2025-05-16 01:03:09,663 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:03:09,663 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:03:09,663 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:09,695 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:03:09,697 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:09,706 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:03:09,707 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:09,716 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:03:09,717 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:03:09,718 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:09,786 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:03:09,787 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:09,813 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:03:09,814 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:10,017 - Experiment - INFO - Preprocessing function 2: distilli_bert__encoder
2025-05-16 01:03:10,018 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:03:10,019 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:03:10,428 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:03:10,428 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:03:10,556 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:03:10,557 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:03:11,262 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 01:03:11,266 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:03:23,438 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:03:23,439 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:03:23,666 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7565591335296631, 'eval_accuracy': 0.6, 'eval_precision': 0.5833333333333334, 'eval_recall': 0.875, 'eval_f1_score': 0.7, 'eval_roc_auc': 0.6785714285714286, 'eval_false_positives_rate': 0.7142857142857143, 'eval_false_negatives_rate': 0.125, 'eval_runtime': 0.0766, 'eval_samples_per_second': 195.939, 'eval_steps_per_second': 13.063, 'epoch': 5.0, 'step': 25}
2025-05-16 01:03:23,667 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:03:23,751 - Experiment - INFO - Test metrics: {'test_loss': 0.32011541724205017, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8461538461538461, 'test_recall': 1.0, 'test_f1_score': 0.9166666666666666, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0799, 'test_samples_per_second': 187.692, 'test_steps_per_second': 12.513, 'test_epoch': 5.0}
2025-05-16 01:03:23,770 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:23,773 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:23,815 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:23,816 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:03:23,817 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:03:24,059 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7565591335296631, 'eval_accuracy': 0.6, 'eval_precision': 0.5833333333333334, 'eval_recall': 0.875, 'eval_f1_score': 0.7, 'eval_roc_auc': 0.6785714285714286, 'eval_false_positives_rate': 0.7142857142857143, 'eval_false_negatives_rate': 0.125, 'eval_runtime': 0.0766, 'eval_samples_per_second': 195.939, 'eval_steps_per_second': 13.063, 'epoch': 5.0, 'step': 25}
2025-05-16 01:03:24,060 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:03:24,128 - Experiment - INFO - Test metrics: {'test_loss': 0.32011541724205017, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8461538461538461, 'test_recall': 1.0, 'test_f1_score': 0.9166666666666666, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0627, 'test_samples_per_second': 239.255, 'test_steps_per_second': 15.95, 'test_epoch': 5.0}
2025-05-16 01:03:24,149 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:24,151 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:24,190 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:24,191 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:03:24,192 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:03:24,431 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7565591335296631, 'eval_accuracy': 0.6, 'eval_precision': 0.5833333333333334, 'eval_recall': 0.875, 'eval_f1_score': 0.7, 'eval_roc_auc': 0.6785714285714286, 'eval_false_positives_rate': 0.7142857142857143, 'eval_false_negatives_rate': 0.125, 'eval_runtime': 0.0766, 'eval_samples_per_second': 195.939, 'eval_steps_per_second': 13.063, 'epoch': 5.0, 'step': 25}
2025-05-16 01:03:24,432 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:03:24,505 - Experiment - INFO - Test metrics: {'test_loss': 0.32011541724205017, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8461538461538461, 'test_recall': 1.0, 'test_f1_score': 0.9166666666666666, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0697, 'test_samples_per_second': 215.285, 'test_steps_per_second': 14.352, 'test_epoch': 5.0}
2025-05-16 01:03:24,526 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:24,528 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:24,574 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:24,575 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:03:24,576 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:03:24,868 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7248929142951965, 'eval_accuracy': 0.5333333333333333, 'eval_precision': 0.5333333333333333, 'eval_recall': 1.0, 'eval_f1_score': 0.6956521739130435, 'eval_roc_auc': 0.7142857142857143, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0796, 'eval_samples_per_second': 188.517, 'eval_steps_per_second': 12.568, 'epoch': 3.0, 'step': 15}
2025-05-16 01:03:24,869 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:03:24,947 - Experiment - INFO - Test metrics: {'test_loss': 0.4287203550338745, 'test_accuracy': 0.8, 'test_precision': 0.7857142857142857, 'test_recall': 1.0, 'test_f1_score': 0.88, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0701, 'test_samples_per_second': 213.951, 'test_steps_per_second': 14.263, 'test_epoch': 3.0}
2025-05-16 01:03:24,964 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:24,967 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:25,004 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:25,005 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:03:25,006 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:03:25,249 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6854579448699951, 'eval_accuracy': 0.5333333333333333, 'eval_precision': 0.5333333333333333, 'eval_recall': 1.0, 'eval_f1_score': 0.6956521739130435, 'eval_roc_auc': 0.6607142857142856, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0717, 'eval_samples_per_second': 209.177, 'eval_steps_per_second': 13.945, 'epoch': 2.0, 'step': 10}
2025-05-16 01:03:25,249 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:03:25,325 - Experiment - INFO - Test metrics: {'test_loss': 0.5222316384315491, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7333333333333333, 'test_recall': 1.0, 'test_f1_score': 0.8461538461538461, 'test_roc_auc': 0.9772727272727273, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0722, 'test_samples_per_second': 207.698, 'test_steps_per_second': 13.847, 'test_epoch': 2.0}
2025-05-16 01:03:25,345 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:25,346 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:25,389 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:25,390 - Experiment - INFO - Finished model evaluations stage.

### Run 3 of 4

2025-05-16 01:03:25,466 - Experiment - INFO - MLflow experiment initialized with ID: 701195748125061381
2025-05-16 01:03:25,467 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:03:25,468 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:03:25,469 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:03:26,390 - Experiment - INFO - Run ID: 5d7033762c4047e585ef964d1427d14f
2025-05-16 01:03:26,391 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_01-03-26;rs=3836033089
2025-05-16 01:03:26,403 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:03:26,440 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:03:26,600 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001CAA819A540>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001CAA81984D0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x000001CAA8199730>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x000001CAA819B020>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x000001CAA819BE90>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:03:26,768 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:03:26,769 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:03:26,770 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:26,787 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:03:26,788 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:26,798 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:03:26,799 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:26,809 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:03:26,810 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:03:26,811 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:26,875 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:03:26,877 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:26,904 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:03:26,905 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:03:26,928 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:03:26,929 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:03:26,929 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:27,107 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:03:27,108 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:27,155 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:03:27,156 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:27,208 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 01:03:27,209 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:03:27,209 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:27,271 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:03:27,273 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:27,294 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:03:27,296 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:03:27,720 - Experiment - INFO - Preprocessing function 4: distilli_bert__encoder
2025-05-16 01:03:27,721 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:03:27,722 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:03:28,552 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:03:28,553 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:03:28,775 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:03:28,776 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:03:29,572 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 01:03:29,576 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:03:56,894 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:03:56,895 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-30
2025-05-16 01:03:57,241 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.386413037776947, 'eval_accuracy': 0.8, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9090909090909091, 'eval_false_positives_rate': 0.75, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0664, 'eval_samples_per_second': 225.762, 'eval_steps_per_second': 15.051, 'epoch': 6.0, 'step': 30}
2025-05-16 01:03:57,242 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 01:03:57,336 - Experiment - INFO - Test metrics: {'test_loss': 0.7300254106521606, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.8214285714285714, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0888, 'test_samples_per_second': 168.859, 'test_steps_per_second': 11.257, 'test_epoch': 6.0}
2025-05-16 01:03:57,368 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:57,372 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:57,416 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:57,418 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:03:57,419 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-30
2025-05-16 01:03:57,676 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.386413037776947, 'eval_accuracy': 0.8, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9090909090909091, 'eval_false_positives_rate': 0.75, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0664, 'eval_samples_per_second': 225.762, 'eval_steps_per_second': 15.051, 'epoch': 6.0, 'step': 30}
2025-05-16 01:03:57,677 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 01:03:57,783 - Experiment - INFO - Test metrics: {'test_loss': 0.7300254106521606, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.8214285714285714, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1023, 'test_samples_per_second': 146.692, 'test_steps_per_second': 9.779, 'test_epoch': 6.0}
2025-05-16 01:03:57,804 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:57,806 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:57,842 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:57,843 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:03:57,844 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-30
2025-05-16 01:03:58,167 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.386413037776947, 'eval_accuracy': 0.8, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9090909090909091, 'eval_false_positives_rate': 0.75, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0664, 'eval_samples_per_second': 225.762, 'eval_steps_per_second': 15.051, 'epoch': 6.0, 'step': 30}
2025-05-16 01:03:58,169 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 01:03:58,285 - Experiment - INFO - Test metrics: {'test_loss': 0.7300254106521606, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.8214285714285714, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1108, 'test_samples_per_second': 135.409, 'test_steps_per_second': 9.027, 'test_epoch': 6.0}
2025-05-16 01:03:58,304 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:58,307 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:58,347 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:58,348 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:03:58,348 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:03:58,677 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5319656729698181, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.7333333333333333, 'eval_recall': 1.0, 'eval_f1_score': 0.8461538461538461, 'eval_roc_auc': 0.9090909090909092, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.234, 'eval_samples_per_second': 64.114, 'eval_steps_per_second': 4.274, 'epoch': 2.0, 'step': 10}
2025-05-16 01:03:58,678 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:03:58,756 - Experiment - INFO - Test metrics: {'test_loss': 0.7430039644241333, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.5333333333333333, 'test_recall': 1.0, 'test_f1_score': 0.6956521739130435, 'test_roc_auc': 0.7321428571428571, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0738, 'test_samples_per_second': 203.218, 'test_steps_per_second': 13.548, 'test_epoch': 2.0}
2025-05-16 01:03:58,777 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:58,778 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:58,816 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:58,817 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:03:58,818 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-30
2025-05-16 01:03:59,087 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.386413037776947, 'eval_accuracy': 0.8, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9090909090909091, 'eval_false_positives_rate': 0.75, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0664, 'eval_samples_per_second': 225.762, 'eval_steps_per_second': 15.051, 'epoch': 6.0, 'step': 30}
2025-05-16 01:03:59,088 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 01:03:59,163 - Experiment - INFO - Test metrics: {'test_loss': 0.7300254106521606, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.8214285714285714, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0718, 'test_samples_per_second': 208.776, 'test_steps_per_second': 13.918, 'test_epoch': 6.0}
2025-05-16 01:03:59,183 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:03:59,185 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:03:59,223 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:03:59,224 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 01:03:59,932 - Experiment - INFO - MLflow experiment initialized with ID: 701195748125061381
2025-05-16 01:03:59,933 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:03:59,933 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:03:59,934 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:04:01,115 - Experiment - INFO - Run ID: a8f6e48fe3114e70af7dc187e8875322
2025-05-16 01:04:01,116 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_01-04-01;rs=3451869701
2025-05-16 01:04:01,131 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:04:01,174 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:04:01,369 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001CAA81987A0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001CAA8199280>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x000001CAA819BC20>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x000001CAA8199AF0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x000001CAA819AF30>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:04:01,538 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:04:01,539 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:04:01,540 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:01,557 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:04:01,558 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:01,571 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:04:01,573 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:01,583 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:04:01,584 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:04:01,585 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:01,650 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:04:01,651 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:01,673 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:04:01,674 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:04:01,694 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:04:01,694 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:04:01,695 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:01,873 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:04:01,873 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:01,922 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:04:01,923 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:01,958 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 01:04:01,959 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:04:01,960 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:02,559 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:04:02,562 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:02,710 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:04:02,711 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:04:02,973 - Experiment - INFO - Preprocessing function 4: distilli_bert__encoder
2025-05-16 01:04:02,973 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:04:02,975 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:04:03,786 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:04:03,788 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:04:04,059 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:04:04,061 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:04:04,786 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 01:04:04,792 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:04:29,114 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:04:29,115 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:04:29,373 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3494666516780853, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8571428571428571, 'eval_recall': 1.0, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 0.861111111111111, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0915, 'eval_samples_per_second': 163.913, 'eval_steps_per_second': 10.928, 'epoch': 10.0, 'step': 50}
2025-05-16 01:04:29,373 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:04:29,465 - Experiment - INFO - Test metrics: {'test_loss': 0.464690625667572, 'test_accuracy': 0.8, 'test_precision': 0.7857142857142857, 'test_recall': 1.0, 'test_f1_score': 0.88, 'test_roc_auc': 0.8636363636363636, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0888, 'test_samples_per_second': 168.957, 'test_steps_per_second': 11.264, 'test_epoch': 10.0}
2025-05-16 01:04:29,482 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:04:29,484 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:04:29,523 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:04:29,524 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:04:29,525 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:04:29,780 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3494666516780853, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8571428571428571, 'eval_recall': 1.0, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 0.861111111111111, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0915, 'eval_samples_per_second': 163.913, 'eval_steps_per_second': 10.928, 'epoch': 10.0, 'step': 50}
2025-05-16 01:04:29,782 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:04:29,880 - Experiment - INFO - Test metrics: {'test_loss': 0.464690625667572, 'test_accuracy': 0.8, 'test_precision': 0.7857142857142857, 'test_recall': 1.0, 'test_f1_score': 0.88, 'test_roc_auc': 0.8636363636363636, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0924, 'test_samples_per_second': 162.36, 'test_steps_per_second': 10.824, 'test_epoch': 10.0}
2025-05-16 01:04:29,908 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:04:29,911 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:04:29,961 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:04:29,962 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:04:29,962 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:04:30,401 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3494666516780853, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8571428571428571, 'eval_recall': 1.0, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 0.861111111111111, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0915, 'eval_samples_per_second': 163.913, 'eval_steps_per_second': 10.928, 'epoch': 10.0, 'step': 50}
2025-05-16 01:04:30,404 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:04:30,500 - Experiment - INFO - Test metrics: {'test_loss': 0.464690625667572, 'test_accuracy': 0.8, 'test_precision': 0.7857142857142857, 'test_recall': 1.0, 'test_f1_score': 0.88, 'test_roc_auc': 0.8636363636363636, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0885, 'test_samples_per_second': 169.449, 'test_steps_per_second': 11.297, 'test_epoch': 10.0}
2025-05-16 01:04:30,524 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:04:30,528 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:04:30,576 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:04:30,577 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:04:30,579 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:04:30,902 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3494666516780853, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8571428571428571, 'eval_recall': 1.0, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 0.861111111111111, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0915, 'eval_samples_per_second': 163.913, 'eval_steps_per_second': 10.928, 'epoch': 10.0, 'step': 50}
2025-05-16 01:04:30,903 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:04:31,005 - Experiment - INFO - Test metrics: {'test_loss': 0.464690625667572, 'test_accuracy': 0.8, 'test_precision': 0.7857142857142857, 'test_recall': 1.0, 'test_f1_score': 0.88, 'test_roc_auc': 0.8636363636363636, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0965, 'test_samples_per_second': 155.386, 'test_steps_per_second': 10.359, 'test_epoch': 10.0}
2025-05-16 01:04:31,027 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:04:31,029 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:04:31,080 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:04:31,081 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:04:31,081 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:04:31,388 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3494666516780853, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8571428571428571, 'eval_recall': 1.0, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 0.861111111111111, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0915, 'eval_samples_per_second': 163.913, 'eval_steps_per_second': 10.928, 'epoch': 10.0, 'step': 50}
2025-05-16 01:04:31,390 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:04:31,500 - Experiment - INFO - Test metrics: {'test_loss': 0.464690625667572, 'test_accuracy': 0.8, 'test_precision': 0.7857142857142857, 'test_recall': 1.0, 'test_f1_score': 0.88, 'test_roc_auc': 0.8636363636363636, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1035, 'test_samples_per_second': 144.897, 'test_steps_per_second': 9.66, 'test_epoch': 10.0}
2025-05-16 01:04:31,538 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:04:31,542 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:04:31,645 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:04:31,647 - Experiment - INFO - Finished model evaluations stage.

### EUvsDisinfo Dataset

In [ ]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### ISOT Dataset

In [ ]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### CZ Dataset

In [6]:
cz_pipelines = []

for max_tokens in max_tokens_params:
    cz_pipelines.extend([PreprocessingPipeline(name='minimal',
                                               iterable=[Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction',
                                               iterable=[NoiseReduction(),
                                                         Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Lemmatization(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_stemming',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Stemming(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)])
                         ])
# optional - for testing purposes, if you want to run fast test on very small datasets
# truncate(cz_pipelines, fraction=0.1)

cz_dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': cz_pipelines})
print('Dataset Hyperparameters Grid Size: ', len(cz_dataset_hparams_grid))
print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(cz_dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

In [7]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          cz_dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 4

2025-05-16 01:25:51,699 - Experiment - INFO - MLflow experiment initialized with ID: 701195748125061381
2025-05-16 01:25:51,700 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:25:51,701 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:25:51,702 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:25:52,877 - Experiment - INFO - Run ID: 73ea8a711d184207afdf21a2f4ac9ba0
2025-05-16 01:25:52,883 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_01-25-52;rs=4146393939
2025-05-16 01:25:52,897 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:25:52,923 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:25:53,035 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000023F86C8B680>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000023F86C8A660>]>
2025-05-16 01:25:53,382 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:25:53,382 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:25:53,382 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:53,407 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:25:53,408 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:53,423 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:25:53,426 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:25:53,626 - Experiment - INFO - Preprocessing function 1: distilli_bert__encoder
2025-05-16 01:25:53,626 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:25:53,627 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:25:54,085 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:25:54,088 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:25:54,290 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:25:54,291 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:25:54,700 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 01:25:54,705 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:26:13,275 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:26:13,276 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:26:13,518 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3789241909980774, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 0.9090909090909091, 'eval_recall': 1.0, 'eval_f1_score': 0.9523809523809523, 'eval_roc_auc': 0.975, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0716, 'eval_samples_per_second': 195.414, 'eval_steps_per_second': 13.958, 'epoch': 3.0, 'step': 15}
2025-05-16 01:26:13,518 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:26:13,599 - Experiment - INFO - Test metrics: {'test_loss': 0.42834699153900146, 'test_accuracy': 0.9333333333333333, 'test_precision': 0.9230769230769231, 'test_recall': 1.0, 'test_f1_score': 0.96, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0798, 'test_samples_per_second': 187.977, 'test_steps_per_second': 12.532, 'test_epoch': 3.0}
2025-05-16 01:26:13,619 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:13,621 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:13,662 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:13,663 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:26:13,664 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:26:13,914 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3789241909980774, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 0.9090909090909091, 'eval_recall': 1.0, 'eval_f1_score': 0.9523809523809523, 'eval_roc_auc': 0.975, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0716, 'eval_samples_per_second': 195.414, 'eval_steps_per_second': 13.958, 'epoch': 3.0, 'step': 15}
2025-05-16 01:26:13,916 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:26:14,000 - Experiment - INFO - Test metrics: {'test_loss': 0.42834699153900146, 'test_accuracy': 0.9333333333333333, 'test_precision': 0.9230769230769231, 'test_recall': 1.0, 'test_f1_score': 0.96, 'test_roc_auc': 0.8333333333333334, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0778, 'test_samples_per_second': 192.713, 'test_steps_per_second': 12.848, 'test_epoch': 3.0}
2025-05-16 01:26:14,224 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:14,228 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:14,284 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:14,286 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:26:14,287 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:26:14,951 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3116833567619324, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.9, 'eval_recall': 0.9, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.975, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.0676, 'eval_samples_per_second': 207.215, 'eval_steps_per_second': 14.801, 'epoch': 4.0, 'step': 20}
2025-05-16 01:26:14,951 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:26:15,059 - Experiment - INFO - Test metrics: {'test_loss': 0.4083625078201294, 'test_accuracy': 0.8, 'test_precision': 0.9090909090909091, 'test_recall': 0.8333333333333334, 'test_f1_score': 0.8695652173913043, 'test_roc_auc': 0.8611111111111112, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.16666666666666666, 'test_runtime': 0.1056, 'test_samples_per_second': 142.0, 'test_steps_per_second': 9.467, 'test_epoch': 4.0}
2025-05-16 01:26:15,089 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:15,091 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:15,133 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:15,134 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:26:15,135 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:26:15,418 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3116833567619324, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.9, 'eval_recall': 0.9, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.975, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.0676, 'eval_samples_per_second': 207.215, 'eval_steps_per_second': 14.801, 'epoch': 4.0, 'step': 20}
2025-05-16 01:26:15,418 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:26:15,513 - Experiment - INFO - Test metrics: {'test_loss': 0.4083625078201294, 'test_accuracy': 0.8, 'test_precision': 0.9090909090909091, 'test_recall': 0.8333333333333334, 'test_f1_score': 0.8695652173913043, 'test_roc_auc': 0.8611111111111112, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.16666666666666666, 'test_runtime': 0.0903, 'test_samples_per_second': 166.138, 'test_steps_per_second': 11.076, 'test_epoch': 4.0}
2025-05-16 01:26:15,549 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:15,551 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:15,595 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:15,597 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:26:15,597 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:26:15,843 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3116833567619324, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.9, 'eval_recall': 0.9, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.975, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.0676, 'eval_samples_per_second': 207.215, 'eval_steps_per_second': 14.801, 'epoch': 4.0, 'step': 20}
2025-05-16 01:26:15,844 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:26:15,937 - Experiment - INFO - Test metrics: {'test_loss': 0.4083625078201294, 'test_accuracy': 0.8, 'test_precision': 0.9090909090909091, 'test_recall': 0.8333333333333334, 'test_f1_score': 0.8695652173913043, 'test_roc_auc': 0.8611111111111112, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.16666666666666666, 'test_runtime': 0.0884, 'test_samples_per_second': 169.604, 'test_steps_per_second': 11.307, 'test_epoch': 4.0}
2025-05-16 01:26:15,953 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:15,955 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:15,998 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:15,999 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 4

2025-05-16 01:26:16,314 - Experiment - INFO - MLflow experiment initialized with ID: 701195748125061381
2025-05-16 01:26:16,314 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:26:16,315 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:26:16,315 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 01:26:17,305 - Experiment - INFO - Run ID: 0f3ce7dba43c415fae831860ffa97671
2025-05-16 01:26:17,305 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_01-26-17;rs=1951543204
2025-05-16 01:26:17,315 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:26:17,334 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:26:17,438 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000023F86C8A450>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000023F86C8AE70>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000023F86C8A240>]>
2025-05-16 01:26:17,601 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:26:17,602 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:26:17,603 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:17,617 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:26:17,618 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:17,626 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:26:17,627 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:17,636 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:26:17,637 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:26:17,637 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:17,696 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:26:17,697 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:17,714 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:26:17,716 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:17,897 - Experiment - INFO - Preprocessing function 2: distilli_bert__encoder
2025-05-16 01:26:17,898 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:26:17,898 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:26:18,301 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:26:18,303 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:26:18,431 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:26:18,432 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:26:18,826 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 01:26:18,829 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:26:28,035 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:26:28,035 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:26:28,305 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6788116693496704, 'eval_accuracy': 0.5714285714285714, 'eval_precision': 0.625, 'eval_recall': 0.625, 'eval_f1_score': 0.625, 'eval_roc_auc': 0.625, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.375, 'eval_runtime': 0.0629, 'eval_samples_per_second': 222.47, 'eval_steps_per_second': 15.891, 'epoch': 4.0, 'step': 20}
2025-05-16 01:26:28,306 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:26:28,456 - Experiment - INFO - Test metrics: {'test_loss': 0.6625257730484009, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.8571428571428571, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.75, 'test_roc_auc': 0.7592592592592592, 'test_false_positives_rate': 0.16666666666666666, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.1404, 'test_samples_per_second': 106.802, 'test_steps_per_second': 7.12, 'test_epoch': 4.0}
2025-05-16 01:26:28,540 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:28,556 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:28,763 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:28,766 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:26:28,771 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:26:29,861 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6880255937576294, 'eval_accuracy': 0.6428571428571429, 'eval_precision': 0.6153846153846154, 'eval_recall': 1.0, 'eval_f1_score': 0.7619047619047619, 'eval_roc_auc': 0.5416666666666667, 'eval_false_positives_rate': 0.8333333333333334, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0633, 'eval_samples_per_second': 221.202, 'eval_steps_per_second': 15.8, 'epoch': 2.0, 'step': 10}
2025-05-16 01:26:29,866 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:26:30,232 - Experiment - INFO - Test metrics: {'test_loss': 0.6863698959350586, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.7962962962962963, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.3461, 'test_samples_per_second': 43.337, 'test_steps_per_second': 2.889, 'test_epoch': 2.0}
2025-05-16 01:26:30,308 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:30,316 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:30,408 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:30,410 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:26:30,410 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:26:30,669 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6788116693496704, 'eval_accuracy': 0.5714285714285714, 'eval_precision': 0.625, 'eval_recall': 0.625, 'eval_f1_score': 0.625, 'eval_roc_auc': 0.625, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.375, 'eval_runtime': 0.0629, 'eval_samples_per_second': 222.47, 'eval_steps_per_second': 15.891, 'epoch': 4.0, 'step': 20}
2025-05-16 01:26:30,670 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:26:30,865 - Experiment - INFO - Test metrics: {'test_loss': 0.6625257730484009, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.8571428571428571, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.75, 'test_roc_auc': 0.7592592592592592, 'test_false_positives_rate': 0.16666666666666666, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.1895, 'test_samples_per_second': 79.151, 'test_steps_per_second': 5.277, 'test_epoch': 4.0}
2025-05-16 01:26:30,887 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:30,889 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:30,935 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:30,936 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:26:30,937 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-5
2025-05-16 01:26:31,208 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6793552041053772, 'eval_accuracy': 0.5714285714285714, 'eval_precision': 0.5714285714285714, 'eval_recall': 1.0, 'eval_f1_score': 0.7272727272727273, 'eval_roc_auc': 0.7916666666666667, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0664, 'eval_samples_per_second': 210.709, 'eval_steps_per_second': 15.051, 'epoch': 1.0, 'step': 5}
2025-05-16 01:26:31,209 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 01:26:31,298 - Experiment - INFO - Test metrics: {'test_loss': 0.6711522340774536, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.7592592592592593, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0838, 'test_samples_per_second': 179.037, 'test_steps_per_second': 11.936, 'test_epoch': 1.0}
2025-05-16 01:26:31,313 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:31,315 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:31,361 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:31,362 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:26:31,363 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:26:31,575 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6788116693496704, 'eval_accuracy': 0.5714285714285714, 'eval_precision': 0.625, 'eval_recall': 0.625, 'eval_f1_score': 0.625, 'eval_roc_auc': 0.625, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.375, 'eval_runtime': 0.0629, 'eval_samples_per_second': 222.47, 'eval_steps_per_second': 15.891, 'epoch': 4.0, 'step': 20}
2025-05-16 01:26:31,576 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:26:31,662 - Experiment - INFO - Test metrics: {'test_loss': 0.6625257730484009, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.8571428571428571, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.75, 'test_roc_auc': 0.7592592592592592, 'test_false_positives_rate': 0.16666666666666666, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.0836, 'test_samples_per_second': 179.373, 'test_steps_per_second': 11.958, 'test_epoch': 4.0}
2025-05-16 01:26:31,681 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:31,682 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:31,721 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:31,722 - Experiment - INFO - Finished model evaluations stage.

### Run 3 of 4

2025-05-16 01:26:32,075 - Experiment - INFO - MLflow experiment initialized with ID: 701195748125061381
2025-05-16 01:26:32,077 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:26:32,078 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:26:32,079 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:26:33,180 - Experiment - INFO - Run ID: ed6e0e012db248bf8ccd1311a260b3f5
2025-05-16 01:26:33,181 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_01-26-33;rs=1196969313
2025-05-16 01:26:33,191 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:26:33,223 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:26:33,325 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000023F86C8A4E0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000023F86C8B500>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000023F86C8B3B0>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000023F86C8B470>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000023F86C8B590>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:26:33,559 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:26:33,560 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:26:33,561 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:33,574 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:26:33,575 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:33,585 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:26:33,586 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:33,596 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:26:33,597 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:26:33,598 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:33,648 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:26:33,649 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:33,668 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:26:33,669 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:26:33,688 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:26:33,689 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:26:33,690 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:33,885 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:26:33,886 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:33,926 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:26:33,927 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:33,967 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 01:26:33,968 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:26:33,969 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:34,193 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:26:34,195 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:34,226 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:26:34,227 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:26:34,430 - Experiment - INFO - Preprocessing function 4: distilli_bert__encoder
2025-05-16 01:26:34,430 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:26:34,432 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:26:35,161 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:26:35,163 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:26:35,386 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:26:35,387 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:26:35,929 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 01:26:35,932 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:26:56,681 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:26:56,682 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-30
2025-05-16 01:26:56,926 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5741661787033081, 'eval_accuracy': 0.7857142857142857, 'eval_precision': 0.75, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.7959183673469387, 'eval_false_positives_rate': 0.2857142857142857, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.058, 'eval_samples_per_second': 241.381, 'eval_steps_per_second': 17.241, 'epoch': 6.0, 'step': 30}
2025-05-16 01:26:56,927 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 01:26:56,987 - Experiment - INFO - Test metrics: {'test_loss': 0.31872767210006714, 'test_accuracy': 0.9333333333333333, 'test_precision': 1.0, 'test_recall': 0.9090909090909091, 'test_f1_score': 0.9523809523809523, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.09090909090909091, 'test_runtime': 0.0548, 'test_samples_per_second': 273.678, 'test_steps_per_second': 18.245, 'test_epoch': 6.0}
2025-05-16 01:26:57,004 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:57,006 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:57,044 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:57,044 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:26:57,045 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-30
2025-05-16 01:26:57,273 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5741661787033081, 'eval_accuracy': 0.7857142857142857, 'eval_precision': 0.75, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.7959183673469387, 'eval_false_positives_rate': 0.2857142857142857, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.058, 'eval_samples_per_second': 241.381, 'eval_steps_per_second': 17.241, 'epoch': 6.0, 'step': 30}
2025-05-16 01:26:57,274 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 01:26:57,353 - Experiment - INFO - Test metrics: {'test_loss': 0.31872767210006714, 'test_accuracy': 0.9333333333333333, 'test_precision': 1.0, 'test_recall': 0.9090909090909091, 'test_f1_score': 0.9523809523809523, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.09090909090909091, 'test_runtime': 0.0744, 'test_samples_per_second': 201.739, 'test_steps_per_second': 13.449, 'test_epoch': 6.0}
2025-05-16 01:26:57,375 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:57,378 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:57,453 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:57,454 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:26:57,455 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-30
2025-05-16 01:26:57,736 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5741661787033081, 'eval_accuracy': 0.7857142857142857, 'eval_precision': 0.75, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.7959183673469387, 'eval_false_positives_rate': 0.2857142857142857, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.058, 'eval_samples_per_second': 241.381, 'eval_steps_per_second': 17.241, 'epoch': 6.0, 'step': 30}
2025-05-16 01:26:57,737 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 01:26:57,813 - Experiment - INFO - Test metrics: {'test_loss': 0.31872767210006714, 'test_accuracy': 0.9333333333333333, 'test_precision': 1.0, 'test_recall': 0.9090909090909091, 'test_f1_score': 0.9523809523809523, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.09090909090909091, 'test_runtime': 0.0724, 'test_samples_per_second': 207.279, 'test_steps_per_second': 13.819, 'test_epoch': 6.0}
2025-05-16 01:26:57,833 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:57,834 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:57,882 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:57,883 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:26:57,884 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 01:26:58,102 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5954240560531616, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.8571428571428571, 'eval_false_positives_rate': 0.42857142857142855, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.0755, 'eval_samples_per_second': 185.524, 'eval_steps_per_second': 13.252, 'epoch': 7.0, 'step': 35}
2025-05-16 01:26:58,103 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 01:26:58,184 - Experiment - INFO - Test metrics: {'test_loss': 0.21310880780220032, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.0771, 'test_samples_per_second': 194.47, 'test_steps_per_second': 12.965, 'test_epoch': 7.0}
2025-05-16 01:26:58,202 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:58,203 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:58,245 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:58,246 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:26:58,247 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:26:58,487 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5710267424583435, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.7959183673469387, 'eval_false_positives_rate': 0.42857142857142855, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.0796, 'eval_samples_per_second': 175.868, 'eval_steps_per_second': 12.562, 'epoch': 5.0, 'step': 25}
2025-05-16 01:26:58,488 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:26:58,573 - Experiment - INFO - Test metrics: {'test_loss': 0.4636874794960022, 'test_accuracy': 0.7333333333333333, 'test_precision': 1.0, 'test_recall': 0.6363636363636364, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.36363636363636365, 'test_runtime': 0.0807, 'test_samples_per_second': 185.938, 'test_steps_per_second': 12.396, 'test_epoch': 5.0}
2025-05-16 01:26:58,590 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:26:58,592 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:26:58,631 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:26:58,632 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 01:26:58,697 - Experiment - INFO - MLflow experiment initialized with ID: 701195748125061381
2025-05-16 01:26:58,698 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 01:26:58,699 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:26:58,699 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 01:26:59,957 - Experiment - INFO - Run ID: 32154051dcf8478c89014ffe85c78124
2025-05-16 01:26:59,959 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_01-26-59;rs=3121896883
2025-05-16 01:26:59,975 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:27:00,010 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:27:00,126 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000023F86C8B6B0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000023F86C8B5C0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000023F86C8B620>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000023F86C8B650>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000023F86C8A300>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:27:00,300 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:27:00,301 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:27:00,302 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:27:00,316 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:27:00,317 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:27:00,327 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:27:00,328 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:27:00,337 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:27:00,338 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:27:00,338 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:27:00,396 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:27:00,397 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:27:00,421 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:27:00,422 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:27:00,438 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:27:00,439 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:27:00,440 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:27:00,579 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:27:00,580 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:27:00,628 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:27:00,628 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:27:00,662 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 01:27:00,663 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:27:00,663 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: EURa
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: NewsMap
warning: skipping word with mixed case: NCjcWaTREH
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: PhDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: PolitRussia
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: rvIOjIM
warning: skipping word with mixed case: sfNcHdxwZ
warning: skipping word with mixed case: MinfinMedia
warning: skipping word with mixed case: AntiDiplomatico
warning: skipping word with mixed case: JHa
warning: skipping word with mixed case: SpringerLink
warning: skipping word with mixed case: CoV
warning: skipping word with mixed case: mRNA
warning: skipping word with mixed case: LinkedIn
warning: skipping word with mixed case: SpringerLink
2025-05-16 01:27:00,785 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:27:00,786 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: KSČíny
warning: skipping word with mixed case: PetrJ
warning: skipping word with mixed case: PetrJ
warning: skipping word with mixed case: REPLlKÁTOR
warning: skipping word with mixed case: OSPODu
warning: skipping word with mixed case: TeamUkraine
2025-05-16 01:27:00,836 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:27:00,837 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McAlester
warning: skipping word with mixed case: BorisJohnson
warning: skipping word with mixed case: FMzemenYY
warning: skipping word with mixed case: JUDr
2025-05-16 01:27:01,073 - Experiment - INFO - Preprocessing function 4: distilli_bert__encoder
2025-05-16 01:27:01,074 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:27:01,075 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:27:01,723 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:27:01,724 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:27:01,985 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:27:01,987 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:27:02,554 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 01:27:02,559 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:27:26,650 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:27:26,652 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-45
2025-05-16 01:27:26,951 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4291217625141144, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 0.8571428571428571, 'eval_recall': 1.0, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 0.8958333333333334, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0708, 'eval_samples_per_second': 197.641, 'eval_steps_per_second': 14.117, 'epoch': 9.0, 'step': 45}
2025-05-16 01:27:26,952 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-16 01:27:27,025 - Experiment - INFO - Test metrics: {'test_loss': 0.4773598313331604, 'test_accuracy': 0.8, 'test_precision': 0.8888888888888888, 'test_recall': 0.8, 'test_f1_score': 0.8421052631578947, 'test_roc_auc': 0.8400000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.2, 'test_runtime': 0.0679, 'test_samples_per_second': 220.762, 'test_steps_per_second': 14.717, 'test_epoch': 9.0}
2025-05-16 01:27:27,041 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:27:27,043 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:27:27,086 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:27:27,087 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:27:27,088 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-45
2025-05-16 01:27:27,301 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4291217625141144, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 0.8571428571428571, 'eval_recall': 1.0, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 0.8958333333333334, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.0708, 'eval_samples_per_second': 197.641, 'eval_steps_per_second': 14.117, 'epoch': 9.0, 'step': 45}
2025-05-16 01:27:27,302 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-16 01:27:27,374 - Experiment - INFO - Test metrics: {'test_loss': 0.4773598313331604, 'test_accuracy': 0.8, 'test_precision': 0.8888888888888888, 'test_recall': 0.8, 'test_f1_score': 0.8421052631578947, 'test_roc_auc': 0.8400000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.2, 'test_runtime': 0.0682, 'test_samples_per_second': 219.898, 'test_steps_per_second': 14.66, 'test_epoch': 9.0}
2025-05-16 01:27:27,392 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:27:27,394 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:27:27,435 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:27:27,436 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:27:27,437 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:27:27,661 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.42455819249153137, 'eval_accuracy': 0.7857142857142857, 'eval_precision': 0.8, 'eval_recall': 0.6666666666666666, 'eval_f1_score': 0.7272727272727273, 'eval_roc_auc': 0.8958333333333334, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.3333333333333333, 'eval_runtime': 0.0587, 'eval_samples_per_second': 238.46, 'eval_steps_per_second': 17.033, 'epoch': 10.0, 'step': 50}
2025-05-16 01:27:27,661 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:27:27,737 - Experiment - INFO - Test metrics: {'test_loss': 0.5134567618370056, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.8400000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.0707, 'test_samples_per_second': 212.17, 'test_steps_per_second': 14.145, 'test_epoch': 10.0}
2025-05-16 01:27:27,760 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:27:27,762 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:27:27,802 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:27:27,803 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:27:27,803 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:27:28,058 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5456773042678833, 'eval_accuracy': 0.7857142857142857, 'eval_precision': 0.8, 'eval_recall': 0.6666666666666666, 'eval_f1_score': 0.7272727272727273, 'eval_roc_auc': 0.9375, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.3333333333333333, 'eval_runtime': 0.0787, 'eval_samples_per_second': 177.826, 'eval_steps_per_second': 12.702, 'epoch': 5.0, 'step': 25}
2025-05-16 01:27:28,059 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:27:28,146 - Experiment - INFO - Test metrics: {'test_loss': 0.6494572758674622, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.75, 'test_recall': 0.3, 'test_f1_score': 0.42857142857142855, 'test_roc_auc': 0.8, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.7, 'test_runtime': 0.0822, 'test_samples_per_second': 182.505, 'test_steps_per_second': 12.167, 'test_epoch': 5.0}
2025-05-16 01:27:28,184 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:27:28,186 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:27:28,229 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:27:28,230 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:27:28,230 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-50
2025-05-16 01:27:28,443 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.42455819249153137, 'eval_accuracy': 0.7857142857142857, 'eval_precision': 0.8, 'eval_recall': 0.6666666666666666, 'eval_f1_score': 0.7272727272727273, 'eval_roc_auc': 0.8958333333333334, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.3333333333333333, 'eval_runtime': 0.0587, 'eval_samples_per_second': 238.46, 'eval_steps_per_second': 17.033, 'epoch': 10.0, 'step': 50}
2025-05-16 01:27:28,444 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-16 01:27:28,528 - Experiment - INFO - Test metrics: {'test_loss': 0.5134567618370056, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.8400000000000001, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.0789, 'test_samples_per_second': 190.12, 'test_steps_per_second': 12.675, 'test_epoch': 10.0}
2025-05-16 01:27:28,544 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:27:28,545 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:27:28,584 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:27:28,585 - Experiment - INFO - Finished model evaluations stage.