In [4]:
from workspace.sources.local_datasets.preprocessing.encoders.distillibert import DistillibertEncoder
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction
from workspace.sources.experiments.metrics import Loss
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.local_datasets.preprocessing.transformations import Truncation
from workspace.sources.models.transformers.bert.distillibert import Distillibert
from sklearn.model_selection import ParameterGrid

import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [5]:
experiment_name = 'prefinal-distillibert-base-uncased'

In [11]:
def conduct_model_experiments(dataset_name,
                              dataset_path,
                              dataset_params_dict,
                              model_hparams_dict):
    dataset_params_grid = ParameterGrid(dataset_params_dict)

    model_hparams_grid = ParameterGrid(model_hparams_dict)

    for dataset_params in dataset_params_grid:
        for model_hparams in model_hparams_grid:
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = Distillibert(train_best_model_metric=Loss,
                                 training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            recovery_experiment.run()

In [ ]:
pipelines = [PreprocessingPipeline(name='truncated_minimal_bert_pipeline',
                                   iterable=[Truncation(0.1),
                                             DistillibertEncoder()]),
             PreprocessingPipeline(name='truncated_noise_reduction_bert_pipeline',
                                   iterable=[Truncation(0.1), NoiseReduction(),
                                             DistillibertEncoder()])]
dataset_params_dict = {'preprocessings_pipeline': pipelines}

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16, 32],
                                    'learning_rate': [5e-04, 5e-05, 5e-06],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [0.0, 1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})

### ReCOVery Dataset

In [7]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

2025/05/14 16:40:17 INFO mlflow.tracking.fluent: Experiment with name 'prefinal-distillibert-base-uncased' does not exist. Creating a new experiment.
2025-05-14 16:40:17,790 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:40:17,791 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:40:17,792 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:40:17,793 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:40:18,149 - Experiment - INFO - Run ID: 6be3442c95514f709feae5df99dc051e
2025-05-14 16:40:18,151 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-40-17;rs=1814631071
2025-05-14 16:40:18,171 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:40:18,210 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:40:18,370 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA0127A570>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA01422630>]>
2025-05-14 16:40:18,663 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:40:18,664 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:40:18,666 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:40:18,701 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:40:18,703 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:40:18,721 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:40:18,722 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:40:18,932 - Experiment - INFO - Preprocessing function 1: distillibert_encoder
2025-05-14 16:40:18,933 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:40:18,934 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:40:20,129 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:40:20,130 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:40:20,385 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:40:20,385 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:40:21,549 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:40:21,553 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:41:25,934 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:41:25,934 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-108
2025-05-14 16:41:26,197 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5020037293434143, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.95, 'eval_recall': 0.8636363636363636, 'eval_f1_score': 0.9047619047619048, 'eval_roc_auc': 0.9318181818181819, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.13636363636363635, 'eval_runtime': 0.5232, 'eval_samples_per_second': 57.335, 'eval_steps_per_second': 7.645, 'epoch': 6.0, 'step': 108}
2025-05-14 16:41:26,198 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:41:26,732 - Experiment - INFO - Test metrics: {'test_loss': 1.552111029624939, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.85, 'test_recall': 0.7727272727272727, 'test_f1_score': 0.8095238095238095, 'test_roc_auc': 0.8409090909090908, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.22727272727272727, 'test_runtime': 0.5291, 'test_samples_per_second': 56.698, 'test_steps_per_second': 7.56, 'test_epoch': 6.0}
2025-05-14 16:41:26,752 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:41:26,756 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:41:26,839 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:41:26,840 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:41:26,841 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-108
2025-05-14 16:41:27,060 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5020037293434143, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.95, 'eval_recall': 0.8636363636363636, 'eval_f1_score': 0.9047619047619048, 'eval_roc_auc': 0.9318181818181819, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.13636363636363635, 'eval_runtime': 0.5232, 'eval_samples_per_second': 57.335, 'eval_steps_per_second': 7.645, 'epoch': 6.0, 'step': 108}
2025-05-14 16:41:27,061 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:41:27,562 - Experiment - INFO - Test metrics: {'test_loss': 1.552111029624939, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.85, 'test_recall': 0.7727272727272727, 'test_f1_score': 0.8095238095238095, 'test_roc_auc': 0.8409090909090908, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.22727272727272727, 'test_runtime': 0.4949, 'test_samples_per_second': 60.62, 'test_steps_per_second': 8.083, 'test_epoch': 6.0}
2025-05-14 16:41:27,591 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:41:27,594 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:41:27,669 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:41:27,670 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:41:27,671 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-108
2025-05-14 16:41:27,925 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5020037293434143, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.95, 'eval_recall': 0.8636363636363636, 'eval_f1_score': 0.9047619047619048, 'eval_roc_auc': 0.9318181818181819, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.13636363636363635, 'eval_runtime': 0.5232, 'eval_samples_per_second': 57.335, 'eval_steps_per_second': 7.645, 'epoch': 6.0, 'step': 108}
2025-05-14 16:41:27,926 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:41:28,424 - Experiment - INFO - Test metrics: {'test_loss': 1.552111029624939, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.85, 'test_recall': 0.7727272727272727, 'test_f1_score': 0.8095238095238095, 'test_roc_auc': 0.8409090909090908, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.22727272727272727, 'test_runtime': 0.4936, 'test_samples_per_second': 60.774, 'test_steps_per_second': 8.103, 'test_epoch': 6.0}
2025-05-14 16:41:28,452 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:41:28,455 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:41:28,536 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:41:28,538 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:41:28,539 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-108
2025-05-14 16:41:28,739 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5020037293434143, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.95, 'eval_recall': 0.8636363636363636, 'eval_f1_score': 0.9047619047619048, 'eval_roc_auc': 0.9318181818181819, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.13636363636363635, 'eval_runtime': 0.5232, 'eval_samples_per_second': 57.335, 'eval_steps_per_second': 7.645, 'epoch': 6.0, 'step': 108}
2025-05-14 16:41:28,739 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:41:29,267 - Experiment - INFO - Test metrics: {'test_loss': 1.552111029624939, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.85, 'test_recall': 0.7727272727272727, 'test_f1_score': 0.8095238095238095, 'test_roc_auc': 0.8409090909090908, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.22727272727272727, 'test_runtime': 0.5162, 'test_samples_per_second': 58.119, 'test_steps_per_second': 7.749, 'test_epoch': 6.0}
2025-05-14 16:41:29,292 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:41:29,296 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:41:29,375 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:41:29,375 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:41:29,376 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-54
2025-05-14 16:41:29,637 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3748057782649994, 'eval_accuracy': 0.8333333333333334, 'eval_precision': 0.8695652173913043, 'eval_recall': 0.9090909090909091, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.8863636363636364, 'eval_false_positives_rate': 0.375, 'eval_false_negatives_rate': 0.09090909090909091, 'eval_runtime': 0.5099, 'eval_samples_per_second': 58.834, 'eval_steps_per_second': 7.845, 'epoch': 3.0, 'step': 54}
2025-05-14 16:41:29,637 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:41:30,149 - Experiment - INFO - Test metrics: {'test_loss': 0.6360557675361633, 'test_accuracy': 0.7, 'test_precision': 0.782608695652174, 'test_recall': 0.8181818181818182, 'test_f1_score': 0.8, 'test_roc_auc': 0.7784090909090909, 'test_false_positives_rate': 0.625, 'test_false_negatives_rate': 0.18181818181818182, 'test_runtime': 0.5097, 'test_samples_per_second': 58.854, 'test_steps_per_second': 7.847, 'test_epoch': 3.0}
2025-05-14 16:41:30,181 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:41:30,185 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:41:30,275 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:41:30,276 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:41:30,978 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:41:30,978 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:41:30,978 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:41:30,978 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:41:31,708 - Experiment - INFO - Run ID: 3d915f0eab7141968787e82eab24239e
2025-05-14 16:41:31,708 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-41-31;rs=828111212
2025-05-14 16:41:31,730 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:41:31,755 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:41:31,903 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA0127A570>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA01422630>]>
2025-05-14 16:41:32,102 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:41:32,102 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:41:32,102 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:41:32,126 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:41:32,127 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:41:32,141 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:41:32,143 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:41:32,324 - Experiment - INFO - Preprocessing function 1: distillibert_encoder
2025-05-14 16:41:32,324 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:41:32,325 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:41:33,411 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:41:33,412 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:41:33,714 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:41:33,715 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:41:35,136 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:41:35,142 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:42:16,673 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:42:16,673 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-54
2025-05-14 16:42:16,892 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5555276870727539, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.8636363636363636, 'eval_recall': 0.7916666666666666, 'eval_f1_score': 0.8260869565217391, 'eval_roc_auc': 0.7986111111111112, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.20833333333333334, 'eval_runtime': 1.7925, 'eval_samples_per_second': 16.737, 'eval_steps_per_second': 2.232, 'epoch': 3.0, 'step': 54}
2025-05-14 16:42:16,893 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:42:17,487 - Experiment - INFO - Test metrics: {'test_loss': 0.5405057668685913, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.782608695652174, 'test_recall': 0.8571428571428571, 'test_f1_score': 0.8181818181818182, 'test_roc_auc': 0.7777777777777778, 'test_false_positives_rate': 0.5555555555555556, 'test_false_negatives_rate': 0.14285714285714285, 'test_runtime': 0.588, 'test_samples_per_second': 51.021, 'test_steps_per_second': 6.803, 'test_epoch': 3.0}
2025-05-14 16:42:17,508 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:42:17,511 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:42:17,588 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:42:17,589 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:42:17,590 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-18
2025-05-14 16:42:17,837 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5357680916786194, 'eval_accuracy': 0.8, 'eval_precision': 0.8, 'eval_recall': 1.0, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.625, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.4973, 'eval_samples_per_second': 60.322, 'eval_steps_per_second': 8.043, 'epoch': 1.0, 'step': 18}
2025-05-14 16:42:17,838 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:42:18,343 - Experiment - INFO - Test metrics: {'test_loss': 0.580525815486908, 'test_accuracy': 0.7, 'test_precision': 0.7, 'test_recall': 1.0, 'test_f1_score': 0.8235294117647058, 'test_roc_auc': 0.8042328042328043, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.4984, 'test_samples_per_second': 60.197, 'test_steps_per_second': 8.026, 'test_epoch': 1.0}
2025-05-14 16:42:18,361 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:42:18,363 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:42:18,445 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:42:18,446 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:42:18,447 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-54
2025-05-14 16:42:18,649 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5555276870727539, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.8636363636363636, 'eval_recall': 0.7916666666666666, 'eval_f1_score': 0.8260869565217391, 'eval_roc_auc': 0.7986111111111112, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.20833333333333334, 'eval_runtime': 1.7925, 'eval_samples_per_second': 16.737, 'eval_steps_per_second': 2.232, 'epoch': 3.0, 'step': 54}
2025-05-14 16:42:18,650 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:42:19,150 - Experiment - INFO - Test metrics: {'test_loss': 0.5405057668685913, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.782608695652174, 'test_recall': 0.8571428571428571, 'test_f1_score': 0.8181818181818182, 'test_roc_auc': 0.7777777777777778, 'test_false_positives_rate': 0.5555555555555556, 'test_false_negatives_rate': 0.14285714285714285, 'test_runtime': 0.495, 'test_samples_per_second': 60.605, 'test_steps_per_second': 8.081, 'test_epoch': 3.0}
2025-05-14 16:42:19,171 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:42:19,172 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:42:19,249 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:42:19,250 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:42:19,250 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-54
2025-05-14 16:42:19,451 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5555276870727539, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.8636363636363636, 'eval_recall': 0.7916666666666666, 'eval_f1_score': 0.8260869565217391, 'eval_roc_auc': 0.7986111111111112, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.20833333333333334, 'eval_runtime': 1.7925, 'eval_samples_per_second': 16.737, 'eval_steps_per_second': 2.232, 'epoch': 3.0, 'step': 54}
2025-05-14 16:42:19,451 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-14 16:42:19,954 - Experiment - INFO - Test metrics: {'test_loss': 0.5405057668685913, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.782608695652174, 'test_recall': 0.8571428571428571, 'test_f1_score': 0.8181818181818182, 'test_roc_auc': 0.7777777777777778, 'test_false_positives_rate': 0.5555555555555556, 'test_false_negatives_rate': 0.14285714285714285, 'test_runtime': 0.4988, 'test_samples_per_second': 60.149, 'test_steps_per_second': 8.02, 'test_epoch': 3.0}
2025-05-14 16:42:19,977 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:42:19,980 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:42:20,060 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:42:20,061 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:42:20,062 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-18
2025-05-14 16:42:20,299 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5357680916786194, 'eval_accuracy': 0.8, 'eval_precision': 0.8, 'eval_recall': 1.0, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.625, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.4973, 'eval_samples_per_second': 60.322, 'eval_steps_per_second': 8.043, 'epoch': 1.0, 'step': 18}
2025-05-14 16:42:20,300 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:42:20,797 - Experiment - INFO - Test metrics: {'test_loss': 0.580525815486908, 'test_accuracy': 0.7, 'test_precision': 0.7, 'test_recall': 1.0, 'test_f1_score': 0.8235294117647058, 'test_roc_auc': 0.8042328042328043, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.4936, 'test_samples_per_second': 60.774, 'test_steps_per_second': 8.103, 'test_epoch': 1.0}
2025-05-14 16:42:20,819 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:42:20,821 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:42:20,897 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:42:20,898 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:42:21,712 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:42:21,713 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:42:21,714 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:42:21,714 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:42:22,374 - Experiment - INFO - Run ID: b1ac06ec18964cd8a9313d347112d716
2025-05-14 16:42:22,374 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-42-22;rs=2877435959
2025-05-14 16:42:22,386 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:42:22,503 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:42:23,273 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA0127AAE0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001FA01422720>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA014222A0>]>
2025-05-14 16:42:23,649 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:42:23,653 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:42:23,656 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:42:23,762 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:42:23,767 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:42:23,836 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:42:23,840 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:42:23,893 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 16:42:23,896 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:42:23,901 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:42:24,448 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:42:24,449 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:42:24,488 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:42:24,488 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:42:24,682 - Experiment - INFO - Preprocessing function 2: distillibert_encoder
2025-05-14 16:42:24,682 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:42:24,685 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:42:25,852 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:42:25,854 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:42:26,202 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:42:26,203 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:42:27,681 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:42:27,686 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:43:10,582 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:43:10,583 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-72
2025-05-14 16:43:10,819 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9013971090316772, 'eval_accuracy': 0.8333333333333334, 'eval_precision': 0.9047619047619048, 'eval_recall': 0.8636363636363636, 'eval_f1_score': 0.8837209302325582, 'eval_roc_auc': 0.8352272727272727, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.13636363636363635, 'eval_runtime': 0.5223, 'eval_samples_per_second': 57.438, 'eval_steps_per_second': 7.658, 'epoch': 4.0, 'step': 72}
2025-05-14 16:43:10,819 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 16:43:11,365 - Experiment - INFO - Test metrics: {'test_loss': 0.8350579738616943, 'test_accuracy': 0.8, 'test_precision': 0.9375, 'test_recall': 0.75, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.8700000000000001, 'test_false_positives_rate': 0.1, 'test_false_negatives_rate': 0.25, 'test_runtime': 0.5404, 'test_samples_per_second': 55.519, 'test_steps_per_second': 7.403, 'test_epoch': 4.0}
2025-05-14 16:43:11,397 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:43:11,400 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:43:11,514 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:43:11,516 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:43:11,517 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-18
2025-05-14 16:43:11,821 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4746986925601959, 'eval_accuracy': 0.9, 'eval_precision': 0.88, 'eval_recall': 1.0, 'eval_f1_score': 0.9361702127659575, 'eval_roc_auc': 0.8579545454545454, 'eval_false_positives_rate': 0.375, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5005, 'eval_samples_per_second': 59.943, 'eval_steps_per_second': 7.992, 'epoch': 1.0, 'step': 18}
2025-05-14 16:43:11,822 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:43:12,342 - Experiment - INFO - Test metrics: {'test_loss': 0.4584001302719116, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8260869565217391, 'test_recall': 0.95, 'test_f1_score': 0.8837209302325582, 'test_roc_auc': 0.88, 'test_false_positives_rate': 0.4, 'test_false_negatives_rate': 0.05, 'test_runtime': 0.5157, 'test_samples_per_second': 58.176, 'test_steps_per_second': 7.757, 'test_epoch': 1.0}
2025-05-14 16:43:12,365 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:43:12,368 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:43:12,453 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:43:12,454 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:43:12,454 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-72
2025-05-14 16:43:12,680 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9013971090316772, 'eval_accuracy': 0.8333333333333334, 'eval_precision': 0.9047619047619048, 'eval_recall': 0.8636363636363636, 'eval_f1_score': 0.8837209302325582, 'eval_roc_auc': 0.8352272727272727, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.13636363636363635, 'eval_runtime': 0.5223, 'eval_samples_per_second': 57.438, 'eval_steps_per_second': 7.658, 'epoch': 4.0, 'step': 72}
2025-05-14 16:43:12,681 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 16:43:13,204 - Experiment - INFO - Test metrics: {'test_loss': 0.8350579738616943, 'test_accuracy': 0.8, 'test_precision': 0.9375, 'test_recall': 0.75, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.8700000000000001, 'test_false_positives_rate': 0.1, 'test_false_negatives_rate': 0.25, 'test_runtime': 0.518, 'test_samples_per_second': 57.917, 'test_steps_per_second': 7.722, 'test_epoch': 4.0}
2025-05-14 16:43:13,226 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:43:13,229 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:43:13,309 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:43:13,311 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:43:13,313 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 16:43:13,572 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5066484212875366, 'eval_accuracy': 0.8333333333333334, 'eval_precision': 0.8695652173913043, 'eval_recall': 0.9090909090909091, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 0.8693181818181819, 'eval_false_positives_rate': 0.375, 'eval_false_negatives_rate': 0.09090909090909091, 'eval_runtime': 0.5093, 'eval_samples_per_second': 58.904, 'eval_steps_per_second': 7.854, 'epoch': 2.0, 'step': 36}
2025-05-14 16:43:13,573 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:43:14,091 - Experiment - INFO - Test metrics: {'test_loss': 0.4014319181442261, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8260869565217391, 'test_recall': 0.95, 'test_f1_score': 0.8837209302325582, 'test_roc_auc': 0.92, 'test_false_positives_rate': 0.4, 'test_false_negatives_rate': 0.05, 'test_runtime': 0.5137, 'test_samples_per_second': 58.405, 'test_steps_per_second': 7.787, 'test_epoch': 2.0}
2025-05-14 16:43:14,113 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:43:14,116 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:43:14,210 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:43:14,212 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:43:14,213 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-18
2025-05-14 16:43:14,454 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4746986925601959, 'eval_accuracy': 0.9, 'eval_precision': 0.88, 'eval_recall': 1.0, 'eval_f1_score': 0.9361702127659575, 'eval_roc_auc': 0.8579545454545454, 'eval_false_positives_rate': 0.375, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5005, 'eval_samples_per_second': 59.943, 'eval_steps_per_second': 7.992, 'epoch': 1.0, 'step': 18}
2025-05-14 16:43:14,456 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:43:14,979 - Experiment - INFO - Test metrics: {'test_loss': 0.4584001302719116, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8260869565217391, 'test_recall': 0.95, 'test_f1_score': 0.8837209302325582, 'test_roc_auc': 0.88, 'test_false_positives_rate': 0.4, 'test_false_negatives_rate': 0.05, 'test_runtime': 0.5171, 'test_samples_per_second': 58.013, 'test_steps_per_second': 7.735, 'test_epoch': 1.0}
2025-05-14 16:43:15,009 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:43:15,013 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:43:15,104 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:43:15,105 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:43:15,619 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:43:15,621 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:43:15,621 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:43:15,622 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:43:16,525 - Experiment - INFO - Run ID: b14f6cbe441c4d9da421d6063d5ebc73
2025-05-14 16:43:16,526 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-43-16;rs=1186755475
2025-05-14 16:43:16,539 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:43:16,575 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:43:16,783 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA0127AAE0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001FA01422720>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA014222A0>]>
2025-05-14 16:43:17,451 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:43:17,460 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:43:17,462 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:43:17,490 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:43:17,491 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:43:17,504 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:43:17,505 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:43:17,518 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 16:43:17,519 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:43:17,519 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:43:17,670 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:43:17,671 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:43:17,709 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:43:17,710 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:43:17,982 - Experiment - INFO - Preprocessing function 2: distillibert_encoder
2025-05-14 16:43:17,983 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:43:17,984 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:43:19,956 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:43:19,958 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:43:20,271 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:43:20,271 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:43:21,765 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:43:21,769 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-14 16:44:15,273 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:44:15,273 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-90
2025-05-14 16:44:15,521 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4649440050125122, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.95, 'eval_recall': 0.7307692307692307, 'eval_f1_score': 0.8260869565217391, 'eval_roc_auc': 0.8365384615384616, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.2692307692307692, 'eval_runtime': 0.5145, 'eval_samples_per_second': 58.314, 'eval_steps_per_second': 7.775, 'epoch': 5.0, 'step': 90}
2025-05-14 16:44:15,522 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-14 16:44:16,061 - Experiment - INFO - Test metrics: {'test_loss': 0.5189769864082336, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.875, 'test_recall': 0.7, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.86, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.3, 'test_runtime': 0.5339, 'test_samples_per_second': 56.188, 'test_steps_per_second': 7.492, 'test_epoch': 5.0}
2025-05-14 16:44:16,083 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:44:16,085 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:44:16,165 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:44:16,167 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:44:16,168 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 16:44:16,433 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4238967299461365, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8666666666666667, 'eval_recall': 1.0, 'eval_f1_score': 0.9285714285714286, 'eval_roc_auc': 0.8365384615384616, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5426, 'eval_samples_per_second': 55.293, 'eval_steps_per_second': 7.372, 'epoch': 2.0, 'step': 36}
2025-05-14 16:44:16,434 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:44:16,955 - Experiment - INFO - Test metrics: {'test_loss': 0.6350271105766296, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.755, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5163, 'test_samples_per_second': 58.11, 'test_steps_per_second': 7.748, 'test_epoch': 2.0}
2025-05-14 16:44:16,977 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:44:16,979 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:44:17,122 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:44:17,123 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:44:17,124 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-18
2025-05-14 16:44:17,380 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.8038100004196167, 'eval_accuracy': 0.13333333333333333, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 0.6826923076923077, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.5395, 'eval_samples_per_second': 55.604, 'eval_steps_per_second': 7.414, 'epoch': 1.0, 'step': 18}
2025-05-14 16:44:17,381 - Experiment - INFO - Best model found at epoch 1.0.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-14 16:44:17,898 - Experiment - INFO - Test metrics: {'test_loss': 0.7496827840805054, 'test_accuracy': 0.3333333333333333, 'test_precision': 0.0, 'test_recall': 0.0, 'test_f1_score': 0.0, 'test_roc_auc': 0.545, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 1.0, 'test_runtime': 0.5112, 'test_samples_per_second': 58.684, 'test_steps_per_second': 7.825, 'test_epoch': 1.0}
2025-05-14 16:44:17,921 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:44:17,923 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:44:18,010 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:44:18,011 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:44:18,011 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 16:44:18,244 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4238967299461365, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8666666666666667, 'eval_recall': 1.0, 'eval_f1_score': 0.9285714285714286, 'eval_roc_auc': 0.8365384615384616, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5426, 'eval_samples_per_second': 55.293, 'eval_steps_per_second': 7.372, 'epoch': 2.0, 'step': 36}
2025-05-14 16:44:18,245 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:44:18,760 - Experiment - INFO - Test metrics: {'test_loss': 0.6350271105766296, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.755, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5097, 'test_samples_per_second': 58.856, 'test_steps_per_second': 7.847, 'test_epoch': 2.0}
2025-05-14 16:44:18,784 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:44:18,787 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:44:18,865 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:44:18,866 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:44:18,866 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 16:44:19,112 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4238967299461365, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8666666666666667, 'eval_recall': 1.0, 'eval_f1_score': 0.9285714285714286, 'eval_roc_auc': 0.8365384615384616, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5426, 'eval_samples_per_second': 55.293, 'eval_steps_per_second': 7.372, 'epoch': 2.0, 'step': 36}
2025-05-14 16:44:19,113 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:44:19,626 - Experiment - INFO - Test metrics: {'test_loss': 0.6350271105766296, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.6666666666666666, 'test_recall': 1.0, 'test_f1_score': 0.8, 'test_roc_auc': 0.755, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5087, 'test_samples_per_second': 58.975, 'test_steps_per_second': 7.863, 'test_epoch': 2.0}
2025-05-14 16:44:19,652 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:44:19,654 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:44:19,733 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:44:19,735 - Experiment - INFO - Finished model evaluations stage.

### EUvsDisinfo Dataset

In [8]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

2025-05-14 16:44:20,422 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:44:20,423 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:44:20,424 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:44:20,424 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:44:21,457 - Experiment - INFO - Run ID: 27761866e9dd4fb98f5cc3c7faa73bb3
2025-05-14 16:44:21,459 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-44-21;rs=966864890
2025-05-14 16:44:21,471 - Experiment - INFO - {'dataset_name': 'euvsdisinfo', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:44:21,500 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:44:21,539 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA24405580>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA24405700>]>
2025-05-14 16:44:21,714 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:44:21,714 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:44:21,715 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:44:21,726 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:44:21,727 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:44:21,737 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:44:21,738 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:44:21,931 - Experiment - INFO - Preprocessing function 1: distillibert_encoder
2025-05-14 16:44:21,933 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:44:21,933 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:44:22,966 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:44:22,967 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:44:23,272 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:44:23,274 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:44:24,932 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:44:24,937 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:45:15,850 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:45:15,851 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-19
2025-05-14 16:45:16,099 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.03189168870449066, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.546, 'eval_samples_per_second': 58.612, 'eval_steps_per_second': 7.326, 'epoch': 1.0, 'step': 19}
2025-05-14 16:45:16,100 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:45:16,633 - Experiment - INFO - Test metrics: {'test_loss': 0.12714572250843048, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 0.5289, 'test_samples_per_second': 60.502, 'test_steps_per_second': 7.563, 'test_epoch': 1.0}
2025-05-14 16:45:16,652 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:45:16,655 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:45:16,741 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:45:16,742 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:45:16,743 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-19
2025-05-14 16:45:16,962 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.03189168870449066, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.546, 'eval_samples_per_second': 58.612, 'eval_steps_per_second': 7.326, 'epoch': 1.0, 'step': 19}
2025-05-14 16:45:16,963 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:45:17,501 - Experiment - INFO - Test metrics: {'test_loss': 0.12714572250843048, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 0.5321, 'test_samples_per_second': 60.14, 'test_steps_per_second': 7.518, 'test_epoch': 1.0}
2025-05-14 16:45:17,530 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:45:17,533 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:45:17,632 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:45:17,633 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:45:17,634 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-19
2025-05-14 16:45:17,867 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.03189168870449066, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.546, 'eval_samples_per_second': 58.612, 'eval_steps_per_second': 7.326, 'epoch': 1.0, 'step': 19}
2025-05-14 16:45:17,868 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:45:18,395 - Experiment - INFO - Test metrics: {'test_loss': 0.12714572250843048, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 0.5227, 'test_samples_per_second': 61.219, 'test_steps_per_second': 7.652, 'test_epoch': 1.0}
2025-05-14 16:45:18,417 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:45:18,420 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:45:18,501 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:45:18,502 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:45:18,503 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-19
2025-05-14 16:45:18,724 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.03189168870449066, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.546, 'eval_samples_per_second': 58.612, 'eval_steps_per_second': 7.326, 'epoch': 1.0, 'step': 19}
2025-05-14 16:45:18,725 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:45:19,280 - Experiment - INFO - Test metrics: {'test_loss': 0.12714572250843048, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 0.5504, 'test_samples_per_second': 58.14, 'test_steps_per_second': 7.268, 'test_epoch': 1.0}
2025-05-14 16:45:19,300 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:45:19,302 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:45:19,384 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:45:19,385 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:45:19,387 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-19
2025-05-14 16:45:19,606 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.03189168870449066, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.546, 'eval_samples_per_second': 58.612, 'eval_steps_per_second': 7.326, 'epoch': 1.0, 'step': 19}
2025-05-14 16:45:19,607 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-14 16:45:20,143 - Experiment - INFO - Test metrics: {'test_loss': 0.12714572250843048, 'test_accuracy': 0.96875, 'test_precision': 1.0, 'test_recall': 0.9473684210526315, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.05263157894736842, 'test_runtime': 0.5309, 'test_samples_per_second': 60.279, 'test_steps_per_second': 7.535, 'test_epoch': 1.0}
2025-05-14 16:45:20,167 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:45:20,170 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:45:20,264 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:45:20,265 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:45:20,903 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:45:20,904 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:45:20,905 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:45:20,906 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:45:21,748 - Experiment - INFO - Run ID: efede7c1e02b43b9a04c9568342a555d
2025-05-14 16:45:21,748 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-45-21;rs=1646151151
2025-05-14 16:45:21,759 - Experiment - INFO - {'dataset_name': 'euvsdisinfo', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:45:21,782 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:45:21,815 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA24405580>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA24405700>]>
2025-05-14 16:45:21,988 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:45:21,989 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:45:21,990 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:45:22,004 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:45:22,006 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:45:22,020 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:45:22,021 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:45:22,204 - Experiment - INFO - Preprocessing function 1: distillibert_encoder
2025-05-14 16:45:22,205 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:45:22,206 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:45:22,930 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:45:22,931 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:45:23,166 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:45:23,166 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:45:24,113 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:45:24,117 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:46:42,846 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:46:42,846 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-133
2025-05-14 16:46:43,211 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0008109976770356297, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5561, 'eval_samples_per_second': 57.548, 'eval_steps_per_second': 7.194, 'epoch': 7.0, 'step': 133}
2025-05-14 16:46:43,212 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 16:46:43,774 - Experiment - INFO - Test metrics: {'test_loss': 0.0006644227541983128, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5561, 'test_samples_per_second': 57.545, 'test_steps_per_second': 7.193, 'test_epoch': 7.0}
2025-05-14 16:46:43,800 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:46:43,804 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:46:43,900 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:46:43,901 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:46:43,902 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-133
2025-05-14 16:46:44,200 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0008109976770356297, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5561, 'eval_samples_per_second': 57.548, 'eval_steps_per_second': 7.194, 'epoch': 7.0, 'step': 133}
2025-05-14 16:46:44,201 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 16:46:44,762 - Experiment - INFO - Test metrics: {'test_loss': 0.0006644227541983128, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5523, 'test_samples_per_second': 57.94, 'test_steps_per_second': 7.243, 'test_epoch': 7.0}
2025-05-14 16:46:44,781 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:46:44,784 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:46:44,872 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:46:44,874 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:46:44,875 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-133
2025-05-14 16:46:45,131 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0008109976770356297, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5561, 'eval_samples_per_second': 57.548, 'eval_steps_per_second': 7.194, 'epoch': 7.0, 'step': 133}
2025-05-14 16:46:45,132 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 16:46:45,675 - Experiment - INFO - Test metrics: {'test_loss': 0.0006644227541983128, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5383, 'test_samples_per_second': 59.45, 'test_steps_per_second': 7.431, 'test_epoch': 7.0}
2025-05-14 16:46:45,698 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:46:45,701 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:46:45,819 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:46:45,823 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:46:45,824 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-133
2025-05-14 16:46:46,199 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0008109976770356297, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5561, 'eval_samples_per_second': 57.548, 'eval_steps_per_second': 7.194, 'epoch': 7.0, 'step': 133}
2025-05-14 16:46:46,200 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 16:46:46,761 - Experiment - INFO - Test metrics: {'test_loss': 0.0006644227541983128, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5545, 'test_samples_per_second': 57.711, 'test_steps_per_second': 7.214, 'test_epoch': 7.0}
2025-05-14 16:46:46,783 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:46:46,786 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:46:46,872 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:46:46,874 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:46:46,876 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-133
2025-05-14 16:46:47,215 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0008109976770356297, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5561, 'eval_samples_per_second': 57.548, 'eval_steps_per_second': 7.194, 'epoch': 7.0, 'step': 133}
2025-05-14 16:46:47,216 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 16:46:47,776 - Experiment - INFO - Test metrics: {'test_loss': 0.0006644227541983128, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5512, 'test_samples_per_second': 58.053, 'test_steps_per_second': 7.257, 'test_epoch': 7.0}
2025-05-14 16:46:47,801 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:46:47,805 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:46:47,923 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:46:47,925 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:46:49,228 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:46:49,299 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:46:49,301 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:46:49,302 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:46:50,572 - Experiment - INFO - Run ID: 79463b675ff84d019caf20f2475f4de7
2025-05-14 16:46:50,573 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-46-50;rs=1358057250
2025-05-14 16:46:50,587 - Experiment - INFO - {'dataset_name': 'euvsdisinfo', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:46:50,621 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:46:50,665 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA017A6F60>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001FA017A7680>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA017A7EC0>]>
2025-05-14 16:46:50,878 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:46:50,879 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:46:50,881 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:46:50,899 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:46:50,901 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:46:50,914 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:46:50,915 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:46:50,928 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 16:46:50,929 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:46:50,930 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:46:50,953 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:46:50,955 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:46:50,976 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:46:50,978 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:46:51,220 - Experiment - INFO - Preprocessing function 2: distillibert_encoder
2025-05-14 16:46:51,222 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:46:51,223 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:46:52,280 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:46:52,281 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:46:52,512 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:46:52,514 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:46:53,869 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:46:53,876 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:48:35,579 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:48:35,579 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:48:35,848 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.06202390417456627, 'eval_accuracy': 0.96875, 'eval_precision': 1.0, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9655172413793104, 'eval_roc_auc': 0.9921568627450981, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 0.5401, 'eval_samples_per_second': 59.252, 'eval_steps_per_second': 7.407, 'epoch': 6.0, 'step': 114}
2025-05-14 16:48:35,848 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:48:36,394 - Experiment - INFO - Test metrics: {'test_loss': 0.24657869338989258, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 0.9642857142857143, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5391, 'test_samples_per_second': 59.359, 'test_steps_per_second': 7.42, 'test_epoch': 6.0}
2025-05-14 16:48:36,407 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:48:36,417 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:48:36,499 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:48:36,501 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:48:36,501 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:48:36,753 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.06202390417456627, 'eval_accuracy': 0.96875, 'eval_precision': 1.0, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9655172413793104, 'eval_roc_auc': 0.9921568627450981, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 0.5401, 'eval_samples_per_second': 59.252, 'eval_steps_per_second': 7.407, 'epoch': 6.0, 'step': 114}
2025-05-14 16:48:36,753 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:48:37,292 - Experiment - INFO - Test metrics: {'test_loss': 0.24657869338989258, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 0.9642857142857143, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.521, 'test_samples_per_second': 61.426, 'test_steps_per_second': 7.678, 'test_epoch': 6.0}
2025-05-14 16:48:37,311 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:48:37,313 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:48:37,405 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:48:37,405 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:48:37,405 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:48:37,642 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.06202390417456627, 'eval_accuracy': 0.96875, 'eval_precision': 1.0, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9655172413793104, 'eval_roc_auc': 0.9921568627450981, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 0.5401, 'eval_samples_per_second': 59.252, 'eval_steps_per_second': 7.407, 'epoch': 6.0, 'step': 114}
2025-05-14 16:48:37,642 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:48:38,183 - Experiment - INFO - Test metrics: {'test_loss': 0.24657869338989258, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 0.9642857142857143, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5412, 'test_samples_per_second': 59.126, 'test_steps_per_second': 7.391, 'test_epoch': 6.0}
2025-05-14 16:48:38,197 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:48:38,213 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:48:38,292 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:48:38,292 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:48:38,292 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-76
2025-05-14 16:48:38,513 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.10012174397706985, 'eval_accuracy': 0.96875, 'eval_precision': 1.0, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9655172413793104, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 0.5373, 'eval_samples_per_second': 59.561, 'eval_steps_per_second': 7.445, 'epoch': 4.0, 'step': 76}
2025-05-14 16:48:38,513 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 16:48:39,060 - Experiment - INFO - Test metrics: {'test_loss': 0.22927531599998474, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 0.9642857142857143, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5471, 'test_samples_per_second': 58.49, 'test_steps_per_second': 7.311, 'test_epoch': 4.0}
2025-05-14 16:48:39,083 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:48:39,085 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:48:39,160 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:48:39,160 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:48:39,160 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-114
2025-05-14 16:48:39,382 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.06202390417456627, 'eval_accuracy': 0.96875, 'eval_precision': 1.0, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9655172413793104, 'eval_roc_auc': 0.9921568627450981, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 0.5401, 'eval_samples_per_second': 59.252, 'eval_steps_per_second': 7.407, 'epoch': 6.0, 'step': 114}
2025-05-14 16:48:39,382 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-14 16:48:39,906 - Experiment - INFO - Test metrics: {'test_loss': 0.24657869338989258, 'test_accuracy': 0.96875, 'test_precision': 0.9473684210526315, 'test_recall': 1.0, 'test_f1_score': 0.972972972972973, 'test_roc_auc': 0.9642857142857143, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5238, 'test_samples_per_second': 61.096, 'test_steps_per_second': 7.637, 'test_epoch': 6.0}
2025-05-14 16:48:39,941 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:48:39,943 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:48:40,026 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:48:40,026 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:48:40,624 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:48:40,624 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:48:40,624 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:48:40,624 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:48:41,689 - Experiment - INFO - Run ID: 937ee7f76a0041769811809a7766af23
2025-05-14 16:48:41,689 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-48-41;rs=2667821919
2025-05-14 16:48:41,704 - Experiment - INFO - {'dataset_name': 'euvsdisinfo', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:48:41,740 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:48:41,780 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA017A6F60>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001FA017A7680>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA017A7EC0>]>
2025-05-14 16:48:42,204 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:48:42,204 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:48:42,204 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:48:42,220 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:48:42,220 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:48:42,236 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:48:42,236 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:48:42,236 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 16:48:42,236 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:48:42,236 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:48:42,263 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:48:42,263 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:48:42,284 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:48:42,286 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:48:42,474 - Experiment - INFO - Preprocessing function 2: distillibert_encoder
2025-05-14 16:48:42,474 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:48:42,474 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:48:43,171 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:48:43,171 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:48:43,362 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:48:43,362 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:48:45,429 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:48:45,435 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:50:02,340 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:50:02,340 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-76
2025-05-14 16:50:02,584 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0016182662220671773, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5495, 'eval_samples_per_second': 58.234, 'eval_steps_per_second': 7.279, 'epoch': 4.0, 'step': 76}
2025-05-14 16:50:02,584 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 16:50:03,134 - Experiment - INFO - Test metrics: {'test_loss': 0.011721422895789146, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.55, 'test_samples_per_second': 58.181, 'test_steps_per_second': 7.273, 'test_epoch': 4.0}
2025-05-14 16:50:03,152 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:50:03,152 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:50:03,245 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:50:03,245 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:50:03,245 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-76
2025-05-14 16:50:03,462 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0016182662220671773, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5495, 'eval_samples_per_second': 58.234, 'eval_steps_per_second': 7.279, 'epoch': 4.0, 'step': 76}
2025-05-14 16:50:03,462 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 16:50:03,998 - Experiment - INFO - Test metrics: {'test_loss': 0.011721422895789146, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5347, 'test_samples_per_second': 59.845, 'test_steps_per_second': 7.481, 'test_epoch': 4.0}
2025-05-14 16:50:04,016 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:50:04,016 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:50:04,098 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:50:04,098 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:50:04,098 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-76
2025-05-14 16:50:04,289 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0016182662220671773, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5495, 'eval_samples_per_second': 58.234, 'eval_steps_per_second': 7.279, 'epoch': 4.0, 'step': 76}
2025-05-14 16:50:04,305 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 16:50:04,834 - Experiment - INFO - Test metrics: {'test_loss': 0.011721422895789146, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5293, 'test_samples_per_second': 60.462, 'test_steps_per_second': 7.558, 'test_epoch': 4.0}
2025-05-14 16:50:04,853 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:50:04,853 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:50:04,931 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:50:04,931 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:50:04,931 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-76
2025-05-14 16:50:05,131 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0016182662220671773, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5495, 'eval_samples_per_second': 58.234, 'eval_steps_per_second': 7.279, 'epoch': 4.0, 'step': 76}
2025-05-14 16:50:05,131 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 16:50:05,679 - Experiment - INFO - Test metrics: {'test_loss': 0.011721422895789146, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.546, 'test_samples_per_second': 58.613, 'test_steps_per_second': 7.327, 'test_epoch': 4.0}
2025-05-14 16:50:05,695 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:50:05,695 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:50:05,773 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:50:05,781 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:50:05,781 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-76
2025-05-14 16:50:05,995 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0016182662220671773, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.5495, 'eval_samples_per_second': 58.234, 'eval_steps_per_second': 7.279, 'epoch': 4.0, 'step': 76}
2025-05-14 16:50:05,995 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 16:50:06,533 - Experiment - INFO - Test metrics: {'test_loss': 0.011721422895789146, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.538, 'test_samples_per_second': 59.483, 'test_steps_per_second': 7.435, 'test_epoch': 4.0}
2025-05-14 16:50:06,558 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:50:06,558 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:50:06,633 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:50:06,642 - Experiment - INFO - Finished model evaluations stage.

### ISOT Dataset

In [9]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

2025-05-14 16:50:07,876 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:50:07,877 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:50:07,878 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:50:07,878 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:50:09,036 - Experiment - INFO - Run ID: 02a5ed65982f42f7bc583c5eb5570854
2025-05-14 16:50:09,036 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-50-08;rs=3591712861
2025-05-14 16:50:09,044 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:50:09,074 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:50:09,401 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA0295CC20>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA0295D550>]>
2025-05-14 16:50:09,737 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:50:09,737 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:50:09,737 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:50:09,764 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:50:09,780 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:50:09,796 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:50:09,796 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:50:09,990 - Experiment - INFO - Preprocessing function 1: distillibert_encoder
2025-05-14 16:50:09,990 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:50:09,990 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:50:14,088 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:50:14,089 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:50:15,251 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:50:15,252 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:50:20,763 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:50:20,768 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:54:15,637 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:54:15,637 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:54:15,915 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0031914699357002974, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5281, 'eval_samples_per_second': 58.939, 'eval_steps_per_second': 7.516, 'epoch': 2.0, 'step': 176}
2025-05-14 16:54:15,917 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:54:18,559 - Experiment - INFO - Test metrics: {'test_loss': 0.040321704000234604, 'test_accuracy': 0.9933333333333333, 'test_precision': 0.9880952380952381, 'test_recall': 1.0, 'test_f1_score': 0.9940119760479041, 'test_roc_auc': 0.999280704909189, 'test_false_positives_rate': 0.014925373134328358, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.6393, 'test_samples_per_second': 56.833, 'test_steps_per_second': 7.199, 'test_epoch': 2.0}
2025-05-14 16:54:18,586 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:54:18,590 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:54:18,982 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:54:18,983 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:54:18,984 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:54:19,228 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0031914699357002974, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5281, 'eval_samples_per_second': 58.939, 'eval_steps_per_second': 7.516, 'epoch': 2.0, 'step': 176}
2025-05-14 16:54:19,229 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:54:21,905 - Experiment - INFO - Test metrics: {'test_loss': 0.040321704000234604, 'test_accuracy': 0.9933333333333333, 'test_precision': 0.9880952380952381, 'test_recall': 1.0, 'test_f1_score': 0.9940119760479041, 'test_roc_auc': 0.999280704909189, 'test_false_positives_rate': 0.014925373134328358, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.6737, 'test_samples_per_second': 56.102, 'test_steps_per_second': 7.106, 'test_epoch': 2.0}
2025-05-14 16:54:21,929 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:54:21,933 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:54:22,395 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:54:22,399 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:54:22,399 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:54:22,642 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0031914699357002974, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5281, 'eval_samples_per_second': 58.939, 'eval_steps_per_second': 7.516, 'epoch': 2.0, 'step': 176}
2025-05-14 16:54:22,642 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:54:25,228 - Experiment - INFO - Test metrics: {'test_loss': 0.040321704000234604, 'test_accuracy': 0.9933333333333333, 'test_precision': 0.9880952380952381, 'test_recall': 1.0, 'test_f1_score': 0.9940119760479041, 'test_roc_auc': 0.999280704909189, 'test_false_positives_rate': 0.014925373134328358, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5823, 'test_samples_per_second': 58.088, 'test_steps_per_second': 7.358, 'test_epoch': 2.0}
2025-05-14 16:54:25,255 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:54:25,260 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:54:25,660 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:54:25,660 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:54:25,660 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:54:25,895 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0031914699357002974, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5281, 'eval_samples_per_second': 58.939, 'eval_steps_per_second': 7.516, 'epoch': 2.0, 'step': 176}
2025-05-14 16:54:25,895 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:54:28,505 - Experiment - INFO - Test metrics: {'test_loss': 0.040321704000234604, 'test_accuracy': 0.9933333333333333, 'test_precision': 0.9880952380952381, 'test_recall': 1.0, 'test_f1_score': 0.9940119760479041, 'test_roc_auc': 0.999280704909189, 'test_false_positives_rate': 0.014925373134328358, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5923, 'test_samples_per_second': 57.863, 'test_steps_per_second': 7.329, 'test_epoch': 2.0}
2025-05-14 16:54:28,531 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:54:28,537 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:54:28,985 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:54:28,988 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:54:28,992 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:54:29,227 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0031914699357002974, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5281, 'eval_samples_per_second': 58.939, 'eval_steps_per_second': 7.516, 'epoch': 2.0, 'step': 176}
2025-05-14 16:54:29,227 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:54:31,811 - Experiment - INFO - Test metrics: {'test_loss': 0.040321704000234604, 'test_accuracy': 0.9933333333333333, 'test_precision': 0.9880952380952381, 'test_recall': 1.0, 'test_f1_score': 0.9940119760479041, 'test_roc_auc': 0.999280704909189, 'test_false_positives_rate': 0.014925373134328358, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5697, 'test_samples_per_second': 58.373, 'test_steps_per_second': 7.394, 'test_epoch': 2.0}
2025-05-14 16:54:31,837 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:54:31,842 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:54:32,330 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:54:32,330 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:54:32,831 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:54:32,833 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 16:54:32,836 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:54:32,836 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:54:34,066 - Experiment - INFO - Run ID: bc81ae015dc345dbb4b8e59d2b65ea10
2025-05-14 16:54:34,068 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-54-33;rs=2857055362
2025-05-14 16:54:34,084 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:54:34,114 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:54:34,431 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA0295CC20>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA0295D550>]>
2025-05-14 16:54:35,772 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:54:35,774 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:54:35,776 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:54:35,821 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:54:35,823 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:54:35,846 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:54:35,848 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:54:36,046 - Experiment - INFO - Preprocessing function 1: distillibert_encoder
2025-05-14 16:54:36,046 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:54:36,047 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:54:40,648 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:54:40,649 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:54:41,686 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:54:41,691 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:54:47,441 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:54:47,446 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 16:58:40,859 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 16:58:40,859 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:58:41,113 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.004201293922960758, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5343, 'eval_samples_per_second': 58.794, 'eval_steps_per_second': 7.497, 'epoch': 2.0, 'step': 176}
2025-05-14 16:58:41,114 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:58:43,766 - Experiment - INFO - Test metrics: {'test_loss': 0.0009433801169507205, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.6463, 'test_samples_per_second': 56.683, 'test_steps_per_second': 7.18, 'test_epoch': 2.0}
2025-05-14 16:58:43,796 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:58:43,802 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:58:44,392 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:58:44,395 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 16:58:44,397 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:58:44,741 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.004201293922960758, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5343, 'eval_samples_per_second': 58.794, 'eval_steps_per_second': 7.497, 'epoch': 2.0, 'step': 176}
2025-05-14 16:58:44,742 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:58:47,336 - Experiment - INFO - Test metrics: {'test_loss': 0.0009433801169507205, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5879, 'test_samples_per_second': 57.961, 'test_steps_per_second': 7.342, 'test_epoch': 2.0}
2025-05-14 16:58:47,360 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:58:47,365 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:58:48,024 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:58:48,027 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 16:58:48,028 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:58:48,333 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.004201293922960758, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5343, 'eval_samples_per_second': 58.794, 'eval_steps_per_second': 7.497, 'epoch': 2.0, 'step': 176}
2025-05-14 16:58:48,334 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:58:50,909 - Experiment - INFO - Test metrics: {'test_loss': 0.0009433801169507205, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5677, 'test_samples_per_second': 58.418, 'test_steps_per_second': 7.4, 'test_epoch': 2.0}
2025-05-14 16:58:50,932 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:58:50,937 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:58:51,370 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:58:51,374 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 16:58:51,375 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:58:51,642 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.004201293922960758, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5343, 'eval_samples_per_second': 58.794, 'eval_steps_per_second': 7.497, 'epoch': 2.0, 'step': 176}
2025-05-14 16:58:51,642 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:58:54,244 - Experiment - INFO - Test metrics: {'test_loss': 0.0009433801169507205, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5968, 'test_samples_per_second': 57.763, 'test_steps_per_second': 7.317, 'test_epoch': 2.0}
2025-05-14 16:58:54,266 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:58:54,271 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:58:54,785 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:58:54,786 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 16:58:54,787 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 16:58:55,032 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.004201293922960758, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5343, 'eval_samples_per_second': 58.794, 'eval_steps_per_second': 7.497, 'epoch': 2.0, 'step': 176}
2025-05-14 16:58:55,033 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 16:58:57,666 - Experiment - INFO - Test metrics: {'test_loss': 0.0009433801169507205, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.628, 'test_samples_per_second': 57.078, 'test_steps_per_second': 7.23, 'test_epoch': 2.0}
2025-05-14 16:58:57,691 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 16:58:57,697 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 16:58:58,110 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 16:58:58,111 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 16:58:59,195 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 16:58:59,200 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 16:58:59,201 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:58:59,207 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 16:59:00,694 - Experiment - INFO - Run ID: 332ad10535804b22bf986e756150cd4c
2025-05-14 16:59:00,694 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_16-59-00;rs=2982179674
2025-05-14 16:59:00,710 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 16:59:00,751 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 16:59:01,409 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA0295CE00>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001FA02BA7B90>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA02BA6D80>]>
2025-05-14 16:59:01,681 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 16:59:01,682 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:59:01,683 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:59:01,749 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:59:01,750 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:59:01,772 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:59:01,774 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:59:01,803 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 16:59:01,805 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:59:01,807 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:59:02,095 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:59:02,097 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:59:02,156 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:59:02,157 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 16:59:02,413 - Experiment - INFO - Preprocessing function 2: distillibert_encoder
2025-05-14 16:59:02,413 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 16:59:02,414 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:59:07,582 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 16:59:07,583 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:59:09,036 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 16:59:09,038 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 16:59:17,061 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 16:59:17,067 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 17:03:03,979 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 17:03:03,979 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 17:03:04,201 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.01307881623506546, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9875, 'eval_recall': 1.0, 'eval_f1_score': 0.9937106918238994, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.014285714285714285, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.4729, 'eval_samples_per_second': 60.252, 'eval_steps_per_second': 7.683, 'epoch': 2.0, 'step': 176}
2025-05-14 17:03:04,201 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 17:03:06,820 - Experiment - INFO - Test metrics: {'test_loss': 0.05673075467348099, 'test_accuracy': 0.9866666666666667, 'test_precision': 0.974025974025974, 'test_recall': 1.0, 'test_f1_score': 0.9868421052631579, 'test_roc_auc': 0.9991111111111112, 'test_false_positives_rate': 0.02666666666666667, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.6155, 'test_samples_per_second': 57.35, 'test_steps_per_second': 7.264, 'test_epoch': 2.0}
2025-05-14 17:03:06,849 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:03:06,857 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:03:07,542 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:03:07,551 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 17:03:07,551 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 17:03:07,786 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.01307881623506546, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9875, 'eval_recall': 1.0, 'eval_f1_score': 0.9937106918238994, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.014285714285714285, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.4729, 'eval_samples_per_second': 60.252, 'eval_steps_per_second': 7.683, 'epoch': 2.0, 'step': 176}
2025-05-14 17:03:07,787 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 17:03:10,356 - Experiment - INFO - Test metrics: {'test_loss': 0.05673075467348099, 'test_accuracy': 0.9866666666666667, 'test_precision': 0.974025974025974, 'test_recall': 1.0, 'test_f1_score': 0.9868421052631579, 'test_roc_auc': 0.9991111111111112, 'test_false_positives_rate': 0.02666666666666667, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5642, 'test_samples_per_second': 58.499, 'test_steps_per_second': 7.41, 'test_epoch': 2.0}
2025-05-14 17:03:10,380 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:03:10,384 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:03:10,836 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:03:10,838 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 17:03:10,842 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 17:03:11,060 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.01307881623506546, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9875, 'eval_recall': 1.0, 'eval_f1_score': 0.9937106918238994, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.014285714285714285, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.4729, 'eval_samples_per_second': 60.252, 'eval_steps_per_second': 7.683, 'epoch': 2.0, 'step': 176}
2025-05-14 17:03:11,061 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 17:03:13,646 - Experiment - INFO - Test metrics: {'test_loss': 0.05673075467348099, 'test_accuracy': 0.9866666666666667, 'test_precision': 0.974025974025974, 'test_recall': 1.0, 'test_f1_score': 0.9868421052631579, 'test_roc_auc': 0.9991111111111112, 'test_false_positives_rate': 0.02666666666666667, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5836, 'test_samples_per_second': 58.057, 'test_steps_per_second': 7.354, 'test_epoch': 2.0}
2025-05-14 17:03:13,676 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:03:13,681 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:03:14,142 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:03:14,146 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 17:03:14,150 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 17:03:14,459 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.01307881623506546, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9875, 'eval_recall': 1.0, 'eval_f1_score': 0.9937106918238994, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.014285714285714285, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.4729, 'eval_samples_per_second': 60.252, 'eval_steps_per_second': 7.683, 'epoch': 2.0, 'step': 176}
2025-05-14 17:03:14,459 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 17:03:17,003 - Experiment - INFO - Test metrics: {'test_loss': 0.05673075467348099, 'test_accuracy': 0.9866666666666667, 'test_precision': 0.974025974025974, 'test_recall': 1.0, 'test_f1_score': 0.9868421052631579, 'test_roc_auc': 0.9991111111111112, 'test_false_positives_rate': 0.02666666666666667, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.5441, 'test_samples_per_second': 58.959, 'test_steps_per_second': 7.468, 'test_epoch': 2.0}
2025-05-14 17:03:17,030 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:03:17,034 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:03:17,533 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:03:17,535 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 17:03:17,537 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
2025-05-14 17:03:17,785 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.01307881623506546, 'eval_accuracy': 0.9932885906040269, 'eval_precision': 0.9875, 'eval_recall': 1.0, 'eval_f1_score': 0.9937106918238994, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.014285714285714285, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.4729, 'eval_samples_per_second': 60.252, 'eval_steps_per_second': 7.683, 'epoch': 2.0, 'step': 176}
2025-05-14 17:03:17,786 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-14 17:03:20,397 - Experiment - INFO - Test metrics: {'test_loss': 0.05673075467348099, 'test_accuracy': 0.9866666666666667, 'test_precision': 0.974025974025974, 'test_recall': 1.0, 'test_f1_score': 0.9868421052631579, 'test_roc_auc': 0.9991111111111112, 'test_false_positives_rate': 0.02666666666666667, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.607, 'test_samples_per_second': 57.537, 'test_steps_per_second': 7.288, 'test_epoch': 2.0}
2025-05-14 17:03:20,423 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:03:20,427 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:03:20,806 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:03:20,806 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 17:03:21,104 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 17:03:21,104 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 17:03:21,104 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:03:21,104 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:03:22,757 - Experiment - INFO - Run ID: 4b1c5f09c31a402f8871367aaf76f380
2025-05-14 17:03:22,757 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-03-22;rs=1207696679
2025-05-14 17:03:22,772 - Experiment - INFO - {'dataset_name': 'isot', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:03:22,804 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:03:23,126 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA0295CE00>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001FA02BA7B90>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FA02BA6D80>]>
2025-05-14 17:03:23,327 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:03:23,328 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:03:23,329 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:03:23,365 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:03:23,365 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:03:23,374 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:03:23,374 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:03:23,390 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 17:03:23,390 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:03:23,405 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:03:23,607 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:03:23,609 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:03:23,658 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:03:23,658 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:03:23,891 - Experiment - INFO - Preprocessing function 2: distillibert_encoder
2025-05-14 17:03:23,891 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:03:23,891 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:03:28,146 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:03:28,147 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:03:29,059 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:03:29,059 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:03:33,918 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 17:03:33,923 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 17:11:10,929 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 17:11:10,930 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-616
2025-05-14 17:11:11,194 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0035494633484631777, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5709, 'eval_samples_per_second': 57.955, 'eval_steps_per_second': 7.39, 'epoch': 7.0, 'step': 616}
2025-05-14 17:11:11,195 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 17:11:13,849 - Experiment - INFO - Test metrics: {'test_loss': 0.04951540380716324, 'test_accuracy': 0.9933333333333333, 'test_precision': 1.0, 'test_recall': 0.9859154929577465, 'test_f1_score': 0.9929078014184397, 'test_roc_auc': 0.9994651453021929, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.014084507042253521, 'test_runtime': 2.6487, 'test_samples_per_second': 56.632, 'test_steps_per_second': 7.173, 'test_epoch': 7.0}
2025-05-14 17:11:13,871 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:11:13,875 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:11:14,284 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:11:14,284 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 17:11:14,285 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-616
2025-05-14 17:11:14,505 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0035494633484631777, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5709, 'eval_samples_per_second': 57.955, 'eval_steps_per_second': 7.39, 'epoch': 7.0, 'step': 616}
2025-05-14 17:11:14,505 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 17:11:17,166 - Experiment - INFO - Test metrics: {'test_loss': 0.04951540380716324, 'test_accuracy': 0.9933333333333333, 'test_precision': 1.0, 'test_recall': 0.9859154929577465, 'test_f1_score': 0.9929078014184397, 'test_roc_auc': 0.9994651453021929, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.014084507042253521, 'test_runtime': 2.6551, 'test_samples_per_second': 56.496, 'test_steps_per_second': 7.156, 'test_epoch': 7.0}
2025-05-14 17:11:17,195 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:11:17,202 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:11:17,594 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:11:17,595 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 17:11:17,596 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-616
2025-05-14 17:11:17,843 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0035494633484631777, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5709, 'eval_samples_per_second': 57.955, 'eval_steps_per_second': 7.39, 'epoch': 7.0, 'step': 616}
2025-05-14 17:11:17,844 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 17:11:20,461 - Experiment - INFO - Test metrics: {'test_loss': 0.04951540380716324, 'test_accuracy': 0.9933333333333333, 'test_precision': 1.0, 'test_recall': 0.9859154929577465, 'test_f1_score': 0.9929078014184397, 'test_roc_auc': 0.9994651453021929, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.014084507042253521, 'test_runtime': 2.6125, 'test_samples_per_second': 57.416, 'test_steps_per_second': 7.273, 'test_epoch': 7.0}
2025-05-14 17:11:20,488 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:11:20,494 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:11:20,903 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:11:20,904 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 17:11:20,904 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-616
2025-05-14 17:11:21,126 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0035494633484631777, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5709, 'eval_samples_per_second': 57.955, 'eval_steps_per_second': 7.39, 'epoch': 7.0, 'step': 616}
2025-05-14 17:11:21,127 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 17:11:23,799 - Experiment - INFO - Test metrics: {'test_loss': 0.04951540380716324, 'test_accuracy': 0.9933333333333333, 'test_precision': 1.0, 'test_recall': 0.9859154929577465, 'test_f1_score': 0.9929078014184397, 'test_roc_auc': 0.9994651453021929, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.014084507042253521, 'test_runtime': 2.6666, 'test_samples_per_second': 56.251, 'test_steps_per_second': 7.125, 'test_epoch': 7.0}
2025-05-14 17:11:23,826 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:11:23,832 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:11:24,716 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:11:24,718 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 17:11:24,720 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-616
2025-05-14 17:11:25,063 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0035494633484631777, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 2.5709, 'eval_samples_per_second': 57.955, 'eval_steps_per_second': 7.39, 'epoch': 7.0, 'step': 616}
2025-05-14 17:11:25,065 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-14 17:11:27,690 - Experiment - INFO - Test metrics: {'test_loss': 0.04951540380716324, 'test_accuracy': 0.9933333333333333, 'test_precision': 1.0, 'test_recall': 0.9859154929577465, 'test_f1_score': 0.9929078014184397, 'test_roc_auc': 0.9994651453021929, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.014084507042253521, 'test_runtime': 2.6198, 'test_samples_per_second': 57.256, 'test_steps_per_second': 7.252, 'test_epoch': 7.0}
2025-05-14 17:11:27,717 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:11:27,723 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:11:28,246 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:11:28,249 - Experiment - INFO - Finished model evaluations stage.

### Czech Dataset

In [10]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_params_dict,
                          model_hparams_dict)

2025-05-14 17:11:32,694 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 17:11:32,696 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 17:11:32,697 - Experiment - INFO - Dataset signature: dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:11:32,698 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:11:33,562 - Experiment - INFO - Run ID: 5027a68187e54dcb9de3db6166396351
2025-05-14 17:11:33,563 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-11-33;rs=4091305702
2025-05-14 17:11:33,575 - Experiment - INFO - {'dataset_name': 'czechdataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:11:33,604 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:11:33,720 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA03150050>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FAE278B500>]>
2025-05-14 17:11:33,923 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:11:33,924 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:11:33,925 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:11:33,941 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:11:33,942 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:11:33,952 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:11:33,953 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:11:34,137 - Experiment - INFO - Preprocessing function 1: distillibert_encoder
2025-05-14 17:11:34,139 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:11:34,140 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:11:34,778 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:11:34,779 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:11:34,989 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:11:34,990 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:11:35,784 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 17:11:35,789 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 17:12:17,228 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 17:12:17,230 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 17:12:17,491 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2447594851255417, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 1.0, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.2627, 'eval_samples_per_second': 53.301, 'eval_steps_per_second': 7.614, 'epoch': 4.0, 'step': 36}
2025-05-14 17:12:17,492 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:12:17,760 - Experiment - INFO - Test metrics: {'test_loss': 0.21626834571361542, 'test_accuracy': 0.9333333333333333, 'test_precision': 1.0, 'test_recall': 0.9, 'test_f1_score': 0.9473684210526315, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.263, 'test_samples_per_second': 57.045, 'test_steps_per_second': 7.606, 'test_epoch': 4.0}
2025-05-14 17:12:17,782 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:12:17,784 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:12:17,829 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:12:17,830 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 17:12:17,831 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 17:12:18,090 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2447594851255417, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 1.0, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.2627, 'eval_samples_per_second': 53.301, 'eval_steps_per_second': 7.614, 'epoch': 4.0, 'step': 36}
2025-05-14 17:12:18,091 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:12:18,357 - Experiment - INFO - Test metrics: {'test_loss': 0.21626834571361542, 'test_accuracy': 0.9333333333333333, 'test_precision': 1.0, 'test_recall': 0.9, 'test_f1_score': 0.9473684210526315, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.2624, 'test_samples_per_second': 57.175, 'test_steps_per_second': 7.623, 'test_epoch': 4.0}
2025-05-14 17:12:18,382 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:12:18,384 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:12:18,427 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:12:18,428 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 17:12:18,429 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 17:12:18,632 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2447594851255417, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 1.0, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.2627, 'eval_samples_per_second': 53.301, 'eval_steps_per_second': 7.614, 'epoch': 4.0, 'step': 36}
2025-05-14 17:12:18,632 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:12:18,894 - Experiment - INFO - Test metrics: {'test_loss': 0.21626834571361542, 'test_accuracy': 0.9333333333333333, 'test_precision': 1.0, 'test_recall': 0.9, 'test_f1_score': 0.9473684210526315, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.2579, 'test_samples_per_second': 58.164, 'test_steps_per_second': 7.755, 'test_epoch': 4.0}
2025-05-14 17:12:18,916 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:12:18,919 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:12:18,959 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:12:18,960 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 17:12:18,961 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 17:12:19,180 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2447594851255417, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 1.0, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.2627, 'eval_samples_per_second': 53.301, 'eval_steps_per_second': 7.614, 'epoch': 4.0, 'step': 36}
2025-05-14 17:12:19,181 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:12:19,444 - Experiment - INFO - Test metrics: {'test_loss': 0.21626834571361542, 'test_accuracy': 0.9333333333333333, 'test_precision': 1.0, 'test_recall': 0.9, 'test_f1_score': 0.9473684210526315, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.2581, 'test_samples_per_second': 58.113, 'test_steps_per_second': 7.748, 'test_epoch': 4.0}
2025-05-14 17:12:19,462 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:12:19,464 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:12:19,504 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:12:19,505 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 17:12:19,505 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-36
2025-05-14 17:12:19,721 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2447594851255417, 'eval_accuracy': 0.9285714285714286, 'eval_precision': 1.0, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 0.2627, 'eval_samples_per_second': 53.301, 'eval_steps_per_second': 7.614, 'epoch': 4.0, 'step': 36}
2025-05-14 17:12:19,722 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-14 17:12:19,984 - Experiment - INFO - Test metrics: {'test_loss': 0.21626834571361542, 'test_accuracy': 0.9333333333333333, 'test_precision': 1.0, 'test_recall': 0.9, 'test_f1_score': 0.9473684210526315, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.2583, 'test_samples_per_second': 58.066, 'test_steps_per_second': 7.742, 'test_epoch': 4.0}
2025-05-14 17:12:20,007 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:12:20,010 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:12:20,053 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:12:20,054 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 17:12:20,270 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 17:12:20,271 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 17:12:20,272 - Experiment - INFO - Dataset signature: dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:12:20,273 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:12:21,647 - Experiment - INFO - Run ID: 95598fcff9a24cdaacd95611d79cc1c1
2025-05-14 17:12:21,648 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-12-21;rs=4223100236
2025-05-14 17:12:21,659 - Experiment - INFO - {'dataset_name': 'czechdataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:12:21,684 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:12:21,791 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_minimal_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FA03150050>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FAE278B500>]>
2025-05-14 17:12:21,974 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:12:21,975 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:12:21,976 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:12:22,093 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:12:22,094 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:12:22,115 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:12:22,117 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:12:22,327 - Experiment - INFO - Preprocessing function 1: distillibert_encoder
2025-05-14 17:12:22,328 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:12:22,329 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:12:22,947 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:12:22,947 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:12:23,117 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:12:23,117 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:12:23,881 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 17:12:23,887 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 17:13:26,249 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 17:13:26,250 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-81
2025-05-14 17:13:26,480 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0032802075147628784, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2531, 'eval_samples_per_second': 55.31, 'eval_steps_per_second': 7.901, 'epoch': 9.0, 'step': 81}
2025-05-14 17:13:26,481 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-14 17:13:26,877 - Experiment - INFO - Test metrics: {'test_loss': 0.003434310434386134, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.3918, 'test_samples_per_second': 38.282, 'test_steps_per_second': 5.104, 'test_epoch': 9.0}
2025-05-14 17:13:26,900 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:13:26,902 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:13:26,947 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:13:26,948 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 17:13:26,949 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-81
2025-05-14 17:13:27,143 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0032802075147628784, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2531, 'eval_samples_per_second': 55.31, 'eval_steps_per_second': 7.901, 'epoch': 9.0, 'step': 81}
2025-05-14 17:13:27,143 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-14 17:13:27,409 - Experiment - INFO - Test metrics: {'test_loss': 0.003434310434386134, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.2612, 'test_samples_per_second': 57.427, 'test_steps_per_second': 7.657, 'test_epoch': 9.0}
2025-05-14 17:13:27,431 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:13:27,433 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:13:27,477 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:13:27,477 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 17:13:27,478 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-81
2025-05-14 17:13:27,693 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0032802075147628784, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2531, 'eval_samples_per_second': 55.31, 'eval_steps_per_second': 7.901, 'epoch': 9.0, 'step': 81}
2025-05-14 17:13:27,694 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-14 17:13:27,955 - Experiment - INFO - Test metrics: {'test_loss': 0.003434310434386134, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.2568, 'test_samples_per_second': 58.415, 'test_steps_per_second': 7.789, 'test_epoch': 9.0}
2025-05-14 17:13:27,979 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:13:27,981 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:13:28,024 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:13:28,025 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 17:13:28,026 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-81
2025-05-14 17:13:28,215 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0032802075147628784, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2531, 'eval_samples_per_second': 55.31, 'eval_steps_per_second': 7.901, 'epoch': 9.0, 'step': 81}
2025-05-14 17:13:28,216 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-14 17:13:28,480 - Experiment - INFO - Test metrics: {'test_loss': 0.003434310434386134, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.2588, 'test_samples_per_second': 57.958, 'test_steps_per_second': 7.728, 'test_epoch': 9.0}
2025-05-14 17:13:28,502 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:13:28,504 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:13:28,548 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:13:28,549 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 17:13:28,550 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-81
2025-05-14 17:13:28,740 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0032802075147628784, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2531, 'eval_samples_per_second': 55.31, 'eval_steps_per_second': 7.901, 'epoch': 9.0, 'step': 81}
2025-05-14 17:13:28,741 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-14 17:13:29,010 - Experiment - INFO - Test metrics: {'test_loss': 0.003434310434386134, 'test_accuracy': 1.0, 'test_precision': 1.0, 'test_recall': 1.0, 'test_f1_score': 1.0, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.265, 'test_samples_per_second': 56.595, 'test_steps_per_second': 7.546, 'test_epoch': 9.0}
2025-05-14 17:13:29,027 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:13:29,030 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:13:29,074 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:13:29,075 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 17:13:29,281 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 17:13:29,281 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001)
2025-05-14 17:13:29,282 - Experiment - INFO - Dataset signature: dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:13:29,283 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:13:30,678 - Experiment - INFO - Run ID: c8f2f4400465490884a46830ac3c1fbf
2025-05-14 17:13:30,679 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=0.0001,wd=0.01,esp=3,est=0.001);dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-13-30;rs=3736908794
2025-05-14 17:13:30,690 - Experiment - INFO - {'dataset_name': 'czechdataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:13:30,720 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:13:30,832 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FAE2788E60>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001FAE278A210>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FAE278B4D0>]>
2025-05-14 17:13:31,048 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:13:31,050 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:13:31,050 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:13:31,065 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:13:31,066 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:13:31,077 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:13:31,078 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:13:31,090 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 17:13:31,091 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:13:31,092 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:13:31,158 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:13:31,160 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:13:31,183 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:13:31,184 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:13:31,567 - Experiment - INFO - Preprocessing function 2: distillibert_encoder
2025-05-14 17:13:31,568 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:13:31,569 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:13:32,164 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:13:32,164 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:13:32,329 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:13:32,330 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:13:33,064 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 17:13:33,069 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 17:14:35,884 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 17:14:35,884 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-90
2025-05-14 17:14:36,117 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0057422807440161705, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2438, 'eval_samples_per_second': 57.415, 'eval_steps_per_second': 8.202, 'epoch': 10.0, 'step': 90}
2025-05-14 17:14:36,117 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-14 17:14:36,374 - Experiment - INFO - Test metrics: {'test_loss': 0.6647014021873474, 'test_accuracy': 0.8666666666666667, 'test_precision': 1.0, 'test_recall': 0.6, 'test_f1_score': 0.75, 'test_roc_auc': 0.8799999999999999, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.4, 'test_runtime': 0.2572, 'test_samples_per_second': 58.322, 'test_steps_per_second': 7.776, 'test_epoch': 10.0}
2025-05-14 17:14:36,389 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:14:36,400 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:14:36,453 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:14:36,453 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 17:14:36,453 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-90
2025-05-14 17:14:36,672 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0057422807440161705, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2438, 'eval_samples_per_second': 57.415, 'eval_steps_per_second': 8.202, 'epoch': 10.0, 'step': 90}
2025-05-14 17:14:36,672 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-14 17:14:36,923 - Experiment - INFO - Test metrics: {'test_loss': 0.6647014021873474, 'test_accuracy': 0.8666666666666667, 'test_precision': 1.0, 'test_recall': 0.6, 'test_f1_score': 0.75, 'test_roc_auc': 0.8799999999999999, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.4, 'test_runtime': 0.2512, 'test_samples_per_second': 59.708, 'test_steps_per_second': 7.961, 'test_epoch': 10.0}
2025-05-14 17:14:36,942 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:14:36,942 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:14:36,984 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:14:36,984 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 17:14:36,984 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-90
2025-05-14 17:14:37,194 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0057422807440161705, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2438, 'eval_samples_per_second': 57.415, 'eval_steps_per_second': 8.202, 'epoch': 10.0, 'step': 90}
2025-05-14 17:14:37,195 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-14 17:14:37,469 - Experiment - INFO - Test metrics: {'test_loss': 0.6647014021873474, 'test_accuracy': 0.8666666666666667, 'test_precision': 1.0, 'test_recall': 0.6, 'test_f1_score': 0.75, 'test_roc_auc': 0.8799999999999999, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.4, 'test_runtime': 0.2698, 'test_samples_per_second': 55.6, 'test_steps_per_second': 7.413, 'test_epoch': 10.0}
2025-05-14 17:14:37,489 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:14:37,492 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:14:37,524 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:14:37,524 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 17:14:37,524 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-90
2025-05-14 17:14:37,736 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0057422807440161705, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2438, 'eval_samples_per_second': 57.415, 'eval_steps_per_second': 8.202, 'epoch': 10.0, 'step': 90}
2025-05-14 17:14:37,736 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-14 17:14:37,989 - Experiment - INFO - Test metrics: {'test_loss': 0.6647014021873474, 'test_accuracy': 0.8666666666666667, 'test_precision': 1.0, 'test_recall': 0.6, 'test_f1_score': 0.75, 'test_roc_auc': 0.8799999999999999, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.4, 'test_runtime': 0.2473, 'test_samples_per_second': 60.663, 'test_steps_per_second': 8.088, 'test_epoch': 10.0}
2025-05-14 17:14:38,005 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:14:38,005 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:14:38,052 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:14:38,052 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 17:14:38,052 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-90
2025-05-14 17:14:38,234 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.0057422807440161705, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2438, 'eval_samples_per_second': 57.415, 'eval_steps_per_second': 8.202, 'epoch': 10.0, 'step': 90}
2025-05-14 17:14:38,234 - Experiment - INFO - Best model found at epoch 10.0.

2025-05-14 17:14:38,501 - Experiment - INFO - Test metrics: {'test_loss': 0.6647014021873474, 'test_accuracy': 0.8666666666666667, 'test_precision': 1.0, 'test_recall': 0.6, 'test_f1_score': 0.75, 'test_roc_auc': 0.8799999999999999, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.4, 'test_runtime': 0.2518, 'test_samples_per_second': 59.58, 'test_steps_per_second': 7.944, 'test_epoch': 10.0}
2025-05-14 17:14:38,520 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:14:38,525 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:14:38,556 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:14:38,556 - Experiment - INFO - Finished model evaluations stage.
2025-05-14 17:14:38,926 - Experiment - INFO - MLflow experiment initialized with ID: 883249264897273672
2025-05-14 17:14:38,926 - Experiment - INFO - Model signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001)
2025-05-14 17:14:38,926 - Experiment - INFO - Dataset signature: dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:14:38,926 - Experiment - INFO - Run signature: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)])
2025-05-14 17:14:40,386 - Experiment - INFO - Run ID: e9911d68cdcd41cd9f1c78396a28e931
2025-05-14 17:14:40,390 - Experiment - INFO - Run name: model(mn=distilbert-base-uncased,mmn=loss,e=10,bs=8,ebs=8,lr=5e-05,wd=0.01,esp=3,est=0.001);dataset(dn=czechdataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.1,tt=top),noise_reduction(),distillibert_encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=512,isiw=false)]);2025-05-14_17-14-40;rs=436864456
2025-05-14 17:14:40,394 - Experiment - INFO - {'dataset_name': 'czechdataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-14 17:14:40,426 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-14 17:14:40,535 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'truncated_noise_reduction_bert_pipeline': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001FAE2788E60>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001FAE278A210>, <workspace.sources.local_datasets.preprocessing.encoders.distillibert.DistillibertEncoder object at 0x000001FAE278B4D0>]>
2025-05-14 17:14:40,892 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-14 17:14:40,892 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:14:40,892 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:14:40,892 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:14:40,892 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:14:40,908 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:14:40,908 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:14:40,924 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-14 17:14:40,924 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:14:40,924 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:14:40,972 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:14:40,972 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:14:41,003 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:14:41,003 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-14 17:14:41,213 - Experiment - INFO - Preprocessing function 2: distillibert_encoder
2025-05-14 17:14:41,221 - Experiment - INFO - Preprocessing split: train_set
2025-05-14 17:14:41,221 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:14:41,749 - Experiment - INFO - Preprocessing split: val_set
2025-05-14 17:14:41,749 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:14:41,922 - Experiment - INFO - Preprocessing split: test_set
2025-05-14 17:14:41,922 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-14 17:14:42,635 - Experiment - INFO - Model name: distilbert-base-uncased
2025-05-14 17:14:42,644 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 8, 'eval_batch_size': 8, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'early_stopping_patience': 3, 'early_stopping_threshold': 0.001}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-14 17:15:41,252 - Experiment - INFO - Evaluating model using precision metric...
2025-05-14 17:15:41,252 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-45
2025-05-14 17:15:41,474 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.576259970664978, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 1.0, 'eval_recall': 0.42857142857142855, 'eval_f1_score': 0.6, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.5714285714285714, 'eval_runtime': 0.2777, 'eval_samples_per_second': 50.414, 'eval_steps_per_second': 7.202, 'epoch': 5.0, 'step': 45}
2025-05-14 17:15:41,474 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-14 17:15:41,728 - Experiment - INFO - Test metrics: {'test_loss': 0.46790120005607605, 'test_accuracy': 0.8666666666666667, 'test_precision': 1.0, 'test_recall': 0.75, 'test_f1_score': 0.8571428571428571, 'test_roc_auc': 0.9464285714285714, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.25, 'test_runtime': 0.2541, 'test_samples_per_second': 59.025, 'test_steps_per_second': 7.87, 'test_epoch': 5.0}
2025-05-14 17:15:41,744 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:15:41,760 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:15:41,795 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:15:41,795 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-14 17:15:41,795 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-72
2025-05-14 17:15:42,034 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3033319413661957, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.7777777777777778, 'eval_recall': 1.0, 'eval_f1_score': 0.875, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.2857142857142857, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.249, 'eval_samples_per_second': 56.217, 'eval_steps_per_second': 8.031, 'epoch': 8.0, 'step': 72}
2025-05-14 17:15:42,034 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-14 17:15:42,302 - Experiment - INFO - Test metrics: {'test_loss': 0.6047855019569397, 'test_accuracy': 0.8, 'test_precision': 0.7777777777777778, 'test_recall': 0.875, 'test_f1_score': 0.8235294117647058, 'test_roc_auc': 0.9464285714285714, 'test_false_positives_rate': 0.2857142857142857, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.2672, 'test_samples_per_second': 56.145, 'test_steps_per_second': 7.486, 'test_epoch': 8.0}
2025-05-14 17:15:42,324 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:15:42,326 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:15:42,372 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:15:42,372 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-14 17:15:42,375 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-45
2025-05-14 17:15:42,590 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.576259970664978, 'eval_accuracy': 0.7142857142857143, 'eval_precision': 1.0, 'eval_recall': 0.42857142857142855, 'eval_f1_score': 0.6, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.5714285714285714, 'eval_runtime': 0.2777, 'eval_samples_per_second': 50.414, 'eval_steps_per_second': 7.202, 'epoch': 5.0, 'step': 45}
2025-05-14 17:15:42,590 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-14 17:15:42,850 - Experiment - INFO - Test metrics: {'test_loss': 0.46790120005607605, 'test_accuracy': 0.8666666666666667, 'test_precision': 1.0, 'test_recall': 0.75, 'test_f1_score': 0.8571428571428571, 'test_roc_auc': 0.9464285714285714, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.25, 'test_runtime': 0.2603, 'test_samples_per_second': 57.617, 'test_steps_per_second': 7.682, 'test_epoch': 5.0}
2025-05-14 17:15:42,866 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:15:42,866 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:15:42,913 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:15:42,913 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-14 17:15:42,913 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-72
2025-05-14 17:15:43,135 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3033319413661957, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.7777777777777778, 'eval_recall': 1.0, 'eval_f1_score': 0.875, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.2857142857142857, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.249, 'eval_samples_per_second': 56.217, 'eval_steps_per_second': 8.031, 'epoch': 8.0, 'step': 72}
2025-05-14 17:15:43,135 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-14 17:15:43,391 - Experiment - INFO - Test metrics: {'test_loss': 0.6047855019569397, 'test_accuracy': 0.8, 'test_precision': 0.7777777777777778, 'test_recall': 0.875, 'test_f1_score': 0.8235294117647058, 'test_roc_auc': 0.9464285714285714, 'test_false_positives_rate': 0.2857142857142857, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.2554, 'test_samples_per_second': 58.73, 'test_steps_per_second': 7.831, 'test_epoch': 8.0}
2025-05-14 17:15:43,411 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:15:43,417 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:15:43,460 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:15:43,462 - Experiment - INFO - Evaluating model using loss metric...
2025-05-14 17:15:43,462 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-72
2025-05-14 17:15:43,709 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3033319413661957, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.7777777777777778, 'eval_recall': 1.0, 'eval_f1_score': 0.875, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.2857142857142857, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.249, 'eval_samples_per_second': 56.217, 'eval_steps_per_second': 8.031, 'epoch': 8.0, 'step': 72}
2025-05-14 17:15:43,709 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-14 17:15:43,967 - Experiment - INFO - Test metrics: {'test_loss': 0.6047855019569397, 'test_accuracy': 0.8, 'test_precision': 0.7777777777777778, 'test_recall': 0.875, 'test_f1_score': 0.8235294117647058, 'test_roc_auc': 0.9464285714285714, 'test_false_positives_rate': 0.2857142857142857, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.2543, 'test_samples_per_second': 58.997, 'test_steps_per_second': 7.866, 'test_epoch': 8.0}
2025-05-14 17:15:43,983 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-14 17:15:43,983 - Experiment - INFO - Saving evaluation data in json...
2025-05-14 17:15:44,031 - Experiment - INFO - Successfully saved evaluation data.
2025-05-14 17:15:44,031 - Experiment - INFO - Finished model evaluations stage.