### Current (11/05/2025) training pipeline

In [11]:
import datasets as hf_datasets

from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.transformations import Truncation, HuggingFaceDatasetConversion
from workspace.sources.local_datasets.preprocessing.tokenization import BertBaseUncasedTokenizer
from workspace.sources.local_datasets.preprocessing.encoding import BertBaseUncasedEncoder
from workspace.sources.local_datasets.data_classes import HuggingFaceData
from workspace.sources.experiments.metrics import Loss
from workspace.sources.models.bert_base_uncased import BertBaseUncased


import mlflow

mlflow.set_tracking_uri('../../../mlruns')
mlflow.set_experiment('test_old_vs_new_training')

<Experiment: artifact_location='file:C:/Users/nikita.bardatskii/git/bi-bap-2025-bardanik/workspace/tests/../mlruns/328346920420097447', creation_time=1746961887234, experiment_id='328346920420097447', last_update_time=1746961887234, lifecycle_stage='active', name='test_old_vs_new_training', tags={}>

In [12]:
random_state = 2703938567

In [13]:
recovery = Dataset('ReCovery',
                   '../../../sources/local_datasets/data/Recovery/recovery.csv').init(random_state=random_state)
train_set_data = recovery.train_set
val_set_data = recovery.val_set
test_set_data = recovery.test_set
train_set_data.dataset.head()

2025-05-11 17:20:38,209 - Dataset - INFO - mlflow is not active, could not log the params: {'preprocessing_pipeline_name': 'empty', 'preprocessing_pipeline_representation': "<PreprocessingPipeline 'empty': []>", 'preprocessing_pipeline': []}
2025-05-11 17:20:38,209 - Dataset - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-11 17:20:38,348 - Dataset - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'empty': []>
2025-05-11 17:20:38,348 - Dataset - INFO - artifacts path is none, skipping saving.

                                                article  label
1117  Study Finds That Cloth Masks Can Increase Heal...      0
1080  How to have an election during COVID-19: India...      1
1015  Family of Amazon employee who died of COVID-19...      1
915   Calls To Helplines In America Increase Dramati...      0
622   Tommy Bartlett Show cancels 2020 season due to...      1

In [14]:
truncated_train_set_data = Truncation().init().preprocess(train_set_data.copy())
truncated_val_set_data = Truncation().init().preprocess(val_set_data.copy())
truncated_test_set_data = Truncation().init().preprocess(test_set_data.copy())
truncated_train_set_data.dataset

                                                article  label
1117  Study Finds That Cloth Masks Can Increase Heal...      0
1080  How to have an election during COVID-19: India...      1
1015  Family of Amazon employee who died of COVID-19...      1
915   Calls To Helplines In America Increase Dramati...      0
622   Tommy Bartlett Show cancels 2020 season due to...      1
...                                                 ...    ...
74    Trump Steps In To Help Oil Industry Facing Its...      1
1688  At least a quarter of the workforce is out of ...      1
1805  Will virus keep Florida spectators from astron...      1
681   WHO Guidelines for Frontline PPE Use Designed ...      1
958   ‘Grandstanding’ by Grand Old Party? Or is Prit...      1

[142 rows x 2 columns]

In [15]:
tokenized_train_set_data = BertBaseUncasedTokenizer().init().preprocess(truncated_train_set_data.copy())
tokenized_train_set_data.dataset

                                                article  label
1117  [study, finds, that, cloth, masks, can, increa...      0
1080  [how, to, have, an, election, during, co, ##vi...      1
1015  [family, of, amazon, employee, who, died, of, ...      1
915   [calls, to, help, ##lines, in, america, increa...      0
622   [tommy, bartlett, show, cancel, ##s, 2020, sea...      1
...                                                 ...    ...
74    [trump, steps, in, to, help, oil, industry, fa...      1
1688  [at, least, a, quarter, of, the, workforce, is...      1
1805  [will, virus, keep, florida, spectators, from,...      1
681   [who, guidelines, for, front, ##line, pp, ##e,...      1
958   [‘, grand, ##standing, ’, by, grand, old, part...      1

[142 rows x 2 columns]

In [7]:
encoded_train_set_data = BertBaseUncasedEncoder().init().preprocess(
    tokenized_train_set_data.copy()
)
encoded_train_set_data.features

,input_ids,token_type_ids,attention_mask,article
1117,"[101, 2025, 4090, 1115, 8217, 17944, 1169, 277...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",NaN
1080,"[101, 1293, 1106, 1138, 1126, 1728, 1219, 1884...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",NaN
1015,"[101, 1266, 1104, 1821, 10961, 1320, 7775, 115...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",NaN
915,"[101, 3675, 1106, 1494, 108, 108, 2442, 1107, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",NaN
622,"[101, 1106, 16211, 2927, 5034, 3069, 1437, 197...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",NaN
...,...,...,...,...
74,NaN,NaN,NaN,"[trump, steps, in, to, help, oil, industry, fa..."
1688,NaN,NaN,NaN,"[at, least, a, quarter, of, the, workforce, is..."
1805,NaN,NaN,NaN,"[will, virus, keep, florida, spectators, from,..."
681,NaN,NaN,NaN,"[who, guidelines, for, front, ##line, pp, ##e,..."
958,NaN,NaN,NaN,"[‘, grand, ##standing, ’, by, grand, old, part..."

In [9]:
converted_train_set_data = HuggingFaceDatasetConversion().init().preprocess(encoded_train_set_data.copy())
converted_train_set_data.dataset

Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'label', '__index_level_0__'],
    num_rows: 142
})

In [11]:
type(converted_train_set_data.dataset)

datasets.arrow_dataset.Dataset

### Old training pipeline

In [7]:
tokenizer_prepr = BertBaseUncasedTokenizer().init()
tokenizer = tokenizer_prepr.tokenizer

In [8]:
hf_train_set = hf_datasets.Dataset.from_pandas(truncated_train_set_data.dataset)
hf_val_set = hf_datasets.Dataset.from_pandas(truncated_val_set_data.dataset)
hf_test_set = hf_datasets.Dataset.from_pandas(truncated_test_set_data.dataset)
hf_train_set

Dataset({
    features: ['article', 'label', '__index_level_0__'],
    num_rows: 142
})

In [9]:
class Encoder:
    print_once = False
    @staticmethod
    def encoding_fn(example):
        output = tokenizer(example['article'],
                           padding='max_length',
                           truncation=True,
                           max_length=512)
        if Encoder.print_once:
            print(example)
            print(example['article'])
            print(output)
            Encoder.print_once = False
        return output

hf_train_set_encoded = hf_train_set.map(Encoder.encoding_fn, batched=True)
hf_val_set_encoded = hf_val_set.map(Encoder.encoding_fn, batched=True)
hf_test_set_encoded = hf_test_set.map(Encoder.encoding_fn, batched=True)
hf_train_set_encoded.set_format(type='torch')
hf_val_set_encoded.set_format(type='torch')
hf_test_set_encoded.set_format(type='torch')

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

In [65]:
converted_train_set_data.dataset[0]

{'input_ids': tensor([  101,  2025,  4090,  1115,  8217, 17944,  1169,  2773, 12520,  3239,
          3187,  1104,  8974,  1107,  4094,  1103,  9193,   131,   170,  2025,
          1502,  1107,  1410,  1276,  1115,  8217, 17944,  1169,  2773, 12520,
          3239,  3187,  1104,  8974,   119,  1122,  1145,  1270,  1154,  2304,
          1103, 23891,  1104,  2657, 17944,   119,  7977,  1113,   131,  1191,
         17944,  1336,  1136,  3244, 12520,  3239,  1107,  1126, 12104,  3545,
           117,  1184,  1132,  1152,  1833,  1111,  1103,  1470,   136,  1132,
          1103,  6134,  1189,  1118,  2332, 12638,  6421,  1579,  1107,  1103,
          1436,  2199,  1104,  1103,  1470,   136,   170,  1974,  1104,  2844,
          1132,  1299,   108,   108,  4676,  1115,  1234,  4330,   170,  7739,
           119,  1199, 14206,  4822,  1303,  1107,  1169,  7971,  1132,  1543,
          1122, 11839,  1111,  1234,  1150,  1328,  1106,  1202,  1199,  6001,
           117,  1105, 12724,  8805,  1279,  2514,  3055, 17983,  1115,  1155,
          1234,  1538,  4330,   170,  7739,  1165,  1280,  1796,   119,  1133,
          1202,  1292,  5252,  1541,  1494,   136,  1195,  1132,  1690,  1107,
          4020,  1551,  1165,  1234,  1176,  4550,  8257,  1132,  2033,   170,
          1974,  1104,   189,   119,   191,   119,  1159,   117,  1112,  1119,
          3093,  1106,  1129,  1103,  1362,   787,   188,  2020,   786,  2332,
           787,  3748,  1113,  1103,  1207,  1884, 15789,   108,   108,  7942,
           117,  1184,  1195,  1431,  1202,   117,  1105,  1293,  1195,   787,
          1231,  1280,  1106,  1831,  1122,   119,  1113,  1103,  1168,  1289,
           117,  1175,  1132,  1317,  8114,  1105,  2020,   174,  1643,   108,
           108, 25021,  1162,   108,   108,  1940,   108,   108,   184, 17246,
          1213,  1103,  1362,  1150,  1138,  1151,  5076, 20942,  1111,  4397,
          1115,  1138,  1151,   172,  1162,   108,   108,   183, 21484,   108,
           108,  5048,  1121,  1934,  2394,  6833,  1111,  6303,  1147,  1844,
          1105, 11089,   119,  1147,  7397,  1132,  1217,  1678,  1205,   117,
          1105,  1199,  1138,  1256,  1151,  5167,   108,   108,   176,  1174,
          1112,   786,  8406,   119,   787,  2367,  3739,   117,  1184,   787,
           188,  2488,  1114,  1142,  3439,   136,  1242,  1104,  1172,  1132,
          8783,  1115,  1103,  1207,  1884, 15789,   108,   108,  7942,  1110,
          1136,  2212,  1112,  4249,  1112,  1122,   787,   188,  1217,  1189,
          1149,  1106,  1129,   119,  1175,  1138,  1151,  2967,  2527,  1115,
          1138,  1145,  3228,  1142,  1359,  1113,  1103,  2233,  1115,  6962,
          1138, 15664,   119,  7965,  2394,  1110,  1774,  1541,  1662,  1106,
          3571,  1412, 11170,  1114, 12747,  1106,  1917,  1115, 22727,  1103,
          1207,  1884, 15789,   108,   108,  7942,   117,  1121,  3252,   117,
          5842,   108,   108,  1205,   108,   108,   188,   117,  1106,  1934,
          4267,   108,   108,   188,  5108,   108,   108,   172,  1158,  1105,
          1277,  1167,   119,  1195,   787,  1396,  2262,   170,  1374,  5136,
          1104,  1292,  8724,  2368,  1147, 11089,  1114, 12747,  1106,  1293,
          4249,  1142,  7942,  2140,  1110,   117,  1184,  1103,  5072,  1110,
           117, 14115,  1105,  1167,   119,  1191,  1128,   787,  1231,  3888,
          1128,  1169,  5991,  1106,  1103,  4237,  5128,  1120,  1103,  3248,
          1104,  1142,  1141,   119,  1120,  1103,  1322,  1104,  1103,  1285,
           117,   170,  1974,  1104,  1184,  1292,  8114,   117,  6479,  1105,
           174,  1643,   108,   108, 25021,  1162,   108,   108,  1940,   108,
           108,   184, 17246,  1138,  1151,  2157,  1290,  1103,  2150,  1104,
          1142,  8010,   117,  1146,  1235,  1208,   117,  1144,  2423, 14255,
          4487,   108,   108,  4267,  5822,   108,   108,  5048,  1103,  8195,
          1104,  2877,  2332, 12638,  6421,  1105,  1103,  1362,  2332,  2369,
           113,   102]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 'label': tensor(0),
 '__index_level_0__': tensor(1117)}

In [66]:
hf_train_set_encoded[0]

{'article': 'Study Finds That Cloth Masks Can Increase Healthcare Workers Risk of Infection In Brief The Facts: A study published in 2015 found that cloth masks can increase healthcare workers risk of infection. It also called into question the efficacy of medical masks.\r\n\r\nReflect On: If masks may not protect healthcare workers in an acute setting, what are they doing for the public? Are the decisions made by health regulatory agencies always in the best interest of the public?\r\n\r\nA lot of places are mandating that people wear a mask. Some grocery stores here in Canada are making it mandatory for people who want to do some shopping, and Los Angeles County recently mandated that all people must wear a mask when going outside. But do these measures really help? We are living in strange times when people like Bill Gates are getting a lot of T.V. time, as he seems to be the world’s leading ‘health’ authority on the new coronavirus, what we should do, and how we’re going to stop it. On the other hand, there are several doctors and leading epidemiologists around the world who have been studying viruses for decades that have been censored from social media platforms for sharing their research and opinions. Their interviews are being taken down, and some have even been flagged as ‘fake.’ Ask yourself, what’s wrong with this picture? Many of them are suggesting that the new coronavirus is not nearly as dangerous as it’s being made out to be. There have been multiple studies that have also suggested this based on the data that researchers have accumulated. Mainstream media is trying really hard to shape our perception with regards to everything that surrounds the new coronavirus, from treatment, lockdowns, to social distancing and much more.\r\n\r\nWe’ve covered a few examples of these experts giving their opinions with regards to how dangerous this virus actually is, what the solution is, treatments and more. If you’re interested you can refer to the articles linked at the bottom of this one. At the end of the day, a lot of what these doctors, scientists and epidemiologists have been saying since the beginning of this outbreak, up until now, has completely contradicted the narrative of federal health regulatory agencies and the World Health Organization (WHO). In fact, social media and other platforms are banning content that opposes and contradicts the WHO, no matter how much evidence is behind the information, or even if the sources are some of the leading experts in the world.\r\n\r\nShould there be a digital authoritarian Orwellian ‘fact checker’ going around the internet telling people what is, and what isn’t? Or should people have the right to examine information, check sources and evidence and ultimately decide for themselves?\r\n\r\nSpecial note to our followers: Is 5G safe? Learn the unbiased truth and the steps to implement better solutions in your community at the 5G Health Summit. It’s a free worldwide call to action from the leading independent experts, scientists and doctors in the field. You can sign up here.\r\n\r\nSo the question is, can we really trust these health authorities to guide us into doing what’s really best for us? Is this really about our health or is something else going on here? Are there powerful people profiting off of this both politically and financially? Was Edward Snowden correct when he said that the new coronavirus fiasco is no different from 9/11, in that it’s simply being used to push more authoritarian measures on the population? Just like they remained after 9/11, will they remain after this coronavirus? Why are there apps tracking people for coronavirus, but not for the pedophiles, murderers and rapists? These are important things to think about.\r\n\r\nThere is a lot of conflicting information out there and again, if you’re interested in going a little deeper you can refer to the articles listed at the end of this one.\r\n\r\nBut what about masks? Do they really help? How effective are they? According to Dr. Dan Erickson (former emergency-room physician) and Dr. Artin Massihi (emergency medicine specialist affiliated with multiple hospitals) of Accelerated Urgent Care in California, they’re not helping at all.\r\n\r\nWhen you wear gloves that transfer disease everywhere, those gloves have bacteria all over them. “I’m wearing gloves,” not helping you…Your mask that you’re wearing for days, you touch the outside of it, COVID, and then touch your mouth, this doesn’t make any sense. We wear masks in an acute setting to protect us, we’re not wearing masks (right now). Why is that? Because we understand microbiology, we understand immunology and we want strong immune systems. I don’t want to hide in my home, develop a weak immune system, and then come out and get disease. We’ve both been to the ER through swine flu and through bird flu, did we shut down for those? Were they much less dangerous than COVID? Is the flu less dangerous than COVID? Let’s look at the death rates, no it’s not. They’re similar in prevalence and in death rate. (source)\r\n\r\nAccording to a study published in BMJ Open in 2015,\r\n\r\nThis study is the first RCT of cloth masks, and the results caution against the use of cloth masks. This is an important finding to inform occupational health and safety. Moisture retention, reuse of cloth masks and poor filtration may result in increased risk of infection. Further research is needed to inform the widespread use of cloth masks globally. However, as a precautionary measure, cloth masks should not be recommended for HCWs, particularly in high-risk situations, and guidelines need to be updated. We have provided the first clinical efficacy data of cloth masks, which suggest HCWs should not use cloth masks as protection against respiratory infection. Cloth masks resulted in significantly higher rates of infection than medical masks, and also performed worse than the control arm. The controls were HCWs who observed standard practice, which involved mask use in the majority, albeit with lower compliance than in the intervention arms. The control HCWs also used medical masks more often than cloth masks. When we analysed all mask-wearers including controls, the higher risk of cloth masks was seen for laboratory-confirmed respiratory viral infection.\r\n\r\nAccording to the study, it was unclear if they help at all, and that they probably need to be worn at all times in acute/dangerous settings within the hospital to be effective at all.\r\n\r\nThere are also other potential health consequences of wearing not just a cloth mask, but also medical masks. The physiological effects of breathing elevated inhaled CO 2 may include changes in visual performance, modified exercise endurance, headaches and dyspnea. The psychological effects include decreased reasoning and alertness, increased irritability, severe dyspnea, headache, dizziness, perspiration, and short-term memory loss. (source)\r\n\r\nThis study suggests that masks don’t really help, and depending on the material, they can actually make things worse. That being said, there are studies suggesting that medical masks are indeed effective, but the studies are referring to health care workers in acute settings, not the general public.\r\n\r\nBelow is a quote from a very interesting paper published in 2016, titled “The Surgical Mask Is A Bad Fit For Risk Reduction.”\r\n\r\nAs represented by our cinema and other media, Western society expects too much of masks. In the public’s mind, the still-legitimate use of masks for source control has gone off-label; masks are thought to prevent infection. From here, another problem arises: because surgical masks are thought to protect against infection in the community setting, people wearing masks for legitimate purposes (those who have a cough in a hospital, say) form part of the larger misperception and act to reinforce it. Even this proper use of surgical masks is incorporated into a larger improper use in the era of pandemic fear, especially in Asia, where such fear is high. The widespread misconception about the use of surgical masks — that wearing a mask protects against the transmission of virus — is a problem of the kind theorized by German sociologist Ulrich Beck. The birth of the mask came from the realization that surgical wounds need protection from the droplets released in the breath of surgeons. The technology was applied outside the operating room in an effort to control the spread of infectious epidemics. In the 1919 influenza pandemic, masks were available and were dispensed to populations, but they had no impact on the epidemic curve. At the time, it was unknown that the influenza organism is nanoscopic and can theoretically penetrate the surgical mask barrier. As recently as 2010, the US National Academy of Sciences declared that, in the community setting, “face masks are not designed or certified to protect the wearer from exposure to respiratory hazards.” A number of studies have shown the inefficacy of the surgical mask in household settings to prevent transmission of the influenza virus…\r\n\r\nRelated CE Articles\r\n\r\nItalian Politician Says The “Lies & Falsification” of COVID-19 Numbers Is Used To “Terrorize Italians” (VIDEO)\r\n\r\nJust Like 9/11 Did, COVID-19 Is Shifting Human Consciousness In A Major Way\r\n\r\nLeading Scientist Claims Lockdown & Quarantine is a “Human Catastrophe” (New Interview)\r\n\r\nIs The COVID-19 Pandemic Pushing Humanity To Re-Imagine Normal?\r\n\r\nVitamin C For COVID-19: Critical Care Medicine Hospital Chief In Wuhan Provides Updates\r\n\r\nTwo Emergency Medicine Doctors On Why Quarantine “Just Doesn’t Make Sense”\r\n\r\nIf You Die of a Clear Alternative Cause, It’s Still Listed As A COVID Death” – Dr. Ngozi Ezike\r\n\r\nVimeo Bans Documentary Exposing “Big Pharma’s” Influence Within The World Health Organization\r\n\r\nWikileaks Highlights The Influence “Big Pharma” Has On The World Health Organization\r\n\r\nNew Study: The Flu Vaccine Is “Significantly Associated” With An Increased Risk of Coronavirus\r\n\r\nBill Gates’ Latest Instagram Post Has Been Bombarded With Accusations & Comments Against Vaccines\r\n\r\nRenowned Microbiology Specialist On Why He Believes Coronavirus Measures Are “Draconian” (Video)\r\n\r\nRenowned German Pulmonologist Questions Coronavirus Measures & If They’re Necessary (Video)\r\n\r\nUpdates On The New Coronavirus Vaccine – Are You Going To Take It? Will It Be Mandatory?\r\n\r\nSpring Has Sprung In Sweden With No Coronavirus Quarantine Or Police Enforced Lockdown\r\n\r\nSome New York Hospitals Are Now Treating Coronavirus With High Dose Vitamin C\r\n\r\nConscious Truth Behind Coronavirus Lockdown\r\n\r\nCoronavirus Is Proving The Human Race Can Come Together, For Anything, At Anytime\r\n\r\nWhite House: Out of 327 Million Americans – Coronavirus May Kill Up To 200,000\r\n\r\nEdward Snowden: Governments Shouldn’t Have The “Mandatory Authority” To Keep People Inside\r\n\r\nScientist Predicts Second Wave of COVID-19 Because “Social Distancing” Has Prevented “Herd Immunity”\r\n\r\nMore Physicians Go On The Record Explaining Why COVID-19 Deaths May Be Exaggerated\r\n\r\nCoronavirus Deaths May Be Miscalculated\r\n\r\nDr. Ron Paul Gets Flagged As “Fake News” For Sharing His Opinion About Coronavirus\r\n\r\nDonald Trump Says The Coronavirus Was “Artificially Induced.”\r\n\r\nCanadian Prime Minister Says We Won’t Return To Normal “Until A Vaccine Is Developed”\r\n\r\nBill Gates: We Won’t Go Back To “Normal Until” A Vaccine Has “Gotten Out To The Entire World”\r\n\r\nLA Doctor: COVID-19 Patients Go From ‘Very Ill’ To ‘Symptom-Free’ In 8 To 12 Hours With Hydroxychloroquine & Zinc\r\n\r\nConfirmed: High-Dose Vitamin C Has Successfully Treated 50 Moderate to Severe COVID-19 Patients',
 'label': tensor(0),
 '__index_level_0__': tensor(1117),
 'input_ids': tensor([  101,  2817,  4858,  2008,  8416, 15806,  2064,  3623,  9871,  3667,
          3891,  1997,  8985,  1999,  4766,  1996,  8866,  1024,  1037,  2817,
          2405,  1999,  2325,  2179,  2008,  8416, 15806,  2064,  3623,  9871,
          3667,  3891,  1997,  8985,  1012,  2009,  2036,  2170,  2046,  3160,
          1996, 21150,  1997,  2966, 15806,  1012,  8339,  2006,  1024,  2065,
         15806,  2089,  2025,  4047,  9871,  3667,  1999,  2019, 11325,  4292,
          1010,  2054,  2024,  2027,  2725,  2005,  1996,  2270,  1029,  2024,
          1996,  6567,  2081,  2011,  2740, 10738,  6736,  2467,  1999,  1996,
          2190,  3037,  1997,  1996,  2270,  1029,  1037,  2843,  1997,  3182,
          2024,  2158, 16616,  2008,  2111,  4929,  1037,  7308,  1012,  2070,
         13025,  5324,  2182,  1999,  2710,  2024,  2437,  2009, 10915,  2005,
          2111,  2040,  2215,  2000,  2079,  2070,  6023,  1010,  1998,  3050,
          3349,  2221,  3728, 16714,  2008,  2035,  2111,  2442,  4929,  1037,
          7308,  2043,  2183,  2648,  1012,  2021,  2079,  2122,  5761,  2428,
          2393,  1029,  2057,  2024,  2542,  1999,  4326,  2335,  2043,  2111,
          2066,  3021,  6733,  2024,  2893,  1037,  2843,  1997,  1056,  1012,
          1058,  1012,  2051,  1010,  2004,  2002,  3849,  2000,  2022,  1996,
          2088,  1521,  1055,  2877,  1520,  2740,  1521,  3691,  2006,  1996,
          2047, 21887, 23350,  1010,  2054,  2057,  2323,  2079,  1010,  1998,
          2129,  2057,  1521,  2128,  2183,  2000,  2644,  2009,  1012,  2006,
          1996,  2060,  2192,  1010,  2045,  2024,  2195,  7435,  1998,  2877,
          4958,  5178,  4328, 16886,  2105,  1996,  2088,  2040,  2031,  2042,
          5702, 18191,  2005,  5109,  2008,  2031,  2042,  8292, 29577,  2098,
          2013,  2591,  2865,  7248,  2005,  6631,  2037,  2470,  1998, 10740,
          1012,  2037,  7636,  2024,  2108,  2579,  2091,  1010,  1998,  2070,
          2031,  2130,  2042,  5210,  5999,  2004,  1520,  8275,  1012,  1521,
          3198,  4426,  1010,  2054,  1521,  1055,  3308,  2007,  2023,  3861,
          1029,  2116,  1997,  2068,  2024,  9104,  2008,  1996,  2047, 21887,
         23350,  2003,  2025,  3053,  2004,  4795,  2004,  2009,  1521,  1055,
          2108,  2081,  2041,  2000,  2022,  1012,  2045,  2031,  2042,  3674,
          2913,  2008,  2031,  2036,  4081,  2023,  2241,  2006,  1996,  2951,
          2008,  6950,  2031, 14830,  1012,  7731,  2865,  2003,  2667,  2428,
          2524,  2000,  4338,  2256, 10617,  2007, 12362,  2000,  2673,  2008,
         20626,  1996,  2047, 21887, 23350,  1010,  2013,  3949,  1010,  5843,
          7698,  2015,  1010,  2000,  2591,  4487, 12693,  6129,  1998,  2172,
          2062,  1012,  2057,  1521,  2310,  3139,  1037,  2261,  4973,  1997,
          2122,  8519,  3228,  2037, 10740,  2007, 12362,  2000,  2129,  4795,
          2023,  7865,  2941,  2003,  1010,  2054,  1996,  5576,  2003,  1010,
         13441,  1998,  2062,  1012,  2065,  2017,  1521,  2128,  4699,  2017,
          2064,  6523,  2000,  1996,  4790,  5799,  2012,  1996,  3953,  1997,
          2023,  2028,  1012,  2012,  1996,  2203,  1997,  1996,  2154,  1010,
          1037,  2843,  1997,  2054,  2122,  7435,  1010,  6529,  1998,  4958,
          5178,  4328, 16886,  2031,  2042,  3038,  2144,  1996,  2927,  1997,
          2023,  8293,  1010,  2039,  2127,  2085,  1010,  2038,  3294, 24528,
         29201,  2098,  1996,  7984,  1997,  2976,  2740, 10738,  6736,  1998,
          1996,  2088,  2740,  3029,  1006,  2040,  1007,  1012,  1999,  2755,
          1010,  2591,  2865,  1998,  2060,  7248,  2024, 21029,  4180,  2008,
         29158,  1998, 24528, 29201,  2015,  1996,  2040,  1010,  2053,  3043,
          2129,  2172,  3350,  2003,  2369,  1996,  2592,  1010,  2030,  2130,
          2065,  1996,  4216,  2024,  2070,  1997,  1996,  2877,  8519,  1999,
          1996,  2088,  1012,  2323,  2045,  2022,  1037,  3617, 27246,  2030,
          4381,   102]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1])}

In [61]:
print(type(converted_train_set_data.dataset['input_ids']))
converted_train_set_data.dataset['input_ids'] == hf_train_set_encoded['input_ids']

<class 'torch.Tensor'>

tensor([[ True, False, False,  ..., False, False,  True],
        [ True, False, False,  ..., False, False,  True],
        [ True, False, False,  ..., False, False,  True],
        ...,
        [ True, False, False,  ..., False, False,  True],
        [ True, False, False,  ...,  True,  True,  True],
        [ True, False, False,  ..., False, False,  True]])

In [63]:
converted_train_set_data.dataset['input_ids']

tensor([[  101,  2025,  4090,  ...,  2369,   113,   102],
        [  101,  1293,  1106,  ...,   108,   182,   102],
        [  101,  1266,  1104,  ...,  1412,  3578,   102],
        ...,
        [  101,  1209,  7942,  ...,  1306,  1115,   102],
        [  101,  1150, 13112,  ...,     0,     0,     0],
        [  101,   786,  5372,  ...,  1198,  1660,   102]])

In [62]:
hf_train_set_encoded['input_ids']

tensor([[  101,  2817,  4858,  ...,  2030,  4381,   102],
        [  101,  2129,  2000,  ...,  6224,  9930,   102],
        [  101,  2155,  1997,  ...,  2129,  2116,   102],
        ...,
        [  101,  2097,  7865,  ...,  2015,  1012,   102],
        [  101,  2040, 11594,  ...,     0,     0,     0],
        [  101,  1520,  2882,  ...,  3901,  1010,   102]])

In [10]:

with mlflow.start_run() as run:
    recovery.init(random_state=random_state)
    recovery.preprocessed_train_set = HuggingFaceData(hf_train_set_encoded)
    recovery.preprocessed_val_set = HuggingFaceData(hf_val_set_encoded)
    recovery.preprocessed_test_set = HuggingFaceData(hf_test_set_encoded)
    recovery.save_prepared_datasets()
    model_training_arguments = {'epochs': 3,
                                'early_stopping_patience': None,
                                'early_stopping_threshold': None}

    model = BertBaseUncased(train_best_model_metric=Loss,
                            training_arguments=model_training_arguments)
    model.init(random_state=random_state)
    model.fit(recovery)
    model.evaluate()

2025-05-11 16:49:12,593 - Dataset - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-11 16:49:12,742 - Dataset - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'empty': []>

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

KeyError: "The `metric_for_best_model` training argument is set to 'eval_loss', which is not found in the evaluation metrics. The available evaluation metrics are: []. Consider changing the `metric_for_best_model` via the TrainingArguments."

### Mapping already encoded

In [48]:
class EncoderFromTokenized:
    print_once = False
    @staticmethod
    def encoding_fn(example):
        output = tokenizer(example['article'],
                           is_split_into_words=True,
                           padding='max_length',
                           truncation=True,
                           max_length=512)
        if EncoderFromTokenized.print_once:
            print(example)
            print(example['article'])
            print(output)
            EncoderFromTokenized.print_once = False
        return output

In [16]:
hf_tokenized_train_set = hf_datasets.Dataset.from_pandas(tokenized_train_set_data.dataset)
hf_tokenized_train_set

Dataset({
    features: ['article', 'label', '__index_level_0__'],
    num_rows: 142
})

In [19]:
hf_tokenized_train_set.set_format(type='torch')
print(hf_tokenized_train_set.format)
hf_tokenized_train_set

{'type': 'torch', 'format_kwargs': {}, 'columns': ['article', 'label', '__index_level_0__'], 'output_all_columns': False}

Dataset({
    features: ['article', 'label', '__index_level_0__'],
    num_rows: 142
})

In [23]:
hf_tokenized_train_set_encoded = hf_tokenized_train_set.map(EncoderFromTokenized.encoding_fn, batched=True)

Map:   0%|          | 0/142 [00:00<?, ? examples/s]

In [26]:
hf_tokenized_train_set_encoded['input_ids']

tensor([[  101,  2817,  4858,  ...,  2591,  2865,   102],
        [  101,  2129,  2000,  ...,  2000,  9689,   102],
        [  101,  2155,  1997,  ...,  1055,  2331,   102],
        ...,
        [  101,  2097,  7865,  ...,  8911,  3958,   102],
        [  101,  2040, 11594,  ...,     0,     0,     0],
        [  101,  1520,  2882,  ...,  4394,  2041,   102]])

In [27]:
hf_train_set_encoded['input_ids']

tensor([[  101,  2817,  4858,  ...,  2030,  4381,   102],
        [  101,  2129,  2000,  ...,  6224,  9930,   102],
        [  101,  2155,  1997,  ...,  2129,  2116,   102],
        ...,
        [  101,  2097,  7865,  ...,  2015,  1012,   102],
        [  101,  2040, 11594,  ...,     0,     0,     0],
        [  101,  1520,  2882,  ...,  3901,  1010,   102]])

In [28]:
hf_tokenized_train_set_encoded['input_ids'] == hf_train_set_encoded['input_ids']

tensor([[ True,  True,  True,  ..., False, False,  True],
        [ True,  True,  True,  ..., False, False,  True],
        [ True,  True,  True,  ..., False, False,  True],
        ...,
        [ True,  True,  True,  ..., False, False,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ..., False, False,  True]])

In [36]:
truncated_train_set_data.features.iloc[5]

'Lyft is offering free e-scooter trips to health care workers fighting COVID-19 Lyft will provide free electric scooter rides to essential workers in response to the COVID-19 pandemic. While most scooter-sharing programs in the US have temporarily ceased operations in response to the pandemic, Lyft is still operating scooters in a handful of cities, and the company wants to support the transportation needs of health care workers and others on the frontlines of the crisis.\r\n\r\nLyft is offering free scooter rides through April 30th, up to 30 minutes in length, for first-responders, health care employees, and transit workers in the following cities: Austin, Denver, Los Angeles, San Diego, Santa Monica, and Washington, DC. Employers like hospitals, clinics, and transit agencies can email Lyft at heroscooters@lyft.com to obtain enrollment information that they can distribute to staff.\r\n\r\nLyft says it will prioritize scooter deployment near local hospitals for health care workers. The company is continuing to disinfect contact surfaces on scooters each time they are recharged, including handlebars, brake levers, bells, and throttles. The team is also disinfecting high contact surfaces on vans used to transport scooters at the start of each shift.\r\n\r\n“Lyft scooters can play a unique role in providing essential transportation to critical workers.”\r\n\r\n“Lyft scooters can play a unique role in providing essential transportation to critical workers on the frontlines against COVID-19,” said Caroline Samponaro, head of micromobility and transit policy at Lyft. “In a time of crisis, we know Lyft can be an essential lifeline, and we are proud to serve first-responders, transit, and healthcare providers as they serve the public.”\r\n\r\nPreviously, the ride-hailing company said it would provide free and discounted bike-share passes to essential workers in half a dozen cities. Free or cheap bike and scooter trips are especially useful as public transportation ridership continues to plummet in most cities and ride-sharing is not seen as a safe alternative. In fact, there has been a surge in cycling in New York City, Philadelphia, and Chicago.\r\n\r\nOf course, Lyft’s ride-sharing business has plummeted as health officials instruct people to avoid unnecessary travel. The company’s rides business has been cut in half in recent weeks, according to The Information. Lyft’s revenue after paying drivers is likely to be less than $150 million a month currently, down from about $260 million a month during the first quarter of last year, the publication reports. Lyft’s rival, Uber, has also seen a huge drop in demand and sales.\r\n\r\nBoth companies have come under fire for classifying drivers and delivery workers as independent contractors. Sen. Elizabeth Warren (D-MA) wrote a letter to gig companies calling on them to “reclassify your delivery workers as employees, rather than independent contractors, and ensure they are provided a full suite of employee protections and benefits.”'

In [45]:
tokenizer.convert_ids_to_tokens(hf_tokenized_train_set_encoded['input_ids'][5][:6])

['[CLS]', 'l', '#', '#', 'y', '#']

In [46]:
tokenizer.convert_ids_to_tokens(hf_train_set_encoded['input_ids'][5][:6])

['[CLS]', 'l', '##y', '##ft', 'is', 'offering']

In [50]:
enc = tokenizer("Lyft is offering")
tokens = tokenizer.convert_ids_to_tokens(enc["input_ids"])
print(tokens)

['[CLS]', 'l', '##y', '##ft', 'is', 'offering', '[SEP]']

In [54]:
words = tokenizer.tokenize("Lyft is offering")            # → ['un',
enc2 = tokenizer(words, is_split_into_words=True)
tokens2 = tokenizer.convert_ids_to_tokens(enc2["input_ids"])
print(tokens2)

['[CLS]', 'l', '#', '#', 'y', '#', '#', 'ft', 'is', 'offering', '[SEP]']

In [55]:
words = ['Lyft', 'is', 'offering']
enc2 = tokenizer(words, is_split_into_words=True)
tokens2 = tokenizer.convert_ids_to_tokens(enc2["input_ids"])
print(tokens2)

['[CLS]', 'l', '##y', '##ft', 'is', 'offering', '[SEP]']