In [8]:
from workspace.sources.local_datasets.preprocessing.tokenization import NLTKTokenizer
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction, Lemmatization, Stemming
from workspace.sources.experiments.metrics import Loss
from workspace.sources.utils import class_name_to_str
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.local_datasets.preprocessing.utils import truncate
from sklearn.model_selection import ParameterGrid
from IPython.display import display, Markdown

from workspace.sources.local_datasets.preprocessing.encoders.encoders import GPT1_Encoder as Encoder
from workspace.sources.models.transformers.openai_gpt_models import GPT1 as Model

import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [9]:
experiment_name = f'prefinal-{class_name_to_str(Model.__name__)}-v2'
print('Experiment:', experiment_name)

Experiment: prefinal-gpt1-v2

In [10]:
def conduct_gpt_model_experiments(dataset_name,
                                  dataset_path,
                                  dataset_hparams_grid,
                                  model_hparams_grid):
    total_runs = len(dataset_hparams_grid) * len(model_hparams_grid)
    for i, dataset_params in enumerate(dataset_hparams_grid):
        encoder = dataset_params['preprocessings_pipeline'][-1]
        for j, model_hparams in enumerate(model_hparams_grid):
            run_number = i * len(model_hparams_grid) + j + 1
            display(Markdown(f'### Run {run_number} of {total_runs}'))
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = Model(gpt_encoder=encoder,
                          train_best_model_metric=Loss,
                          training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            recovery_experiment.run()

In [11]:

# max_tokens_params = [128, 512]
max_tokens_params = [128, 256]

pipelines = []

for max_tokens in max_tokens_params:
    pipelines.extend([PreprocessingPipeline(name='minimal',
                                            iterable=[Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction',
                                            iterable=[NoiseReduction(),
                                                      Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Lemmatization(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_stemming',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Stemming(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)])
                      ])
# optional - for testing purposes, if you want to run fast test on very small datasets
# truncate(pipelines, fraction=0.05)

dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': pipelines})

print('Dataset Hyperparameters Grid Size: ', len(dataset_hparams_grid))

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16],
                                    'learning_rate': [1e-05, 5e-05],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [0.0, 1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})

print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### ReCOVery Dataset

In [12]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_gpt_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid)

### Run 1 of 4

2025/05/16 01:29:36 INFO mlflow.tracking.fluent: Experiment with name 'prefinal-gpt1-v2' does not exist. Creating a new experiment.
2025-05-16 01:29:36,856 - Experiment - INFO - MLflow experiment initialized with ID: 455212717504321152
2025-05-16 01:29:36,857 - Experiment - INFO - Model signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 01:29:36,858 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 01:29:36,859 - Experiment - INFO - Run signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 01:29:37,131 - Experiment - INFO - Run ID: d3b8c925e82944228ff7235b3ce2d91b
2025-05-16 01:29:37,132 - Experiment - INFO - Run name: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)]);2025-05-16_01-29-36;rs=298574374
2025-05-16 01:29:37,145 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:29:37,173 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:29:37,351 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000232B0E98D10>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT1_Encoder object at 0x00000232B0E9BD10>]>
2025-05-16 01:29:37,728 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:29:37,728 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:29:37,731 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:29:37,751 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:29:37,753 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:29:37,773 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:29:37,775 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:29:38,040 - Experiment - INFO - Preprocessing function 1: gpt1__encoder
2025-05-16 01:29:38,041 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:29:38,042 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:29:38,498 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:29:38,499 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:29:38,761 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:29:38,764 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:29:39,723 - Experiment - INFO - Model name: GPT1
2025-05-16 01:29:39,728 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of OpenAIGPTForSequenceClassification were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:32:33,786 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:32:33,787 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:32:34,257 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5421847105026245, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.8, 'eval_recall': 0.8, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.7400000000000001, 'eval_false_positives_rate': 0.4, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.7117, 'eval_samples_per_second': 21.075, 'eval_steps_per_second': 1.405, 'epoch': 5.0, 'step': 25}
2025-05-16 01:32:34,258 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:32:35,385 - Experiment - INFO - Test metrics: {'test_loss': 1.054443597793579, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.5555555555555556, 'test_recall': 0.5555555555555556, 'test_f1_score': 0.5555555555555556, 'test_roc_auc': 0.3148148148148148, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.4444444444444444, 'test_runtime': 1.1233, 'test_samples_per_second': 13.354, 'test_steps_per_second': 0.89, 'test_epoch': 5.0}
2025-05-16 01:32:35,407 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:32:35,409 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:32:35,454 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:32:35,455 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:32:35,456 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:32:36,154 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5549389123916626, 'eval_accuracy': 0.8, 'eval_precision': 0.7692307692307693, 'eval_recall': 1.0, 'eval_f1_score': 0.8695652173913043, 'eval_roc_auc': 0.76, 'eval_false_positives_rate': 0.6, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.6733, 'eval_samples_per_second': 22.277, 'eval_steps_per_second': 1.485, 'epoch': 3.0, 'step': 15}
2025-05-16 01:32:36,155 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:32:36,662 - Experiment - INFO - Test metrics: {'test_loss': 0.8507499098777771, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.6, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.631578947368421, 'test_roc_auc': 0.35185185185185186, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.5013, 'test_samples_per_second': 29.922, 'test_steps_per_second': 1.995, 'test_epoch': 3.0}
2025-05-16 01:32:36,681 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:32:36,683 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:32:36,725 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:32:36,726 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:32:36,727 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:32:37,177 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5421847105026245, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.8, 'eval_recall': 0.8, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.7400000000000001, 'eval_false_positives_rate': 0.4, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.7117, 'eval_samples_per_second': 21.075, 'eval_steps_per_second': 1.405, 'epoch': 5.0, 'step': 25}
2025-05-16 01:32:37,178 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:32:37,836 - Experiment - INFO - Test metrics: {'test_loss': 1.054443597793579, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.5555555555555556, 'test_recall': 0.5555555555555556, 'test_f1_score': 0.5555555555555556, 'test_roc_auc': 0.3148148148148148, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.4444444444444444, 'test_runtime': 0.6539, 'test_samples_per_second': 22.938, 'test_steps_per_second': 1.529, 'test_epoch': 5.0}
2025-05-16 01:32:37,858 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:32:37,860 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:32:37,911 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:32:37,913 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:32:37,915 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:32:38,455 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5549389123916626, 'eval_accuracy': 0.8, 'eval_precision': 0.7692307692307693, 'eval_recall': 1.0, 'eval_f1_score': 0.8695652173913043, 'eval_roc_auc': 0.76, 'eval_false_positives_rate': 0.6, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.6733, 'eval_samples_per_second': 22.277, 'eval_steps_per_second': 1.485, 'epoch': 3.0, 'step': 15}
2025-05-16 01:32:38,456 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:32:38,962 - Experiment - INFO - Test metrics: {'test_loss': 0.8507499098777771, 'test_accuracy': 0.5333333333333333, 'test_precision': 0.6, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.631578947368421, 'test_roc_auc': 0.35185185185185186, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.5009, 'test_samples_per_second': 29.947, 'test_steps_per_second': 1.996, 'test_epoch': 3.0}
2025-05-16 01:32:38,982 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:32:38,984 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:32:39,039 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:32:39,040 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:32:39,041 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-25
2025-05-16 01:32:39,516 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5421847105026245, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.8, 'eval_recall': 0.8, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.7400000000000001, 'eval_false_positives_rate': 0.4, 'eval_false_negatives_rate': 0.2, 'eval_runtime': 0.7117, 'eval_samples_per_second': 21.075, 'eval_steps_per_second': 1.405, 'epoch': 5.0, 'step': 25}
2025-05-16 01:32:39,517 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:32:40,225 - Experiment - INFO - Test metrics: {'test_loss': 1.054443597793579, 'test_accuracy': 0.4666666666666667, 'test_precision': 0.5555555555555556, 'test_recall': 0.5555555555555556, 'test_f1_score': 0.5555555555555556, 'test_roc_auc': 0.3148148148148148, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.4444444444444444, 'test_runtime': 0.7042, 'test_samples_per_second': 21.299, 'test_steps_per_second': 1.42, 'test_epoch': 5.0}
2025-05-16 01:32:40,243 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:32:40,245 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:32:40,286 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:32:40,288 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 4

2025-05-16 01:32:40,860 - Experiment - INFO - MLflow experiment initialized with ID: 455212717504321152
2025-05-16 01:32:40,860 - Experiment - INFO - Model signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 01:32:40,861 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 01:32:40,861 - Experiment - INFO - Run signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 01:32:41,422 - Experiment - INFO - Run ID: 0ce01868c5ff481e8efd0c2600784726
2025-05-16 01:32:41,422 - Experiment - INFO - Run name: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)]);2025-05-16_01-32-41;rs=1977938443
2025-05-16 01:32:41,438 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:32:41,463 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:32:41,637 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000232B0E9BE90>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000232B0E9A120>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT1_Encoder object at 0x00000232B0E9A060>]>
2025-05-16 01:32:41,911 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:32:41,912 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:32:41,913 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:32:41,935 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:32:41,938 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:32:41,959 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:32:41,961 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:32:41,976 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:32:41,978 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:32:41,979 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:32:42,104 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:32:42,106 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:32:42,196 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:32:42,198 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:32:42,688 - Experiment - INFO - Preprocessing function 2: gpt1__encoder
2025-05-16 01:32:42,690 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:32:42,691 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:32:43,603 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:32:43,604 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:32:44,002 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:32:44,004 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:32:44,735 - Experiment - INFO - Model name: GPT1
2025-05-16 01:32:44,739 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of OpenAIGPTForSequenceClassification were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:34:25,609 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:34:25,611 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:34:26,059 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7390815019607544, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.75, 'eval_recall': 0.9, 'eval_f1_score': 0.8181818181818182, 'eval_roc_auc': 0.64, 'eval_false_positives_rate': 0.6, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.8726, 'eval_samples_per_second': 17.191, 'eval_steps_per_second': 1.146, 'epoch': 3.0, 'step': 15}
2025-05-16 01:34:26,059 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:34:27,039 - Experiment - INFO - Test metrics: {'test_loss': 0.5983543992042542, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.6923076923076923, 'test_recall': 0.9, 'test_f1_score': 0.782608695652174, 'test_roc_auc': 0.72, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.9776, 'test_samples_per_second': 15.343, 'test_steps_per_second': 1.023, 'test_epoch': 3.0}
2025-05-16 01:34:27,057 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:34:27,060 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:34:27,100 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:34:27,101 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:34:27,101 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:34:27,561 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7390815019607544, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.75, 'eval_recall': 0.9, 'eval_f1_score': 0.8181818181818182, 'eval_roc_auc': 0.64, 'eval_false_positives_rate': 0.6, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.8726, 'eval_samples_per_second': 17.191, 'eval_steps_per_second': 1.146, 'epoch': 3.0, 'step': 15}
2025-05-16 01:34:27,561 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:34:28,168 - Experiment - INFO - Test metrics: {'test_loss': 0.5983543992042542, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.6923076923076923, 'test_recall': 0.9, 'test_f1_score': 0.782608695652174, 'test_roc_auc': 0.72, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.601, 'test_samples_per_second': 24.959, 'test_steps_per_second': 1.664, 'test_epoch': 3.0}
2025-05-16 01:34:28,184 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:34:28,186 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:34:28,228 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:34:28,229 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:34:28,230 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:34:28,675 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7390815019607544, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.75, 'eval_recall': 0.9, 'eval_f1_score': 0.8181818181818182, 'eval_roc_auc': 0.64, 'eval_false_positives_rate': 0.6, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.8726, 'eval_samples_per_second': 17.191, 'eval_steps_per_second': 1.146, 'epoch': 3.0, 'step': 15}
2025-05-16 01:34:28,675 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:34:29,566 - Experiment - INFO - Test metrics: {'test_loss': 0.5983543992042542, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.6923076923076923, 'test_recall': 0.9, 'test_f1_score': 0.782608695652174, 'test_roc_auc': 0.72, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.8847, 'test_samples_per_second': 16.954, 'test_steps_per_second': 1.13, 'test_epoch': 3.0}
2025-05-16 01:34:29,586 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:34:29,589 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:34:29,633 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:34:29,633 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:34:29,634 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 01:34:30,083 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7390815019607544, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.75, 'eval_recall': 0.9, 'eval_f1_score': 0.8181818181818182, 'eval_roc_auc': 0.64, 'eval_false_positives_rate': 0.6, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.8726, 'eval_samples_per_second': 17.191, 'eval_steps_per_second': 1.146, 'epoch': 3.0, 'step': 15}
2025-05-16 01:34:30,084 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:34:30,648 - Experiment - INFO - Test metrics: {'test_loss': 0.5983543992042542, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.6923076923076923, 'test_recall': 0.9, 'test_f1_score': 0.782608695652174, 'test_roc_auc': 0.72, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.559, 'test_samples_per_second': 26.834, 'test_steps_per_second': 1.789, 'test_epoch': 3.0}
2025-05-16 01:34:30,669 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:34:30,671 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:34:30,721 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:34:30,723 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:34:30,724 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:34:31,340 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6569555997848511, 'eval_accuracy': 0.6666666666666666, 'eval_precision': 0.6923076923076923, 'eval_recall': 0.9, 'eval_f1_score': 0.782608695652174, 'eval_roc_auc': 0.5599999999999999, 'eval_false_positives_rate': 0.8, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.39, 'eval_samples_per_second': 38.464, 'eval_steps_per_second': 2.564, 'epoch': 2.0, 'step': 10}
2025-05-16 01:34:31,341 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:34:32,110 - Experiment - INFO - Test metrics: {'test_loss': 0.6048048734664917, 'test_accuracy': 0.6, 'test_precision': 0.6428571428571429, 'test_recall': 0.9, 'test_f1_score': 0.75, 'test_roc_auc': 0.66, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.7651, 'test_samples_per_second': 19.605, 'test_steps_per_second': 1.307, 'test_epoch': 2.0}
2025-05-16 01:34:32,128 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:34:32,131 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:34:32,172 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:34:32,173 - Experiment - INFO - Finished model evaluations stage.

### Run 3 of 4

2025-05-16 01:34:32,721 - Experiment - INFO - MLflow experiment initialized with ID: 455212717504321152
2025-05-16 01:34:32,723 - Experiment - INFO - Model signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 01:34:32,724 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 01:34:32,725 - Experiment - INFO - Run signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 01:34:33,490 - Experiment - INFO - Run ID: e1b34dd532f04ec38a9a2ae1bd2eea92
2025-05-16 01:34:33,490 - Experiment - INFO - Run name: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)]);2025-05-16_01-34-33;rs=986685015
2025-05-16 01:34:33,504 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:34:33,542 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:34:33,714 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000232B0E9B890>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000232B0E9A150>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x00000232B0E9BAD0>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x00000232B0E9BAA0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT1_Encoder object at 0x00000232B0E9BD40>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:34:34,027 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:34:34,028 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:34:34,029 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,042 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:34:34,043 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,053 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:34:34,054 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,063 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:34:34,064 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:34:34,065 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,121 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:34:34,122 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,155 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:34:34,156 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:34:34,178 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:34:34,179 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:34:34,180 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,375 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:34:34,376 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,445 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:34:34,446 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,489 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 01:34:34,490 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:34:34,490 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,647 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:34:34,648 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:34,678 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:34:34,679 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:34:35,003 - Experiment - INFO - Preprocessing function 4: gpt1__encoder
2025-05-16 01:34:35,005 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:34:35,006 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:34:35,785 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:34:35,786 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:34:36,109 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:34:36,110 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:34:36,929 - Experiment - INFO - Model name: GPT1
2025-05-16 01:34:36,932 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of OpenAIGPTForSequenceClassification were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:37:26,206 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:37:26,207 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:37:26,708 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7941224575042725, 'eval_accuracy': 0.6, 'eval_precision': 0.6, 'eval_recall': 1.0, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.5740740740740741, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.5461, 'eval_samples_per_second': 9.702, 'eval_steps_per_second': 0.647, 'epoch': 2.0, 'step': 10}
2025-05-16 01:37:26,709 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:37:29,681 - Experiment - INFO - Test metrics: {'test_loss': 0.6164006590843201, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.64, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.9644, 'test_samples_per_second': 5.06, 'test_steps_per_second': 0.337, 'test_epoch': 2.0}
2025-05-16 01:37:29,702 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:37:29,705 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:37:29,771 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:37:29,773 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:37:29,774 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:37:30,458 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7941224575042725, 'eval_accuracy': 0.6, 'eval_precision': 0.6, 'eval_recall': 1.0, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.5740740740740741, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.5461, 'eval_samples_per_second': 9.702, 'eval_steps_per_second': 0.647, 'epoch': 2.0, 'step': 10}
2025-05-16 01:37:30,459 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:37:31,520 - Experiment - INFO - Test metrics: {'test_loss': 0.6164006590843201, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.64, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.0562, 'test_samples_per_second': 14.202, 'test_steps_per_second': 0.947, 'test_epoch': 2.0}
2025-05-16 01:37:31,544 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:37:31,547 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:37:31,605 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:37:31,607 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:37:31,608 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:37:32,294 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7941224575042725, 'eval_accuracy': 0.6, 'eval_precision': 0.6, 'eval_recall': 1.0, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.5740740740740741, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.5461, 'eval_samples_per_second': 9.702, 'eval_steps_per_second': 0.647, 'epoch': 2.0, 'step': 10}
2025-05-16 01:37:32,295 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:37:35,076 - Experiment - INFO - Test metrics: {'test_loss': 0.6164006590843201, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.64, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.7742, 'test_samples_per_second': 5.407, 'test_steps_per_second': 0.36, 'test_epoch': 2.0}
2025-05-16 01:37:35,092 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:37:35,094 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:37:35,146 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:37:35,148 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:37:35,149 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:37:35,655 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 1.073309063911438, 'eval_accuracy': 0.6, 'eval_precision': 0.6, 'eval_recall': 1.0, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.7037037037037037, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.5494, 'eval_samples_per_second': 9.681, 'eval_steps_per_second': 0.645, 'epoch': 4.0, 'step': 20}
2025-05-16 01:37:35,656 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:37:36,561 - Experiment - INFO - Test metrics: {'test_loss': 0.751035749912262, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.64, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.9001, 'test_samples_per_second': 16.665, 'test_steps_per_second': 1.111, 'test_epoch': 4.0}
2025-05-16 01:37:36,581 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:37:36,582 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:37:36,629 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:37:36,631 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:37:36,633 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:37:37,337 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7941224575042725, 'eval_accuracy': 0.6, 'eval_precision': 0.6, 'eval_recall': 1.0, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.5740740740740741, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 1.5461, 'eval_samples_per_second': 9.702, 'eval_steps_per_second': 0.647, 'epoch': 2.0, 'step': 10}
2025-05-16 01:37:37,338 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:37:40,082 - Experiment - INFO - Test metrics: {'test_loss': 0.6164006590843201, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7142857142857143, 'test_recall': 1.0, 'test_f1_score': 0.8333333333333334, 'test_roc_auc': 0.64, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.0, 'test_runtime': 2.7372, 'test_samples_per_second': 5.48, 'test_steps_per_second': 0.365, 'test_epoch': 2.0}
2025-05-16 01:37:40,110 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:37:40,113 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:37:40,189 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:37:40,190 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 01:37:40,384 - Experiment - INFO - MLflow experiment initialized with ID: 455212717504321152
2025-05-16 01:37:40,385 - Experiment - INFO - Model signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 01:37:40,387 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 01:37:40,387 - Experiment - INFO - Run signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 01:37:41,909 - Experiment - INFO - Run ID: 440bfa2c645f4a088791f687e978056c
2025-05-16 01:37:41,911 - Experiment - INFO - Run name: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)]);2025-05-16_01-37-41;rs=2001508348
2025-05-16 01:37:41,931 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:37:42,055 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:37:42,298 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x00000232B0E9A1B0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x00000232B0E9B770>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x00000232B0E9BCB0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x00000232B0E9B8C0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT1_Encoder object at 0x00000232B0E9BE30>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:37:42,604 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:37:42,606 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:37:42,607 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:42,628 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:37:42,630 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:42,648 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:37:42,650 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:42,667 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:37:42,669 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:37:42,670 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:42,787 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:37:42,789 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:42,816 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:37:42,817 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:37:42,851 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:37:42,852 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:37:42,853 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:43,106 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:37:43,107 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:43,153 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:37:43,154 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:43,227 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 01:37:43,227 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:37:43,229 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:43,886 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:37:43,889 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:44,007 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:37:44,009 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:37:44,534 - Experiment - INFO - Preprocessing function 4: gpt1__encoder
2025-05-16 01:37:44,536 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:37:44,537 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:37:45,464 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:37:45,466 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:37:45,704 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:37:45,705 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:37:46,673 - Experiment - INFO - Model name: GPT1
2025-05-16 01:37:46,677 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of OpenAIGPTForSequenceClassification were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:40:57,182 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:40:57,183 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:40:57,717 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.46003302931785583, 'eval_accuracy': 0.8, 'eval_precision': 0.8, 'eval_recall': 0.8888888888888888, 'eval_f1_score': 0.8421052631578947, 'eval_roc_auc': 0.8518518518518519, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 0.1111111111111111, 'eval_runtime': 0.4638, 'eval_samples_per_second': 32.343, 'eval_steps_per_second': 2.156, 'epoch': 4.0, 'step': 20}
2025-05-16 01:40:57,718 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:40:58,669 - Experiment - INFO - Test metrics: {'test_loss': 0.5568803548812866, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7, 'test_recall': 0.875, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.7142857142857143, 'test_false_positives_rate': 0.42857142857142855, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.9464, 'test_samples_per_second': 15.849, 'test_steps_per_second': 1.057, 'test_epoch': 4.0}
2025-05-16 01:40:58,689 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:40:58,691 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:40:58,742 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:40:58,743 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:40:58,744 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 01:40:59,231 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5549112558364868, 'eval_accuracy': 0.8, 'eval_precision': 0.75, 'eval_recall': 1.0, 'eval_f1_score': 0.8571428571428571, 'eval_roc_auc': 0.8148148148148149, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.4846, 'eval_samples_per_second': 30.951, 'eval_steps_per_second': 2.063, 'epoch': 2.0, 'step': 10}
2025-05-16 01:40:59,232 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:40:59,727 - Experiment - INFO - Test metrics: {'test_loss': 0.5691461563110352, 'test_accuracy': 0.6666666666666666, 'test_precision': 0.6153846153846154, 'test_recall': 1.0, 'test_f1_score': 0.7619047619047619, 'test_roc_auc': 0.8035714285714286, 'test_false_positives_rate': 0.7142857142857143, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.4904, 'test_samples_per_second': 30.586, 'test_steps_per_second': 2.039, 'test_epoch': 2.0}
2025-05-16 01:40:59,744 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:40:59,746 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:40:59,790 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:40:59,791 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:40:59,791 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:41:00,275 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.46003302931785583, 'eval_accuracy': 0.8, 'eval_precision': 0.8, 'eval_recall': 0.8888888888888888, 'eval_f1_score': 0.8421052631578947, 'eval_roc_auc': 0.8518518518518519, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 0.1111111111111111, 'eval_runtime': 0.4638, 'eval_samples_per_second': 32.343, 'eval_steps_per_second': 2.156, 'epoch': 4.0, 'step': 20}
2025-05-16 01:41:00,276 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:41:01,075 - Experiment - INFO - Test metrics: {'test_loss': 0.5568803548812866, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7, 'test_recall': 0.875, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.7142857142857143, 'test_false_positives_rate': 0.42857142857142855, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.7945, 'test_samples_per_second': 18.879, 'test_steps_per_second': 1.259, 'test_epoch': 4.0}
2025-05-16 01:41:01,093 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:41:01,095 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:41:01,142 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:41:01,144 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:41:01,145 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:41:01,660 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.46003302931785583, 'eval_accuracy': 0.8, 'eval_precision': 0.8, 'eval_recall': 0.8888888888888888, 'eval_f1_score': 0.8421052631578947, 'eval_roc_auc': 0.8518518518518519, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 0.1111111111111111, 'eval_runtime': 0.4638, 'eval_samples_per_second': 32.343, 'eval_steps_per_second': 2.156, 'epoch': 4.0, 'step': 20}
2025-05-16 01:41:01,661 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:41:02,273 - Experiment - INFO - Test metrics: {'test_loss': 0.5568803548812866, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7, 'test_recall': 0.875, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.7142857142857143, 'test_false_positives_rate': 0.42857142857142855, 'test_false_negatives_rate': 0.125, 'test_runtime': 0.6074, 'test_samples_per_second': 24.695, 'test_steps_per_second': 1.646, 'test_epoch': 4.0}
2025-05-16 01:41:02,296 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:41:02,298 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:41:02,356 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:41:02,357 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:41:02,358 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 01:41:02,848 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.46003302931785583, 'eval_accuracy': 0.8, 'eval_precision': 0.8, 'eval_recall': 0.8888888888888888, 'eval_f1_score': 0.8421052631578947, 'eval_roc_auc': 0.8518518518518519, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 0.1111111111111111, 'eval_runtime': 0.4638, 'eval_samples_per_second': 32.343, 'eval_steps_per_second': 2.156, 'epoch': 4.0, 'step': 20}
2025-05-16 01:41:02,849 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:41:04,167 - Experiment - INFO - Test metrics: {'test_loss': 0.5568803548812866, 'test_accuracy': 0.7333333333333333, 'test_precision': 0.7, 'test_recall': 0.875, 'test_f1_score': 0.7777777777777778, 'test_roc_auc': 0.7142857142857143, 'test_false_positives_rate': 0.42857142857142855, 'test_false_negatives_rate': 0.125, 'test_runtime': 1.3105, 'test_samples_per_second': 11.446, 'test_steps_per_second': 0.763, 'test_epoch': 4.0}
2025-05-16 01:41:04,195 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:41:04,197 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:41:04,255 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:41:04,256 - Experiment - INFO - Finished model evaluations stage.

### EUvsDisinfo Dataset

In [ ]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_gpt_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid)

### ISOT Dataset

In [ ]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_gpt_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid)

### CZ Dataset

In [13]:
cz_pipelines = []

for max_tokens in max_tokens_params:
    cz_pipelines.extend([PreprocessingPipeline(name='minimal',
                                               iterable=[Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction',
                                               iterable=[NoiseReduction(),
                                                         Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Lemmatization(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_stemming',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Stemming(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)])
                         ])
# optional - for testing purposes, if you want to run fast test on very small datasets
# truncate(cz_pipelines, fraction=0.15)

cz_dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': cz_pipelines})
print('Dataset Hyperparameters Grid Size: ', len(cz_dataset_hparams_grid))
print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(cz_dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

In [14]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_gpt_model_experiments(dataset_name,
                              dataset_path,
                              cz_dataset_hparams_grid,
                              model_hparams_grid)

### Run 1 of 4

2025-05-16 01:41:04,957 - Experiment - INFO - MLflow experiment initialized with ID: 455212717504321152
2025-05-16 01:41:04,961 - Experiment - INFO - Model signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 01:41:04,963 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 01:41:04,964 - Experiment - INFO - Run signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 01:41:06,012 - Experiment - INFO - Run ID: 417f52cf0974427b9c87e6dbe4103ad8
2025-05-16 01:41:06,014 - Experiment - INFO - Run name: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)]);2025-05-16_01-41-05;rs=2858750860
2025-05-16 01:41:06,035 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:41:06,065 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:41:06,218 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000023311DC5820>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT1_Encoder object at 0x00000232AEE0D8E0>]>
2025-05-16 01:41:06,533 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:41:06,534 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:41:06,535 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:41:06,552 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:41:06,555 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:41:06,566 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:41:06,567 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:41:06,914 - Experiment - INFO - Preprocessing function 1: gpt1__encoder
2025-05-16 01:41:06,914 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:41:06,915 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:41:07,473 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:41:07,474 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:41:07,765 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:41:07,768 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:41:08,572 - Experiment - INFO - Model name: GPT1
2025-05-16 01:41:08,580 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of OpenAIGPTForSequenceClassification were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:43:13,285 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:43:13,286 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 01:43:13,787 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7605804204940796, 'eval_accuracy': 0.6818181818181818, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.6956521739130435, 'eval_roc_auc': 0.5454545454545454, 'eval_false_positives_rate': 0.36363636363636365, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.6807, 'eval_samples_per_second': 32.319, 'eval_steps_per_second': 2.938, 'epoch': 2.0, 'step': 14}
2025-05-16 01:43:13,788 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:43:14,124 - Experiment - INFO - Test metrics: {'test_loss': 0.7057594656944275, 'test_accuracy': 0.36363636363636365, 'test_precision': 0.5, 'test_recall': 0.2857142857142857, 'test_f1_score': 0.36363636363636365, 'test_roc_auc': 0.45535714285714285, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.7142857142857143, 'test_runtime': 0.3332, 'test_samples_per_second': 66.018, 'test_steps_per_second': 6.002, 'test_epoch': 2.0}
2025-05-16 01:43:14,146 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:43:14,148 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:43:14,206 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:43:14,207 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:43:14,208 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 01:43:14,696 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7605804204940796, 'eval_accuracy': 0.6818181818181818, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.6956521739130435, 'eval_roc_auc': 0.5454545454545454, 'eval_false_positives_rate': 0.36363636363636365, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.6807, 'eval_samples_per_second': 32.319, 'eval_steps_per_second': 2.938, 'epoch': 2.0, 'step': 14}
2025-05-16 01:43:14,697 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:43:15,143 - Experiment - INFO - Test metrics: {'test_loss': 0.7057594656944275, 'test_accuracy': 0.36363636363636365, 'test_precision': 0.5, 'test_recall': 0.2857142857142857, 'test_f1_score': 0.36363636363636365, 'test_roc_auc': 0.45535714285714285, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.7142857142857143, 'test_runtime': 0.44, 'test_samples_per_second': 50.0, 'test_steps_per_second': 4.545, 'test_epoch': 2.0}
2025-05-16 01:43:15,163 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:43:15,165 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:43:15,227 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:43:15,229 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:43:15,229 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 01:43:15,709 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7605804204940796, 'eval_accuracy': 0.6818181818181818, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.6956521739130435, 'eval_roc_auc': 0.5454545454545454, 'eval_false_positives_rate': 0.36363636363636365, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.6807, 'eval_samples_per_second': 32.319, 'eval_steps_per_second': 2.938, 'epoch': 2.0, 'step': 14}
2025-05-16 01:43:15,710 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:43:16,022 - Experiment - INFO - Test metrics: {'test_loss': 0.7057594656944275, 'test_accuracy': 0.36363636363636365, 'test_precision': 0.5, 'test_recall': 0.2857142857142857, 'test_f1_score': 0.36363636363636365, 'test_roc_auc': 0.45535714285714285, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.7142857142857143, 'test_runtime': 0.3083, 'test_samples_per_second': 71.362, 'test_steps_per_second': 6.487, 'test_epoch': 2.0}
2025-05-16 01:43:16,043 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:43:16,045 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:43:16,107 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:43:16,108 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:43:16,109 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 01:43:16,595 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7605804204940796, 'eval_accuracy': 0.6818181818181818, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.6956521739130435, 'eval_roc_auc': 0.5454545454545454, 'eval_false_positives_rate': 0.36363636363636365, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.6807, 'eval_samples_per_second': 32.319, 'eval_steps_per_second': 2.938, 'epoch': 2.0, 'step': 14}
2025-05-16 01:43:16,596 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:43:17,047 - Experiment - INFO - Test metrics: {'test_loss': 0.7057594656944275, 'test_accuracy': 0.36363636363636365, 'test_precision': 0.5, 'test_recall': 0.2857142857142857, 'test_f1_score': 0.36363636363636365, 'test_roc_auc': 0.45535714285714285, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.7142857142857143, 'test_runtime': 0.4467, 'test_samples_per_second': 49.254, 'test_steps_per_second': 4.478, 'test_epoch': 2.0}
2025-05-16 01:43:17,066 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:43:17,069 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:43:17,132 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:43:17,133 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:43:17,134 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 01:43:17,647 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7605804204940796, 'eval_accuracy': 0.6818181818181818, 'eval_precision': 0.6666666666666666, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.6956521739130435, 'eval_roc_auc': 0.5454545454545454, 'eval_false_positives_rate': 0.36363636363636365, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.6807, 'eval_samples_per_second': 32.319, 'eval_steps_per_second': 2.938, 'epoch': 2.0, 'step': 14}
2025-05-16 01:43:17,648 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:43:17,972 - Experiment - INFO - Test metrics: {'test_loss': 0.7057594656944275, 'test_accuracy': 0.36363636363636365, 'test_precision': 0.5, 'test_recall': 0.2857142857142857, 'test_f1_score': 0.36363636363636365, 'test_roc_auc': 0.45535714285714285, 'test_false_positives_rate': 0.5, 'test_false_negatives_rate': 0.7142857142857143, 'test_runtime': 0.3182, 'test_samples_per_second': 69.129, 'test_steps_per_second': 6.284, 'test_epoch': 2.0}
2025-05-16 01:43:17,994 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:43:17,997 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:43:18,061 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:43:18,062 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 4

2025-05-16 01:43:18,310 - Experiment - INFO - MLflow experiment initialized with ID: 455212717504321152
2025-05-16 01:43:18,311 - Experiment - INFO - Model signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 01:43:18,312 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 01:43:18,313 - Experiment - INFO - Run signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 01:43:19,214 - Experiment - INFO - Run ID: 431be65f776c44b8a95f86922cc1f20b
2025-05-16 01:43:19,215 - Experiment - INFO - Run name: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=false,pt=none)]);2025-05-16_01-43-19;rs=2064007360
2025-05-16 01:43:19,225 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:43:19,251 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:43:19,370 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000002342C6D4C80>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000023311DC74D0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT1_Encoder object at 0x0000023311DC4CB0>]>
2025-05-16 01:43:19,662 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:43:19,663 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:43:19,664 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:43:19,684 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:43:19,686 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:43:19,699 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:43:19,700 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:43:19,711 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:43:19,712 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:43:19,713 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:43:19,796 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:43:19,797 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:43:19,817 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:43:19,818 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:43:20,156 - Experiment - INFO - Preprocessing function 2: gpt1__encoder
2025-05-16 01:43:20,157 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:43:20,158 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:43:20,740 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:43:20,741 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:43:20,913 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:43:20,914 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:43:21,496 - Experiment - INFO - Model name: GPT1
2025-05-16 01:43:21,500 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of OpenAIGPTForSequenceClassification were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:45:04,511 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:45:04,512 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 01:45:05,121 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6953856945037842, 'eval_accuracy': 0.5909090909090909, 'eval_precision': 0.9090909090909091, 'eval_recall': 0.5555555555555556, 'eval_f1_score': 0.6896551724137931, 'eval_roc_auc': 0.5694444444444445, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.4444444444444444, 'eval_runtime': 0.7209, 'eval_samples_per_second': 30.515, 'eval_steps_per_second': 2.774, 'epoch': 1.0, 'step': 7}
2025-05-16 01:45:05,123 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 01:45:05,585 - Experiment - INFO - Test metrics: {'test_loss': 0.7038134336471558, 'test_accuracy': 0.45454545454545453, 'test_precision': 0.5, 'test_recall': 0.5833333333333334, 'test_f1_score': 0.5384615384615384, 'test_roc_auc': 0.41666666666666663, 'test_false_positives_rate': 0.7, 'test_false_negatives_rate': 0.4166666666666667, 'test_runtime': 0.4554, 'test_samples_per_second': 48.306, 'test_steps_per_second': 4.391, 'test_epoch': 1.0}
2025-05-16 01:45:05,604 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:45:05,607 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:45:05,681 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:45:05,682 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:45:05,683 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 01:45:06,154 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6229334473609924, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.8947368421052632, 'eval_recall': 0.9444444444444444, 'eval_f1_score': 0.918918918918919, 'eval_roc_auc': 0.8472222222222222, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.05555555555555555, 'eval_runtime': 0.5906, 'eval_samples_per_second': 37.251, 'eval_steps_per_second': 3.386, 'epoch': 5.0, 'step': 35}
2025-05-16 01:45:06,155 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:45:06,658 - Experiment - INFO - Test metrics: {'test_loss': 1.849001407623291, 'test_accuracy': 0.5909090909090909, 'test_precision': 0.5789473684210527, 'test_recall': 0.9166666666666666, 'test_f1_score': 0.7096774193548387, 'test_roc_auc': 0.5416666666666666, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.08333333333333333, 'test_runtime': 0.4968, 'test_samples_per_second': 44.28, 'test_steps_per_second': 4.025, 'test_epoch': 5.0}
2025-05-16 01:45:06,685 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:45:06,687 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:45:06,763 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:45:06,764 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:45:06,765 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 01:45:07,389 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6953856945037842, 'eval_accuracy': 0.5909090909090909, 'eval_precision': 0.9090909090909091, 'eval_recall': 0.5555555555555556, 'eval_f1_score': 0.6896551724137931, 'eval_roc_auc': 0.5694444444444445, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.4444444444444444, 'eval_runtime': 0.7209, 'eval_samples_per_second': 30.515, 'eval_steps_per_second': 2.774, 'epoch': 1.0, 'step': 7}
2025-05-16 01:45:07,391 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 01:45:07,761 - Experiment - INFO - Test metrics: {'test_loss': 0.7038134336471558, 'test_accuracy': 0.45454545454545453, 'test_precision': 0.5, 'test_recall': 0.5833333333333334, 'test_f1_score': 0.5384615384615384, 'test_roc_auc': 0.41666666666666663, 'test_false_positives_rate': 0.7, 'test_false_negatives_rate': 0.4166666666666667, 'test_runtime': 0.3616, 'test_samples_per_second': 60.832, 'test_steps_per_second': 5.53, 'test_epoch': 1.0}
2025-05-16 01:45:07,782 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:45:07,785 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:45:07,863 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:45:07,864 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:45:07,866 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 01:45:08,387 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6229334473609924, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.8947368421052632, 'eval_recall': 0.9444444444444444, 'eval_f1_score': 0.918918918918919, 'eval_roc_auc': 0.8472222222222222, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.05555555555555555, 'eval_runtime': 0.5906, 'eval_samples_per_second': 37.251, 'eval_steps_per_second': 3.386, 'epoch': 5.0, 'step': 35}
2025-05-16 01:45:08,388 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:45:08,898 - Experiment - INFO - Test metrics: {'test_loss': 1.849001407623291, 'test_accuracy': 0.5909090909090909, 'test_precision': 0.5789473684210527, 'test_recall': 0.9166666666666666, 'test_f1_score': 0.7096774193548387, 'test_roc_auc': 0.5416666666666666, 'test_false_positives_rate': 0.8, 'test_false_negatives_rate': 0.08333333333333333, 'test_runtime': 0.504, 'test_samples_per_second': 43.647, 'test_steps_per_second': 3.968, 'test_epoch': 5.0}
2025-05-16 01:45:08,923 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:45:08,926 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:45:08,994 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:45:08,995 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:45:08,997 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 01:45:09,560 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4542187452316284, 'eval_accuracy': 0.8181818181818182, 'eval_precision': 0.8181818181818182, 'eval_recall': 1.0, 'eval_f1_score': 0.9, 'eval_roc_auc': 0.6666666666666667, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.8072, 'eval_samples_per_second': 27.253, 'eval_steps_per_second': 2.478, 'epoch': 2.0, 'step': 14}
2025-05-16 01:45:09,561 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:45:09,922 - Experiment - INFO - Test metrics: {'test_loss': 0.9187113046646118, 'test_accuracy': 0.5454545454545454, 'test_precision': 0.5454545454545454, 'test_recall': 1.0, 'test_f1_score': 0.7058823529411765, 'test_roc_auc': 0.35, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.3562, 'test_samples_per_second': 61.757, 'test_steps_per_second': 5.614, 'test_epoch': 2.0}
2025-05-16 01:45:09,941 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:45:09,943 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:45:10,006 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:45:10,007 - Experiment - INFO - Finished model evaluations stage.

### Run 3 of 4

2025-05-16 01:45:10,580 - Experiment - INFO - MLflow experiment initialized with ID: 455212717504321152
2025-05-16 01:45:10,581 - Experiment - INFO - Model signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 01:45:10,582 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 01:45:10,583 - Experiment - INFO - Run signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 01:45:11,512 - Experiment - INFO - Run ID: 6e72893b3cde4be3aabac007d92cfd92
2025-05-16 01:45:11,513 - Experiment - INFO - Run name: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)]);2025-05-16_01-45-11;rs=3754363327
2025-05-16 01:45:11,526 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:45:11,573 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:45:11,708 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000002342C6D7EF0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000023311DC79B0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000023311DC4770>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000023311DC4B60>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT1_Encoder object at 0x0000023311DC7590>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:45:12,003 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:45:12,005 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:45:12,006 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,038 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:45:12,040 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,054 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:45:12,056 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,070 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:45:12,071 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:45:12,072 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,165 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:45:12,166 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,187 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:45:12,188 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:45:12,213 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:45:12,214 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:45:12,216 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,524 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:45:12,525 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,564 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:45:12,565 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,617 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 01:45:12,618 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:45:12,619 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,957 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:45:12,959 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:12,987 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:45:12,989 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:45:13,302 - Experiment - INFO - Preprocessing function 4: gpt1__encoder
2025-05-16 01:45:13,303 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:45:13,304 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:45:14,510 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:45:14,510 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:45:14,800 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:45:14,802 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:45:15,598 - Experiment - INFO - Model name: GPT1
2025-05-16 01:45:15,604 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of OpenAIGPTForSequenceClassification were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:46:40,964 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:46:40,966 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 01:46:41,578 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9783410429954529, 'eval_accuracy': 0.4090909090909091, 'eval_precision': 0.875, 'eval_recall': 0.3684210526315789, 'eval_f1_score': 0.5185185185185185, 'eval_roc_auc': 0.38596491228070173, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 0.631578947368421, 'eval_runtime': 0.4481, 'eval_samples_per_second': 49.095, 'eval_steps_per_second': 4.463, 'epoch': 1.0, 'step': 7}
2025-05-16 01:46:41,579 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 01:46:41,860 - Experiment - INFO - Test metrics: {'test_loss': 0.9223088622093201, 'test_accuracy': 0.4090909090909091, 'test_precision': 0.5, 'test_recall': 0.3076923076923077, 'test_f1_score': 0.38095238095238093, 'test_roc_auc': 0.4273504273504274, 'test_false_positives_rate': 0.4444444444444444, 'test_false_negatives_rate': 0.6923076923076923, 'test_runtime': 0.2751, 'test_samples_per_second': 79.975, 'test_steps_per_second': 7.27, 'test_epoch': 1.0}
2025-05-16 01:46:41,883 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:46:41,885 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:46:41,954 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:46:41,955 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:46:41,956 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-21
2025-05-16 01:46:42,541 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7834665775299072, 'eval_accuracy': 0.6363636363636364, 'eval_precision': 0.8235294117647058, 'eval_recall': 0.7368421052631579, 'eval_f1_score': 0.7777777777777778, 'eval_roc_auc': 0.2456140350877193, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.2631578947368421, 'eval_runtime': 0.3827, 'eval_samples_per_second': 57.488, 'eval_steps_per_second': 5.226, 'epoch': 3.0, 'step': 21}
2025-05-16 01:46:42,542 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 01:46:42,907 - Experiment - INFO - Test metrics: {'test_loss': 0.9145483374595642, 'test_accuracy': 0.45454545454545453, 'test_precision': 0.5384615384615384, 'test_recall': 0.5384615384615384, 'test_f1_score': 0.5384615384615384, 'test_roc_auc': 0.452991452991453, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.46153846153846156, 'test_runtime': 0.3593, 'test_samples_per_second': 61.237, 'test_steps_per_second': 5.567, 'test_epoch': 3.0}
2025-05-16 01:46:42,929 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:46:42,932 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:46:42,995 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:46:42,996 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:46:42,998 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 01:46:43,559 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9783410429954529, 'eval_accuracy': 0.4090909090909091, 'eval_precision': 0.875, 'eval_recall': 0.3684210526315789, 'eval_f1_score': 0.5185185185185185, 'eval_roc_auc': 0.38596491228070173, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 0.631578947368421, 'eval_runtime': 0.4481, 'eval_samples_per_second': 49.095, 'eval_steps_per_second': 4.463, 'epoch': 1.0, 'step': 7}
2025-05-16 01:46:43,560 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 01:46:43,783 - Experiment - INFO - Test metrics: {'test_loss': 0.9223088622093201, 'test_accuracy': 0.4090909090909091, 'test_precision': 0.5, 'test_recall': 0.3076923076923077, 'test_f1_score': 0.38095238095238093, 'test_roc_auc': 0.4273504273504274, 'test_false_positives_rate': 0.4444444444444444, 'test_false_negatives_rate': 0.6923076923076923, 'test_runtime': 0.2146, 'test_samples_per_second': 102.532, 'test_steps_per_second': 9.321, 'test_epoch': 1.0}
2025-05-16 01:46:43,812 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:46:43,816 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:46:43,888 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:46:43,889 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:46:43,890 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 01:46:44,406 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9891147017478943, 'eval_accuracy': 0.5454545454545454, 'eval_precision': 0.8461538461538461, 'eval_recall': 0.5789473684210527, 'eval_f1_score': 0.6875, 'eval_roc_auc': 0.5263157894736843, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.42105263157894735, 'eval_runtime': 0.4506, 'eval_samples_per_second': 48.823, 'eval_steps_per_second': 4.438, 'epoch': 5.0, 'step': 35}
2025-05-16 01:46:44,407 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 01:46:44,773 - Experiment - INFO - Test metrics: {'test_loss': 1.9634032249450684, 'test_accuracy': 0.4090909090909091, 'test_precision': 0.5, 'test_recall': 0.5384615384615384, 'test_f1_score': 0.5185185185185185, 'test_roc_auc': 0.4017094017094017, 'test_false_positives_rate': 0.7777777777777778, 'test_false_negatives_rate': 0.46153846153846156, 'test_runtime': 0.3606, 'test_samples_per_second': 61.008, 'test_steps_per_second': 5.546, 'test_epoch': 5.0}
2025-05-16 01:46:44,794 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:46:44,797 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:46:44,871 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:46:44,872 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:46:44,873 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 01:46:45,469 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7398651242256165, 'eval_accuracy': 0.5909090909090909, 'eval_precision': 0.8125, 'eval_recall': 0.6842105263157895, 'eval_f1_score': 0.7428571428571429, 'eval_roc_auc': 0.2280701754385965, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.3157894736842105, 'eval_runtime': 0.4012, 'eval_samples_per_second': 54.831, 'eval_steps_per_second': 4.985, 'epoch': 2.0, 'step': 14}
2025-05-16 01:46:45,470 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:46:45,676 - Experiment - INFO - Test metrics: {'test_loss': 0.7790502309799194, 'test_accuracy': 0.45454545454545453, 'test_precision': 0.5384615384615384, 'test_recall': 0.5384615384615384, 'test_f1_score': 0.5384615384615384, 'test_roc_auc': 0.5213675213675214, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.46153846153846156, 'test_runtime': 0.2, 'test_samples_per_second': 110.025, 'test_steps_per_second': 10.002, 'test_epoch': 2.0}
2025-05-16 01:46:45,700 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:46:45,703 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:46:45,772 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:46:45,773 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 01:46:46,001 - Experiment - INFO - MLflow experiment initialized with ID: 455212717504321152
2025-05-16 01:46:46,003 - Experiment - INFO - Model signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 01:46:46,004 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 01:46:46,004 - Experiment - INFO - Run signature: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 01:46:47,050 - Experiment - INFO - Run ID: 43ae211d60814aaca2fd52aeaa0f52ca
2025-05-16 01:46:47,051 - Experiment - INFO - Run name: model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),gpt1__encoder(t=openai-gpt,t=true,p=max_length,tml=128,isiw=true,pt=none)]);2025-05-16_01-46-46;rs=3479272676
2025-05-16 01:46:47,068 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 01:46:47,120 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 01:46:47,250 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000002342C6D69C0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000023311DC6720>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000023311DC4E60>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000023311DC6C00>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT1_Encoder object at 0x0000023311DC6D20>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:46:47,559 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 01:46:47,561 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:46:47,563 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:46:47,595 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:46:47,597 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:46:47,616 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:46:47,618 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:46:47,635 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 01:46:47,637 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:46:47,638 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:46:47,810 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:46:47,811 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:46:47,860 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:46:47,862 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 01:46:47,912 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 01:46:47,913 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:46:47,915 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:46:48,211 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:46:48,212 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:46:48,270 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:46:48,271 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 01:46:48,337 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 01:46:48,338 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:46:48,339 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: ProuvostDecember
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: MWh
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: ECLNWHgl
warning: skipping word with mixed case: mSv
warning: skipping word with mixed case: mSv
warning: skipping word with mixed case: FEGURsVhCv
warning: skipping word with mixed case: KeepCalmAndSmile
warning: skipping word with mixed case: DrabovaDana
warning: skipping word with mixed case: KeepCalmAndSmile
warning: skipping word with mixed case: DrabovaDana
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: rvIOjIM
warning: skipping word with mixed case: ueqBIFUbyM
warning: skipping word with mixed case: ProtiproudTV
warning: skipping word with mixed case: SwedishPM
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: kOXEJFeHj
warning: skipping word with mixed case: xivAtTQk
warning: skipping word with mixed case: PhDr
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: iDnes
warning: skipping word with mixed case: CzechInvest
warning: skipping word with mixed case: CzechInvest
warning: skipping word with mixed case: ParlamentníListy
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: OpenCard
warning: skipping word with mixed case: QUAcyLckUj
warning: skipping word with mixed case: MaxxPro
warning: skipping word with mixed case: mírUkrajině
warning: skipping word with mixed case: vícTo
warning: skipping word with mixed case: líbíOkomentovatSdílet
warning: skipping word with mixed case: PhD
warning: skipping word with mixed case: TikToku
warning: skipping word with mixed case: TikToku
warning: skipping word with mixed case: TikToku
warning: skipping word with mixed case: iPhonech
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: EADaily
warning: skipping word with mixed case: iNews
warning: skipping word with mixed case: ParlamentnímListům
warning: skipping word with mixed case: McChicken
2025-05-16 01:46:48,561 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:46:48,564 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: wXaQklCz
warning: skipping word with mixed case: OSPODu
warning: skipping word with mixed case: McAlester
warning: skipping word with mixed case: mRNA
warning: skipping word with mixed case: CoV
warning: skipping word with mixed case: mRNA
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitiFor
2025-05-16 01:46:48,616 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:46:48,618 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: RuSSáci
warning: skipping word with mixed case: ZeGoebbels
warning: skipping word with mixed case: McCallister
warning: skipping word with mixed case: UguwdpjEJo
warning: skipping word with mixed case: jvbXUwDjc
warning: skipping word with mixed case: weeoOEKcP
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: DeLuca
warning: skipping word with mixed case: DeLuca
2025-05-16 01:46:48,962 - Experiment - INFO - Preprocessing function 4: gpt1__encoder
2025-05-16 01:46:48,963 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 01:46:48,964 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:46:50,085 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 01:46:50,088 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:46:50,372 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 01:46:50,374 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 01:46:51,165 - Experiment - INFO - Model name: GPT1
2025-05-16 01:46:51,169 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of OpenAIGPTForSequenceClassification were not initialized from the model checkpoint at openai-gpt and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 01:48:31,375 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 01:48:31,376 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 01:48:31,897 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6363430619239807, 'eval_accuracy': 0.5454545454545454, 'eval_precision': 0.8333333333333334, 'eval_recall': 0.35714285714285715, 'eval_f1_score': 0.5, 'eval_roc_auc': 0.8214285714285714, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.6428571428571429, 'eval_runtime': 0.4131, 'eval_samples_per_second': 53.252, 'eval_steps_per_second': 4.841, 'epoch': 1.0, 'step': 7}
2025-05-16 01:48:31,898 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 01:48:32,160 - Experiment - INFO - Test metrics: {'test_loss': 0.7086583971977234, 'test_accuracy': 0.3181818181818182, 'test_precision': 0.3333333333333333, 'test_recall': 0.15384615384615385, 'test_f1_score': 0.21052631578947367, 'test_roc_auc': 0.41880341880341887, 'test_false_positives_rate': 0.4444444444444444, 'test_false_negatives_rate': 0.8461538461538461, 'test_runtime': 0.2571, 'test_samples_per_second': 85.568, 'test_steps_per_second': 7.779, 'test_epoch': 1.0}
2025-05-16 01:48:32,188 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:48:32,192 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:48:32,260 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:48:32,261 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 01:48:32,262 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 01:48:32,768 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7082191109657288, 'eval_accuracy': 0.7727272727272727, 'eval_precision': 0.7368421052631579, 'eval_recall': 1.0, 'eval_f1_score': 0.8484848484848485, 'eval_roc_auc': 0.7678571428571429, 'eval_false_positives_rate': 0.625, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.4678, 'eval_samples_per_second': 47.032, 'eval_steps_per_second': 4.276, 'epoch': 4.0, 'step': 28}
2025-05-16 01:48:32,769 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 01:48:32,976 - Experiment - INFO - Test metrics: {'test_loss': 1.2725361585617065, 'test_accuracy': 0.6818181818181818, 'test_precision': 0.65, 'test_recall': 1.0, 'test_f1_score': 0.7878787878787878, 'test_roc_auc': 0.5042735042735043, 'test_false_positives_rate': 0.7777777777777778, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.2034, 'test_samples_per_second': 108.178, 'test_steps_per_second': 9.834, 'test_epoch': 4.0}
2025-05-16 01:48:32,992 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:48:32,994 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:48:33,058 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:48:33,059 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 01:48:33,060 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 01:48:33,637 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6363430619239807, 'eval_accuracy': 0.5454545454545454, 'eval_precision': 0.8333333333333334, 'eval_recall': 0.35714285714285715, 'eval_f1_score': 0.5, 'eval_roc_auc': 0.8214285714285714, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.6428571428571429, 'eval_runtime': 0.4131, 'eval_samples_per_second': 53.252, 'eval_steps_per_second': 4.841, 'epoch': 1.0, 'step': 7}
2025-05-16 01:48:33,637 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 01:48:33,855 - Experiment - INFO - Test metrics: {'test_loss': 0.7086583971977234, 'test_accuracy': 0.3181818181818182, 'test_precision': 0.3333333333333333, 'test_recall': 0.15384615384615385, 'test_f1_score': 0.21052631578947367, 'test_roc_auc': 0.41880341880341887, 'test_false_positives_rate': 0.4444444444444444, 'test_false_negatives_rate': 0.8461538461538461, 'test_runtime': 0.213, 'test_samples_per_second': 103.308, 'test_steps_per_second': 9.392, 'test_epoch': 1.0}
2025-05-16 01:48:33,876 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:48:33,879 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:48:33,942 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:48:33,943 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 01:48:33,944 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 01:48:34,557 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6363430619239807, 'eval_accuracy': 0.5454545454545454, 'eval_precision': 0.8333333333333334, 'eval_recall': 0.35714285714285715, 'eval_f1_score': 0.5, 'eval_roc_auc': 0.8214285714285714, 'eval_false_positives_rate': 0.125, 'eval_false_negatives_rate': 0.6428571428571429, 'eval_runtime': 0.4131, 'eval_samples_per_second': 53.252, 'eval_steps_per_second': 4.841, 'epoch': 1.0, 'step': 7}
2025-05-16 01:48:34,558 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 01:48:34,772 - Experiment - INFO - Test metrics: {'test_loss': 0.7086583971977234, 'test_accuracy': 0.3181818181818182, 'test_precision': 0.3333333333333333, 'test_recall': 0.15384615384615385, 'test_f1_score': 0.21052631578947367, 'test_roc_auc': 0.41880341880341887, 'test_false_positives_rate': 0.4444444444444444, 'test_false_negatives_rate': 0.8461538461538461, 'test_runtime': 0.2075, 'test_samples_per_second': 106.026, 'test_steps_per_second': 9.639, 'test_epoch': 1.0}
2025-05-16 01:48:34,792 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:48:34,795 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:48:34,859 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:48:34,860 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 01:48:34,861 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 01:48:35,469 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.602102518081665, 'eval_accuracy': 0.6818181818181818, 'eval_precision': 0.6666666666666666, 'eval_recall': 1.0, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.7410714285714286, 'eval_false_positives_rate': 0.875, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.3816, 'eval_samples_per_second': 57.659, 'eval_steps_per_second': 5.242, 'epoch': 2.0, 'step': 14}
2025-05-16 01:48:35,470 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 01:48:35,684 - Experiment - INFO - Test metrics: {'test_loss': 0.8452208042144775, 'test_accuracy': 0.5909090909090909, 'test_precision': 0.6, 'test_recall': 0.9230769230769231, 'test_f1_score': 0.7272727272727273, 'test_roc_auc': 0.5213675213675214, 'test_false_positives_rate': 0.8888888888888888, 'test_false_negatives_rate': 0.07692307692307693, 'test_runtime': 0.2086, 'test_samples_per_second': 105.459, 'test_steps_per_second': 9.587, 'test_epoch': 2.0}
2025-05-16 01:48:35,701 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 01:48:35,703 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 01:48:35,767 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 01:48:35,768 - Experiment - INFO - Finished model evaluations stage.