In [18]:
from IPython.display import display, Markdown
from workspace.sources.experiments.metrics import Loss, standard_evaluation_metrics
from workspace.sources.experiments.visualizations.utils import pick_best_run_by_metric
from workspace.sources.experiments.visualizations.tables import create_metrics_comparison_df, \
    export_best_models_to_latex
from workspace.sources.experiments.visualizations.utils import METRICS_PLOT_NAMES_MAPPING
import os
import mlflow

mlflow.set_tracking_uri('../mlruns')

In [2]:
experiments = ['prefinal-bert-base-uncased', 'prefinal-distillibert-base-uncased']

In [21]:
def get_best_models_results(dataset_name, experiments):
    client = mlflow.tracking.MlflowClient()

    experiments_runs = dict()
    for experiment in experiments:
        experiment_runs = client.search_runs(
            experiment_ids=[client.get_experiment_by_name(experiment).experiment_id],
            filter_string=f"params.dataset_name = '{dataset_name}'"
        )
        experiments_runs[experiment] = experiment_runs

    best_models_by_metrics = dict()
    for metric in standard_evaluation_metrics:
        best_models_by_metrics[metric.name] = dict()
        for experiment, runs in experiments_runs.items():
            best_run = pick_best_run_by_metric(runs, metric)
            if best_run is not None:
                best_models_by_metrics[metric.name][experiment] = best_run
    output_dir = os.path.join('assets', dataset_name, 'tables')
    for metric in standard_evaluation_metrics:
        display(Markdown(f'### {METRICS_PLOT_NAMES_MAPPING[metric.name]}:'))

        best_models_df = create_metrics_comparison_df(metric,
                                                      best_models_by_metrics,
                                                      output_dir)
        latex_table = export_best_models_to_latex(metric,
                                                  dataset_name,
                                                  best_models_df,
                                                  output_dir)
        display(Markdown('#### Dataframe:'))
        display(best_models_df)
        display(Markdown('#### LaTeX Table:'))
        print(latex_table)

### ReCOVery Dataset

In [22]:
dataset_name = 'recovery'
get_best_models_results(dataset_name, experiments)

### Precision:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.766667,0.875,0.736842,0.800000,0.832536,0.181818,0.263158,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",precision,4.0
1,distilbert-base-uncased,0.733333,0.875,0.700000,0.777778,0.860000,0.200000,0.300000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",precision,5.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Precision metric.}
    \label{tab:recovery_best_models_by_precision}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.767 & 0.875 & 0.737 & 0.800 & 0.833 & 0.182 & 0.263 \\
distilbert-base-uncased & 0.733 & 0.875 & 0.700 & 0.778 & 0.860 & 0.200 & 0.300 \\
\bottomrule
\end{tabular}
\end{table}

### F1-Score:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.733333,0.761905,0.842105,0.8,0.822967,0.454545,0.157895,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",f1_score,5.0
1,distilbert-base-uncased,0.666667,0.666667,1.000000,0.8,0.755000,1.000000,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",f1_score,2.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by F1-Score metric.}
    \label{tab:recovery_best_models_by_f1_score}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.733 & 0.762 & 0.842 & 0.800 & 0.823 & 0.455 & 0.158 \\
distilbert-base-uncased & 0.667 & 0.667 & 1.000 & 0.800 & 0.755 & 1.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### FPR:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.766667,0.875,0.736842,0.8,0.832536,0.181818,0.263158,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",false_positives_rate,4.0
1,distilbert-base-uncased,0.333333,0.000,0.000000,0.0,0.545000,0.000000,1.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",false_positives_rate,1.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by FPR metric.}
    \label{tab:recovery_best_models_by_false_positives_rate}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.767 & 0.875 & 0.737 & 0.800 & 0.833 & 0.182 & 0.263 \\
distilbert-base-uncased & 0.333 & 0.000 & 0.000 & 0.000 & 0.545 & 0.000 & 1.000 \\
\bottomrule
\end{tabular}
\end{table}

### ROC-AUC:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.733333,0.761905,0.842105,0.8,0.822967,0.454545,0.157895,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",roc_auc,5.0
1,distilbert-base-uncased,0.666667,0.666667,1.000000,0.8,0.755000,1.000000,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",roc_auc,2.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by ROC-AUC metric.}
    \label{tab:recovery_best_models_by_roc_auc}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.733 & 0.762 & 0.842 & 0.800 & 0.823 & 0.455 & 0.158 \\
distilbert-base-uncased & 0.667 & 0.667 & 1.000 & 0.800 & 0.755 & 1.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### Loss:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.633333,0.633333,1.0,0.77551,0.722488,1.0,0.0,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",loss,2.0
1,distilbert-base-uncased,0.666667,0.666667,1.0,0.80000,0.755000,1.0,0.0,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",loss,2.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Loss metric.}
    \label{tab:recovery_best_models_by_loss}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.633 & 0.633 & 1.000 & 0.776 & 0.722 & 1.000 & 0.000 \\
distilbert-base-uncased & 0.667 & 0.667 & 1.000 & 0.800 & 0.755 & 1.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### EUvsDisinfo Dataset

In [24]:
dataset_name = 'euvsdisinfo'
get_best_models_results(dataset_name, experiments)

### Precision:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",precision,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",precision,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Precision metric.}
    \label{tab:euvsdisinfo_best_models_by_precision}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### F1-Score:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",f1_score,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",f1_score,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by F1-Score metric.}
    \label{tab:euvsdisinfo_best_models_by_f1_score}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### FPR:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",false_positives_rate,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",false_positives_rate,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by FPR metric.}
    \label{tab:euvsdisinfo_best_models_by_false_positives_rate}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### ROC-AUC:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",roc_auc,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",roc_auc,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by ROC-AUC metric.}
    \label{tab:euvsdisinfo_best_models_by_roc_auc}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### Loss:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",loss,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",loss,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Loss metric.}
    \label{tab:euvsdisinfo_best_models_by_loss}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### ISOT Dataset

In [25]:
dataset_name = 'isot'
get_best_models_results(dataset_name, experiments)

### Precision:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.985714,0.945205,0.965035,0.994040,0.012987,0.054795,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",precision,4.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",precision,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Precision metric.}
    \label{tab:isot_best_models_by_precision}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.986 & 0.945 & 0.965 & 0.994 & 0.013 & 0.055 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### F1-Score:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.959459,0.972603,0.965986,0.992528,0.038961,0.027397,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",f1_score,3.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",f1_score,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by F1-Score metric.}
    \label{tab:isot_best_models_by_f1_score}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.959 & 0.973 & 0.966 & 0.993 & 0.039 & 0.027 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### FPR:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.985714,0.945205,0.965035,0.994040,0.012987,0.054795,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",false_positives_rate,4.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",false_positives_rate,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by FPR metric.}
    \label{tab:isot_best_models_by_false_positives_rate}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.986 & 0.945 & 0.965 & 0.994 & 0.013 & 0.055 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### ROC-AUC:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.959459,0.972603,0.965986,0.992528,0.038961,0.027397,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",roc_auc,3.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",roc_auc,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by ROC-AUC metric.}
    \label{tab:isot_best_models_by_roc_auc}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.959 & 0.973 & 0.966 & 0.993 & 0.039 & 0.027 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### Loss:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.959459,0.972603,0.965986,0.992528,0.038961,0.027397,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",loss,3.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",loss,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Loss metric.}
    \label{tab:isot_best_models_by_loss}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.959 & 0.973 & 0.966 & 0.993 & 0.039 & 0.027 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### CZ Dataset

In [27]:
dataset_name = 'czech_dataset'
get_best_models_results(dataset_name, experiments)

### Precision:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.800000,0.888889,0.80,0.842105,0.800000,0.2,0.20,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",precision,5.0
1,distilbert-base-uncased,0.866667,1.000000,0.75,0.857143,0.946429,0.0,0.25,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",precision,5.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Precision metric.}
    \label{tab:czechdataset_best_models_by_precision}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.800 & 0.889 & 0.800 & 0.842 & 0.800 & 0.200 & 0.200 \\
distilbert-base-uncased & 0.867 & 1.000 & 0.750 & 0.857 & 0.946 & 0.000 & 0.250 \\
\bottomrule
\end{tabular}
\end{table}

### F1-Score:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.8,0.888889,0.800,0.842105,0.800000,0.200000,0.200,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",f1_score,5.0
1,distilbert-base-uncased,0.8,0.777778,0.875,0.823529,0.946429,0.285714,0.125,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",f1_score,8.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by F1-Score metric.}
    \label{tab:czechdataset_best_models_by_f1_score}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.800 & 0.889 & 0.800 & 0.842 & 0.800 & 0.200 & 0.200 \\
distilbert-base-uncased & 0.800 & 0.778 & 0.875 & 0.824 & 0.946 & 0.286 & 0.125 \\
\bottomrule
\end{tabular}
\end{table}

### FPR:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.800000,0.888889,0.80,0.842105,0.800000,0.2,0.20,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",false_positives_rate,5.0
1,distilbert-base-uncased,0.866667,1.000000,0.75,0.857143,0.946429,0.0,0.25,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",false_positives_rate,5.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by FPR metric.}
    \label{tab:czechdataset_best_models_by_false_positives_rate}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.800 & 0.889 & 0.800 & 0.842 & 0.800 & 0.200 & 0.200 \\
distilbert-base-uncased & 0.867 & 1.000 & 0.750 & 0.857 & 0.946 & 0.000 & 0.250 \\
\bottomrule
\end{tabular}
\end{table}

### ROC-AUC:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.8,0.888889,0.800,0.842105,0.800000,0.200000,0.200,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",roc_auc,5.0
1,distilbert-base-uncased,0.8,0.777778,0.875,0.823529,0.946429,0.285714,0.125,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",roc_auc,8.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by ROC-AUC metric.}
    \label{tab:czechdataset_best_models_by_roc_auc}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.800 & 0.889 & 0.800 & 0.842 & 0.800 & 0.200 & 0.200 \\
distilbert-base-uncased & 0.800 & 0.778 & 0.875 & 0.824 & 0.946 & 0.286 & 0.125 \\
\bottomrule
\end{tabular}
\end{table}

### Loss:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Evaluation Metric,best_epoch
0,bert-base-uncased,0.8,0.888889,0.800,0.842105,0.800000,0.200000,0.200,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",loss,5.0
1,distilbert-base-uncased,0.8,0.777778,0.875,0.823529,0.946429,0.285714,0.125,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",loss,8.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Loss metric.}
    \label{tab:czechdataset_best_models_by_loss}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.800 & 0.889 & 0.800 & 0.842 & 0.800 & 0.200 & 0.200 \\
distilbert-base-uncased & 0.800 & 0.778 & 0.875 & 0.824 & 0.946 & 0.286 & 0.125 \\
\bottomrule
\end{tabular}
\end{table}