In [1]:
from IPython.display import display, Markdown
from workspace.sources.experiments.metrics import Loss, standard_evaluation_metrics
from workspace.sources.experiments.utils import get_best_models_by_metrics
from workspace.sources.experiments.visualizations.tables import create_metrics_comparison_df, \
    export_best_models_to_latex
from workspace.sources.experiments.visualizations.utils import METRICS_PLOT_NAMES_MAPPING
import os
import mlflow

mlflow.set_tracking_uri('../mlruns')

In [2]:
experiments = ['bert',
               'distillibert',
               'roberta',
               'gpt1',
               'gpt2']
#
#
# experiments = ['bert',
#                'distillibert',
#                'roberta',
#                'gpt1',
#                'gpt2']

In [3]:
def get_best_models_results(dataset_name, experiments):
    best_models_by_metrics = get_best_models_by_metrics(dataset_name, experiments)
    output_dir = os.path.join('assets', dataset_name, 'tables')
    for metric in standard_evaluation_metrics:
        display(Markdown(f'### {METRICS_PLOT_NAMES_MAPPING[metric.name]}:'))

        best_models_df = create_metrics_comparison_df(metric,
                                                      best_models_by_metrics,
                                                      output_dir)
        latex_table = export_best_models_to_latex(metric,
                                                  best_models_df,
                                                  output_dir)
        display(Markdown('#### Dataframe:'))
        display(best_models_df)
        display(Markdown('#### LaTeX Table:'))
        print(latex_table)

### ReCOVery Dataset

In [4]:
dataset_name = 'recovery'
get_best_models_results(dataset_name, experiments)

### Precision:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,0.666667,1.000,0.800000,0.580000,1.000000,0.000,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31382e36c6b14d5eb51afe4589a8359e,precision,1.0
1,DistilliBERT,0.800000,0.785714,1.000,0.880000,0.863636,0.750000,0.000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",a8f6e48fe3114e70af7dc187e8875322,precision,10.0
2,RoBERTa,0.600000,0.600000,1.000,0.750000,0.722222,1.000000,0.000,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",705b97a4338b4695a874b956d8836855,precision,9.0
3,GPT1,0.733333,0.700000,0.875,0.777778,0.714286,0.428571,0.125,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",440bfa2c645f4a088791f687e978056c,precision,4.0
4,GPT2,0.600000,0.600000,1.000,0.750000,0.518519,1.000000,0.000,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",8812f16ef6f548918a2ef001c7ca1ec2,precision,1.0

#### LaTeX Table:

\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & \textbf{Accuracy} & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 0.667 & 1.000 & 0.800 & 0.580 & 1.000 & 0.000 \\
DistilliBERT & 0.800 & 0.786 & 1.000 & 0.880 & 0.864 & 0.750 & 0.000 \\
RoBERTa & 0.600 & 0.600 & 1.000 & 0.750 & 0.722 & 1.000 & 0.000 \\
GPT1 & 0.733 & 0.700 & 0.875 & 0.778 & 0.714 & 0.429 & 0.125 \\
GPT2 & 0.600 & 0.600 & 1.000 & 0.750 & 0.519 & 1.000 & 0.000 \\
\bottomrule
\end{tabular}

### F1-Score:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,0.666667,1.0,0.800000,0.580000,1.000000,0.0,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31382e36c6b14d5eb51afe4589a8359e,f1_score,1.0
1,DistilliBERT,0.800000,0.785714,1.0,0.880000,0.863636,0.750000,0.0,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",a8f6e48fe3114e70af7dc187e8875322,f1_score,10.0
2,RoBERTa,0.600000,0.600000,1.0,0.750000,0.666667,1.000000,0.0,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",705b97a4338b4695a874b956d8836855,f1_score,7.0
3,GPT1,0.666667,0.615385,1.0,0.761905,0.803571,0.714286,0.0,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",440bfa2c645f4a088791f687e978056c,f1_score,2.0
4,GPT2,0.600000,0.600000,1.0,0.750000,0.518519,1.000000,0.0,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",8812f16ef6f548918a2ef001c7ca1ec2,f1_score,1.0

#### LaTeX Table:

\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & \textbf{Accuracy} & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 0.667 & 1.000 & 0.800 & 0.580 & 1.000 & 0.000 \\
DistilliBERT & 0.800 & 0.786 & 1.000 & 0.880 & 0.864 & 0.750 & 0.000 \\
RoBERTa & 0.600 & 0.600 & 1.000 & 0.750 & 0.667 & 1.000 & 0.000 \\
GPT1 & 0.667 & 0.615 & 1.000 & 0.762 & 0.804 & 0.714 & 0.000 \\
GPT2 & 0.600 & 0.600 & 1.000 & 0.750 & 0.519 & 1.000 & 0.000 \\
\bottomrule
\end{tabular}

### FPR:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,0.666667,1.000000,0.800000,0.580000,1.000000,0.000000,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31382e36c6b14d5eb51afe4589a8359e,false_positives_rate,1.0
1,DistilliBERT,0.800000,0.785714,1.000000,0.880000,0.863636,0.750000,0.000000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",a8f6e48fe3114e70af7dc187e8875322,false_positives_rate,10.0
2,RoBERTa,0.600000,0.600000,1.000000,0.750000,0.722222,1.000000,0.000000,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",705b97a4338b4695a874b956d8836855,false_positives_rate,9.0
3,GPT1,0.733333,0.700000,0.875000,0.777778,0.714286,0.428571,0.125000,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",440bfa2c645f4a088791f687e978056c,false_positives_rate,4.0
4,GPT2,0.400000,0.500000,0.666667,0.571429,0.574074,1.000000,0.333333,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",8812f16ef6f548918a2ef001c7ca1ec2,false_positives_rate,2.0

#### LaTeX Table:

\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & \textbf{Accuracy} & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 0.667 & 1.000 & 0.800 & 0.580 & 1.000 & 0.000 \\
DistilliBERT & 0.800 & 0.786 & 1.000 & 0.880 & 0.864 & 0.750 & 0.000 \\
RoBERTa & 0.600 & 0.600 & 1.000 & 0.750 & 0.722 & 1.000 & 0.000 \\
GPT1 & 0.733 & 0.700 & 0.875 & 0.778 & 0.714 & 0.429 & 0.125 \\
GPT2 & 0.400 & 0.500 & 0.667 & 0.571 & 0.574 & 1.000 & 0.333 \\
\bottomrule
\end{tabular}

### ROC-AUC:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,0.666667,1.000000,0.800000,0.560000,1.000000,0.000000,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31382e36c6b14d5eb51afe4589a8359e,roc_auc,2.0
1,DistilliBERT,0.800000,0.785714,1.000000,0.880000,0.863636,0.750000,0.000000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",a8f6e48fe3114e70af7dc187e8875322,roc_auc,10.0
2,RoBERTa,0.600000,0.600000,1.000000,0.750000,0.537037,1.000000,0.000000,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",705b97a4338b4695a874b956d8836855,roc_auc,4.0
3,GPT1,0.733333,0.700000,0.875000,0.777778,0.714286,0.428571,0.125000,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",440bfa2c645f4a088791f687e978056c,roc_auc,4.0
4,GPT2,0.400000,0.500000,0.666667,0.571429,0.537037,1.000000,0.333333,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",8812f16ef6f548918a2ef001c7ca1ec2,roc_auc,3.0

#### LaTeX Table:

\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & \textbf{Accuracy} & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 0.667 & 1.000 & 0.800 & 0.560 & 1.000 & 0.000 \\
DistilliBERT & 0.800 & 0.786 & 1.000 & 0.880 & 0.864 & 0.750 & 0.000 \\
RoBERTa & 0.600 & 0.600 & 1.000 & 0.750 & 0.537 & 1.000 & 0.000 \\
GPT1 & 0.733 & 0.700 & 0.875 & 0.778 & 0.714 & 0.429 & 0.125 \\
GPT2 & 0.400 & 0.500 & 0.667 & 0.571 & 0.537 & 1.000 & 0.333 \\
\bottomrule
\end{tabular}

### Loss:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,0.666667,1.000000,0.800000,0.580000,1.000000,0.000000,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31382e36c6b14d5eb51afe4589a8359e,loss,1.0
1,DistilliBERT,0.800000,0.785714,1.000000,0.880000,0.863636,0.750000,0.000000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",a8f6e48fe3114e70af7dc187e8875322,loss,10.0
2,RoBERTa,0.600000,0.600000,1.000000,0.750000,0.629630,1.000000,0.000000,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",705b97a4338b4695a874b956d8836855,loss,6.0
3,GPT1,0.733333,0.700000,0.875000,0.777778,0.714286,0.428571,0.125000,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",440bfa2c645f4a088791f687e978056c,loss,4.0
4,GPT2,0.400000,0.500000,0.666667,0.571429,0.574074,1.000000,0.333333,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",8812f16ef6f548918a2ef001c7ca1ec2,loss,2.0

#### LaTeX Table:

\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & \textbf{Accuracy} & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 0.667 & 1.000 & 0.800 & 0.580 & 1.000 & 0.000 \\
DistilliBERT & 0.800 & 0.786 & 1.000 & 0.880 & 0.864 & 0.750 & 0.000 \\
RoBERTa & 0.600 & 0.600 & 1.000 & 0.750 & 0.630 & 1.000 & 0.000 \\
GPT1 & 0.733 & 0.700 & 0.875 & 0.778 & 0.714 & 0.429 & 0.125 \\
GPT2 & 0.400 & 0.500 & 0.667 & 0.571 & 0.574 & 1.000 & 0.333 \\
\bottomrule
\end{tabular}

### EUvsDisinfo Dataset

In [9]:
dataset_name = 'euvsdisinfo'
get_best_models_results(dataset_name, experiments)

### Precision:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",eb640078966f4f08bd82144e24c23422,precision,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",937ee7f76a0041769811809a7766af23,precision,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Precision metric.}
    \label{tab:euvsdisinfo_best_models_by_precision}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### F1-Score:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",eb640078966f4f08bd82144e24c23422,f1_score,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",937ee7f76a0041769811809a7766af23,f1_score,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by F1-Score metric.}
    \label{tab:euvsdisinfo_best_models_by_f1_score}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### FPR:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",eb640078966f4f08bd82144e24c23422,false_positives_rate,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",937ee7f76a0041769811809a7766af23,false_positives_rate,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by FPR metric.}
    \label{tab:euvsdisinfo_best_models_by_false_positives_rate}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### ROC-AUC:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",eb640078966f4f08bd82144e24c23422,roc_auc,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",937ee7f76a0041769811809a7766af23,roc_auc,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by ROC-AUC metric.}
    \label{tab:euvsdisinfo_best_models_by_roc_auc}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### Loss:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.96875,1.0,0.947368,0.972973,1.0,0.0,0.052632,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",eb640078966f4f08bd82144e24c23422,loss,3.0
1,distilbert-base-uncased,1.00000,1.0,1.000000,1.000000,1.0,0.0,0.000000,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",937ee7f76a0041769811809a7766af23,loss,4.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Loss metric.}
    \label{tab:euvsdisinfo_best_models_by_loss}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.969 & 1.000 & 0.947 & 0.973 & 1.000 & 0.000 & 0.053 \\
distilbert-base-uncased & 1.000 & 1.000 & 1.000 & 1.000 & 1.000 & 0.000 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}

### ISOT Dataset

In [10]:
dataset_name = 'isot'
get_best_models_results(dataset_name, experiments)

### Precision:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.985714,0.945205,0.965035,0.994040,0.012987,0.054795,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",5ab18520410c4e7ab95591ee9e6eff63,precision,4.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",4b1c5f09c31a402f8871367aaf76f380,precision,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Precision metric.}
    \label{tab:isot_best_models_by_precision}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.986 & 0.945 & 0.965 & 0.994 & 0.013 & 0.055 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### F1-Score:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.959459,0.972603,0.965986,0.992528,0.038961,0.027397,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",5ab18520410c4e7ab95591ee9e6eff63,f1_score,3.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",4b1c5f09c31a402f8871367aaf76f380,f1_score,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by F1-Score metric.}
    \label{tab:isot_best_models_by_f1_score}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.959 & 0.973 & 0.966 & 0.993 & 0.039 & 0.027 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### FPR:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.985714,0.945205,0.965035,0.994040,0.012987,0.054795,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",5ab18520410c4e7ab95591ee9e6eff63,false_positives_rate,4.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",4b1c5f09c31a402f8871367aaf76f380,false_positives_rate,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by FPR metric.}
    \label{tab:isot_best_models_by_false_positives_rate}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.986 & 0.945 & 0.965 & 0.994 & 0.013 & 0.055 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### ROC-AUC:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.959459,0.972603,0.965986,0.992528,0.038961,0.027397,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",5ab18520410c4e7ab95591ee9e6eff63,roc_auc,3.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",4b1c5f09c31a402f8871367aaf76f380,roc_auc,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by ROC-AUC metric.}
    \label{tab:isot_best_models_by_roc_auc}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.959 & 0.973 & 0.966 & 0.993 & 0.039 & 0.027 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### Loss:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,bert-base-uncased,0.966667,0.959459,0.972603,0.965986,0.992528,0.038961,0.027397,prefinal-bert-base-uncased,"model(mn=bert-base-uncased,mmn=loss,e=10,bs=8,...",5ab18520410c4e7ab95591ee9e6eff63,loss,3.0
1,distilbert-base-uncased,0.993333,1.000000,0.985915,0.992908,0.999465,0.000000,0.014085,prefinal-distillibert-base-uncased,"model(mn=distilbert-base-uncased,mmn=loss,e=10...",4b1c5f09c31a402f8871367aaf76f380,loss,7.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Loss metric.}
    \label{tab:isot_best_models_by_loss}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
bert-base-uncased & 0.967 & 0.959 & 0.973 & 0.966 & 0.993 & 0.039 & 0.027 \\
distilbert-base-uncased & 0.993 & 1.000 & 0.986 & 0.993 & 0.999 & 0.000 & 0.014 \\
\bottomrule
\end{tabular}
\end{table}

### CZ Dataset

In [19]:
dataset_name = 'cz_dataset'
get_best_models_results(dataset_name, experiments)

### Precision:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,1.000000,0.545455,0.705882,0.977273,0.000000,0.454545,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31fe9869fc8f4bf19ec32316af796f51,precision,3.0
1,DistilliBERT,0.800000,0.888889,0.800000,0.842105,0.840000,0.200000,0.200000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",32154051dcf8478c89014ffe85c78124,precision,9.0
2,RoBERTa,0.818182,1.000000,0.733333,0.846154,0.904762,0.000000,0.266667,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",c1bff05932834464aab83e1393aa3d9e,precision,6.0
3,GPT1,0.318182,0.333333,0.153846,0.210526,0.418803,0.444444,0.846154,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",43ae211d60814aaca2fd52aeaa0f52ca,precision,1.0
4,GPT2,0.500000,0.625000,0.666667,0.645161,0.485714,0.857143,0.333333,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",a5b643c9f57d4ea4ab9203bf3f3671fb,precision,6.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Precision metric.}
    \label{tab:cz_dataset_best_models_by_precision}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 1.000 & 0.545 & 0.706 & 0.977 & 0.000 & 0.455 \\
DistilliBERT & 0.800 & 0.889 & 0.800 & 0.842 & 0.840 & 0.200 & 0.200 \\
RoBERTa & 0.818 & 1.000 & 0.733 & 0.846 & 0.905 & 0.000 & 0.267 \\
GPT1 & 0.318 & 0.333 & 0.154 & 0.211 & 0.419 & 0.444 & 0.846 \\
GPT2 & 0.500 & 0.625 & 0.667 & 0.645 & 0.486 & 0.857 & 0.333 \\
\bottomrule
\end{tabular}
\end{table}

### F1-Score:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,1.000000,0.545455,0.705882,0.977273,0.000000,0.454545,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31fe9869fc8f4bf19ec32316af796f51,f1_score,3.0
1,DistilliBERT,0.800000,0.888889,0.800000,0.842105,0.840000,0.200000,0.200000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",32154051dcf8478c89014ffe85c78124,f1_score,9.0
2,RoBERTa,0.681818,0.750000,0.800000,0.774194,0.771429,0.571429,0.200000,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",c1bff05932834464aab83e1393aa3d9e,f1_score,7.0
3,GPT1,0.681818,0.650000,1.000000,0.787879,0.504274,0.777778,0.000000,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",43ae211d60814aaca2fd52aeaa0f52ca,f1_score,4.0
4,GPT2,0.636364,0.684211,0.866667,0.764706,0.476190,0.857143,0.133333,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",a5b643c9f57d4ea4ab9203bf3f3671fb,f1_score,3.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by F1-Score metric.}
    \label{tab:cz_dataset_best_models_by_f1_score}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 1.000 & 0.545 & 0.706 & 0.977 & 0.000 & 0.455 \\
DistilliBERT & 0.800 & 0.889 & 0.800 & 0.842 & 0.840 & 0.200 & 0.200 \\
RoBERTa & 0.682 & 0.750 & 0.800 & 0.774 & 0.771 & 0.571 & 0.200 \\
GPT1 & 0.682 & 0.650 & 1.000 & 0.788 & 0.504 & 0.778 & 0.000 \\
GPT2 & 0.636 & 0.684 & 0.867 & 0.765 & 0.476 & 0.857 & 0.133 \\
\bottomrule
\end{tabular}
\end{table}

### FPR:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,1.000000,0.545455,0.705882,0.977273,0.000000,0.454545,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31fe9869fc8f4bf19ec32316af796f51,false_positives_rate,3.0
1,DistilliBERT,0.733333,0.875000,0.700000,0.777778,0.840000,0.200000,0.300000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",32154051dcf8478c89014ffe85c78124,false_positives_rate,10.0
2,RoBERTa,0.318182,0.000000,0.000000,0.000000,0.952381,0.000000,1.000000,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",c1bff05932834464aab83e1393aa3d9e,false_positives_rate,1.0
3,GPT1,0.318182,0.333333,0.153846,0.210526,0.418803,0.444444,0.846154,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",43ae211d60814aaca2fd52aeaa0f52ca,false_positives_rate,1.0
4,GPT2,0.500000,0.625000,0.666667,0.645161,0.485714,0.857143,0.333333,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",a5b643c9f57d4ea4ab9203bf3f3671fb,false_positives_rate,6.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by FPR metric.}
    \label{tab:cz_dataset_best_models_by_false_positives_rate}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 1.000 & 0.545 & 0.706 & 0.977 & 0.000 & 0.455 \\
DistilliBERT & 0.733 & 0.875 & 0.700 & 0.778 & 0.840 & 0.200 & 0.300 \\
RoBERTa & 0.318 & 0.000 & 0.000 & 0.000 & 0.952 & 0.000 & 1.000 \\
GPT1 & 0.318 & 0.333 & 0.154 & 0.211 & 0.419 & 0.444 & 0.846 \\
GPT2 & 0.500 & 0.625 & 0.667 & 0.645 & 0.486 & 0.857 & 0.333 \\
\bottomrule
\end{tabular}
\end{table}

### ROC-AUC:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,1.000000,0.545455,0.705882,0.977273,0.000000,0.454545,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31fe9869fc8f4bf19ec32316af796f51,roc_auc,3.0
1,DistilliBERT,0.466667,0.750000,0.300000,0.428571,0.800000,0.200000,0.700000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",32154051dcf8478c89014ffe85c78124,roc_auc,5.0
2,RoBERTa,0.681818,0.681818,1.000000,0.810811,0.885714,1.000000,0.000000,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",c1bff05932834464aab83e1393aa3d9e,roc_auc,4.0
3,GPT1,0.318182,0.333333,0.153846,0.210526,0.418803,0.444444,0.846154,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",43ae211d60814aaca2fd52aeaa0f52ca,roc_auc,1.0
4,GPT2,0.636364,0.684211,0.866667,0.764706,0.476190,0.857143,0.133333,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",a5b643c9f57d4ea4ab9203bf3f3671fb,roc_auc,3.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by ROC-AUC metric.}
    \label{tab:cz_dataset_best_models_by_roc_auc}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 1.000 & 0.545 & 0.706 & 0.977 & 0.000 & 0.455 \\
DistilliBERT & 0.467 & 0.750 & 0.300 & 0.429 & 0.800 & 0.200 & 0.700 \\
RoBERTa & 0.682 & 0.682 & 1.000 & 0.811 & 0.886 & 1.000 & 0.000 \\
GPT1 & 0.318 & 0.333 & 0.154 & 0.211 & 0.419 & 0.444 & 0.846 \\
GPT2 & 0.636 & 0.684 & 0.867 & 0.765 & 0.476 & 0.857 & 0.133 \\
\bottomrule
\end{tabular}
\end{table}

### Loss:

#### Dataframe:

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,FPR,FNR,Experiment,Run Signature,Run ID,Evaluation Metric,best_epoch
0,BERT,0.666667,1.000000,0.545455,0.705882,0.977273,0.000000,0.454545,prefinal-bert-v2,"model(mn=bert,ti=bert-base-uncased,mmn=loss,e=...",31fe9869fc8f4bf19ec32316af796f51,loss,3.0
1,DistilliBERT,0.733333,0.875000,0.700000,0.777778,0.840000,0.200000,0.300000,prefinal-distilli_bert-v2,"model(mn=distillibert,ti=distilbert-base-uncas...",32154051dcf8478c89014ffe85c78124,loss,10.0
2,RoBERTa,0.818182,1.000000,0.733333,0.846154,0.904762,0.000000,0.266667,prefinal-roberta-v2,"model(mn=roberta,ti=roberta-base,mmn=loss,e=10...",c1bff05932834464aab83e1393aa3d9e,loss,6.0
3,GPT1,0.590909,0.600000,0.923077,0.727273,0.521368,0.888889,0.076923,prefinal-gpt1-v2,"model(mn=gpt1,ti=openai-gpt,mmn=loss,e=10,bs=1...",43ae211d60814aaca2fd52aeaa0f52ca,loss,2.0
4,GPT2,0.636364,0.684211,0.866667,0.764706,0.476190,0.857143,0.133333,prefinal-gpt2-v2,"model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=...",a5b643c9f57d4ea4ab9203bf3f3671fb,loss,3.0

#### LaTeX Table:

\begin{table}[]
    \footnotesize
    \caption{Best models selected by Loss metric.}
    \label{tab:cz_dataset_best_models_by_loss}
    \centering
\begin{tabular}{|l||r|r|r|r|r|r|r|}
\toprule
Model & Accuracy & \textbf{Precision} & Recall & \textbf{F1-Score} & \textbf{ROC-AUC} & \textbf{FPR} & FNR \\
\midrule \midrule
BERT & 0.667 & 1.000 & 0.545 & 0.706 & 0.977 & 0.000 & 0.455 \\
DistilliBERT & 0.733 & 0.875 & 0.700 & 0.778 & 0.840 & 0.200 & 0.300 \\
RoBERTa & 0.818 & 1.000 & 0.733 & 0.846 & 0.905 & 0.000 & 0.267 \\
GPT1 & 0.591 & 0.600 & 0.923 & 0.727 & 0.521 & 0.889 & 0.077 \\
GPT2 & 0.636 & 0.684 & 0.867 & 0.765 & 0.476 & 0.857 & 0.133 \\
\bottomrule
\end{tabular}
\end{table}