In [1]:
%cd bert_base_uncased
%run training.ipynb

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\workspace\notebooks\bert_base_uncased
Experiment: bert
Dataset Hyperparameters Grid Size:  8
Model Hyperparameters Grid Size:  4
Total Hyperparameter Combinations:  32

### Run 1 of 32

2025/05/16 06:27:36 INFO mlflow.tracking.fluent: Experiment with name 'bert' does not exist. Creating a new experiment.
2025-05-16 06:27:36,020 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 06:27:36,021 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01)
2025-05-16 06:27:36,022 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 06:27:36,022 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 06:27:36,256 - Experiment - INFO - Run ID: 32899b59ef4c4c5ebeaf8eae49355ff9
2025-05-16 06:27:36,256 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.0,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_06-27-36;rs=768241735
2025-05-16 06:27:36,272 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 06:27:36,289 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 06:27:36,447 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x000001AC385751C0>]>
2025-05-16 06:27:36,938 - Experiment - INFO - Preprocessing function 0: bert_base_uncased_encoder
2025-05-16 06:27:36,938 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 06:27:36,938 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

2025-05-16 06:27:44,832 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 06:27:44,833 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 06:27:46,245 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 06:27:46,246 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 06:27:50,317 - Experiment - INFO - Model name: BERT
2025-05-16 06:27:50,321 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 1e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.0, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 06:31:27,955 - Experiment - INFO - Evaluating model using accuracy metric...
2025-05-16 06:31:27,955 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 06:31:28,345 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4081558287143707, 'eval_accuracy': 0.868421052631579, 'eval_precision': 0.8820960698689956, 'eval_recall': 0.9395348837209302, 'eval_f1_score': 0.9099099099099099, 'eval_roc_auc': 0.9041546903579828, 'eval_false_positives_rate': 0.30337078651685395, 'eval_false_negatives_rate': 0.06046511627906977, 'eval_runtime': 2.4906, 'eval_samples_per_second': 122.058, 'eval_steps_per_second': 7.629, 'epoch': 4.0, 'step': 356}
2025-05-16 06:31:28,345 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 06:31:32,386 - Experiment - INFO - Test metrics: {'test_loss': 0.33064308762550354, 'test_accuracy': 0.8819672131147541, 'test_precision': 0.871244635193133, 'test_recall': 0.9712918660287081, 'test_f1_score': 0.918552036199095, 'test_roc_auc': 0.9175139553429027, 'test_false_positives_rate': 0.3125, 'test_false_negatives_rate': 0.028708133971291867, 'test_runtime': 4.0358, 'test_samples_per_second': 75.574, 'test_steps_per_second': 4.956, 'test_epoch': 4.0}
2025-05-16 06:31:32,416 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 06:31:32,428 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 06:31:33,113 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 06:31:33,113 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 06:31:33,113 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-178
2025-05-16 06:31:33,612 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.37988683581352234, 'eval_accuracy': 0.8256578947368421, 'eval_precision': 0.8932038834951457, 'eval_recall': 0.8558139534883721, 'eval_f1_score': 0.8741092636579573, 'eval_roc_auc': 0.8910373660830939, 'eval_false_positives_rate': 0.24719101123595505, 'eval_false_negatives_rate': 0.14418604651162792, 'eval_runtime': 2.3719, 'eval_samples_per_second': 128.168, 'eval_steps_per_second': 8.01, 'epoch': 2.0, 'step': 178}
2025-05-16 06:31:33,612 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 06:31:36,087 - Experiment - INFO - Test metrics: {'test_loss': 0.38077208399772644, 'test_accuracy': 0.8295081967213115, 'test_precision': 0.8755980861244019, 'test_recall': 0.8755980861244019, 'test_f1_score': 0.8755980861244019, 'test_roc_auc': 0.8879585326953747, 'test_false_positives_rate': 0.2708333333333333, 'test_false_negatives_rate': 0.12440191387559808, 'test_runtime': 2.472, 'test_samples_per_second': 123.383, 'test_steps_per_second': 8.091, 'test_epoch': 2.0}
2025-05-16 06:31:36,122 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 06:31:36,130 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 06:31:36,832 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 06:31:36,832 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 06:31:36,833 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 06:31:37,201 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4081558287143707, 'eval_accuracy': 0.868421052631579, 'eval_precision': 0.8820960698689956, 'eval_recall': 0.9395348837209302, 'eval_f1_score': 0.9099099099099099, 'eval_roc_auc': 0.9041546903579828, 'eval_false_positives_rate': 0.30337078651685395, 'eval_false_negatives_rate': 0.06046511627906977, 'eval_runtime': 2.4906, 'eval_samples_per_second': 122.058, 'eval_steps_per_second': 7.629, 'epoch': 4.0, 'step': 356}
2025-05-16 06:31:37,201 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 06:31:41,466 - Experiment - INFO - Test metrics: {'test_loss': 0.33064308762550354, 'test_accuracy': 0.8819672131147541, 'test_precision': 0.871244635193133, 'test_recall': 0.9712918660287081, 'test_f1_score': 0.918552036199095, 'test_roc_auc': 0.9175139553429027, 'test_false_positives_rate': 0.3125, 'test_false_negatives_rate': 0.028708133971291867, 'test_runtime': 4.2631, 'test_samples_per_second': 71.545, 'test_steps_per_second': 4.691, 'test_epoch': 4.0}
2025-05-16 06:31:41,502 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 06:31:41,511 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 06:31:42,191 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 06:31:42,191 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 06:31:42,191 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-178
2025-05-16 06:31:42,548 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.37988683581352234, 'eval_accuracy': 0.8256578947368421, 'eval_precision': 0.8932038834951457, 'eval_recall': 0.8558139534883721, 'eval_f1_score': 0.8741092636579573, 'eval_roc_auc': 0.8910373660830939, 'eval_false_positives_rate': 0.24719101123595505, 'eval_false_negatives_rate': 0.14418604651162792, 'eval_runtime': 2.3719, 'eval_samples_per_second': 128.168, 'eval_steps_per_second': 8.01, 'epoch': 2.0, 'step': 178}
2025-05-16 06:31:42,548 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 06:31:44,934 - Experiment - INFO - Test metrics: {'test_loss': 0.38077208399772644, 'test_accuracy': 0.8295081967213115, 'test_precision': 0.8755980861244019, 'test_recall': 0.8755980861244019, 'test_f1_score': 0.8755980861244019, 'test_roc_auc': 0.8879585326953747, 'test_false_positives_rate': 0.2708333333333333, 'test_false_negatives_rate': 0.12440191387559808, 'test_runtime': 2.3848, 'test_samples_per_second': 127.893, 'test_steps_per_second': 8.386, 'test_epoch': 2.0}
2025-05-16 06:31:44,959 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 06:31:44,967 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 06:31:45,631 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 06:31:45,631 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 06:31:45,631 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 06:31:45,967 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4081558287143707, 'eval_accuracy': 0.868421052631579, 'eval_precision': 0.8820960698689956, 'eval_recall': 0.9395348837209302, 'eval_f1_score': 0.9099099099099099, 'eval_roc_auc': 0.9041546903579828, 'eval_false_positives_rate': 0.30337078651685395, 'eval_false_negatives_rate': 0.06046511627906977, 'eval_runtime': 2.4906, 'eval_samples_per_second': 122.058, 'eval_steps_per_second': 7.629, 'epoch': 4.0, 'step': 356}
2025-05-16 06:31:45,967 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 06:31:50,025 - Experiment - INFO - Test metrics: {'test_loss': 0.33064308762550354, 'test_accuracy': 0.8819672131147541, 'test_precision': 0.871244635193133, 'test_recall': 0.9712918660287081, 'test_f1_score': 0.918552036199095, 'test_roc_auc': 0.9175139553429027, 'test_false_positives_rate': 0.3125, 'test_false_negatives_rate': 0.028708133971291867, 'test_runtime': 4.0565, 'test_samples_per_second': 75.187, 'test_steps_per_second': 4.93, 'test_epoch': 4.0}
2025-05-16 06:31:50,058 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 06:31:50,066 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 06:31:50,803 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 06:31:50,803 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 06:31:50,803 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-178
2025-05-16 06:31:51,213 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.37988683581352234, 'eval_accuracy': 0.8256578947368421, 'eval_precision': 0.8932038834951457, 'eval_recall': 0.8558139534883721, 'eval_f1_score': 0.8741092636579573, 'eval_roc_auc': 0.8910373660830939, 'eval_false_positives_rate': 0.24719101123595505, 'eval_false_negatives_rate': 0.14418604651162792, 'eval_runtime': 2.3719, 'eval_samples_per_second': 128.168, 'eval_steps_per_second': 8.01, 'epoch': 2.0, 'step': 178}
2025-05-16 06:31:51,213 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 06:31:53,700 - Experiment - INFO - Test metrics: {'test_loss': 0.38077208399772644, 'test_accuracy': 0.8295081967213115, 'test_precision': 0.8755980861244019, 'test_recall': 0.8755980861244019, 'test_f1_score': 0.8755980861244019, 'test_roc_auc': 0.8879585326953747, 'test_false_positives_rate': 0.2708333333333333, 'test_false_negatives_rate': 0.12440191387559808, 'test_runtime': 2.4706, 'test_samples_per_second': 123.452, 'test_steps_per_second': 8.095, 'test_epoch': 2.0}
2025-05-16 06:31:53,728 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 06:31:53,740 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 06:31:54,425 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 06:31:54,425 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 32

2025-05-16 06:31:55,218 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 06:31:55,219 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 06:31:55,219 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 06:31:55,220 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 06:31:55,422 - Experiment - INFO - Run ID: f998c224d55e41a8b73e5a986dbbbd08
2025-05-16 06:31:55,423 - Experiment - INFO - Run name: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=1e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_06-31-55;rs=2684974863
2025-05-16 06:31:55,435 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 06:31:55,450 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 06:31:55,608 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.encoders.encoders.BertBaseUncasedEncoder object at 0x000001AC385751C0>]>
2025-05-16 06:31:56,193 - Experiment - INFO - Preprocessing function 0: bert_base_uncased_encoder
2025-05-16 06:31:56,193 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 06:31:56,194 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

2025-05-16 06:32:02,728 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 06:32:02,730 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 06:32:04,392 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 06:32:04,394 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 06:32:08,729 - Experiment - INFO - Model name: BERT
2025-05-16 06:32:08,733 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 1e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

KeyboardInterrupt:

KeyboardInterrupt:

In [ ]:
%cd ../distillibert
%run training.ipynb

In [ ]:
%cd ../roberta
%run training.ipynb

In [ ]:
%cd ../openai_gpt1
%run training.ipynb

In [ ]:
%cd ../openai_gpt2
%run training.ipynb