In [1]:
%cd bert_base_uncased
%run training.ipynb

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\workspace\notebooks\bert_base_uncased
Experiment: bert
Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### Run 1 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:41:43,072 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:41:43,074 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:41:43,075 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:41:43,076 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:04,701 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:04,701 - Experiment - INFO - Existing run ID: 5cd11c9c0b444ac39c0b6db83d30eda0
INFO:Experiment:Existing run ID: 5cd11c9c0b444ac39c0b6db83d30eda0
2025-05-16 15:42:04,701 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:04,714 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:04,716 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:04,717 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:04,717 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:06,745 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:06,745 - Experiment - INFO - Existing run ID: 5cd11c9c0b444ac39c0b6db83d30eda0
INFO:Experiment:Existing run ID: 5cd11c9c0b444ac39c0b6db83d30eda0
2025-05-16 15:42:06,878 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:06,879 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:06,896 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:06,897 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:06,899 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:06,900 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:09,276 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:09,276 - Experiment - INFO - Existing run ID: 75aeff0f31c3454f835e20bf3f9a2443
INFO:Experiment:Existing run ID: 75aeff0f31c3454f835e20bf3f9a2443
2025-05-16 15:42:09,276 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:09,293 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:09,295 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:09,296 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:09,297 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:11,844 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:11,844 - Experiment - INFO - Existing run ID: 75aeff0f31c3454f835e20bf3f9a2443
INFO:Experiment:Existing run ID: 75aeff0f31c3454f835e20bf3f9a2443
2025-05-16 15:42:11,981 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:11,983 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:11,998 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:12,000 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:12,001 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:12,002 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:13,995 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:13,995 - Experiment - INFO - Existing run ID: b253f3bc3c97417f91ae776fe46ce56c
INFO:Experiment:Existing run ID: b253f3bc3c97417f91ae776fe46ce56c
2025-05-16 15:42:13,995 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:14,016 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:14,018 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:14,019 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:14,020 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:15,980 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:15,980 - Experiment - INFO - Existing run ID: b253f3bc3c97417f91ae776fe46ce56c
INFO:Experiment:Existing run ID: b253f3bc3c97417f91ae776fe46ce56c
2025-05-16 15:42:16,119 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:16,120 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:16,136 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:16,138 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:16,140 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:16,141 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:18,168 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:18,168 - Experiment - INFO - Existing run ID: b0b89f040fc64ea693279210ccee8ee0
INFO:Experiment:Existing run ID: b0b89f040fc64ea693279210ccee8ee0
2025-05-16 15:42:18,168 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:18,188 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:18,189 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:18,190 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:18,191 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:20,192 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:20,192 - Experiment - INFO - Existing run ID: b0b89f040fc64ea693279210ccee8ee0
INFO:Experiment:Existing run ID: b0b89f040fc64ea693279210ccee8ee0
2025-05-16 15:42:20,344 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:20,346 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 1 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:20,365 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:20,366 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:20,367 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:20,368 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:22,383 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:22,383 - Experiment - INFO - Existing run ID: b205a95f5c234fdaaaea5c5f2f240bb3
INFO:Experiment:Existing run ID: b205a95f5c234fdaaaea5c5f2f240bb3
2025-05-16 15:42:22,383 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:22,402 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:22,403 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:22,405 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:22,406 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:25,051 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:25,051 - Experiment - INFO - Existing run ID: b205a95f5c234fdaaaea5c5f2f240bb3
INFO:Experiment:Existing run ID: b205a95f5c234fdaaaea5c5f2f240bb3
2025-05-16 15:42:25,203 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:25,203 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:25,220 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:25,222 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:25,223 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:25,224 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:27,306 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:27,306 - Experiment - INFO - Existing run ID: 55c6987e36ea436787796965d2e70423
INFO:Experiment:Existing run ID: 55c6987e36ea436787796965d2e70423
2025-05-16 15:42:27,308 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:27,320 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:27,321 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:27,323 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:27,324 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:29,456 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:29,472 - Experiment - INFO - Existing run ID: 55c6987e36ea436787796965d2e70423
INFO:Experiment:Existing run ID: 55c6987e36ea436787796965d2e70423
2025-05-16 15:42:29,586 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:29,602 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:29,617 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:29,618 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:29,619 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:29,620 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:31,662 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:31,662 - Experiment - INFO - Existing run ID: 219027de228540188f607a23161224b5
INFO:Experiment:Existing run ID: 219027de228540188f607a23161224b5
2025-05-16 15:42:31,662 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:31,685 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:31,687 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:31,688 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:31,689 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:33,889 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:33,893 - Experiment - INFO - Existing run ID: 219027de228540188f607a23161224b5
INFO:Experiment:Existing run ID: 219027de228540188f607a23161224b5
2025-05-16 15:42:34,186 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:34,186 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:34,207 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:34,209 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:34,211 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:34,212 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:36,400 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:36,400 - Experiment - INFO - Existing run ID: 83b19dda48144cc29d44c33bbe6fa77f
INFO:Experiment:Existing run ID: 83b19dda48144cc29d44c33bbe6fa77f
2025-05-16 15:42:36,400 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:36,420 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:36,422 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:36,423 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:36,424 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:38,437 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:38,437 - Experiment - INFO - Existing run ID: 83b19dda48144cc29d44c33bbe6fa77f
INFO:Experiment:Existing run ID: 83b19dda48144cc29d44c33bbe6fa77f
2025-05-16 15:42:38,587 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:38,587 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 1 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:38,605 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:38,606 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:38,607 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:38,608 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:40,671 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:40,671 - Experiment - INFO - Existing run ID: b9136f21ebca4b3897ce9e9c7ffd2c33
INFO:Experiment:Existing run ID: b9136f21ebca4b3897ce9e9c7ffd2c33
2025-05-16 15:42:40,671 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:40,692 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:40,693 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:40,695 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:40,695 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:42,689 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:42,689 - Experiment - INFO - Existing run ID: b9136f21ebca4b3897ce9e9c7ffd2c33
INFO:Experiment:Existing run ID: b9136f21ebca4b3897ce9e9c7ffd2c33
2025-05-16 15:42:42,820 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:42,820 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:42,850 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:42,851 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:42,852 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:42,853 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:44,868 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:44,868 - Experiment - INFO - Existing run ID: 9345159fb5be4532bfc130acf3534204
INFO:Experiment:Existing run ID: 9345159fb5be4532bfc130acf3534204
2025-05-16 15:42:44,868 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:44,882 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:44,883 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:44,885 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:44,887 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:46,888 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:46,888 - Experiment - INFO - Existing run ID: 9345159fb5be4532bfc130acf3534204
INFO:Experiment:Existing run ID: 9345159fb5be4532bfc130acf3534204
2025-05-16 15:42:47,020 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:47,020 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:47,049 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:47,050 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:47,052 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:47,053 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:49,329 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:49,345 - Experiment - INFO - Existing run ID: 31323945998f4b4faaa656d27a2b6e5e
INFO:Experiment:Existing run ID: 31323945998f4b4faaa656d27a2b6e5e
2025-05-16 15:42:49,345 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:49,355 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:49,357 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:49,358 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:49,359 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:51,331 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:51,331 - Experiment - INFO - Existing run ID: 31323945998f4b4faaa656d27a2b6e5e
INFO:Experiment:Existing run ID: 31323945998f4b4faaa656d27a2b6e5e
2025-05-16 15:42:51,481 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:51,482 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:51,497 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:51,499 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:51,500 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:51,502 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:53,513 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:53,513 - Experiment - INFO - Existing run ID: 15215fb6a8b84888b921c81397470f6a
INFO:Experiment:Existing run ID: 15215fb6a8b84888b921c81397470f6a
2025-05-16 15:42:53,513 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:53,533 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:53,535 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:53,537 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:53,537 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:55,594 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:42:55,594 - Experiment - INFO - Existing run ID: 15215fb6a8b84888b921c81397470f6a
INFO:Experiment:Existing run ID: 15215fb6a8b84888b921c81397470f6a
2025-05-16 15:42:55,735 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:55,735 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### Run 1 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:55,758 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:55,759 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:55,760 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:55,761 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:57,768 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:57,768 - Experiment - INFO - Existing run ID: 2d9a83602fe54f9ea27f98e79066af41
INFO:Experiment:Existing run ID: 2d9a83602fe54f9ea27f98e79066af41
2025-05-16 15:42:57,768 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:57,781 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:57,782 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:57,784 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:57,785 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:59,783 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:59,783 - Experiment - INFO - Existing run ID: 2d9a83602fe54f9ea27f98e79066af41
INFO:Experiment:Existing run ID: 2d9a83602fe54f9ea27f98e79066af41
2025-05-16 15:42:59,919 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:42:59,919 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:42:59,942 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:42:59,943 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:42:59,944 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:42:59,945 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:01,976 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:01,976 - Experiment - INFO - Existing run ID: 6d89176a1de34ca69ec4663f1794b332
INFO:Experiment:Existing run ID: 6d89176a1de34ca69ec4663f1794b332
2025-05-16 15:43:01,976 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:01,992 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:43:01,994 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:01,995 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:01,996 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:04,005 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:04,005 - Experiment - INFO - Existing run ID: 6d89176a1de34ca69ec4663f1794b332
INFO:Experiment:Existing run ID: 6d89176a1de34ca69ec4663f1794b332
2025-05-16 15:43:04,134 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:04,135 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:04,150 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:43:04,151 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:04,152 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:04,153 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:06,180 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:06,180 - Experiment - INFO - Existing run ID: ffc05d6faae04c0aa0f7a0336ecddd15
INFO:Experiment:Existing run ID: ffc05d6faae04c0aa0f7a0336ecddd15
2025-05-16 15:43:06,180 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:06,193 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:43:06,195 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:06,197 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:06,199 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:08,237 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:08,237 - Experiment - INFO - Existing run ID: ffc05d6faae04c0aa0f7a0336ecddd15
INFO:Experiment:Existing run ID: ffc05d6faae04c0aa0f7a0336ecddd15
2025-05-16 15:43:08,387 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:08,387 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:08,409 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:43:08,410 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:08,411 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:08,413 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:10,912 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:10,928 - Experiment - INFO - Existing run ID: 573b2e233d1f4fe68c12ccae7bd06f41
INFO:Experiment:Existing run ID: 573b2e233d1f4fe68c12ccae7bd06f41
2025-05-16 15:43:10,928 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:10,938 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
INFO:Experiment:MLflow experiment initialized with ID: 852930392549225895
2025-05-16 15:43:10,940 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:10,941 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:10,942 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:13,116 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:13,116 - Experiment - INFO - Existing run ID: 573b2e233d1f4fe68c12ccae7bd06f41
INFO:Experiment:Existing run ID: 573b2e233d1f4fe68c12ccae7bd06f41
2025-05-16 15:43:13,253 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:13,253 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

In [2]:
%cd ../distillibert
%run training.ipynb

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\workspace\notebooks\distillibert
Experiment: distillibert
Dataset Hyperparameters Grid Size:  8
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  8

### Run 1 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:13,601 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:13,602 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:13,603 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:13,604 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:32,167 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:32,167 - Experiment - INFO - Existing run ID: 543cc24c779d495ea8a48b3a9d35b764
INFO:Experiment:Existing run ID: 543cc24c779d495ea8a48b3a9d35b764
2025-05-16 15:43:32,167 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:32,181 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:32,182 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:32,183 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:32,184 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:33,660 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:33,660 - Experiment - INFO - Existing run ID: 543cc24c779d495ea8a48b3a9d35b764
INFO:Experiment:Existing run ID: 543cc24c779d495ea8a48b3a9d35b764
2025-05-16 15:43:33,781 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:33,782 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:33,797 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:33,798 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:33,800 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:33,801 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:35,279 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:35,279 - Experiment - INFO - Existing run ID: b45a2f7bbfd640fcbc6ffb7a61f76392
INFO:Experiment:Existing run ID: b45a2f7bbfd640fcbc6ffb7a61f76392
2025-05-16 15:43:35,279 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:35,299 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:35,300 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:35,300 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:35,301 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:36,920 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:36,922 - Experiment - INFO - Existing run ID: b45a2f7bbfd640fcbc6ffb7a61f76392
INFO:Experiment:Existing run ID: b45a2f7bbfd640fcbc6ffb7a61f76392
2025-05-16 15:43:37,065 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:37,067 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:37,083 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:37,084 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:37,085 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:37,086 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:38,641 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:38,641 - Experiment - INFO - Existing run ID: a8667e40ae5f4bd4850881a05c6a9417
INFO:Experiment:Existing run ID: a8667e40ae5f4bd4850881a05c6a9417
2025-05-16 15:43:38,655 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:38,666 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:38,667 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:38,668 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:38,669 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:40,309 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:40,309 - Experiment - INFO - Existing run ID: a8667e40ae5f4bd4850881a05c6a9417
INFO:Experiment:Existing run ID: a8667e40ae5f4bd4850881a05c6a9417
2025-05-16 15:43:40,428 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:40,428 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:40,458 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:40,460 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:40,461 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:40,464 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:41,996 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:41,996 - Experiment - INFO - Existing run ID: d0d8fbbf6c5b42108fdce0a1d75a2600
INFO:Experiment:Existing run ID: d0d8fbbf6c5b42108fdce0a1d75a2600
2025-05-16 15:43:41,996 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:42,017 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:42,018 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:42,019 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:42,020 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:43,572 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:43:43,572 - Experiment - INFO - Existing run ID: d0d8fbbf6c5b42108fdce0a1d75a2600
INFO:Experiment:Existing run ID: d0d8fbbf6c5b42108fdce0a1d75a2600
2025-05-16 15:43:43,695 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:43,695 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 5 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:43,716 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:43,717 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:43,718 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:43,720 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:45,392 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:45,392 - Experiment - INFO - Existing run ID: e0d1bd7a559449caa4dbf1e4f00a0655
INFO:Experiment:Existing run ID: e0d1bd7a559449caa4dbf1e4f00a0655
2025-05-16 15:43:45,392 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:45,414 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:45,416 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:45,418 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:45,419 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:47,181 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:47,181 - Experiment - INFO - Existing run ID: e0d1bd7a559449caa4dbf1e4f00a0655
INFO:Experiment:Existing run ID: e0d1bd7a559449caa4dbf1e4f00a0655
2025-05-16 15:43:47,326 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:47,327 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 6 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:47,342 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:47,343 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:47,344 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:47,345 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:48,958 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:48,958 - Experiment - INFO - Existing run ID: 92315196f327472ebfdf917ca0454640
INFO:Experiment:Existing run ID: 92315196f327472ebfdf917ca0454640
2025-05-16 15:43:48,958 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:48,979 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:48,982 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:48,984 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:48,986 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:50,779 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:43:50,779 - Experiment - INFO - Existing run ID: 92315196f327472ebfdf917ca0454640
INFO:Experiment:Existing run ID: 92315196f327472ebfdf917ca0454640
2025-05-16 15:43:50,894 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:50,894 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 7 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:50,921 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:50,922 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:50,923 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:50,924 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:52,533 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:52,544 - Experiment - INFO - Existing run ID: 8eb8e8174d334e0ba8a4eaa3a0073399
INFO:Experiment:Existing run ID: 8eb8e8174d334e0ba8a4eaa3a0073399
2025-05-16 15:43:52,545 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:52,556 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:52,557 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:52,558 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:52,559 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:54,516 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:54,516 - Experiment - INFO - Existing run ID: 8eb8e8174d334e0ba8a4eaa3a0073399
INFO:Experiment:Existing run ID: 8eb8e8174d334e0ba8a4eaa3a0073399
2025-05-16 15:43:54,644 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:54,645 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 8 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:54,661 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:54,662 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:54,664 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:54,665 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:56,193 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:56,209 - Experiment - INFO - Existing run ID: 2699cbf231cc40e29585d3baa107994c
INFO:Experiment:Existing run ID: 2699cbf231cc40e29585d3baa107994c
2025-05-16 15:43:56,209 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:56,222 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:56,222 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:56,225 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:56,225 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:57,796 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:43:57,796 - Experiment - INFO - Existing run ID: 2699cbf231cc40e29585d3baa107994c
INFO:Experiment:Existing run ID: 2699cbf231cc40e29585d3baa107994c
2025-05-16 15:43:57,943 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:43:57,943 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 1 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:57,962 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:57,964 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:57,965 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:57,966 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:59,522 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:59,522 - Experiment - INFO - Existing run ID: e504256ffe19417889534c2210303dcd
INFO:Experiment:Existing run ID: e504256ffe19417889534c2210303dcd
2025-05-16 15:43:59,522 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:43:59,536 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:43:59,538 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:43:59,539 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:43:59,540 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:01,384 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:01,384 - Experiment - INFO - Existing run ID: e504256ffe19417889534c2210303dcd
INFO:Experiment:Existing run ID: e504256ffe19417889534c2210303dcd
2025-05-16 15:44:01,516 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:01,518 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:01,534 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:01,535 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:01,535 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:01,536 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:03,167 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:03,167 - Experiment - INFO - Existing run ID: d7377cfff1df49b69e97f9336697dc2b
INFO:Experiment:Existing run ID: d7377cfff1df49b69e97f9336697dc2b
2025-05-16 15:44:03,167 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:03,180 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:03,181 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:03,183 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:03,184 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:04,861 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:04,861 - Experiment - INFO - Existing run ID: d7377cfff1df49b69e97f9336697dc2b
INFO:Experiment:Existing run ID: d7377cfff1df49b69e97f9336697dc2b
2025-05-16 15:44:04,994 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:04,994 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:05,024 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:05,025 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:05,027 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:05,028 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:06,865 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:06,865 - Experiment - INFO - Existing run ID: 9ca301e907b1433cb86908da2a2d9397
INFO:Experiment:Existing run ID: 9ca301e907b1433cb86908da2a2d9397
2025-05-16 15:44:06,865 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:06,880 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:06,881 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:06,884 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:06,885 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:08,925 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:08,925 - Experiment - INFO - Existing run ID: 9ca301e907b1433cb86908da2a2d9397
INFO:Experiment:Existing run ID: 9ca301e907b1433cb86908da2a2d9397
2025-05-16 15:44:09,094 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:09,094 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:09,118 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:09,119 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:09,121 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:09,122 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:11,004 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:11,004 - Experiment - INFO - Existing run ID: 56833a5627914f84874f1d1645090572
INFO:Experiment:Existing run ID: 56833a5627914f84874f1d1645090572
2025-05-16 15:44:11,004 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:11,023 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:11,024 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:11,025 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:11,025 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:12,611 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:12,611 - Experiment - INFO - Existing run ID: 56833a5627914f84874f1d1645090572
INFO:Experiment:Existing run ID: 56833a5627914f84874f1d1645090572
2025-05-16 15:44:12,751 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:12,752 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 5 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:12,766 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:12,766 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:12,767 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:12,768 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:14,382 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:14,382 - Experiment - INFO - Existing run ID: dd38a7cec0384680b2f80dd9e59a60f1
INFO:Experiment:Existing run ID: dd38a7cec0384680b2f80dd9e59a60f1
2025-05-16 15:44:14,382 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:14,397 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:14,398 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:14,399 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:14,401 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:16,185 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:16,185 - Experiment - INFO - Existing run ID: dd38a7cec0384680b2f80dd9e59a60f1
INFO:Experiment:Existing run ID: dd38a7cec0384680b2f80dd9e59a60f1
2025-05-16 15:44:16,323 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:16,325 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 6 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:16,338 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:16,341 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:16,342 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:16,343 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:18,066 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:18,066 - Experiment - INFO - Existing run ID: f5364c5a403549f385786c88a222a40c
INFO:Experiment:Existing run ID: f5364c5a403549f385786c88a222a40c
2025-05-16 15:44:18,076 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:18,081 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:18,097 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:18,099 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:18,099 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:19,637 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:19,637 - Experiment - INFO - Existing run ID: f5364c5a403549f385786c88a222a40c
INFO:Experiment:Existing run ID: f5364c5a403549f385786c88a222a40c
2025-05-16 15:44:19,785 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:19,786 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 7 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:19,802 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:19,803 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:19,804 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:19,804 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:21,687 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:21,687 - Experiment - INFO - Existing run ID: 0887126bc53b4ae4bb331263849f2972
INFO:Experiment:Existing run ID: 0887126bc53b4ae4bb331263849f2972
2025-05-16 15:44:21,703 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:21,713 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:21,714 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:21,716 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:21,716 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:23,561 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:23,565 - Experiment - INFO - Existing run ID: 0887126bc53b4ae4bb331263849f2972
INFO:Experiment:Existing run ID: 0887126bc53b4ae4bb331263849f2972
2025-05-16 15:44:23,710 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:23,710 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 8 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:23,730 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:23,731 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:23,732 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:23,733 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:25,469 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:25,470 - Experiment - INFO - Existing run ID: 6c580d701a664acb92f17e892ea23404
INFO:Experiment:Existing run ID: 6c580d701a664acb92f17e892ea23404
2025-05-16 15:44:25,472 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:25,481 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:25,482 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:25,483 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:25,484 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:27,410 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:27,410 - Experiment - INFO - Existing run ID: 6c580d701a664acb92f17e892ea23404
INFO:Experiment:Existing run ID: 6c580d701a664acb92f17e892ea23404
2025-05-16 15:44:27,548 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:27,549 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 1 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:27,565 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:27,567 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:27,569 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:27,570 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:29,318 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:29,319 - Experiment - INFO - Existing run ID: 429df52ddc6c496fb09dbddbd21e9337
INFO:Experiment:Existing run ID: 429df52ddc6c496fb09dbddbd21e9337
2025-05-16 15:44:29,321 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:29,333 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:29,334 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:29,335 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:29,336 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:30,967 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:30,967 - Experiment - INFO - Existing run ID: 429df52ddc6c496fb09dbddbd21e9337
INFO:Experiment:Existing run ID: 429df52ddc6c496fb09dbddbd21e9337
2025-05-16 15:44:31,110 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:31,112 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:31,125 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:31,127 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:31,128 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:31,130 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:32,710 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:32,710 - Experiment - INFO - Existing run ID: b504abfbc74047e6be92d6001ae6da8d
INFO:Experiment:Existing run ID: b504abfbc74047e6be92d6001ae6da8d
2025-05-16 15:44:32,726 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:32,736 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:32,737 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:32,738 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:32,739 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:34,288 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:34,288 - Experiment - INFO - Existing run ID: b504abfbc74047e6be92d6001ae6da8d
INFO:Experiment:Existing run ID: b504abfbc74047e6be92d6001ae6da8d
2025-05-16 15:44:34,435 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:34,437 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:34,451 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:34,452 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:34,454 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:34,455 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:35,985 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:35,985 - Experiment - INFO - Existing run ID: b0aef19b41854c9f91f57d39312ed295
INFO:Experiment:Existing run ID: b0aef19b41854c9f91f57d39312ed295
2025-05-16 15:44:35,985 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:36,005 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:36,006 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:36,008 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:36,009 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:37,630 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:37,630 - Experiment - INFO - Existing run ID: b0aef19b41854c9f91f57d39312ed295
INFO:Experiment:Existing run ID: b0aef19b41854c9f91f57d39312ed295
2025-05-16 15:44:37,791 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:37,791 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:37,806 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:37,807 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:37,808 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:37,809 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:39,506 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:39,508 - Experiment - INFO - Existing run ID: 9230e876026e4754995af5c080940e1c
INFO:Experiment:Existing run ID: 9230e876026e4754995af5c080940e1c
2025-05-16 15:44:39,509 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:39,519 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:39,521 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:39,522 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:39,523 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:41,120 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:44:41,120 - Experiment - INFO - Existing run ID: 9230e876026e4754995af5c080940e1c
INFO:Experiment:Existing run ID: 9230e876026e4754995af5c080940e1c
2025-05-16 15:44:41,282 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:41,284 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 5 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:41,300 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:41,302 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:41,303 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:41,304 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:42,878 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:42,878 - Experiment - INFO - Existing run ID: 623b40e4252e43bf87e87d87ab595403
INFO:Experiment:Existing run ID: 623b40e4252e43bf87e87d87ab595403
2025-05-16 15:44:42,878 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:42,897 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:42,898 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:42,900 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:42,901 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:44,580 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:44,587 - Experiment - INFO - Existing run ID: 623b40e4252e43bf87e87d87ab595403
INFO:Experiment:Existing run ID: 623b40e4252e43bf87e87d87ab595403
2025-05-16 15:44:44,726 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:44,727 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 6 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:44,743 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:44,744 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:44,745 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:44,747 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:46,360 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:46,360 - Experiment - INFO - Existing run ID: 4be78506bdb842989e1ff36b02a2d0b2
INFO:Experiment:Existing run ID: 4be78506bdb842989e1ff36b02a2d0b2
2025-05-16 15:44:46,360 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:46,384 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:46,386 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:46,387 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:46,388 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:48,044 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:44:48,044 - Experiment - INFO - Existing run ID: 4be78506bdb842989e1ff36b02a2d0b2
INFO:Experiment:Existing run ID: 4be78506bdb842989e1ff36b02a2d0b2
2025-05-16 15:44:48,194 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:48,196 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 7 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:48,209 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:48,211 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:48,212 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:48,213 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:50,163 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:50,163 - Experiment - INFO - Existing run ID: 2ae2b86ec66847c3b3e68047129f0e74
INFO:Experiment:Existing run ID: 2ae2b86ec66847c3b3e68047129f0e74
2025-05-16 15:44:50,179 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:50,191 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:50,192 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:50,194 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:50,195 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:51,896 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:51,898 - Experiment - INFO - Existing run ID: 2ae2b86ec66847c3b3e68047129f0e74
INFO:Experiment:Existing run ID: 2ae2b86ec66847c3b3e68047129f0e74
2025-05-16 15:44:52,060 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:52,062 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 8 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:52,075 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:52,076 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:52,077 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:52,078 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:53,723 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:53,730 - Experiment - INFO - Existing run ID: a80fe7e889794de5aa34fd124954bf17
INFO:Experiment:Existing run ID: a80fe7e889794de5aa34fd124954bf17
2025-05-16 15:44:53,730 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:53,741 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:53,742 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:53,743 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:53,744 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:55,499 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:44:55,499 - Experiment - INFO - Existing run ID: a80fe7e889794de5aa34fd124954bf17
INFO:Experiment:Existing run ID: a80fe7e889794de5aa34fd124954bf17
2025-05-16 15:44:55,655 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:55,657 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

Dataset Hyperparameters Grid Size:  8
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  8

### Run 1 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:55,676 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:55,677 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:55,678 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:55,680 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:57,274 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:57,274 - Experiment - INFO - Existing run ID: cffd1660cf5741b9bdca9406af475010
INFO:Experiment:Existing run ID: cffd1660cf5741b9bdca9406af475010
2025-05-16 15:44:57,290 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:57,300 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:57,301 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:57,302 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:57,302 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:58,867 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:58,867 - Experiment - INFO - Existing run ID: cffd1660cf5741b9bdca9406af475010
INFO:Experiment:Existing run ID: cffd1660cf5741b9bdca9406af475010
2025-05-16 15:44:59,002 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:44:59,004 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:44:59,017 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:44:59,018 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:44:59,019 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:44:59,020 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:45:00,585 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:45:00,594 - Experiment - INFO - Existing run ID: e75b933cc3d34a25afe9601119af15f8
INFO:Experiment:Existing run ID: e75b933cc3d34a25afe9601119af15f8
2025-05-16 15:45:00,594 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
INFO:Experiment:Skipping current experiment run, because run with same signature already exists.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:45:00,606 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:45:00,607 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:45:00,608 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:45:00,609 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:45:02,362 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:45:02,378 - Experiment - INFO - Existing run ID: e75b933cc3d34a25afe9601119af15f8
INFO:Experiment:Existing run ID: e75b933cc3d34a25afe9601119af15f8
2025-05-16 15:45:02,514 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:45:02,515 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...
INFO:Experiment:Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:45:02,530 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:45:02,530 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:45:02,532 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:45:02,532 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:45:04,477 - Experiment - INFO - Run ID: d834644566ae4d6987751b7b6a64e8e1
INFO:Experiment:Run ID: d834644566ae4d6987751b7b6a64e8e1
2025-05-16 15:45:04,477 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_15-45-04;rs=3599959477
INFO:Experiment:Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_15-45-04;rs=3599959477
2025-05-16 15:45:04,497 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
INFO:Experiment:{'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 15:45:04,529 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
INFO:Experiment:Prepared dataset does not exist, computing from scratch.
2025-05-16 15:45:04,661 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A12DFA7B0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000013A12D4B0B0>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000013A3BBEBAA0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A10F8B800>]>
INFO:Experiment:Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A12DFA7B0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000013A12D4B0B0>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000013A3BBEBAA0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A10F8B800>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 15:45:05,025 - Experiment - INFO - Preprocessing function 0: noise_reduction
INFO:Experiment:Preprocessing function 0: noise_reduction
2025-05-16 15:45:05,025 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:45:05,025 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:45:05,499 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:45:05,499 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:45:05,628 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:45:05,630 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 15:45:05,759 - Experiment - INFO - Preprocessing function 1: nltk_tokenizer
INFO:Experiment:Preprocessing function 1: nltk_tokenizer
2025-05-16 15:45:05,761 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:45:05,762 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:45:07,342 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:45:07,342 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:45:07,669 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:45:07,669 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:45:07,971 - Experiment - INFO - Preprocessing function 2: lemmatization
INFO:Experiment:Preprocessing function 2: lemmatization
2025-05-16 15:45:07,971 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:45:07,971 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:45:08,846 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:45:08,858 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:45:09,031 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:45:09,033 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:45:09,389 - Experiment - INFO - Preprocessing function 3: distilli_bert__encoder
INFO:Experiment:Preprocessing function 3: distilli_bert__encoder
2025-05-16 15:45:09,404 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:45:09,404 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:45:14,973 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:45:14,977 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:45:16,202 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:45:16,206 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:45:18,962 - Experiment - INFO - Model name: DistilliBERT
INFO:Experiment:Model name: DistilliBERT
2025-05-16 15:45:18,965 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
INFO:Experiment:Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 15:46:36,596 - Experiment - INFO - Evaluating model using accuracy metric...
INFO:Experiment:Evaluating model using accuracy metric...
2025-05-16 15:46:36,596 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-220
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-220
2025-05-16 15:46:36,801 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4134460687637329, 'eval_accuracy': 0.8993288590604027, 'eval_precision': 0.8936170212765957, 'eval_recall': 0.9438202247191011, 'eval_f1_score': 0.9180327868852459, 'eval_roc_auc': 0.9610486891385768, 'eval_false_positives_rate': 0.16666666666666666, 'eval_false_negatives_rate': 0.056179775280898875, 'eval_runtime': 0.6068, 'eval_samples_per_second': 245.551, 'eval_steps_per_second': 16.48, 'epoch': 5.0, 'step': 220}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.4134460687637329, 'eval_accuracy': 0.8993288590604027, 'eval_precision': 0.8936170212765957, 'eval_recall': 0.9438202247191011, 'eval_f1_score': 0.9180327868852459, 'eval_roc_auc': 0.9610486891385768, 'eval_false_positives_rate': 0.16666666666666666, 'eval_false_negatives_rate': 0.056179775280898875, 'eval_runtime': 0.6068, 'eval_samples_per_second': 245.551, 'eval_steps_per_second': 16.48, 'epoch': 5.0, 'step': 220}
2025-05-16 15:46:36,803 - Experiment - INFO - Best model found at epoch 5.0.
INFO:Experiment:Best model found at epoch 5.0.

2025-05-16 15:46:37,394 - Experiment - INFO - Test metrics: {'test_loss': 0.5901784300804138, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8837209302325582, 'test_recall': 0.8837209302325582, 'test_f1_score': 0.8837209302325582, 'test_roc_auc': 0.9182412790697674, 'test_false_positives_rate': 0.15625, 'test_false_negatives_rate': 0.11627906976744186, 'test_runtime': 0.5844, 'test_samples_per_second': 256.694, 'test_steps_per_second': 17.113, 'test_epoch': 5.0}
INFO:Experiment:Test metrics: {'test_loss': 0.5901784300804138, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8837209302325582, 'test_recall': 0.8837209302325582, 'test_f1_score': 0.8837209302325582, 'test_roc_auc': 0.9182412790697674, 'test_false_positives_rate': 0.15625, 'test_false_negatives_rate': 0.11627906976744186, 'test_runtime': 0.5844, 'test_samples_per_second': 256.694, 'test_steps_per_second': 17.113, 'test_epoch': 5.0}
2025-05-16 15:46:37,418 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:46:37,423 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:46:37,785 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:46:37,787 - Experiment - INFO - Evaluating model using precision metric...
INFO:Experiment:Evaluating model using precision metric...
2025-05-16 15:46:37,788 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:46:37,988 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.31857535243034363, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9390243902439024, 'eval_recall': 0.8651685393258427, 'eval_f1_score': 0.9005847953216374, 'eval_roc_auc': 0.946629213483146, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.1348314606741573, 'eval_runtime': 0.6135, 'eval_samples_per_second': 242.862, 'eval_steps_per_second': 16.299, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.31857535243034363, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9390243902439024, 'eval_recall': 0.8651685393258427, 'eval_f1_score': 0.9005847953216374, 'eval_roc_auc': 0.946629213483146, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.1348314606741573, 'eval_runtime': 0.6135, 'eval_samples_per_second': 242.862, 'eval_steps_per_second': 16.299, 'epoch': 3.0, 'step': 132}
2025-05-16 15:46:37,989 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:46:38,575 - Experiment - INFO - Test metrics: {'test_loss': 0.45653143525123596, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8674698795180723, 'test_recall': 0.8372093023255814, 'test_f1_score': 0.8520710059171598, 'test_roc_auc': 0.9029796511627907, 'test_false_positives_rate': 0.171875, 'test_false_negatives_rate': 0.16279069767441862, 'test_runtime': 0.5795, 'test_samples_per_second': 258.862, 'test_steps_per_second': 17.257, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.45653143525123596, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8674698795180723, 'test_recall': 0.8372093023255814, 'test_f1_score': 0.8520710059171598, 'test_roc_auc': 0.9029796511627907, 'test_false_positives_rate': 0.171875, 'test_false_negatives_rate': 0.16279069767441862, 'test_runtime': 0.5795, 'test_samples_per_second': 258.862, 'test_steps_per_second': 17.257, 'test_epoch': 3.0}
2025-05-16 15:46:38,596 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:46:38,602 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:46:38,964 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:46:38,965 - Experiment - INFO - Evaluating model using f1_score metric...
INFO:Experiment:Evaluating model using f1_score metric...
2025-05-16 15:46:38,966 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-220
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-220
2025-05-16 15:46:39,150 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4134460687637329, 'eval_accuracy': 0.8993288590604027, 'eval_precision': 0.8936170212765957, 'eval_recall': 0.9438202247191011, 'eval_f1_score': 0.9180327868852459, 'eval_roc_auc': 0.9610486891385768, 'eval_false_positives_rate': 0.16666666666666666, 'eval_false_negatives_rate': 0.056179775280898875, 'eval_runtime': 0.6068, 'eval_samples_per_second': 245.551, 'eval_steps_per_second': 16.48, 'epoch': 5.0, 'step': 220}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.4134460687637329, 'eval_accuracy': 0.8993288590604027, 'eval_precision': 0.8936170212765957, 'eval_recall': 0.9438202247191011, 'eval_f1_score': 0.9180327868852459, 'eval_roc_auc': 0.9610486891385768, 'eval_false_positives_rate': 0.16666666666666666, 'eval_false_negatives_rate': 0.056179775280898875, 'eval_runtime': 0.6068, 'eval_samples_per_second': 245.551, 'eval_steps_per_second': 16.48, 'epoch': 5.0, 'step': 220}
2025-05-16 15:46:39,152 - Experiment - INFO - Best model found at epoch 5.0.
INFO:Experiment:Best model found at epoch 5.0.

2025-05-16 15:46:39,731 - Experiment - INFO - Test metrics: {'test_loss': 0.5901784300804138, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8837209302325582, 'test_recall': 0.8837209302325582, 'test_f1_score': 0.8837209302325582, 'test_roc_auc': 0.9182412790697674, 'test_false_positives_rate': 0.15625, 'test_false_negatives_rate': 0.11627906976744186, 'test_runtime': 0.5743, 'test_samples_per_second': 261.205, 'test_steps_per_second': 17.414, 'test_epoch': 5.0}
INFO:Experiment:Test metrics: {'test_loss': 0.5901784300804138, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8837209302325582, 'test_recall': 0.8837209302325582, 'test_f1_score': 0.8837209302325582, 'test_roc_auc': 0.9182412790697674, 'test_false_positives_rate': 0.15625, 'test_false_negatives_rate': 0.11627906976744186, 'test_runtime': 0.5743, 'test_samples_per_second': 261.205, 'test_steps_per_second': 17.414, 'test_epoch': 5.0}
2025-05-16 15:46:39,749 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:46:39,754 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:46:40,129 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:46:40,131 - Experiment - INFO - Evaluating model using false_positives_rate metric...
INFO:Experiment:Evaluating model using false_positives_rate metric...
2025-05-16 15:46:40,132 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:46:40,395 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.31857535243034363, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9390243902439024, 'eval_recall': 0.8651685393258427, 'eval_f1_score': 0.9005847953216374, 'eval_roc_auc': 0.946629213483146, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.1348314606741573, 'eval_runtime': 0.6135, 'eval_samples_per_second': 242.862, 'eval_steps_per_second': 16.299, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.31857535243034363, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9390243902439024, 'eval_recall': 0.8651685393258427, 'eval_f1_score': 0.9005847953216374, 'eval_roc_auc': 0.946629213483146, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.1348314606741573, 'eval_runtime': 0.6135, 'eval_samples_per_second': 242.862, 'eval_steps_per_second': 16.299, 'epoch': 3.0, 'step': 132}
2025-05-16 15:46:40,397 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:46:40,991 - Experiment - INFO - Test metrics: {'test_loss': 0.45653143525123596, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8674698795180723, 'test_recall': 0.8372093023255814, 'test_f1_score': 0.8520710059171598, 'test_roc_auc': 0.9029796511627907, 'test_false_positives_rate': 0.171875, 'test_false_negatives_rate': 0.16279069767441862, 'test_runtime': 0.5877, 'test_samples_per_second': 255.226, 'test_steps_per_second': 17.015, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.45653143525123596, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8674698795180723, 'test_recall': 0.8372093023255814, 'test_f1_score': 0.8520710059171598, 'test_roc_auc': 0.9029796511627907, 'test_false_positives_rate': 0.171875, 'test_false_negatives_rate': 0.16279069767441862, 'test_runtime': 0.5877, 'test_samples_per_second': 255.226, 'test_steps_per_second': 17.015, 'test_epoch': 3.0}
2025-05-16 15:46:41,013 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:46:41,018 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:46:41,388 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:46:41,389 - Experiment - INFO - Evaluating model using roc_auc metric...
INFO:Experiment:Evaluating model using roc_auc metric...
2025-05-16 15:46:41,390 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-176
2025-05-16 15:46:41,594 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3427349328994751, 'eval_accuracy': 0.8926174496644296, 'eval_precision': 0.8842105263157894, 'eval_recall': 0.9438202247191011, 'eval_f1_score': 0.9130434782608695, 'eval_roc_auc': 0.9619850187265918, 'eval_false_positives_rate': 0.18333333333333332, 'eval_false_negatives_rate': 0.056179775280898875, 'eval_runtime': 0.5895, 'eval_samples_per_second': 252.75, 'eval_steps_per_second': 16.963, 'epoch': 4.0, 'step': 176}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.3427349328994751, 'eval_accuracy': 0.8926174496644296, 'eval_precision': 0.8842105263157894, 'eval_recall': 0.9438202247191011, 'eval_f1_score': 0.9130434782608695, 'eval_roc_auc': 0.9619850187265918, 'eval_false_positives_rate': 0.18333333333333332, 'eval_false_negatives_rate': 0.056179775280898875, 'eval_runtime': 0.5895, 'eval_samples_per_second': 252.75, 'eval_steps_per_second': 16.963, 'epoch': 4.0, 'step': 176}
2025-05-16 15:46:41,595 - Experiment - INFO - Best model found at epoch 4.0.
INFO:Experiment:Best model found at epoch 4.0.

2025-05-16 15:46:42,183 - Experiment - INFO - Test metrics: {'test_loss': 0.5105301737785339, 'test_accuracy': 0.8133333333333334, 'test_precision': 0.79, 'test_recall': 0.9186046511627907, 'test_f1_score': 0.8494623655913979, 'test_roc_auc': 0.9178779069767442, 'test_false_positives_rate': 0.328125, 'test_false_negatives_rate': 0.08139534883720931, 'test_runtime': 0.5811, 'test_samples_per_second': 258.143, 'test_steps_per_second': 17.21, 'test_epoch': 4.0}
INFO:Experiment:Test metrics: {'test_loss': 0.5105301737785339, 'test_accuracy': 0.8133333333333334, 'test_precision': 0.79, 'test_recall': 0.9186046511627907, 'test_f1_score': 0.8494623655913979, 'test_roc_auc': 0.9178779069767442, 'test_false_positives_rate': 0.328125, 'test_false_negatives_rate': 0.08139534883720931, 'test_runtime': 0.5811, 'test_samples_per_second': 258.143, 'test_steps_per_second': 17.21, 'test_epoch': 4.0}
2025-05-16 15:46:42,204 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:46:42,210 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:46:42,586 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:46:42,587 - Experiment - INFO - Evaluating model using loss metric...
INFO:Experiment:Evaluating model using loss metric...
2025-05-16 15:46:42,588 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:46:42,795 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.31857535243034363, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9390243902439024, 'eval_recall': 0.8651685393258427, 'eval_f1_score': 0.9005847953216374, 'eval_roc_auc': 0.946629213483146, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.1348314606741573, 'eval_runtime': 0.6135, 'eval_samples_per_second': 242.862, 'eval_steps_per_second': 16.299, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.31857535243034363, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9390243902439024, 'eval_recall': 0.8651685393258427, 'eval_f1_score': 0.9005847953216374, 'eval_roc_auc': 0.946629213483146, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.1348314606741573, 'eval_runtime': 0.6135, 'eval_samples_per_second': 242.862, 'eval_steps_per_second': 16.299, 'epoch': 3.0, 'step': 132}
2025-05-16 15:46:42,796 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:46:43,391 - Experiment - INFO - Test metrics: {'test_loss': 0.45653143525123596, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8674698795180723, 'test_recall': 0.8372093023255814, 'test_f1_score': 0.8520710059171598, 'test_roc_auc': 0.9029796511627907, 'test_false_positives_rate': 0.171875, 'test_false_negatives_rate': 0.16279069767441862, 'test_runtime': 0.5875, 'test_samples_per_second': 255.306, 'test_steps_per_second': 17.02, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.45653143525123596, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.8674698795180723, 'test_recall': 0.8372093023255814, 'test_f1_score': 0.8520710059171598, 'test_roc_auc': 0.9029796511627907, 'test_false_positives_rate': 0.171875, 'test_false_negatives_rate': 0.16279069767441862, 'test_runtime': 0.5875, 'test_samples_per_second': 255.306, 'test_steps_per_second': 17.02, 'test_epoch': 3.0}
2025-05-16 15:46:43,411 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:46:43,416 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:46:43,787 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:46:43,789 - Experiment - INFO - Finished model evaluations stage.
INFO:Experiment:Finished model evaluations stage.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:46:44,647 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:46:44,649 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:46:44,650 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:46:44,651 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:46:47,218 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:46:47,219 - Experiment - INFO - Existing run ID: d834644566ae4d6987751b7b6a64e8e1
INFO:Experiment:Existing run ID: d834644566ae4d6987751b7b6a64e8e1
2025-05-16 15:46:47,372 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:46:48,026 - Experiment - INFO - Pruning models artifacts done...
INFO:Experiment:Pruning models artifacts done...

### Run 4 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:46:48,047 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:46:48,048 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:46:48,050 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:46:48,051 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:46:50,554 - Experiment - INFO - Run ID: d94c2bb331734facb41099ca7cdb4668
INFO:Experiment:Run ID: d94c2bb331734facb41099ca7cdb4668
2025-05-16 15:46:50,555 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_15-46-50;rs=2673017686
INFO:Experiment:Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_15-46-50;rs=2673017686
2025-05-16 15:46:50,569 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
INFO:Experiment:{'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 15:46:50,611 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
INFO:Experiment:Prepared dataset does not exist, computing from scratch.
2025-05-16 15:46:50,729 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A11A8D340>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000013A11BA7C80>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000013A12DA4140>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA4A70>]>
INFO:Experiment:Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A11A8D340>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000013A11BA7C80>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000013A12DA4140>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA4A70>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 15:46:51,798 - Experiment - INFO - Preprocessing function 0: noise_reduction
INFO:Experiment:Preprocessing function 0: noise_reduction
2025-05-16 15:46:51,799 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:46:51,800 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:46:52,297 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:46:52,300 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:46:52,402 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:46:52,404 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 15:46:52,506 - Experiment - INFO - Preprocessing function 1: nltk_tokenizer
INFO:Experiment:Preprocessing function 1: nltk_tokenizer
2025-05-16 15:46:52,507 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:46:52,508 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:46:53,865 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:46:53,865 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:46:54,135 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:46:54,136 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:46:54,385 - Experiment - INFO - Preprocessing function 2: stemming
INFO:Experiment:Preprocessing function 2: stemming
2025-05-16 15:46:54,387 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:46:54,388 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: PolitikaIlustrace
warning: skipping word with mixed case: McKinley
warning: skipping word with mixed case: McKinley
warning: skipping word with mixed case: VelkoRusko
warning: skipping word with mixed case: svkMeZnPH
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: QiMLlGBjz
warning: skipping word with mixed case: jdInUhcutm
warning: skipping word with mixed case: ueqBIFUbyM
warning: skipping word with mixed case: HouškaV
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: FACs
warning: skipping word with mixed case: UAVs
warning: skipping word with mixed case: ProuvostDecember
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: qLCBuVdns
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: aODS
warning: skipping word with mixed case: RuSSáci
warning: skipping word with mixed case: iportaL
warning: skipping word with mixed case: iportaL
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: NLujLXkmQ
warning: skipping word with mixed case: McChicken
warning: skipping word with mixed case: jvbXUwDjc
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: ProtiproudTV
warning: skipping word with mixed case: SMERu
warning: skipping word with mixed case: TeamUkraine
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: weeoOEKcP
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: NordStream
warning: skipping word with mixed case: NordStream
warning: skipping word with mixed case: NordStreamu
warning: skipping word with mixed case: AlJazeera
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: GAZPROMu
warning: skipping word with mixed case: iCloudu
warning: skipping word with mixed case: iPhonu
warning: skipping word with mixed case: iPhone
warning: skipping word with mixed case: iCloud
warning: skipping word with mixed case: iPhonu
warning: skipping word with mixed case: iCloud
warning: skipping word with mixed case: KiLJURyqj
warning: skipping word with mixed case: OvYkxqdJr
warning: skipping word with mixed case: BBCWillVernon
warning: skipping word with mixed case: iportaL
warning: skipping word with mixed case: JPMorgan
warning: skipping word with mixed case: ParlamentnímListům
warning: skipping word with mixed case: iDNES
warning: skipping word with mixed case: PrahaIN
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: kV
warning: skipping word with mixed case: DeepL
warning: skipping word with mixed case: yhYZeissQb
warning: skipping word with mixed case: FNQpqAj
warning: skipping word with mixed case: KWh
warning: skipping word with mixed case: KWh
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: ParlamentníListy
warning: skipping word with mixed case: InoSMI
warning: skipping word with mixed case: SudRadio
warning: skipping word with mixed case: SudRadia
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: ParlamentníListy
warning: skipping word with mixed case: PhDr
warning: skipping word with mixed case: SPOLUobčané
warning: skipping word with mixed case: oCxcRRwKl
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: sikorskiRadek
warning: skipping word with mixed case: GAZPROMu
warning: skipping word with mixed case: iCloudu
warning: skipping word with mixed case: iPhonu
warning: skipping word with mixed case: iPhone
warning: skipping word with mixed case: iCloud
warning: skipping word with mixed case: iPhonu
warning: skipping word with mixed case: iCloud
warning: skipping word with mixed case: kW
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: DeLuca
warning: skipping word with mixed case: DeLuca
warning: skipping word with mixed case: DMcuBPKUj
warning: skipping word with mixed case: KSČíny
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: DShK
warning: skipping word with mixed case: BellingCat
warning: skipping word with mixed case: RiP
warning: skipping word with mixed case: MichalKubal
warning: skipping word with mixed case: JPMorgan
warning: skipping word with mixed case: PrisonPlanet
warning: skipping word with mixed case: PhDr
warning: skipping word with mixed case: ArmUkraineNow
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: sVDMmb
warning: skipping word with mixed case: StratcomCentre
warning: skipping word with mixed case: SwedishPM
warning: skipping word with mixed case: mMztqsJRQT
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: vRZVPINNiX
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: QsRsXmnJ
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: hzeEh
warning: skipping word with mixed case: MinColonna
warning: skipping word with mixed case: xbEvtzzm
warning: skipping word with mixed case: BelTA
warning: skipping word with mixed case: BelTA
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: GRTgaz
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: EURa
warning: skipping word with mixed case: KrAZ
warning: skipping word with mixed case: WFmrAdBZ
warning: skipping word with mixed case: RWApodcast
warning: skipping word with mixed case: ParlamentníListy
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: ZvsgC
warning: skipping word with mixed case: kOXEJFeHj
warning: skipping word with mixed case: YXpleSIp
warning: skipping word with mixed case: PolitRussia
warning: skipping word with mixed case: LONGi
warning: skipping word with mixed case: jtkSidjpX
warning: skipping word with mixed case: ZDjqiwFMb
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: GYFPXwFpsp
warning: skipping word with mixed case: bcJGNajX
warning: skipping word with mixed case: LibkošObyvatelé
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: iZTdGDa
warning: skipping word with mixed case: MUDr
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: ParlamentníListy
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: antiRusko
warning: skipping word with mixed case: LightRocket
warning: skipping word with mixed case: OSPODu
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: MeToo
warning: skipping word with mixed case: PiS
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: mRNA
warning: skipping word with mixed case: CoV
warning: skipping word with mixed case: mRNA
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitiFor
warning: skipping word with mixed case: ZelenskyyUa
warning: skipping word with mixed case: zkcQcrv
warning: skipping word with mixed case: LONGi
warning: skipping word with mixed case: LNAGYgCK
warning: skipping word with mixed case: PhD
warning: skipping word with mixed case: TikToku
warning: skipping word with mixed case: TikToku
warning: skipping word with mixed case: TikToku
warning: skipping word with mixed case: iPhonech
warning: skipping word with mixed case: MaxxPro
warning: skipping word with mixed case: mírUkrajině
warning: skipping word with mixed case: vícTo
warning: skipping word with mixed case: líbíOkomentovatSdílet
warning: skipping word with mixed case: PepsiCo
warning: skipping word with mixed case: TOPky
warning: skipping word with mixed case: MafiánStan
warning: skipping word with mixed case: ViktoriaGruppe
warning: skipping word with mixed case: BorisJohnson
warning: skipping word with mixed case: FMzemenYY
warning: skipping word with mixed case: EleZYZwTa
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: EADaily
warning: skipping word with mixed case: ParlamentníListy
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: sfNcHdxwZ
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: EavdZJspc
warning: skipping word with mixed case: OpenCard
warning: skipping word with mixed case: SpaceX
warning: skipping word with mixed case: ZeGoebels
warning: skipping word with mixed case: SpaceX
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: AntiDiplomatico
warning: skipping word with mixed case: JHa
warning: skipping word with mixed case: PhDr
warning: skipping word with mixed case: PaeDr
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: WeChat
warning: skipping word with mixed case: WeChat
warning: skipping word with mixed case: YouTube

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:47:02,586 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:47:02,598 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:47:03,823 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:47:03,826 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:47:06,744 - Experiment - INFO - Model name: DistilliBERT
INFO:Experiment:Model name: DistilliBERT
2025-05-16 15:47:06,749 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
INFO:Experiment:Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 15:48:07,198 - Experiment - INFO - Evaluating model using accuracy metric...
INFO:Experiment:Evaluating model using accuracy metric...
2025-05-16 15:48:07,198 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-176
2025-05-16 15:48:07,389 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5714709758758545, 'eval_accuracy': 0.8322147651006712, 'eval_precision': 0.8586956521739131, 'eval_recall': 0.8681318681318682, 'eval_f1_score': 0.8633879781420765, 'eval_roc_auc': 0.8969306555513452, 'eval_false_positives_rate': 0.22413793103448276, 'eval_false_negatives_rate': 0.13186813186813187, 'eval_runtime': 0.5921, 'eval_samples_per_second': 251.629, 'eval_steps_per_second': 16.888, 'epoch': 4.0, 'step': 176}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.5714709758758545, 'eval_accuracy': 0.8322147651006712, 'eval_precision': 0.8586956521739131, 'eval_recall': 0.8681318681318682, 'eval_f1_score': 0.8633879781420765, 'eval_roc_auc': 0.8969306555513452, 'eval_false_positives_rate': 0.22413793103448276, 'eval_false_negatives_rate': 0.13186813186813187, 'eval_runtime': 0.5921, 'eval_samples_per_second': 251.629, 'eval_steps_per_second': 16.888, 'epoch': 4.0, 'step': 176}
2025-05-16 15:48:07,389 - Experiment - INFO - Best model found at epoch 4.0.
INFO:Experiment:Best model found at epoch 4.0.

2025-05-16 15:48:07,945 - Experiment - INFO - Test metrics: {'test_loss': 0.5347694158554077, 'test_accuracy': 0.8533333333333334, 'test_precision': 0.9081632653061225, 'test_recall': 0.8725490196078431, 'test_f1_score': 0.89, 'test_roc_auc': 0.9150326797385621, 'test_false_positives_rate': 0.1875, 'test_false_negatives_rate': 0.12745098039215685, 'test_runtime': 0.5566, 'test_samples_per_second': 269.473, 'test_steps_per_second': 17.965, 'test_epoch': 4.0}
INFO:Experiment:Test metrics: {'test_loss': 0.5347694158554077, 'test_accuracy': 0.8533333333333334, 'test_precision': 0.9081632653061225, 'test_recall': 0.8725490196078431, 'test_f1_score': 0.89, 'test_roc_auc': 0.9150326797385621, 'test_false_positives_rate': 0.1875, 'test_false_negatives_rate': 0.12745098039215685, 'test_runtime': 0.5566, 'test_samples_per_second': 269.473, 'test_steps_per_second': 17.965, 'test_epoch': 4.0}
2025-05-16 15:48:07,977 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:48:07,977 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:48:08,303 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:48:08,303 - Experiment - INFO - Evaluating model using precision metric...
INFO:Experiment:Evaluating model using precision metric...
2025-05-16 15:48:08,303 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-220
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-220
2025-05-16 15:48:08,476 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7596588134765625, 'eval_accuracy': 0.7986577181208053, 'eval_precision': 0.8961038961038961, 'eval_recall': 0.7582417582417582, 'eval_f1_score': 0.8214285714285714, 'eval_roc_auc': 0.9120879120879121, 'eval_false_positives_rate': 0.13793103448275862, 'eval_false_negatives_rate': 0.24175824175824176, 'eval_runtime': 0.5657, 'eval_samples_per_second': 263.411, 'eval_steps_per_second': 17.679, 'epoch': 5.0, 'step': 220}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.7596588134765625, 'eval_accuracy': 0.7986577181208053, 'eval_precision': 0.8961038961038961, 'eval_recall': 0.7582417582417582, 'eval_f1_score': 0.8214285714285714, 'eval_roc_auc': 0.9120879120879121, 'eval_false_positives_rate': 0.13793103448275862, 'eval_false_negatives_rate': 0.24175824175824176, 'eval_runtime': 0.5657, 'eval_samples_per_second': 263.411, 'eval_steps_per_second': 17.679, 'epoch': 5.0, 'step': 220}
2025-05-16 15:48:08,476 - Experiment - INFO - Best model found at epoch 5.0.
INFO:Experiment:Best model found at epoch 5.0.

2025-05-16 15:48:09,062 - Experiment - INFO - Test metrics: {'test_loss': 0.7761148810386658, 'test_accuracy': 0.7933333333333333, 'test_precision': 0.9493670886075949, 'test_recall': 0.7352941176470589, 'test_f1_score': 0.8287292817679558, 'test_roc_auc': 0.9219771241830065, 'test_false_positives_rate': 0.08333333333333333, 'test_false_negatives_rate': 0.2647058823529412, 'test_runtime': 0.5856, 'test_samples_per_second': 256.133, 'test_steps_per_second': 17.076, 'test_epoch': 5.0}
INFO:Experiment:Test metrics: {'test_loss': 0.7761148810386658, 'test_accuracy': 0.7933333333333333, 'test_precision': 0.9493670886075949, 'test_recall': 0.7352941176470589, 'test_f1_score': 0.8287292817679558, 'test_roc_auc': 0.9219771241830065, 'test_false_positives_rate': 0.08333333333333333, 'test_false_negatives_rate': 0.2647058823529412, 'test_runtime': 0.5856, 'test_samples_per_second': 256.133, 'test_steps_per_second': 17.076, 'test_epoch': 5.0}
2025-05-16 15:48:09,080 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:48:09,080 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:48:09,446 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:48:09,446 - Experiment - INFO - Evaluating model using f1_score metric...
INFO:Experiment:Evaluating model using f1_score metric...
2025-05-16 15:48:09,446 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:48:09,668 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5252124071121216, 'eval_accuracy': 0.8187919463087249, 'eval_precision': 0.7758620689655172, 'eval_recall': 0.989010989010989, 'eval_f1_score': 0.8695652173913043, 'eval_roc_auc': 0.8899204244031831, 'eval_false_positives_rate': 0.4482758620689655, 'eval_false_negatives_rate': 0.01098901098901099, 'eval_runtime': 1.7933, 'eval_samples_per_second': 83.085, 'eval_steps_per_second': 5.576, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.5252124071121216, 'eval_accuracy': 0.8187919463087249, 'eval_precision': 0.7758620689655172, 'eval_recall': 0.989010989010989, 'eval_f1_score': 0.8695652173913043, 'eval_roc_auc': 0.8899204244031831, 'eval_false_positives_rate': 0.4482758620689655, 'eval_false_negatives_rate': 0.01098901098901099, 'eval_runtime': 1.7933, 'eval_samples_per_second': 83.085, 'eval_steps_per_second': 5.576, 'epoch': 3.0, 'step': 132}
2025-05-16 15:48:09,668 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:48:10,262 - Experiment - INFO - Test metrics: {'test_loss': 0.5357303619384766, 'test_accuracy': 0.82, 'test_precision': 0.7906976744186046, 'test_recall': 1.0, 'test_f1_score': 0.8831168831168831, 'test_roc_auc': 0.8958333333333333, 'test_false_positives_rate': 0.5625, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5937, 'test_samples_per_second': 252.647, 'test_steps_per_second': 16.843, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.5357303619384766, 'test_accuracy': 0.82, 'test_precision': 0.7906976744186046, 'test_recall': 1.0, 'test_f1_score': 0.8831168831168831, 'test_roc_auc': 0.8958333333333333, 'test_false_positives_rate': 0.5625, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.5937, 'test_samples_per_second': 252.647, 'test_steps_per_second': 16.843, 'test_epoch': 3.0}
2025-05-16 15:48:10,293 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:48:10,293 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:48:10,626 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:48:10,626 - Experiment - INFO - Evaluating model using false_positives_rate metric...
INFO:Experiment:Evaluating model using false_positives_rate metric...
2025-05-16 15:48:10,626 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-220
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-220
2025-05-16 15:48:10,805 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7596588134765625, 'eval_accuracy': 0.7986577181208053, 'eval_precision': 0.8961038961038961, 'eval_recall': 0.7582417582417582, 'eval_f1_score': 0.8214285714285714, 'eval_roc_auc': 0.9120879120879121, 'eval_false_positives_rate': 0.13793103448275862, 'eval_false_negatives_rate': 0.24175824175824176, 'eval_runtime': 0.5657, 'eval_samples_per_second': 263.411, 'eval_steps_per_second': 17.679, 'epoch': 5.0, 'step': 220}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.7596588134765625, 'eval_accuracy': 0.7986577181208053, 'eval_precision': 0.8961038961038961, 'eval_recall': 0.7582417582417582, 'eval_f1_score': 0.8214285714285714, 'eval_roc_auc': 0.9120879120879121, 'eval_false_positives_rate': 0.13793103448275862, 'eval_false_negatives_rate': 0.24175824175824176, 'eval_runtime': 0.5657, 'eval_samples_per_second': 263.411, 'eval_steps_per_second': 17.679, 'epoch': 5.0, 'step': 220}
2025-05-16 15:48:10,805 - Experiment - INFO - Best model found at epoch 5.0.
INFO:Experiment:Best model found at epoch 5.0.

2025-05-16 15:48:11,385 - Experiment - INFO - Test metrics: {'test_loss': 0.7761148810386658, 'test_accuracy': 0.7933333333333333, 'test_precision': 0.9493670886075949, 'test_recall': 0.7352941176470589, 'test_f1_score': 0.8287292817679558, 'test_roc_auc': 0.9219771241830065, 'test_false_positives_rate': 0.08333333333333333, 'test_false_negatives_rate': 0.2647058823529412, 'test_runtime': 0.58, 'test_samples_per_second': 258.628, 'test_steps_per_second': 17.242, 'test_epoch': 5.0}
INFO:Experiment:Test metrics: {'test_loss': 0.7761148810386658, 'test_accuracy': 0.7933333333333333, 'test_precision': 0.9493670886075949, 'test_recall': 0.7352941176470589, 'test_f1_score': 0.8287292817679558, 'test_roc_auc': 0.9219771241830065, 'test_false_positives_rate': 0.08333333333333333, 'test_false_negatives_rate': 0.2647058823529412, 'test_runtime': 0.58, 'test_samples_per_second': 258.628, 'test_steps_per_second': 17.242, 'test_epoch': 5.0}
2025-05-16 15:48:11,401 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:48:11,401 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:48:11,770 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:48:11,770 - Experiment - INFO - Evaluating model using roc_auc metric...
INFO:Experiment:Evaluating model using roc_auc metric...
2025-05-16 15:48:11,770 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-220
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-220
2025-05-16 15:48:11,939 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7596588134765625, 'eval_accuracy': 0.7986577181208053, 'eval_precision': 0.8961038961038961, 'eval_recall': 0.7582417582417582, 'eval_f1_score': 0.8214285714285714, 'eval_roc_auc': 0.9120879120879121, 'eval_false_positives_rate': 0.13793103448275862, 'eval_false_negatives_rate': 0.24175824175824176, 'eval_runtime': 0.5657, 'eval_samples_per_second': 263.411, 'eval_steps_per_second': 17.679, 'epoch': 5.0, 'step': 220}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.7596588134765625, 'eval_accuracy': 0.7986577181208053, 'eval_precision': 0.8961038961038961, 'eval_recall': 0.7582417582417582, 'eval_f1_score': 0.8214285714285714, 'eval_roc_auc': 0.9120879120879121, 'eval_false_positives_rate': 0.13793103448275862, 'eval_false_negatives_rate': 0.24175824175824176, 'eval_runtime': 0.5657, 'eval_samples_per_second': 263.411, 'eval_steps_per_second': 17.679, 'epoch': 5.0, 'step': 220}
2025-05-16 15:48:11,939 - Experiment - INFO - Best model found at epoch 5.0.
INFO:Experiment:Best model found at epoch 5.0.

2025-05-16 15:48:12,517 - Experiment - INFO - Test metrics: {'test_loss': 0.7761148810386658, 'test_accuracy': 0.7933333333333333, 'test_precision': 0.9493670886075949, 'test_recall': 0.7352941176470589, 'test_f1_score': 0.8287292817679558, 'test_roc_auc': 0.9219771241830065, 'test_false_positives_rate': 0.08333333333333333, 'test_false_negatives_rate': 0.2647058823529412, 'test_runtime': 0.5649, 'test_samples_per_second': 265.546, 'test_steps_per_second': 17.703, 'test_epoch': 5.0}
INFO:Experiment:Test metrics: {'test_loss': 0.7761148810386658, 'test_accuracy': 0.7933333333333333, 'test_precision': 0.9493670886075949, 'test_recall': 0.7352941176470589, 'test_f1_score': 0.8287292817679558, 'test_roc_auc': 0.9219771241830065, 'test_false_positives_rate': 0.08333333333333333, 'test_false_negatives_rate': 0.2647058823529412, 'test_runtime': 0.5649, 'test_samples_per_second': 265.546, 'test_steps_per_second': 17.703, 'test_epoch': 5.0}
2025-05-16 15:48:12,540 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:48:12,540 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:48:12,884 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:48:12,884 - Experiment - INFO - Evaluating model using loss metric...
INFO:Experiment:Evaluating model using loss metric...
2025-05-16 15:48:12,889 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-88
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-88
2025-05-16 15:48:13,079 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.45619702339172363, 'eval_accuracy': 0.8187919463087249, 'eval_precision': 0.8076923076923077, 'eval_recall': 0.9230769230769231, 'eval_f1_score': 0.8615384615384616, 'eval_roc_auc': 0.8637741568776052, 'eval_false_positives_rate': 0.3448275862068966, 'eval_false_negatives_rate': 0.07692307692307693, 'eval_runtime': 0.5754, 'eval_samples_per_second': 258.94, 'eval_steps_per_second': 17.379, 'epoch': 2.0, 'step': 88}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.45619702339172363, 'eval_accuracy': 0.8187919463087249, 'eval_precision': 0.8076923076923077, 'eval_recall': 0.9230769230769231, 'eval_f1_score': 0.8615384615384616, 'eval_roc_auc': 0.8637741568776052, 'eval_false_positives_rate': 0.3448275862068966, 'eval_false_negatives_rate': 0.07692307692307693, 'eval_runtime': 0.5754, 'eval_samples_per_second': 258.94, 'eval_steps_per_second': 17.379, 'epoch': 2.0, 'step': 88}
2025-05-16 15:48:13,079 - Experiment - INFO - Best model found at epoch 2.0.
INFO:Experiment:Best model found at epoch 2.0.

2025-05-16 15:48:13,652 - Experiment - INFO - Test metrics: {'test_loss': 0.4370245337486267, 'test_accuracy': 0.84, 'test_precision': 0.8362068965517241, 'test_recall': 0.9509803921568627, 'test_f1_score': 0.8899082568807339, 'test_roc_auc': 0.8790849673202614, 'test_false_positives_rate': 0.3958333333333333, 'test_false_negatives_rate': 0.049019607843137254, 'test_runtime': 0.573, 'test_samples_per_second': 261.774, 'test_steps_per_second': 17.452, 'test_epoch': 2.0}
INFO:Experiment:Test metrics: {'test_loss': 0.4370245337486267, 'test_accuracy': 0.84, 'test_precision': 0.8362068965517241, 'test_recall': 0.9509803921568627, 'test_f1_score': 0.8899082568807339, 'test_roc_auc': 0.8790849673202614, 'test_false_positives_rate': 0.3958333333333333, 'test_false_negatives_rate': 0.049019607843137254, 'test_runtime': 0.573, 'test_samples_per_second': 261.774, 'test_steps_per_second': 17.452, 'test_epoch': 2.0}
2025-05-16 15:48:13,668 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:48:13,668 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:48:14,016 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:48:14,016 - Experiment - INFO - Finished model evaluations stage.
INFO:Experiment:Finished model evaluations stage.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:48:14,294 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:48:14,294 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:48:14,294 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:48:14,294 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:48:16,814 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 15:48:16,814 - Experiment - INFO - Existing run ID: d94c2bb331734facb41099ca7cdb4668
INFO:Experiment:Existing run ID: d94c2bb331734facb41099ca7cdb4668
2025-05-16 15:48:16,956 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:48:17,361 - Experiment - INFO - Pruning models artifacts done...
INFO:Experiment:Pruning models artifacts done...

### Run 5 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:48:17,379 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:48:17,381 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:48:17,382 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:48:17,383 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:48:19,191 - Experiment - INFO - Run ID: dc8d86e812b948b0947960bd7c280cde
INFO:Experiment:Run ID: dc8d86e812b948b0947960bd7c280cde
2025-05-16 15:48:19,191 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)]);2025-05-16_15-48-19;rs=3026648893
INFO:Experiment:Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)]);2025-05-16_15-48-19;rs=3026648893
2025-05-16 15:48:19,207 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
INFO:Experiment:{'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 15:48:19,215 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
INFO:Experiment:Prepared dataset does not exist, computing from scratch.
2025-05-16 15:48:19,310 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA61E0>]>
INFO:Experiment:Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA61E0>]>
2025-05-16 15:48:19,668 - Experiment - INFO - Preprocessing function 0: distilli_bert__encoder
INFO:Experiment:Preprocessing function 0: distilli_bert__encoder
2025-05-16 15:48:19,668 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:48:19,668 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:48:23,031 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:48:23,031 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:48:23,799 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:48:23,799 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:48:26,363 - Experiment - INFO - Model name: DistilliBERT
INFO:Experiment:Model name: DistilliBERT
2025-05-16 15:48:26,375 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
INFO:Experiment:Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 15:50:03,409 - Experiment - INFO - Evaluating model using accuracy metric...
INFO:Experiment:Evaluating model using accuracy metric...
2025-05-16 15:50:03,409 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:50:03,609 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.21152588725090027, 'eval_accuracy': 0.9395973154362416, 'eval_precision': 0.9655172413793104, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9491525423728814, 'eval_roc_auc': 0.9623352165725048, 'eval_false_positives_rate': 0.05084745762711865, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 1.1286, 'eval_samples_per_second': 132.022, 'eval_steps_per_second': 8.861, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.21152588725090027, 'eval_accuracy': 0.9395973154362416, 'eval_precision': 0.9655172413793104, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9491525423728814, 'eval_roc_auc': 0.9623352165725048, 'eval_false_positives_rate': 0.05084745762711865, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 1.1286, 'eval_samples_per_second': 132.022, 'eval_steps_per_second': 8.861, 'epoch': 3.0, 'step': 132}
2025-05-16 15:50:03,609 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:50:04,755 - Experiment - INFO - Test metrics: {'test_loss': 0.2527039051055908, 'test_accuracy': 0.9266666666666666, 'test_precision': 0.9560439560439561, 'test_recall': 0.925531914893617, 'test_f1_score': 0.9405405405405406, 'test_roc_auc': 0.9481382978723404, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.07446808510638298, 'test_runtime': 1.1455, 'test_samples_per_second': 130.946, 'test_steps_per_second': 8.73, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.2527039051055908, 'test_accuracy': 0.9266666666666666, 'test_precision': 0.9560439560439561, 'test_recall': 0.925531914893617, 'test_f1_score': 0.9405405405405406, 'test_roc_auc': 0.9481382978723404, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.07446808510638298, 'test_runtime': 1.1455, 'test_samples_per_second': 130.946, 'test_steps_per_second': 8.73, 'test_epoch': 3.0}
2025-05-16 15:50:04,775 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:50:04,780 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:50:05,143 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:50:05,145 - Experiment - INFO - Evaluating model using precision metric...
INFO:Experiment:Evaluating model using precision metric...
2025-05-16 15:50:05,147 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:50:05,355 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.21152588725090027, 'eval_accuracy': 0.9395973154362416, 'eval_precision': 0.9655172413793104, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9491525423728814, 'eval_roc_auc': 0.9623352165725048, 'eval_false_positives_rate': 0.05084745762711865, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 1.1286, 'eval_samples_per_second': 132.022, 'eval_steps_per_second': 8.861, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.21152588725090027, 'eval_accuracy': 0.9395973154362416, 'eval_precision': 0.9655172413793104, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9491525423728814, 'eval_roc_auc': 0.9623352165725048, 'eval_false_positives_rate': 0.05084745762711865, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 1.1286, 'eval_samples_per_second': 132.022, 'eval_steps_per_second': 8.861, 'epoch': 3.0, 'step': 132}
2025-05-16 15:50:05,355 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:50:06,507 - Experiment - INFO - Test metrics: {'test_loss': 0.2527039051055908, 'test_accuracy': 0.9266666666666666, 'test_precision': 0.9560439560439561, 'test_recall': 0.925531914893617, 'test_f1_score': 0.9405405405405406, 'test_roc_auc': 0.9481382978723404, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.07446808510638298, 'test_runtime': 1.1513, 'test_samples_per_second': 130.285, 'test_steps_per_second': 8.686, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.2527039051055908, 'test_accuracy': 0.9266666666666666, 'test_precision': 0.9560439560439561, 'test_recall': 0.925531914893617, 'test_f1_score': 0.9405405405405406, 'test_roc_auc': 0.9481382978723404, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.07446808510638298, 'test_runtime': 1.1513, 'test_samples_per_second': 130.285, 'test_steps_per_second': 8.686, 'test_epoch': 3.0}
2025-05-16 15:50:06,529 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:50:06,533 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:50:06,906 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:50:06,906 - Experiment - INFO - Evaluating model using f1_score metric...
INFO:Experiment:Evaluating model using f1_score metric...
2025-05-16 15:50:06,906 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:50:07,091 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.21152588725090027, 'eval_accuracy': 0.9395973154362416, 'eval_precision': 0.9655172413793104, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9491525423728814, 'eval_roc_auc': 0.9623352165725048, 'eval_false_positives_rate': 0.05084745762711865, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 1.1286, 'eval_samples_per_second': 132.022, 'eval_steps_per_second': 8.861, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.21152588725090027, 'eval_accuracy': 0.9395973154362416, 'eval_precision': 0.9655172413793104, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9491525423728814, 'eval_roc_auc': 0.9623352165725048, 'eval_false_positives_rate': 0.05084745762711865, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 1.1286, 'eval_samples_per_second': 132.022, 'eval_steps_per_second': 8.861, 'epoch': 3.0, 'step': 132}
2025-05-16 15:50:07,091 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:50:08,244 - Experiment - INFO - Test metrics: {'test_loss': 0.2527039051055908, 'test_accuracy': 0.9266666666666666, 'test_precision': 0.9560439560439561, 'test_recall': 0.925531914893617, 'test_f1_score': 0.9405405405405406, 'test_roc_auc': 0.9481382978723404, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.07446808510638298, 'test_runtime': 1.1497, 'test_samples_per_second': 130.466, 'test_steps_per_second': 8.698, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.2527039051055908, 'test_accuracy': 0.9266666666666666, 'test_precision': 0.9560439560439561, 'test_recall': 0.925531914893617, 'test_f1_score': 0.9405405405405406, 'test_roc_auc': 0.9481382978723404, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.07446808510638298, 'test_runtime': 1.1497, 'test_samples_per_second': 130.466, 'test_steps_per_second': 8.698, 'test_epoch': 3.0}
2025-05-16 15:50:08,264 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:50:08,268 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:50:08,613 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:50:08,614 - Experiment - INFO - Evaluating model using false_positives_rate metric...
INFO:Experiment:Evaluating model using false_positives_rate metric...
2025-05-16 15:50:08,614 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:50:08,804 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.21152588725090027, 'eval_accuracy': 0.9395973154362416, 'eval_precision': 0.9655172413793104, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9491525423728814, 'eval_roc_auc': 0.9623352165725048, 'eval_false_positives_rate': 0.05084745762711865, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 1.1286, 'eval_samples_per_second': 132.022, 'eval_steps_per_second': 8.861, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.21152588725090027, 'eval_accuracy': 0.9395973154362416, 'eval_precision': 0.9655172413793104, 'eval_recall': 0.9333333333333333, 'eval_f1_score': 0.9491525423728814, 'eval_roc_auc': 0.9623352165725048, 'eval_false_positives_rate': 0.05084745762711865, 'eval_false_negatives_rate': 0.06666666666666667, 'eval_runtime': 1.1286, 'eval_samples_per_second': 132.022, 'eval_steps_per_second': 8.861, 'epoch': 3.0, 'step': 132}
2025-05-16 15:50:08,804 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:50:09,972 - Experiment - INFO - Test metrics: {'test_loss': 0.2527039051055908, 'test_accuracy': 0.9266666666666666, 'test_precision': 0.9560439560439561, 'test_recall': 0.925531914893617, 'test_f1_score': 0.9405405405405406, 'test_roc_auc': 0.9481382978723404, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.07446808510638298, 'test_runtime': 1.1675, 'test_samples_per_second': 128.481, 'test_steps_per_second': 8.565, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.2527039051055908, 'test_accuracy': 0.9266666666666666, 'test_precision': 0.9560439560439561, 'test_recall': 0.925531914893617, 'test_f1_score': 0.9405405405405406, 'test_roc_auc': 0.9481382978723404, 'test_false_positives_rate': 0.07142857142857142, 'test_false_negatives_rate': 0.07446808510638298, 'test_runtime': 1.1675, 'test_samples_per_second': 128.481, 'test_steps_per_second': 8.565, 'test_epoch': 3.0}
2025-05-16 15:50:09,990 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:50:10,004 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:50:10,387 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:50:10,390 - Experiment - INFO - Evaluating model using roc_auc metric...
INFO:Experiment:Evaluating model using roc_auc metric...
2025-05-16 15:50:10,390 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-220
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-220
2025-05-16 15:50:10,594 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.35221561789512634, 'eval_accuracy': 0.912751677852349, 'eval_precision': 0.9529411764705882, 'eval_recall': 0.9, 'eval_f1_score': 0.9257142857142857, 'eval_roc_auc': 0.9757062146892654, 'eval_false_positives_rate': 0.06779661016949153, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 1.1213, 'eval_samples_per_second': 132.885, 'eval_steps_per_second': 8.918, 'epoch': 5.0, 'step': 220}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.35221561789512634, 'eval_accuracy': 0.912751677852349, 'eval_precision': 0.9529411764705882, 'eval_recall': 0.9, 'eval_f1_score': 0.9257142857142857, 'eval_roc_auc': 0.9757062146892654, 'eval_false_positives_rate': 0.06779661016949153, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 1.1213, 'eval_samples_per_second': 132.885, 'eval_steps_per_second': 8.918, 'epoch': 5.0, 'step': 220}
2025-05-16 15:50:10,596 - Experiment - INFO - Best model found at epoch 5.0.
INFO:Experiment:Best model found at epoch 5.0.

2025-05-16 15:50:11,778 - Experiment - INFO - Test metrics: {'test_loss': 0.5084330439567566, 'test_accuracy': 0.8933333333333333, 'test_precision': 0.9642857142857143, 'test_recall': 0.8617021276595744, 'test_f1_score': 0.9101123595505618, 'test_roc_auc': 0.9728343465045594, 'test_false_positives_rate': 0.05357142857142857, 'test_false_negatives_rate': 0.13829787234042554, 'test_runtime': 1.1783, 'test_samples_per_second': 127.3, 'test_steps_per_second': 8.487, 'test_epoch': 5.0}
INFO:Experiment:Test metrics: {'test_loss': 0.5084330439567566, 'test_accuracy': 0.8933333333333333, 'test_precision': 0.9642857142857143, 'test_recall': 0.8617021276595744, 'test_f1_score': 0.9101123595505618, 'test_roc_auc': 0.9728343465045594, 'test_false_positives_rate': 0.05357142857142857, 'test_false_negatives_rate': 0.13829787234042554, 'test_runtime': 1.1783, 'test_samples_per_second': 127.3, 'test_steps_per_second': 8.487, 'test_epoch': 5.0}
2025-05-16 15:50:11,805 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:50:11,809 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:50:12,166 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:50:12,172 - Experiment - INFO - Evaluating model using loss metric...
INFO:Experiment:Evaluating model using loss metric...
2025-05-16 15:50:12,172 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-88
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-88
2025-05-16 15:50:12,388 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.20399640500545502, 'eval_accuracy': 0.9328859060402684, 'eval_precision': 0.925531914893617, 'eval_recall': 0.9666666666666667, 'eval_f1_score': 0.9456521739130435, 'eval_roc_auc': 0.9736346516007534, 'eval_false_positives_rate': 0.11864406779661017, 'eval_false_negatives_rate': 0.03333333333333333, 'eval_runtime': 1.1194, 'eval_samples_per_second': 133.105, 'eval_steps_per_second': 8.933, 'epoch': 2.0, 'step': 88}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.20399640500545502, 'eval_accuracy': 0.9328859060402684, 'eval_precision': 0.925531914893617, 'eval_recall': 0.9666666666666667, 'eval_f1_score': 0.9456521739130435, 'eval_roc_auc': 0.9736346516007534, 'eval_false_positives_rate': 0.11864406779661017, 'eval_false_negatives_rate': 0.03333333333333333, 'eval_runtime': 1.1194, 'eval_samples_per_second': 133.105, 'eval_steps_per_second': 8.933, 'epoch': 2.0, 'step': 88}
2025-05-16 15:50:12,388 - Experiment - INFO - Best model found at epoch 2.0.
INFO:Experiment:Best model found at epoch 2.0.

2025-05-16 15:50:13,566 - Experiment - INFO - Test metrics: {'test_loss': 0.25852903723716736, 'test_accuracy': 0.92, 'test_precision': 0.9270833333333334, 'test_recall': 0.9468085106382979, 'test_f1_score': 0.9368421052631579, 'test_roc_auc': 0.9661854103343465, 'test_false_positives_rate': 0.125, 'test_false_negatives_rate': 0.05319148936170213, 'test_runtime': 1.1726, 'test_samples_per_second': 127.926, 'test_steps_per_second': 8.528, 'test_epoch': 2.0}
INFO:Experiment:Test metrics: {'test_loss': 0.25852903723716736, 'test_accuracy': 0.92, 'test_precision': 0.9270833333333334, 'test_recall': 0.9468085106382979, 'test_f1_score': 0.9368421052631579, 'test_roc_auc': 0.9661854103343465, 'test_false_positives_rate': 0.125, 'test_false_negatives_rate': 0.05319148936170213, 'test_runtime': 1.1726, 'test_samples_per_second': 127.926, 'test_steps_per_second': 8.528, 'test_epoch': 2.0}
2025-05-16 15:50:13,594 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:50:13,599 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:50:13,956 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:50:13,956 - Experiment - INFO - Finished model evaluations stage.
INFO:Experiment:Finished model evaluations stage.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:50:14,504 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:50:14,504 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:50:14,518 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:50:14,518 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:50:17,219 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:50:17,219 - Experiment - INFO - Existing run ID: dc8d86e812b948b0947960bd7c280cde
INFO:Experiment:Existing run ID: dc8d86e812b948b0947960bd7c280cde
2025-05-16 15:50:17,346 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:50:17,731 - Experiment - INFO - Pruning models artifacts done...
INFO:Experiment:Pruning models artifacts done...

### Run 6 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:50:17,750 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:50:17,750 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:50:17,750 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:50:17,750 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:50:19,673 - Experiment - INFO - Run ID: 21d3496408a248f3b7053334bfb2b4f9
INFO:Experiment:Run ID: 21d3496408a248f3b7053334bfb2b4f9
2025-05-16 15:50:19,673 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)]);2025-05-16_15-50-19;rs=3835274838
INFO:Experiment:Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)]);2025-05-16_15-50-19;rs=3835274838
2025-05-16 15:50:19,698 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
INFO:Experiment:{'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 15:50:19,704 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
INFO:Experiment:Prepared dataset does not exist, computing from scratch.
2025-05-16 15:50:19,809 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A12DA69F0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA7D70>]>
INFO:Experiment:Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A12DA69F0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA7D70>]>
2025-05-16 15:50:19,982 - Experiment - INFO - Preprocessing function 0: noise_reduction
INFO:Experiment:Preprocessing function 0: noise_reduction
2025-05-16 15:50:19,982 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:50:19,982 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:50:20,439 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:50:20,439 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:50:20,566 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:50:20,566 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:50:20,837 - Experiment - INFO - Preprocessing function 1: distilli_bert__encoder
INFO:Experiment:Preprocessing function 1: distilli_bert__encoder
2025-05-16 15:50:20,837 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:50:20,837 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:50:24,586 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:50:24,586 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:50:25,428 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:50:25,428 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:50:28,174 - Experiment - INFO - Model name: DistilliBERT
INFO:Experiment:Model name: DistilliBERT
2025-05-16 15:50:28,188 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
INFO:Experiment:Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 15:52:06,995 - Experiment - INFO - Evaluating model using accuracy metric...
INFO:Experiment:Evaluating model using accuracy metric...
2025-05-16 15:52:06,995 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:52:07,199 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.39280781149864197, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9125, 'eval_recall': 0.8795180722891566, 'eval_f1_score': 0.8957055214723927, 'eval_roc_auc': 0.9375684556407448, 'eval_false_positives_rate': 0.10606060606060606, 'eval_false_negatives_rate': 0.12048192771084337, 'eval_runtime': 1.1566, 'eval_samples_per_second': 128.831, 'eval_steps_per_second': 8.646, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.39280781149864197, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9125, 'eval_recall': 0.8795180722891566, 'eval_f1_score': 0.8957055214723927, 'eval_roc_auc': 0.9375684556407448, 'eval_false_positives_rate': 0.10606060606060606, 'eval_false_negatives_rate': 0.12048192771084337, 'eval_runtime': 1.1566, 'eval_samples_per_second': 128.831, 'eval_steps_per_second': 8.646, 'epoch': 3.0, 'step': 132}
2025-05-16 15:52:07,199 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:52:08,335 - Experiment - INFO - Test metrics: {'test_loss': 0.4847294092178345, 'test_accuracy': 0.82, 'test_precision': 0.8876404494382022, 'test_recall': 0.8229166666666666, 'test_f1_score': 0.8540540540540541, 'test_roc_auc': 0.9268904320987654, 'test_false_positives_rate': 0.18518518518518517, 'test_false_negatives_rate': 0.17708333333333334, 'test_runtime': 1.1326, 'test_samples_per_second': 132.435, 'test_steps_per_second': 8.829, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.4847294092178345, 'test_accuracy': 0.82, 'test_precision': 0.8876404494382022, 'test_recall': 0.8229166666666666, 'test_f1_score': 0.8540540540540541, 'test_roc_auc': 0.9268904320987654, 'test_false_positives_rate': 0.18518518518518517, 'test_false_negatives_rate': 0.17708333333333334, 'test_runtime': 1.1326, 'test_samples_per_second': 132.435, 'test_steps_per_second': 8.829, 'test_epoch': 3.0}
2025-05-16 15:52:08,351 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:52:08,351 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:52:08,708 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:52:08,708 - Experiment - INFO - Evaluating model using precision metric...
INFO:Experiment:Evaluating model using precision metric...
2025-05-16 15:52:08,710 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:52:08,887 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.39280781149864197, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9125, 'eval_recall': 0.8795180722891566, 'eval_f1_score': 0.8957055214723927, 'eval_roc_auc': 0.9375684556407448, 'eval_false_positives_rate': 0.10606060606060606, 'eval_false_negatives_rate': 0.12048192771084337, 'eval_runtime': 1.1566, 'eval_samples_per_second': 128.831, 'eval_steps_per_second': 8.646, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.39280781149864197, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9125, 'eval_recall': 0.8795180722891566, 'eval_f1_score': 0.8957055214723927, 'eval_roc_auc': 0.9375684556407448, 'eval_false_positives_rate': 0.10606060606060606, 'eval_false_negatives_rate': 0.12048192771084337, 'eval_runtime': 1.1566, 'eval_samples_per_second': 128.831, 'eval_steps_per_second': 8.646, 'epoch': 3.0, 'step': 132}
2025-05-16 15:52:08,887 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:52:10,037 - Experiment - INFO - Test metrics: {'test_loss': 0.4847294092178345, 'test_accuracy': 0.82, 'test_precision': 0.8876404494382022, 'test_recall': 0.8229166666666666, 'test_f1_score': 0.8540540540540541, 'test_roc_auc': 0.9268904320987654, 'test_false_positives_rate': 0.18518518518518517, 'test_false_negatives_rate': 0.17708333333333334, 'test_runtime': 1.1373, 'test_samples_per_second': 131.896, 'test_steps_per_second': 8.793, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.4847294092178345, 'test_accuracy': 0.82, 'test_precision': 0.8876404494382022, 'test_recall': 0.8229166666666666, 'test_f1_score': 0.8540540540540541, 'test_roc_auc': 0.9268904320987654, 'test_false_positives_rate': 0.18518518518518517, 'test_false_negatives_rate': 0.17708333333333334, 'test_runtime': 1.1373, 'test_samples_per_second': 131.896, 'test_steps_per_second': 8.793, 'test_epoch': 3.0}
2025-05-16 15:52:10,055 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:52:10,055 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:52:10,430 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:52:10,430 - Experiment - INFO - Evaluating model using f1_score metric...
INFO:Experiment:Evaluating model using f1_score metric...
2025-05-16 15:52:10,438 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:52:10,630 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.39280781149864197, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9125, 'eval_recall': 0.8795180722891566, 'eval_f1_score': 0.8957055214723927, 'eval_roc_auc': 0.9375684556407448, 'eval_false_positives_rate': 0.10606060606060606, 'eval_false_negatives_rate': 0.12048192771084337, 'eval_runtime': 1.1566, 'eval_samples_per_second': 128.831, 'eval_steps_per_second': 8.646, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.39280781149864197, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9125, 'eval_recall': 0.8795180722891566, 'eval_f1_score': 0.8957055214723927, 'eval_roc_auc': 0.9375684556407448, 'eval_false_positives_rate': 0.10606060606060606, 'eval_false_negatives_rate': 0.12048192771084337, 'eval_runtime': 1.1566, 'eval_samples_per_second': 128.831, 'eval_steps_per_second': 8.646, 'epoch': 3.0, 'step': 132}
2025-05-16 15:52:10,630 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:52:11,786 - Experiment - INFO - Test metrics: {'test_loss': 0.4847294092178345, 'test_accuracy': 0.82, 'test_precision': 0.8876404494382022, 'test_recall': 0.8229166666666666, 'test_f1_score': 0.8540540540540541, 'test_roc_auc': 0.9268904320987654, 'test_false_positives_rate': 0.18518518518518517, 'test_false_negatives_rate': 0.17708333333333334, 'test_runtime': 1.1462, 'test_samples_per_second': 130.868, 'test_steps_per_second': 8.725, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.4847294092178345, 'test_accuracy': 0.82, 'test_precision': 0.8876404494382022, 'test_recall': 0.8229166666666666, 'test_f1_score': 0.8540540540540541, 'test_roc_auc': 0.9268904320987654, 'test_false_positives_rate': 0.18518518518518517, 'test_false_negatives_rate': 0.17708333333333334, 'test_runtime': 1.1462, 'test_samples_per_second': 130.868, 'test_steps_per_second': 8.725, 'test_epoch': 3.0}
2025-05-16 15:52:11,829 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:52:11,833 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:52:12,164 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:52:12,180 - Experiment - INFO - Evaluating model using false_positives_rate metric...
INFO:Experiment:Evaluating model using false_positives_rate metric...
2025-05-16 15:52:12,180 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:52:12,366 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.39280781149864197, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9125, 'eval_recall': 0.8795180722891566, 'eval_f1_score': 0.8957055214723927, 'eval_roc_auc': 0.9375684556407448, 'eval_false_positives_rate': 0.10606060606060606, 'eval_false_negatives_rate': 0.12048192771084337, 'eval_runtime': 1.1566, 'eval_samples_per_second': 128.831, 'eval_steps_per_second': 8.646, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.39280781149864197, 'eval_accuracy': 0.8859060402684564, 'eval_precision': 0.9125, 'eval_recall': 0.8795180722891566, 'eval_f1_score': 0.8957055214723927, 'eval_roc_auc': 0.9375684556407448, 'eval_false_positives_rate': 0.10606060606060606, 'eval_false_negatives_rate': 0.12048192771084337, 'eval_runtime': 1.1566, 'eval_samples_per_second': 128.831, 'eval_steps_per_second': 8.646, 'epoch': 3.0, 'step': 132}
2025-05-16 15:52:12,366 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:52:13,509 - Experiment - INFO - Test metrics: {'test_loss': 0.4847294092178345, 'test_accuracy': 0.82, 'test_precision': 0.8876404494382022, 'test_recall': 0.8229166666666666, 'test_f1_score': 0.8540540540540541, 'test_roc_auc': 0.9268904320987654, 'test_false_positives_rate': 0.18518518518518517, 'test_false_negatives_rate': 0.17708333333333334, 'test_runtime': 1.1333, 'test_samples_per_second': 132.355, 'test_steps_per_second': 8.824, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.4847294092178345, 'test_accuracy': 0.82, 'test_precision': 0.8876404494382022, 'test_recall': 0.8229166666666666, 'test_f1_score': 0.8540540540540541, 'test_roc_auc': 0.9268904320987654, 'test_false_positives_rate': 0.18518518518518517, 'test_false_negatives_rate': 0.17708333333333334, 'test_runtime': 1.1333, 'test_samples_per_second': 132.355, 'test_steps_per_second': 8.824, 'test_epoch': 3.0}
2025-05-16 15:52:13,525 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:52:13,525 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:52:13,919 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:52:13,919 - Experiment - INFO - Evaluating model using roc_auc metric...
INFO:Experiment:Evaluating model using roc_auc metric...
2025-05-16 15:52:13,919 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-176
2025-05-16 15:52:14,115 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7793934941291809, 'eval_accuracy': 0.7718120805369127, 'eval_precision': 0.7247706422018348, 'eval_recall': 0.9518072289156626, 'eval_f1_score': 0.8229166666666666, 'eval_roc_auc': 0.9428623585250091, 'eval_false_positives_rate': 0.45454545454545453, 'eval_false_negatives_rate': 0.04819277108433735, 'eval_runtime': 1.1617, 'eval_samples_per_second': 128.265, 'eval_steps_per_second': 8.608, 'epoch': 4.0, 'step': 176}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.7793934941291809, 'eval_accuracy': 0.7718120805369127, 'eval_precision': 0.7247706422018348, 'eval_recall': 0.9518072289156626, 'eval_f1_score': 0.8229166666666666, 'eval_roc_auc': 0.9428623585250091, 'eval_false_positives_rate': 0.45454545454545453, 'eval_false_negatives_rate': 0.04819277108433735, 'eval_runtime': 1.1617, 'eval_samples_per_second': 128.265, 'eval_steps_per_second': 8.608, 'epoch': 4.0, 'step': 176}
2025-05-16 15:52:14,115 - Experiment - INFO - Best model found at epoch 4.0.
INFO:Experiment:Best model found at epoch 4.0.

2025-05-16 15:52:15,299 - Experiment - INFO - Test metrics: {'test_loss': 0.4680134057998657, 'test_accuracy': 0.8733333333333333, 'test_precision': 0.8347826086956521, 'test_recall': 1.0, 'test_f1_score': 0.909952606635071, 'test_roc_auc': 0.9434799382716048, 'test_false_positives_rate': 0.35185185185185186, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.168, 'test_samples_per_second': 128.42, 'test_steps_per_second': 8.561, 'test_epoch': 4.0}
INFO:Experiment:Test metrics: {'test_loss': 0.4680134057998657, 'test_accuracy': 0.8733333333333333, 'test_precision': 0.8347826086956521, 'test_recall': 1.0, 'test_f1_score': 0.909952606635071, 'test_roc_auc': 0.9434799382716048, 'test_false_positives_rate': 0.35185185185185186, 'test_false_negatives_rate': 0.0, 'test_runtime': 1.168, 'test_samples_per_second': 128.42, 'test_steps_per_second': 8.561, 'test_epoch': 4.0}
2025-05-16 15:52:15,314 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:52:15,314 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:52:15,691 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:52:15,691 - Experiment - INFO - Evaluating model using loss metric...
INFO:Experiment:Evaluating model using loss metric...
2025-05-16 15:52:15,702 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-88
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-88
2025-05-16 15:52:15,897 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3856308162212372, 'eval_accuracy': 0.87248322147651, 'eval_precision': 0.8478260869565217, 'eval_recall': 0.9397590361445783, 'eval_f1_score': 0.8914285714285715, 'eval_roc_auc': 0.9331872946330778, 'eval_false_positives_rate': 0.21212121212121213, 'eval_false_negatives_rate': 0.060240963855421686, 'eval_runtime': 1.1608, 'eval_samples_per_second': 128.363, 'eval_steps_per_second': 8.615, 'epoch': 2.0, 'step': 88}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.3856308162212372, 'eval_accuracy': 0.87248322147651, 'eval_precision': 0.8478260869565217, 'eval_recall': 0.9397590361445783, 'eval_f1_score': 0.8914285714285715, 'eval_roc_auc': 0.9331872946330778, 'eval_false_positives_rate': 0.21212121212121213, 'eval_false_negatives_rate': 0.060240963855421686, 'eval_runtime': 1.1608, 'eval_samples_per_second': 128.363, 'eval_steps_per_second': 8.615, 'epoch': 2.0, 'step': 88}
2025-05-16 15:52:15,897 - Experiment - INFO - Best model found at epoch 2.0.
INFO:Experiment:Best model found at epoch 2.0.

2025-05-16 15:52:17,048 - Experiment - INFO - Test metrics: {'test_loss': 0.3607916831970215, 'test_accuracy': 0.8466666666666667, 'test_precision': 0.8476190476190476, 'test_recall': 0.9270833333333334, 'test_f1_score': 0.8855721393034826, 'test_roc_auc': 0.9130015432098766, 'test_false_positives_rate': 0.2962962962962963, 'test_false_negatives_rate': 0.07291666666666667, 'test_runtime': 1.1459, 'test_samples_per_second': 130.899, 'test_steps_per_second': 8.727, 'test_epoch': 2.0}
INFO:Experiment:Test metrics: {'test_loss': 0.3607916831970215, 'test_accuracy': 0.8466666666666667, 'test_precision': 0.8476190476190476, 'test_recall': 0.9270833333333334, 'test_f1_score': 0.8855721393034826, 'test_roc_auc': 0.9130015432098766, 'test_false_positives_rate': 0.2962962962962963, 'test_false_negatives_rate': 0.07291666666666667, 'test_runtime': 1.1459, 'test_samples_per_second': 130.899, 'test_steps_per_second': 8.727, 'test_epoch': 2.0}
2025-05-16 15:52:17,056 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:52:17,056 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:52:17,428 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:52:17,428 - Experiment - INFO - Finished model evaluations stage.
INFO:Experiment:Finished model evaluations stage.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:52:18,075 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:52:18,075 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:52:18,075 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:52:18,075 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:52:20,790 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=false)])
2025-05-16 15:52:20,790 - Experiment - INFO - Existing run ID: 21d3496408a248f3b7053334bfb2b4f9
INFO:Experiment:Existing run ID: 21d3496408a248f3b7053334bfb2b4f9
2025-05-16 15:52:20,933 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:52:21,279 - Experiment - INFO - Pruning models artifacts done...
INFO:Experiment:Pruning models artifacts done...

### Run 7 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:52:21,302 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:52:21,302 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:52:21,304 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:52:21,304 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:52:23,292 - Experiment - INFO - Run ID: e1f30a18581143fc8ac4e4908fb6caad
INFO:Experiment:Run ID: e1f30a18581143fc8ac4e4908fb6caad
2025-05-16 15:52:23,292 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)]);2025-05-16_15-52-23;rs=1731780390
INFO:Experiment:Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)]);2025-05-16_15-52-23;rs=1731780390
2025-05-16 15:52:23,292 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
INFO:Experiment:{'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 15:52:23,323 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
INFO:Experiment:Prepared dataset does not exist, computing from scratch.
2025-05-16 15:52:23,423 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A12DA7E60>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000013A12DA7E30>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000013A12DA6F90>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA7FB0>]>
INFO:Experiment:Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A12DA7E60>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000013A12DA7E30>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000013A12DA6F90>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA7FB0>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 15:52:23,583 - Experiment - INFO - Preprocessing function 0: noise_reduction
INFO:Experiment:Preprocessing function 0: noise_reduction
2025-05-16 15:52:23,599 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:52:23,599 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:52:24,088 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:52:24,088 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:52:24,191 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:52:24,191 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 15:52:24,287 - Experiment - INFO - Preprocessing function 1: nltk_tokenizer
INFO:Experiment:Preprocessing function 1: nltk_tokenizer
2025-05-16 15:52:24,287 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:52:24,303 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:52:25,595 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:52:25,595 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:52:25,911 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:52:25,911 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:52:26,148 - Experiment - INFO - Preprocessing function 2: lemmatization
INFO:Experiment:Preprocessing function 2: lemmatization
2025-05-16 15:52:26,148 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:52:26,157 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:52:26,505 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:52:26,505 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:52:26,600 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:52:26,616 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:52:26,839 - Experiment - INFO - Preprocessing function 3: distilli_bert__encoder
INFO:Experiment:Preprocessing function 3: distilli_bert__encoder
2025-05-16 15:52:26,839 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:52:26,858 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:52:33,264 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:52:33,265 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:52:34,669 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:52:34,669 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:52:38,276 - Experiment - INFO - Model name: DistilliBERT
INFO:Experiment:Model name: DistilliBERT
2025-05-16 15:52:38,291 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
INFO:Experiment:Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 15:54:00,687 - Experiment - INFO - Evaluating model using accuracy metric...
INFO:Experiment:Evaluating model using accuracy metric...
2025-05-16 15:54:00,687 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-176
2025-05-16 15:54:00,878 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6356511116027832, 'eval_accuracy': 0.825503355704698, 'eval_precision': 0.7685185185185185, 'eval_recall': 0.9880952380952381, 'eval_f1_score': 0.8645833333333334, 'eval_roc_auc': 0.9434065934065934, 'eval_false_positives_rate': 0.38461538461538464, 'eval_false_negatives_rate': 0.011904761904761904, 'eval_runtime': 1.1243, 'eval_samples_per_second': 132.531, 'eval_steps_per_second': 8.895, 'epoch': 4.0, 'step': 176}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.6356511116027832, 'eval_accuracy': 0.825503355704698, 'eval_precision': 0.7685185185185185, 'eval_recall': 0.9880952380952381, 'eval_f1_score': 0.8645833333333334, 'eval_roc_auc': 0.9434065934065934, 'eval_false_positives_rate': 0.38461538461538464, 'eval_false_negatives_rate': 0.011904761904761904, 'eval_runtime': 1.1243, 'eval_samples_per_second': 132.531, 'eval_steps_per_second': 8.895, 'epoch': 4.0, 'step': 176}
2025-05-16 15:54:00,878 - Experiment - INFO - Best model found at epoch 4.0.
INFO:Experiment:Best model found at epoch 4.0.

2025-05-16 15:54:02,015 - Experiment - INFO - Test metrics: {'test_loss': 0.6188122630119324, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.7798165137614679, 'test_recall': 0.9883720930232558, 'test_f1_score': 0.8717948717948718, 'test_roc_auc': 0.9442223837209303, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.011627906976744186, 'test_runtime': 1.137, 'test_samples_per_second': 131.927, 'test_steps_per_second': 8.795, 'test_epoch': 4.0}
INFO:Experiment:Test metrics: {'test_loss': 0.6188122630119324, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.7798165137614679, 'test_recall': 0.9883720930232558, 'test_f1_score': 0.8717948717948718, 'test_roc_auc': 0.9442223837209303, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.011627906976744186, 'test_runtime': 1.137, 'test_samples_per_second': 131.927, 'test_steps_per_second': 8.795, 'test_epoch': 4.0}
2025-05-16 15:54:02,047 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:54:02,047 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:54:02,426 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:54:02,433 - Experiment - INFO - Evaluating model using precision metric...
INFO:Experiment:Evaluating model using precision metric...
2025-05-16 15:54:02,433 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:54:02,623 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5126835107803345, 'eval_accuracy': 0.8053691275167785, 'eval_precision': 0.9230769230769231, 'eval_recall': 0.7142857142857143, 'eval_f1_score': 0.8053691275167785, 'eval_roc_auc': 0.9435897435897436, 'eval_false_positives_rate': 0.07692307692307693, 'eval_false_negatives_rate': 0.2857142857142857, 'eval_runtime': 1.128, 'eval_samples_per_second': 132.097, 'eval_steps_per_second': 8.866, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.5126835107803345, 'eval_accuracy': 0.8053691275167785, 'eval_precision': 0.9230769230769231, 'eval_recall': 0.7142857142857143, 'eval_f1_score': 0.8053691275167785, 'eval_roc_auc': 0.9435897435897436, 'eval_false_positives_rate': 0.07692307692307693, 'eval_false_negatives_rate': 0.2857142857142857, 'eval_runtime': 1.128, 'eval_samples_per_second': 132.097, 'eval_steps_per_second': 8.866, 'epoch': 3.0, 'step': 132}
2025-05-16 15:54:02,623 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:54:03,775 - Experiment - INFO - Test metrics: {'test_loss': 0.47554194927215576, 'test_accuracy': 0.8066666666666666, 'test_precision': 0.9130434782608695, 'test_recall': 0.7325581395348837, 'test_f1_score': 0.8129032258064516, 'test_roc_auc': 0.938953488372093, 'test_false_positives_rate': 0.09375, 'test_false_negatives_rate': 0.26744186046511625, 'test_runtime': 1.1516, 'test_samples_per_second': 130.258, 'test_steps_per_second': 8.684, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.47554194927215576, 'test_accuracy': 0.8066666666666666, 'test_precision': 0.9130434782608695, 'test_recall': 0.7325581395348837, 'test_f1_score': 0.8129032258064516, 'test_roc_auc': 0.938953488372093, 'test_false_positives_rate': 0.09375, 'test_false_negatives_rate': 0.26744186046511625, 'test_runtime': 1.1516, 'test_samples_per_second': 130.258, 'test_steps_per_second': 8.684, 'test_epoch': 3.0}
2025-05-16 15:54:03,804 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:54:03,815 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:54:04,184 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:54:04,184 - Experiment - INFO - Evaluating model using f1_score metric...
INFO:Experiment:Evaluating model using f1_score metric...
2025-05-16 15:54:04,184 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-176
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-176
2025-05-16 15:54:04,356 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6356511116027832, 'eval_accuracy': 0.825503355704698, 'eval_precision': 0.7685185185185185, 'eval_recall': 0.9880952380952381, 'eval_f1_score': 0.8645833333333334, 'eval_roc_auc': 0.9434065934065934, 'eval_false_positives_rate': 0.38461538461538464, 'eval_false_negatives_rate': 0.011904761904761904, 'eval_runtime': 1.1243, 'eval_samples_per_second': 132.531, 'eval_steps_per_second': 8.895, 'epoch': 4.0, 'step': 176}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.6356511116027832, 'eval_accuracy': 0.825503355704698, 'eval_precision': 0.7685185185185185, 'eval_recall': 0.9880952380952381, 'eval_f1_score': 0.8645833333333334, 'eval_roc_auc': 0.9434065934065934, 'eval_false_positives_rate': 0.38461538461538464, 'eval_false_negatives_rate': 0.011904761904761904, 'eval_runtime': 1.1243, 'eval_samples_per_second': 132.531, 'eval_steps_per_second': 8.895, 'epoch': 4.0, 'step': 176}
2025-05-16 15:54:04,356 - Experiment - INFO - Best model found at epoch 4.0.
INFO:Experiment:Best model found at epoch 4.0.

2025-05-16 15:54:05,505 - Experiment - INFO - Test metrics: {'test_loss': 0.6188122630119324, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.7798165137614679, 'test_recall': 0.9883720930232558, 'test_f1_score': 0.8717948717948718, 'test_roc_auc': 0.9442223837209303, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.011627906976744186, 'test_runtime': 1.1495, 'test_samples_per_second': 130.494, 'test_steps_per_second': 8.7, 'test_epoch': 4.0}
INFO:Experiment:Test metrics: {'test_loss': 0.6188122630119324, 'test_accuracy': 0.8333333333333334, 'test_precision': 0.7798165137614679, 'test_recall': 0.9883720930232558, 'test_f1_score': 0.8717948717948718, 'test_roc_auc': 0.9442223837209303, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.011627906976744186, 'test_runtime': 1.1495, 'test_samples_per_second': 130.494, 'test_steps_per_second': 8.7, 'test_epoch': 4.0}
2025-05-16 15:54:05,537 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:54:05,553 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:54:05,910 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:54:05,910 - Experiment - INFO - Evaluating model using false_positives_rate metric...
INFO:Experiment:Evaluating model using false_positives_rate metric...
2025-05-16 15:54:05,910 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:54:06,098 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5126835107803345, 'eval_accuracy': 0.8053691275167785, 'eval_precision': 0.9230769230769231, 'eval_recall': 0.7142857142857143, 'eval_f1_score': 0.8053691275167785, 'eval_roc_auc': 0.9435897435897436, 'eval_false_positives_rate': 0.07692307692307693, 'eval_false_negatives_rate': 0.2857142857142857, 'eval_runtime': 1.128, 'eval_samples_per_second': 132.097, 'eval_steps_per_second': 8.866, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.5126835107803345, 'eval_accuracy': 0.8053691275167785, 'eval_precision': 0.9230769230769231, 'eval_recall': 0.7142857142857143, 'eval_f1_score': 0.8053691275167785, 'eval_roc_auc': 0.9435897435897436, 'eval_false_positives_rate': 0.07692307692307693, 'eval_false_negatives_rate': 0.2857142857142857, 'eval_runtime': 1.128, 'eval_samples_per_second': 132.097, 'eval_steps_per_second': 8.866, 'epoch': 3.0, 'step': 132}
2025-05-16 15:54:06,098 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:54:07,258 - Experiment - INFO - Test metrics: {'test_loss': 0.47554194927215576, 'test_accuracy': 0.8066666666666666, 'test_precision': 0.9130434782608695, 'test_recall': 0.7325581395348837, 'test_f1_score': 0.8129032258064516, 'test_roc_auc': 0.938953488372093, 'test_false_positives_rate': 0.09375, 'test_false_negatives_rate': 0.26744186046511625, 'test_runtime': 1.1427, 'test_samples_per_second': 131.269, 'test_steps_per_second': 8.751, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.47554194927215576, 'test_accuracy': 0.8066666666666666, 'test_precision': 0.9130434782608695, 'test_recall': 0.7325581395348837, 'test_f1_score': 0.8129032258064516, 'test_roc_auc': 0.938953488372093, 'test_false_positives_rate': 0.09375, 'test_false_negatives_rate': 0.26744186046511625, 'test_runtime': 1.1427, 'test_samples_per_second': 131.269, 'test_steps_per_second': 8.751, 'test_epoch': 3.0}
2025-05-16 15:54:07,279 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:54:07,279 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:54:07,642 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:54:07,642 - Experiment - INFO - Evaluating model using roc_auc metric...
INFO:Experiment:Evaluating model using roc_auc metric...
2025-05-16 15:54:07,650 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:54:07,839 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5126835107803345, 'eval_accuracy': 0.8053691275167785, 'eval_precision': 0.9230769230769231, 'eval_recall': 0.7142857142857143, 'eval_f1_score': 0.8053691275167785, 'eval_roc_auc': 0.9435897435897436, 'eval_false_positives_rate': 0.07692307692307693, 'eval_false_negatives_rate': 0.2857142857142857, 'eval_runtime': 1.128, 'eval_samples_per_second': 132.097, 'eval_steps_per_second': 8.866, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.5126835107803345, 'eval_accuracy': 0.8053691275167785, 'eval_precision': 0.9230769230769231, 'eval_recall': 0.7142857142857143, 'eval_f1_score': 0.8053691275167785, 'eval_roc_auc': 0.9435897435897436, 'eval_false_positives_rate': 0.07692307692307693, 'eval_false_negatives_rate': 0.2857142857142857, 'eval_runtime': 1.128, 'eval_samples_per_second': 132.097, 'eval_steps_per_second': 8.866, 'epoch': 3.0, 'step': 132}
2025-05-16 15:54:07,839 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:54:08,967 - Experiment - INFO - Test metrics: {'test_loss': 0.47554194927215576, 'test_accuracy': 0.8066666666666666, 'test_precision': 0.9130434782608695, 'test_recall': 0.7325581395348837, 'test_f1_score': 0.8129032258064516, 'test_roc_auc': 0.938953488372093, 'test_false_positives_rate': 0.09375, 'test_false_negatives_rate': 0.26744186046511625, 'test_runtime': 1.1275, 'test_samples_per_second': 133.033, 'test_steps_per_second': 8.869, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.47554194927215576, 'test_accuracy': 0.8066666666666666, 'test_precision': 0.9130434782608695, 'test_recall': 0.7325581395348837, 'test_f1_score': 0.8129032258064516, 'test_roc_auc': 0.938953488372093, 'test_false_positives_rate': 0.09375, 'test_false_negatives_rate': 0.26744186046511625, 'test_runtime': 1.1275, 'test_samples_per_second': 133.033, 'test_steps_per_second': 8.869, 'test_epoch': 3.0}
2025-05-16 15:54:08,999 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:54:08,999 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:54:09,350 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:54:09,350 - Experiment - INFO - Evaluating model using loss metric...
INFO:Experiment:Evaluating model using loss metric...
2025-05-16 15:54:09,350 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-44
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-44
2025-05-16 15:54:09,591 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.440527081489563, 'eval_accuracy': 0.7919463087248322, 'eval_precision': 0.8533333333333334, 'eval_recall': 0.7619047619047619, 'eval_f1_score': 0.8050314465408805, 'eval_roc_auc': 0.8882783882783882, 'eval_false_positives_rate': 0.16923076923076924, 'eval_false_negatives_rate': 0.23809523809523808, 'eval_runtime': 1.1191, 'eval_samples_per_second': 133.148, 'eval_steps_per_second': 8.936, 'epoch': 1.0, 'step': 44}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.440527081489563, 'eval_accuracy': 0.7919463087248322, 'eval_precision': 0.8533333333333334, 'eval_recall': 0.7619047619047619, 'eval_f1_score': 0.8050314465408805, 'eval_roc_auc': 0.8882783882783882, 'eval_false_positives_rate': 0.16923076923076924, 'eval_false_negatives_rate': 0.23809523809523808, 'eval_runtime': 1.1191, 'eval_samples_per_second': 133.148, 'eval_steps_per_second': 8.936, 'epoch': 1.0, 'step': 44}
2025-05-16 15:54:09,591 - Experiment - INFO - Best model found at epoch 1.0.
INFO:Experiment:Best model found at epoch 1.0.

2025-05-16 15:54:10,737 - Experiment - INFO - Test metrics: {'test_loss': 0.45438894629478455, 'test_accuracy': 0.7866666666666666, 'test_precision': 0.8292682926829268, 'test_recall': 0.7906976744186046, 'test_f1_score': 0.8095238095238095, 'test_roc_auc': 0.8824491279069768, 'test_false_positives_rate': 0.21875, 'test_false_negatives_rate': 0.20930232558139536, 'test_runtime': 1.1466, 'test_samples_per_second': 130.821, 'test_steps_per_second': 8.721, 'test_epoch': 1.0}
INFO:Experiment:Test metrics: {'test_loss': 0.45438894629478455, 'test_accuracy': 0.7866666666666666, 'test_precision': 0.8292682926829268, 'test_recall': 0.7906976744186046, 'test_f1_score': 0.8095238095238095, 'test_roc_auc': 0.8824491279069768, 'test_false_positives_rate': 0.21875, 'test_false_negatives_rate': 0.20930232558139536, 'test_runtime': 1.1466, 'test_samples_per_second': 130.821, 'test_steps_per_second': 8.721, 'test_epoch': 1.0}
2025-05-16 15:54:10,753 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:54:10,753 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:54:11,111 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:54:11,111 - Experiment - INFO - Finished model evaluations stage.
INFO:Experiment:Finished model evaluations stage.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:54:11,803 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:54:11,803 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:54:11,805 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:54:11,805 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:54:14,316 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:54:14,316 - Experiment - INFO - Existing run ID: e1f30a18581143fc8ac4e4908fb6caad
INFO:Experiment:Existing run ID: e1f30a18581143fc8ac4e4908fb6caad
2025-05-16 15:54:14,458 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:54:14,778 - Experiment - INFO - Pruning models artifacts done...
INFO:Experiment:Pruning models artifacts done...

### Run 8 of 8

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:54:14,797 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:54:14,797 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:54:14,799 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:54:14,799 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:54:16,783 - Experiment - INFO - Run ID: 61424a7a6e0b445bb878273f0aebf3ab
INFO:Experiment:Run ID: 61424a7a6e0b445bb878273f0aebf3ab
2025-05-16 15:54:16,791 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)]);2025-05-16_15-54-16;rs=3647333353
INFO:Experiment:Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)]);2025-05-16_15-54-16;rs=3647333353
2025-05-16 15:54:16,801 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
INFO:Experiment:{'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 15:54:16,832 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
INFO:Experiment:Prepared dataset does not exist, computing from scratch.
2025-05-16 15:54:16,910 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A12DA4200>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000013A12DA6510>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000013A12DA5220>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA6900>]>
INFO:Experiment:Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000013A12DA4200>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000013A12DA6510>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000013A12DA5220>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000013A12DA6900>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 15:54:17,091 - Experiment - INFO - Preprocessing function 0: noise_reduction
INFO:Experiment:Preprocessing function 0: noise_reduction
2025-05-16 15:54:17,091 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:54:17,091 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:54:17,524 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:54:17,529 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:54:17,624 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:54:17,624 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 15:54:17,730 - Experiment - INFO - Preprocessing function 1: nltk_tokenizer
INFO:Experiment:Preprocessing function 1: nltk_tokenizer
2025-05-16 15:54:17,746 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:54:17,746 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:54:18,975 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:54:18,975 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:54:19,245 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:54:19,245 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
2025-05-16 15:54:19,547 - Experiment - INFO - Preprocessing function 2: stemming
INFO:Experiment:Preprocessing function 2: stemming
2025-05-16 15:54:19,547 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:54:19,547 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: xivAtTQk
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: DeLuca
warning: skipping word with mixed case: DeLuca
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: zGrIFnzC
warning: skipping word with mixed case: ParlamentníListy
warning: skipping word with mixed case: NjovoEp
warning: skipping word with mixed case: FNQpqAj
warning: skipping word with mixed case: PepsiCo
warning: skipping word with mixed case: yhYZeissQb
warning: skipping word with mixed case: MaxxPro
warning: skipping word with mixed case: mírUkrajině
warning: skipping word with mixed case: vícTo
warning: skipping word with mixed case: líbíOkomentovatSdílet
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: EURa
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: IwARDcassoKYvhlJMWhvz
warning: skipping word with mixed case: GMujI
warning: skipping word with mixed case: EzRhjPb
warning: skipping word with mixed case: RlL
warning: skipping word with mixed case: NpFsrXeTtLA
warning: skipping word with mixed case: iDnes
warning: skipping word with mixed case: iDnes
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: qLCBuVdns
warning: skipping word with mixed case: FACs
warning: skipping word with mixed case: UAVs
warning: skipping word with mixed case: QRRaplKK
warning: skipping word with mixed case: BMVg
warning: skipping word with mixed case: ParlamentnímListům
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: mSmlhLVUE
warning: skipping word with mixed case: JackPosobiec
warning: skipping word with mixed case: JPMorgan
warning: skipping word with mixed case: ECLNWHgl
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: ZvsgC
warning: skipping word with mixed case: kW
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: EADaily
warning: skipping word with mixed case: NewsMap
warning: skipping word with mixed case: NCjcWaTREH
warning: skipping word with mixed case: XoBrKkRry
warning: skipping word with mixed case: DMcuBPKUj
warning: skipping word with mixed case: KyjevaVÍCE
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: sikorskiRadek
warning: skipping word with mixed case: GAZPROMu
warning: skipping word with mixed case: iCloudu
warning: skipping word with mixed case: iPhonu
warning: skipping word with mixed case: iPhone
warning: skipping word with mixed case: iCloud
warning: skipping word with mixed case: iPhonu
warning: skipping word with mixed case: iCloud
warning: skipping word with mixed case: DShK
warning: skipping word with mixed case: SPOLUobčané
warning: skipping word with mixed case: KSČíny
warning: skipping word with mixed case: KSČíny
warning: skipping word with mixed case: HIMARSy
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: SkyLink
warning: skipping word with mixed case: bcJGNajX
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: MOSADu
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: PiS
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: aJWmHMLT
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: TOPky
warning: skipping word with mixed case: MafiánStan
warning: skipping word with mixed case: ViktoriaGruppe
warning: skipping word with mixed case: BelTA
warning: skipping word with mixed case: BelTA
warning: skipping word with mixed case: LigaBusinessInform
warning: skipping word with mixed case: wXaQklCz
warning: skipping word with mixed case: SudRadio
warning: skipping word with mixed case: SudRadia
warning: skipping word with mixed case: McCarthy
warning: skipping word with mixed case: WatchAbrams
warning: skipping word with mixed case: LibkošObyvatelé
warning: skipping word with mixed case: BémODS
warning: skipping word with mixed case: WiFi
warning: skipping word with mixed case: KčSanace
warning: skipping word with mixed case: RuSSáci
warning: skipping word with mixed case: ProtiproudTV
warning: skipping word with mixed case: QUAcyLckUj
warning: skipping word with mixed case: mSv
warning: skipping word with mixed case: mSv
warning: skipping word with mixed case: FEGURsVhCv
warning: skipping word with mixed case: KeepCalmAndSmile
warning: skipping word with mixed case: DrabovaDana
warning: skipping word with mixed case: KeepCalmAndSmile
warning: skipping word with mixed case: DrabovaDana
warning: skipping word with mixed case: JanLipavsky
warning: skipping word with mixed case: ZelenskyyUa
warning: skipping word with mixed case: LONGi
warning: skipping word with mixed case: MUDr
warning: skipping word with mixed case: OSPODu
warning: skipping word with mixed case: ProLibertate
warning: skipping word with mixed case: SJupGg
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: iZTdGDa
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: ČvT
warning: skipping word with mixed case: ČvT
warning: skipping word with mixed case: ČvT
warning: skipping word with mixed case: TeamUkraine
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: QsRsXmnJ
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: fbnFYnDr
warning: skipping word with mixed case: OvYkxqdJr
warning: skipping word with mixed case: BBCWillVernon
warning: skipping word with mixed case: PetrJ
warning: skipping word with mixed case: PetrJ
warning: skipping word with mixed case: REPLlKÁTOR
warning: skipping word with mixed case: SpringerLink
warning: skipping word with mixed case: CoV
warning: skipping word with mixed case: mRNA
warning: skipping word with mixed case: LinkedIn
warning: skipping word with mixed case: SpringerLink
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: WeChat
warning: skipping word with mixed case: WeChat
warning: skipping word with mixed case: MinfinMedia
warning: skipping word with mixed case: PhDr
warning: skipping word with mixed case: CSc
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: QsRsXmnJ
warning: skipping word with mixed case: LONGi
warning: skipping word with mixed case: ZDjqiwFMb
warning: skipping word with mixed case: JPMorgan
warning: skipping word with mixed case: CzechInvest
warning: skipping word with mixed case: CzechInvest
warning: skipping word with mixed case: mMztqsJRQT
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: ArmUkraineNow
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: sVDMmb
warning: skipping word with mixed case: StratcomCentre
warning: skipping word with mixed case: RealScottRitter
warning: skipping word with mixed case: ScottRitter
warning: skipping word with mixed case: EvaKBartlett
warning: skipping word with mixed case: EvaKBartlett
warning: skipping word with mixed case: EvaKBartlett
warning: skipping word with mixed case: StopKillingDonbass
warning: skipping word with mixed case: StopKillingDonbass
warning: skipping word with mixed case: TMUgBkcKC
warning: skipping word with mixed case: EvaKBartlett
warning: skipping word with mixed case: oCxcRRwKl
warning: skipping word with mixed case: jvbXUwDjc
warning: skipping word with mixed case: ProuvostDecember
warning: skipping word with mixed case: TOSy
warning: skipping word with mixed case: mRNA
warning: skipping word with mixed case: CoV
warning: skipping word with mixed case: mRNA
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitFor
warning: skipping word with mixed case: FitiFor
warning: skipping word with mixed case: kV
warning: skipping word with mixed case: SAMů
warning: skipping word with mixed case: PhDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: YXpleSIp
warning: skipping word with mixed case: ProtiproudTV
warning: skipping word with mixed case: iNews
warning: skipping word with mixed case: NordStream
warning: skipping word with mixed case: NordStream
warning: skipping word with mixed case: NordStreamu
warning: skipping word with mixed case: AlJazeera
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: McCallister
warning: skipping word with mixed case: UguwdpjEJo
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: InoSMI
warning: skipping word with mixed case: OpenCard
warning: skipping word with mixed case: KWh
warning: skipping word with mixed case: KWh
warning: skipping word with mixed case: KrAZ
warning: skipping word with mixed case: WFmrAdBZ
warning: skipping word with mixed case: RWApodcast
warning: skipping word with mixed case: ParlamentníListy
warning: skipping word with mixed case: GYFPXwFpsp
warning: skipping word with mixed case: jtkSidjpX
warning: skipping word with mixed case: SwedishPM

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Map:   0%|          | 0/696 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:54:27,126 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:54:27,142 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Map:   0%|          | 0/149 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:54:28,350 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:54:28,350 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:54:31,698 - Experiment - INFO - Model name: DistilliBERT
INFO:Experiment:Model name: DistilliBERT
2025-05-16 15:54:31,698 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
INFO:Experiment:Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 15:56:27,621 - Experiment - INFO - Evaluating model using accuracy metric...
INFO:Experiment:Evaluating model using accuracy metric...
2025-05-16 15:56:27,627 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-264
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-264
2025-05-16 15:56:27,817 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3630145192146301, 'eval_accuracy': 0.9060402684563759, 'eval_precision': 0.8787878787878788, 'eval_recall': 0.9775280898876404, 'eval_f1_score': 0.925531914893617, 'eval_roc_auc': 0.9705992509363296, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.02247191011235955, 'eval_runtime': 1.1442, 'eval_samples_per_second': 130.218, 'eval_steps_per_second': 8.739, 'epoch': 6.0, 'step': 264}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.3630145192146301, 'eval_accuracy': 0.9060402684563759, 'eval_precision': 0.8787878787878788, 'eval_recall': 0.9775280898876404, 'eval_f1_score': 0.925531914893617, 'eval_roc_auc': 0.9705992509363296, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.02247191011235955, 'eval_runtime': 1.1442, 'eval_samples_per_second': 130.218, 'eval_steps_per_second': 8.739, 'epoch': 6.0, 'step': 264}
2025-05-16 15:56:27,817 - Experiment - INFO - Best model found at epoch 6.0.
INFO:Experiment:Best model found at epoch 6.0.

2025-05-16 15:56:28,970 - Experiment - INFO - Test metrics: {'test_loss': 0.30922073125839233, 'test_accuracy': 0.92, 'test_precision': 0.9010989010989011, 'test_recall': 0.9647058823529412, 'test_f1_score': 0.9318181818181818, 'test_roc_auc': 0.9784615384615385, 'test_false_positives_rate': 0.13846153846153847, 'test_false_negatives_rate': 0.03529411764705882, 'test_runtime': 1.1531, 'test_samples_per_second': 130.087, 'test_steps_per_second': 8.672, 'test_epoch': 6.0}
INFO:Experiment:Test metrics: {'test_loss': 0.30922073125839233, 'test_accuracy': 0.92, 'test_precision': 0.9010989010989011, 'test_recall': 0.9647058823529412, 'test_f1_score': 0.9318181818181818, 'test_roc_auc': 0.9784615384615385, 'test_false_positives_rate': 0.13846153846153847, 'test_false_negatives_rate': 0.03529411764705882, 'test_runtime': 1.1531, 'test_samples_per_second': 130.087, 'test_steps_per_second': 8.672, 'test_epoch': 6.0}
2025-05-16 15:56:28,992 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:56:29,002 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:56:29,381 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:56:29,381 - Experiment - INFO - Evaluating model using precision metric...
INFO:Experiment:Evaluating model using precision metric...
2025-05-16 15:56:29,396 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:56:29,586 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.29390451312065125, 'eval_accuracy': 0.8523489932885906, 'eval_precision': 0.935064935064935, 'eval_recall': 0.8089887640449438, 'eval_f1_score': 0.8674698795180723, 'eval_roc_auc': 0.9574906367041198, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.19101123595505617, 'eval_runtime': 1.1319, 'eval_samples_per_second': 131.641, 'eval_steps_per_second': 8.835, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.29390451312065125, 'eval_accuracy': 0.8523489932885906, 'eval_precision': 0.935064935064935, 'eval_recall': 0.8089887640449438, 'eval_f1_score': 0.8674698795180723, 'eval_roc_auc': 0.9574906367041198, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.19101123595505617, 'eval_runtime': 1.1319, 'eval_samples_per_second': 131.641, 'eval_steps_per_second': 8.835, 'epoch': 3.0, 'step': 132}
2025-05-16 15:56:29,586 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:56:30,761 - Experiment - INFO - Test metrics: {'test_loss': 0.26339513063430786, 'test_accuracy': 0.8866666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.8352941176470589, 'test_f1_score': 0.8930817610062893, 'test_roc_auc': 0.9706787330316742, 'test_false_positives_rate': 0.046153846153846156, 'test_false_negatives_rate': 0.16470588235294117, 'test_runtime': 1.1744, 'test_samples_per_second': 127.721, 'test_steps_per_second': 8.515, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.26339513063430786, 'test_accuracy': 0.8866666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.8352941176470589, 'test_f1_score': 0.8930817610062893, 'test_roc_auc': 0.9706787330316742, 'test_false_positives_rate': 0.046153846153846156, 'test_false_negatives_rate': 0.16470588235294117, 'test_runtime': 1.1744, 'test_samples_per_second': 127.721, 'test_steps_per_second': 8.515, 'test_epoch': 3.0}
2025-05-16 15:56:30,780 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:56:30,790 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:56:31,173 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:56:31,173 - Experiment - INFO - Evaluating model using f1_score metric...
INFO:Experiment:Evaluating model using f1_score metric...
2025-05-16 15:56:31,173 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-264
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-264
2025-05-16 15:56:31,379 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3630145192146301, 'eval_accuracy': 0.9060402684563759, 'eval_precision': 0.8787878787878788, 'eval_recall': 0.9775280898876404, 'eval_f1_score': 0.925531914893617, 'eval_roc_auc': 0.9705992509363296, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.02247191011235955, 'eval_runtime': 1.1442, 'eval_samples_per_second': 130.218, 'eval_steps_per_second': 8.739, 'epoch': 6.0, 'step': 264}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.3630145192146301, 'eval_accuracy': 0.9060402684563759, 'eval_precision': 0.8787878787878788, 'eval_recall': 0.9775280898876404, 'eval_f1_score': 0.925531914893617, 'eval_roc_auc': 0.9705992509363296, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.02247191011235955, 'eval_runtime': 1.1442, 'eval_samples_per_second': 130.218, 'eval_steps_per_second': 8.739, 'epoch': 6.0, 'step': 264}
2025-05-16 15:56:31,379 - Experiment - INFO - Best model found at epoch 6.0.
INFO:Experiment:Best model found at epoch 6.0.

2025-05-16 15:56:32,577 - Experiment - INFO - Test metrics: {'test_loss': 0.30922073125839233, 'test_accuracy': 0.92, 'test_precision': 0.9010989010989011, 'test_recall': 0.9647058823529412, 'test_f1_score': 0.9318181818181818, 'test_roc_auc': 0.9784615384615385, 'test_false_positives_rate': 0.13846153846153847, 'test_false_negatives_rate': 0.03529411764705882, 'test_runtime': 1.1984, 'test_samples_per_second': 125.169, 'test_steps_per_second': 8.345, 'test_epoch': 6.0}
INFO:Experiment:Test metrics: {'test_loss': 0.30922073125839233, 'test_accuracy': 0.92, 'test_precision': 0.9010989010989011, 'test_recall': 0.9647058823529412, 'test_f1_score': 0.9318181818181818, 'test_roc_auc': 0.9784615384615385, 'test_false_positives_rate': 0.13846153846153847, 'test_false_negatives_rate': 0.03529411764705882, 'test_runtime': 1.1984, 'test_samples_per_second': 125.169, 'test_steps_per_second': 8.345, 'test_epoch': 6.0}
2025-05-16 15:56:32,593 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:56:32,593 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:56:32,965 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:56:32,965 - Experiment - INFO - Evaluating model using false_positives_rate metric...
INFO:Experiment:Evaluating model using false_positives_rate metric...
2025-05-16 15:56:32,965 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:56:33,148 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.29390451312065125, 'eval_accuracy': 0.8523489932885906, 'eval_precision': 0.935064935064935, 'eval_recall': 0.8089887640449438, 'eval_f1_score': 0.8674698795180723, 'eval_roc_auc': 0.9574906367041198, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.19101123595505617, 'eval_runtime': 1.1319, 'eval_samples_per_second': 131.641, 'eval_steps_per_second': 8.835, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.29390451312065125, 'eval_accuracy': 0.8523489932885906, 'eval_precision': 0.935064935064935, 'eval_recall': 0.8089887640449438, 'eval_f1_score': 0.8674698795180723, 'eval_roc_auc': 0.9574906367041198, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.19101123595505617, 'eval_runtime': 1.1319, 'eval_samples_per_second': 131.641, 'eval_steps_per_second': 8.835, 'epoch': 3.0, 'step': 132}
2025-05-16 15:56:33,165 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:56:34,347 - Experiment - INFO - Test metrics: {'test_loss': 0.26339513063430786, 'test_accuracy': 0.8866666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.8352941176470589, 'test_f1_score': 0.8930817610062893, 'test_roc_auc': 0.9706787330316742, 'test_false_positives_rate': 0.046153846153846156, 'test_false_negatives_rate': 0.16470588235294117, 'test_runtime': 1.1819, 'test_samples_per_second': 126.918, 'test_steps_per_second': 8.461, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.26339513063430786, 'test_accuracy': 0.8866666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.8352941176470589, 'test_f1_score': 0.8930817610062893, 'test_roc_auc': 0.9706787330316742, 'test_false_positives_rate': 0.046153846153846156, 'test_false_negatives_rate': 0.16470588235294117, 'test_runtime': 1.1819, 'test_samples_per_second': 126.918, 'test_steps_per_second': 8.461, 'test_epoch': 3.0}
2025-05-16 15:56:34,366 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:56:34,366 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:56:34,732 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:56:34,732 - Experiment - INFO - Evaluating model using roc_auc metric...
INFO:Experiment:Evaluating model using roc_auc metric...
2025-05-16 15:56:34,732 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-264
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-264
2025-05-16 15:56:34,933 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3630145192146301, 'eval_accuracy': 0.9060402684563759, 'eval_precision': 0.8787878787878788, 'eval_recall': 0.9775280898876404, 'eval_f1_score': 0.925531914893617, 'eval_roc_auc': 0.9705992509363296, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.02247191011235955, 'eval_runtime': 1.1442, 'eval_samples_per_second': 130.218, 'eval_steps_per_second': 8.739, 'epoch': 6.0, 'step': 264}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.3630145192146301, 'eval_accuracy': 0.9060402684563759, 'eval_precision': 0.8787878787878788, 'eval_recall': 0.9775280898876404, 'eval_f1_score': 0.925531914893617, 'eval_roc_auc': 0.9705992509363296, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.02247191011235955, 'eval_runtime': 1.1442, 'eval_samples_per_second': 130.218, 'eval_steps_per_second': 8.739, 'epoch': 6.0, 'step': 264}
2025-05-16 15:56:34,933 - Experiment - INFO - Best model found at epoch 6.0.
INFO:Experiment:Best model found at epoch 6.0.

2025-05-16 15:56:36,167 - Experiment - INFO - Test metrics: {'test_loss': 0.30922073125839233, 'test_accuracy': 0.92, 'test_precision': 0.9010989010989011, 'test_recall': 0.9647058823529412, 'test_f1_score': 0.9318181818181818, 'test_roc_auc': 0.9784615384615385, 'test_false_positives_rate': 0.13846153846153847, 'test_false_negatives_rate': 0.03529411764705882, 'test_runtime': 1.2345, 'test_samples_per_second': 121.502, 'test_steps_per_second': 8.1, 'test_epoch': 6.0}
INFO:Experiment:Test metrics: {'test_loss': 0.30922073125839233, 'test_accuracy': 0.92, 'test_precision': 0.9010989010989011, 'test_recall': 0.9647058823529412, 'test_f1_score': 0.9318181818181818, 'test_roc_auc': 0.9784615384615385, 'test_false_positives_rate': 0.13846153846153847, 'test_false_negatives_rate': 0.03529411764705882, 'test_runtime': 1.2345, 'test_samples_per_second': 121.502, 'test_steps_per_second': 8.1, 'test_epoch': 6.0}
2025-05-16 15:56:36,199 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:56:36,199 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:56:36,547 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:56:36,547 - Experiment - INFO - Evaluating model using loss metric...
INFO:Experiment:Evaluating model using loss metric...
2025-05-16 15:56:36,547 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-132
INFO:Experiment:Found checkpoint with best metrics at: checkpoint-132
2025-05-16 15:56:36,754 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.29390451312065125, 'eval_accuracy': 0.8523489932885906, 'eval_precision': 0.935064935064935, 'eval_recall': 0.8089887640449438, 'eval_f1_score': 0.8674698795180723, 'eval_roc_auc': 0.9574906367041198, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.19101123595505617, 'eval_runtime': 1.1319, 'eval_samples_per_second': 131.641, 'eval_steps_per_second': 8.835, 'epoch': 3.0, 'step': 132}
INFO:Experiment:Best entry according to validation metrics: {'eval_loss': 0.29390451312065125, 'eval_accuracy': 0.8523489932885906, 'eval_precision': 0.935064935064935, 'eval_recall': 0.8089887640449438, 'eval_f1_score': 0.8674698795180723, 'eval_roc_auc': 0.9574906367041198, 'eval_false_positives_rate': 0.08333333333333333, 'eval_false_negatives_rate': 0.19101123595505617, 'eval_runtime': 1.1319, 'eval_samples_per_second': 131.641, 'eval_steps_per_second': 8.835, 'epoch': 3.0, 'step': 132}
2025-05-16 15:56:36,754 - Experiment - INFO - Best model found at epoch 3.0.
INFO:Experiment:Best model found at epoch 3.0.

2025-05-16 15:56:37,947 - Experiment - INFO - Test metrics: {'test_loss': 0.26339513063430786, 'test_accuracy': 0.8866666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.8352941176470589, 'test_f1_score': 0.8930817610062893, 'test_roc_auc': 0.9706787330316742, 'test_false_positives_rate': 0.046153846153846156, 'test_false_negatives_rate': 0.16470588235294117, 'test_runtime': 1.1922, 'test_samples_per_second': 125.815, 'test_steps_per_second': 8.388, 'test_epoch': 3.0}
INFO:Experiment:Test metrics: {'test_loss': 0.26339513063430786, 'test_accuracy': 0.8866666666666667, 'test_precision': 0.9594594594594594, 'test_recall': 0.8352941176470589, 'test_f1_score': 0.8930817610062893, 'test_roc_auc': 0.9706787330316742, 'test_false_positives_rate': 0.046153846153846156, 'test_false_negatives_rate': 0.16470588235294117, 'test_runtime': 1.1922, 'test_samples_per_second': 125.815, 'test_steps_per_second': 8.388, 'test_epoch': 3.0}
2025-05-16 15:56:37,969 - Experiment - INFO - Saving evaluation data in pickle...
INFO:Experiment:Saving evaluation data in pickle...
2025-05-16 15:56:37,975 - Experiment - INFO - Saving evaluation data in json...
INFO:Experiment:Saving evaluation data in json...
2025-05-16 15:56:38,336 - Experiment - INFO - Successfully saved evaluation data.
INFO:Experiment:Successfully saved evaluation data.
2025-05-16 15:56:38,352 - Experiment - INFO - Finished model evaluations stage.
INFO:Experiment:Finished model evaluations stage.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025-05-16 15:56:38,728 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
INFO:Experiment:MLflow experiment initialized with ID: 580058141891138922
2025-05-16 15:56:38,728 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:56:38,728 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:56:38,728 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:56:41,714 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
INFO:Experiment:Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=256,isiw=true)])
2025-05-16 15:56:41,714 - Experiment - INFO - Existing run ID: 61424a7a6e0b445bb878273f0aebf3ab
INFO:Experiment:Existing run ID: 61424a7a6e0b445bb878273f0aebf3ab
2025-05-16 15:56:41,857 - Experiment - INFO - Pruning models artifacts to free space...
INFO:Experiment:Pruning models artifacts to free space...
2025-05-16 15:56:42,296 - Experiment - INFO - Pruning models artifacts done...
INFO:Experiment:Pruning models artifacts done...

In [ ]:
%cd ../roberta
%run training.ipynb

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\workspace\notebooks\roberta
Experiment: roberta
Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### Run 1 of 4

WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
WARNING:root:Malformed experiment 'tmp'. Detailed error Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 329, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 427, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1373, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1366, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '..\..\mlruns\tmp\meta.yaml' does not exist.
2025/05/16 15:56:42 INFO mlflow.tracking.fluent: Experiment with name 'roberta' does not exist. Creating a new experiment.
2025-05-16 15:56:42,437 - Experiment - INFO - MLflow experiment initialized with ID: 217717477222705143
INFO:Experiment:MLflow experiment initialized with ID: 217717477222705143
2025-05-16 15:56:42,440 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
INFO:Experiment:Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 15:56:42,442 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:56:42,442 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
INFO:Experiment:Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 15:56:42,494 - Experiment - INFO - Run ID: aaf2c9e6f3ee49d18eaeecb0e850314d
INFO:Experiment:Run ID: aaf2c9e6f3ee49d18eaeecb0e850314d
2025-05-16 15:56:42,494 - Experiment - INFO - Run name: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_15-56-42;rs=2003940551
INFO:Experiment:Run name: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_15-56-42;rs=2003940551
2025-05-16 15:56:42,510 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
INFO:Experiment:{'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 15:56:42,526 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
INFO:Experiment:Prepared dataset does not exist, computing from scratch.
2025-05-16 15:56:42,685 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.encoders.encoders.RoBERTaEncoder object at 0x0000013A16F75670>]>
INFO:Experiment:Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.encoders.encoders.RoBERTaEncoder object at 0x0000013A16F75670>]>
2025-05-16 15:56:43,359 - Experiment - INFO - Preprocessing function 0: ro_ber_ta_encoder
INFO:Experiment:Preprocessing function 0: ro_ber_ta_encoder
2025-05-16 15:56:43,359 - Experiment - INFO - Preprocessing split: train_set
INFO:Experiment:Preprocessing split: train_set
2025-05-16 15:56:43,359 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

2025-05-16 15:56:50,844 - Experiment - INFO - Preprocessing split: val_set
INFO:Experiment:Preprocessing split: val_set
2025-05-16 15:56:50,844 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:56:52,440 - Experiment - INFO - Preprocessing split: test_set
INFO:Experiment:Preprocessing split: test_set
2025-05-16 15:56:52,442 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
INFO:Experiment:Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 15:56:56,147 - Experiment - INFO - Model name: RoBERTa
INFO:Experiment:Model name: RoBERTa
2025-05-16 15:56:56,152 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
INFO:Experiment:Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

In [ ]:
%cd ../openai_gpt1
%run training.ipynb

In [ ]:
%cd ../openai_gpt2
%run training.ipynb