In [1]:
%cd bert_base_uncased
%run training.ipynb

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\workspace\notebooks\bert_base_uncased
Experiment: bert
Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### Run 1 of 4

2025-05-16 12:04:33,500 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:33,501 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:33,502 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:33,503 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:35,953 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:35,953 - Experiment - INFO - Existing run ID: 5cd11c9c0b444ac39c0b6db83d30eda0
2025-05-16 12:04:35,953 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:04:35,964 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:35,965 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:35,966 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:35,967 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:37,952 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:37,952 - Experiment - INFO - Existing run ID: 5cd11c9c0b444ac39c0b6db83d30eda0
2025-05-16 12:04:38,078 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:04:38,079 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 4

2025-05-16 12:04:38,094 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:38,095 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:38,096 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:38,097 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:40,313 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:40,313 - Experiment - INFO - Existing run ID: 75aeff0f31c3454f835e20bf3f9a2443
2025-05-16 12:04:40,313 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:04:40,337 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:40,338 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:40,339 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:40,339 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:42,382 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:42,382 - Experiment - INFO - Existing run ID: 75aeff0f31c3454f835e20bf3f9a2443
2025-05-16 12:04:42,521 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:04:42,522 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 4

2025-05-16 12:04:42,535 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:42,536 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:42,537 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:42,538 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:44,626 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:44,626 - Experiment - INFO - Existing run ID: b253f3bc3c97417f91ae776fe46ce56c
2025-05-16 12:04:44,626 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:04:44,642 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:44,642 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:44,642 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:44,642 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:46,682 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:46,682 - Experiment - INFO - Existing run ID: b253f3bc3c97417f91ae776fe46ce56c
2025-05-16 12:04:46,813 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:04:46,813 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 4

2025-05-16 12:04:46,842 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:46,843 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:46,844 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:46,844 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:48,868 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:48,868 - Experiment - INFO - Existing run ID: b0b89f040fc64ea693279210ccee8ee0
2025-05-16 12:04:48,868 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:04:48,878 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:48,879 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:48,879 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:48,880 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:50,913 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:04:50,913 - Experiment - INFO - Existing run ID: b0b89f040fc64ea693279210ccee8ee0
2025-05-16 12:04:51,046 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:04:51,046 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 1 of 4

2025-05-16 12:04:51,077 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:51,077 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:51,078 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:51,079 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:53,309 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:53,309 - Experiment - INFO - Existing run ID: b205a95f5c234fdaaaea5c5f2f240bb3
2025-05-16 12:04:53,309 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:04:53,325 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:53,326 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:53,326 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:53,327 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:55,539 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:55,539 - Experiment - INFO - Existing run ID: b205a95f5c234fdaaaea5c5f2f240bb3
2025-05-16 12:04:55,668 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:04:55,669 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 4

2025-05-16 12:04:55,682 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:55,683 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:55,684 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:55,685 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:57,953 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:57,953 - Experiment - INFO - Existing run ID: 55c6987e36ea436787796965d2e70423
2025-05-16 12:04:57,961 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:04:57,965 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:04:57,965 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:04:57,965 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:04:57,965 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:00,118 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:00,118 - Experiment - INFO - Existing run ID: 55c6987e36ea436787796965d2e70423
2025-05-16 12:05:00,262 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:00,262 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 4

2025-05-16 12:05:00,283 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:00,283 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:00,284 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:00,284 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:02,294 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:02,294 - Experiment - INFO - Existing run ID: 219027de228540188f607a23161224b5
2025-05-16 12:05:02,294 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:02,308 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:02,309 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:02,309 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:02,310 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:04,265 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:04,265 - Experiment - INFO - Existing run ID: 219027de228540188f607a23161224b5
2025-05-16 12:05:04,408 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:04,409 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 4

2025-05-16 12:05:04,422 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:04,423 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:04,424 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:04,424 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:06,431 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:06,431 - Experiment - INFO - Existing run ID: 83b19dda48144cc29d44c33bbe6fa77f
2025-05-16 12:05:06,431 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:06,443 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:06,444 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:06,444 - Experiment - INFO - Dataset signature: dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:06,445 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:08,453 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=euvsdisinfo,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:08,453 - Experiment - INFO - Existing run ID: 83b19dda48144cc29d44c33bbe6fa77f
2025-05-16 12:05:08,595 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:08,595 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 1 of 4

2025-05-16 12:05:08,611 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:08,612 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:08,613 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:08,614 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:10,578 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:10,578 - Experiment - INFO - Existing run ID: b9136f21ebca4b3897ce9e9c7ffd2c33
2025-05-16 12:05:10,578 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:10,594 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:10,595 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:10,597 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:10,598 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:12,586 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:12,586 - Experiment - INFO - Existing run ID: b9136f21ebca4b3897ce9e9c7ffd2c33
2025-05-16 12:05:12,729 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:12,729 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 4

2025-05-16 12:05:12,746 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:12,747 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:12,748 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:12,749 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:14,689 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:14,689 - Experiment - INFO - Existing run ID: 9345159fb5be4532bfc130acf3534204
2025-05-16 12:05:14,689 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:14,709 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:14,710 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:14,711 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:14,713 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:16,657 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:16,657 - Experiment - INFO - Existing run ID: 9345159fb5be4532bfc130acf3534204
2025-05-16 12:05:16,795 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:16,795 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 4

2025-05-16 12:05:16,814 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:16,814 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:16,815 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:16,816 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:18,769 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:18,769 - Experiment - INFO - Existing run ID: 31323945998f4b4faaa656d27a2b6e5e
2025-05-16 12:05:18,769 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:18,779 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:18,781 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:18,782 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:18,783 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:20,737 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:20,737 - Experiment - INFO - Existing run ID: 31323945998f4b4faaa656d27a2b6e5e
2025-05-16 12:05:20,874 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:20,875 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 4

2025-05-16 12:05:20,889 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:20,890 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:20,891 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:20,891 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:22,890 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:22,890 - Experiment - INFO - Existing run ID: 15215fb6a8b84888b921c81397470f6a
2025-05-16 12:05:22,890 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:22,899 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:22,900 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:22,901 - Experiment - INFO - Dataset signature: dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:22,901 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:24,844 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=isot,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:24,844 - Experiment - INFO - Existing run ID: 15215fb6a8b84888b921c81397470f6a
2025-05-16 12:05:24,979 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:24,979 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### Run 1 of 4

2025-05-16 12:05:25,001 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:25,002 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:25,003 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:25,003 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:26,997 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:26,997 - Experiment - INFO - Existing run ID: 2d9a83602fe54f9ea27f98e79066af41
2025-05-16 12:05:26,997 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:27,008 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:27,009 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:27,009 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:27,010 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:28,974 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:28,974 - Experiment - INFO - Existing run ID: 2d9a83602fe54f9ea27f98e79066af41
2025-05-16 12:05:29,108 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:29,108 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 2 of 4

2025-05-16 12:05:29,122 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:29,123 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:29,123 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:29,124 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:31,084 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:31,084 - Experiment - INFO - Existing run ID: 6d89176a1de34ca69ec4663f1794b332
2025-05-16 12:05:31,084 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:31,103 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:31,104 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:31,105 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:31,105 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:33,051 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:33,051 - Experiment - INFO - Existing run ID: 6d89176a1de34ca69ec4663f1794b332
2025-05-16 12:05:33,179 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:33,179 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 3 of 4

2025-05-16 12:05:33,200 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:33,201 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:33,201 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:33,203 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:35,207 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:35,207 - Experiment - INFO - Existing run ID: ffc05d6faae04c0aa0f7a0336ecddd15
2025-05-16 12:05:35,207 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:35,221 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:35,222 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:35,223 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:35,224 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:37,201 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:37,201 - Experiment - INFO - Existing run ID: ffc05d6faae04c0aa0f7a0336ecddd15
2025-05-16 12:05:37,337 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:37,338 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

### Run 4 of 4

2025-05-16 12:05:37,351 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:37,353 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:37,354 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:37,355 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:39,306 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:39,306 - Experiment - INFO - Existing run ID: 573b2e233d1f4fe68c12ccae7bd06f41
2025-05-16 12:05:39,306 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.
2025-05-16 12:05:39,329 - Experiment - INFO - MLflow experiment initialized with ID: 852930392549225895
2025-05-16 12:05:39,329 - Experiment - INFO - Model signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:39,330 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:39,330 - Experiment - INFO - Run signature: model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:41,261 - Experiment - INFO - Found existing run with signature model(mn=bert,ti=bert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),bert_base_uncased_encoder(t=bert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:05:41,261 - Experiment - INFO - Existing run ID: 573b2e233d1f4fe68c12ccae7bd06f41
2025-05-16 12:05:41,397 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:05:41,398 - Experiment - INFO - Model artifacts path does not exist. Could not prune artifacts...

In [ ]:
%cd ../distillibert
%run training.ipynb

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\workspace\notebooks\distillibert
Experiment: distillibert
Dataset Hyperparameters Grid Size:  8
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  8

### Run 1 of 8

2025/05/16 12:05:41 INFO mlflow.tracking.fluent: Experiment with name 'distillibert' does not exist. Creating a new experiment.
2025-05-16 12:05:41,622 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
2025-05-16 12:05:41,623 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:05:41,623 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:41,624 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:05:41,825 - Experiment - INFO - Run ID: 543cc24c779d495ea8a48b3a9d35b764
2025-05-16 12:05:41,825 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_12-05-41;rs=718206653
2025-05-16 12:05:41,853 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 12:05:41,868 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 12:05:42,012 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000011E77BFC5F0>]>
2025-05-16 12:05:42,388 - Experiment - INFO - Preprocessing function 0: distilli_bert__encoder
2025-05-16 12:05:42,388 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 12:05:42,388 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

2025-05-16 12:05:48,097 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 12:05:48,099 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 12:05:49,479 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 12:05:49,480 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 12:05:52,837 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 12:05:52,843 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 12:07:43,242 - Experiment - INFO - Evaluating model using accuracy metric...
2025-05-16 12:07:43,242 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-445
2025-05-16 12:07:43,427 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6311241984367371, 'eval_accuracy': 0.9046052631578947, 'eval_precision': 0.8917748917748918, 'eval_recall': 0.9809523809523809, 'eval_f1_score': 0.9342403628117913, 'eval_roc_auc': 0.9451874366767983, 'eval_false_positives_rate': 0.26595744680851063, 'eval_false_negatives_rate': 0.01904761904761905, 'eval_runtime': 2.9361, 'eval_samples_per_second': 103.539, 'eval_steps_per_second': 6.471, 'epoch': 5.0, 'step': 445}
2025-05-16 12:07:43,427 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 12:07:46,328 - Experiment - INFO - Test metrics: {'test_loss': 0.6164563298225403, 'test_accuracy': 0.8950819672131147, 'test_precision': 0.8778280542986425, 'test_recall': 0.9748743718592965, 'test_f1_score': 0.9238095238095239, 'test_roc_auc': 0.9384185076325021, 'test_false_positives_rate': 0.25471698113207547, 'test_false_negatives_rate': 0.02512562814070352, 'test_runtime': 2.8824, 'test_samples_per_second': 105.813, 'test_steps_per_second': 6.939, 'test_epoch': 5.0}
2025-05-16 12:07:46,361 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:07:46,372 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:07:47,031 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:07:47,031 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 12:07:47,031 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-267
2025-05-16 12:07:47,227 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3790765106678009, 'eval_accuracy': 0.8881578947368421, 'eval_precision': 0.9112149532710281, 'eval_recall': 0.9285714285714286, 'eval_f1_score': 0.9198113207547169, 'eval_roc_auc': 0.9385005065856129, 'eval_false_positives_rate': 0.20212765957446807, 'eval_false_negatives_rate': 0.07142857142857142, 'eval_runtime': 2.8794, 'eval_samples_per_second': 105.577, 'eval_steps_per_second': 6.599, 'epoch': 3.0, 'step': 267}
2025-05-16 12:07:47,227 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 12:07:48,469 - Experiment - INFO - Test metrics: {'test_loss': 0.40707793831825256, 'test_accuracy': 0.9016393442622951, 'test_precision': 0.9246231155778895, 'test_recall': 0.9246231155778895, 'test_f1_score': 0.9246231155778895, 'test_roc_auc': 0.9483739451976865, 'test_false_positives_rate': 0.14150943396226415, 'test_false_negatives_rate': 0.07537688442211055, 'test_runtime': 1.2395, 'test_samples_per_second': 246.06, 'test_steps_per_second': 16.135, 'test_epoch': 3.0}
2025-05-16 12:07:48,495 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:07:48,503 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:07:49,170 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:07:49,170 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 12:07:49,170 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-445
2025-05-16 12:07:49,345 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6311241984367371, 'eval_accuracy': 0.9046052631578947, 'eval_precision': 0.8917748917748918, 'eval_recall': 0.9809523809523809, 'eval_f1_score': 0.9342403628117913, 'eval_roc_auc': 0.9451874366767983, 'eval_false_positives_rate': 0.26595744680851063, 'eval_false_negatives_rate': 0.01904761904761905, 'eval_runtime': 2.9361, 'eval_samples_per_second': 103.539, 'eval_steps_per_second': 6.471, 'epoch': 5.0, 'step': 445}
2025-05-16 12:07:49,345 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 12:07:50,580 - Experiment - INFO - Test metrics: {'test_loss': 0.6164563298225403, 'test_accuracy': 0.8950819672131147, 'test_precision': 0.8778280542986425, 'test_recall': 0.9748743718592965, 'test_f1_score': 0.9238095238095239, 'test_roc_auc': 0.9384185076325021, 'test_false_positives_rate': 0.25471698113207547, 'test_false_negatives_rate': 0.02512562814070352, 'test_runtime': 1.2334, 'test_samples_per_second': 247.282, 'test_steps_per_second': 16.215, 'test_epoch': 5.0}
2025-05-16 12:07:50,604 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:07:50,613 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:07:51,296 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:07:51,296 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 12:07:51,296 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-267
2025-05-16 12:07:51,478 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3790765106678009, 'eval_accuracy': 0.8881578947368421, 'eval_precision': 0.9112149532710281, 'eval_recall': 0.9285714285714286, 'eval_f1_score': 0.9198113207547169, 'eval_roc_auc': 0.9385005065856129, 'eval_false_positives_rate': 0.20212765957446807, 'eval_false_negatives_rate': 0.07142857142857142, 'eval_runtime': 2.8794, 'eval_samples_per_second': 105.577, 'eval_steps_per_second': 6.599, 'epoch': 3.0, 'step': 267}
2025-05-16 12:07:51,478 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 12:07:52,726 - Experiment - INFO - Test metrics: {'test_loss': 0.40707793831825256, 'test_accuracy': 0.9016393442622951, 'test_precision': 0.9246231155778895, 'test_recall': 0.9246231155778895, 'test_f1_score': 0.9246231155778895, 'test_roc_auc': 0.9483739451976865, 'test_false_positives_rate': 0.14150943396226415, 'test_false_negatives_rate': 0.07537688442211055, 'test_runtime': 1.2306, 'test_samples_per_second': 247.852, 'test_steps_per_second': 16.253, 'test_epoch': 3.0}
2025-05-16 12:07:52,756 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:07:52,764 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:07:53,435 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:07:53,435 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 12:07:53,435 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 12:07:53,642 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4840156137943268, 'eval_accuracy': 0.9013157894736842, 'eval_precision': 0.9054054054054054, 'eval_recall': 0.9571428571428572, 'eval_f1_score': 0.9305555555555556, 'eval_roc_auc': 0.9518237082066869, 'eval_false_positives_rate': 0.22340425531914893, 'eval_false_negatives_rate': 0.04285714285714286, 'eval_runtime': 1.2234, 'eval_samples_per_second': 248.484, 'eval_steps_per_second': 15.53, 'epoch': 4.0, 'step': 356}
2025-05-16 12:07:53,643 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 12:07:54,880 - Experiment - INFO - Test metrics: {'test_loss': 0.4827880859375, 'test_accuracy': 0.9081967213114754, 'test_precision': 0.9130434782608695, 'test_recall': 0.949748743718593, 'test_f1_score': 0.9310344827586207, 'test_roc_auc': 0.9490613444581397, 'test_false_positives_rate': 0.16981132075471697, 'test_false_negatives_rate': 0.05025125628140704, 'test_runtime': 1.2346, 'test_samples_per_second': 247.035, 'test_steps_per_second': 16.199, 'test_epoch': 4.0}
2025-05-16 12:07:54,908 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:07:54,915 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:07:55,576 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:07:55,576 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 12:07:55,576 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-178
2025-05-16 12:07:55,778 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.35659676790237427, 'eval_accuracy': 0.8782894736842105, 'eval_precision': 0.8649789029535865, 'eval_recall': 0.9761904761904762, 'eval_f1_score': 0.9172259507829977, 'eval_roc_auc': 0.9370567375886525, 'eval_false_positives_rate': 0.3404255319148936, 'eval_false_negatives_rate': 0.023809523809523808, 'eval_runtime': 1.1996, 'eval_samples_per_second': 253.418, 'eval_steps_per_second': 15.839, 'epoch': 2.0, 'step': 178}
2025-05-16 12:07:55,778 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 12:07:58,680 - Experiment - INFO - Test metrics: {'test_loss': 0.419228732585907, 'test_accuracy': 0.8590163934426229, 'test_precision': 0.8421052631578947, 'test_recall': 0.964824120603015, 'test_f1_score': 0.8992974238875878, 'test_roc_auc': 0.9360481653550773, 'test_false_positives_rate': 0.33962264150943394, 'test_false_negatives_rate': 0.035175879396984924, 'test_runtime': 2.9009, 'test_samples_per_second': 105.14, 'test_steps_per_second': 6.894, 'test_epoch': 2.0}
2025-05-16 12:07:58,705 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:07:58,715 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:07:59,395 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:07:59,395 - Experiment - INFO - Finished model evaluations stage.
2025-05-16 12:08:00,396 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
2025-05-16 12:08:00,412 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:08:00,412 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:08:00,412 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:08:01,015 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:08:01,015 - Experiment - INFO - Existing run ID: 543cc24c779d495ea8a48b3a9d35b764
2025-05-16 12:08:01,146 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:08:01,535 - Experiment - INFO - Pruning models artifacts done...

### Run 2 of 8

2025-05-16 12:08:01,562 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
2025-05-16 12:08:01,563 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:08:01,563 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:08:01,564 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:08:01,686 - Experiment - INFO - Run ID: b45a2f7bbfd640fcbc6ffb7a61f76392
2025-05-16 12:08:01,686 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_12-08-01;rs=2887865862
2025-05-16 12:08:01,698 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 12:08:01,716 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 12:08:01,870 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000011E77BFECC0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000011E77BFFCE0>]>
2025-05-16 12:08:02,029 - Experiment - INFO - Preprocessing function 0: noise_reduction
2025-05-16 12:08:02,030 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 12:08:02,031 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:08:03,267 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 12:08:03,267 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:08:03,540 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 12:08:03,540 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:08:03,975 - Experiment - INFO - Preprocessing function 1: distilli_bert__encoder
2025-05-16 12:08:03,975 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 12:08:03,975 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

2025-05-16 12:08:09,459 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 12:08:09,460 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Map:   0%|          | 0/304 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 12:08:10,787 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 12:08:10,789 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Map:   0%|          | 0/305 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/2 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 12:08:14,054 - Experiment - INFO - Model name: DistilliBERT
2025-05-16 12:08:14,057 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 12:09:47,318 - Experiment - INFO - Evaluating model using accuracy metric...
2025-05-16 12:09:47,319 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-178
2025-05-16 12:09:47,542 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.503424882888794, 'eval_accuracy': 0.8388157894736842, 'eval_precision': 0.8285714285714286, 'eval_recall': 0.9666666666666667, 'eval_f1_score': 0.8923076923076924, 'eval_roc_auc': 0.8977710233029381, 'eval_false_positives_rate': 0.44680851063829785, 'eval_false_negatives_rate': 0.03333333333333333, 'eval_runtime': 1.2319, 'eval_samples_per_second': 246.771, 'eval_steps_per_second': 15.423, 'epoch': 2.0, 'step': 178}
2025-05-16 12:09:47,543 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 12:09:48,795 - Experiment - INFO - Test metrics: {'test_loss': 0.5126537680625916, 'test_accuracy': 0.8426229508196721, 'test_precision': 0.8209606986899564, 'test_recall': 0.9641025641025641, 'test_f1_score': 0.8867924528301887, 'test_roc_auc': 0.933939393939394, 'test_false_positives_rate': 0.37272727272727274, 'test_false_negatives_rate': 0.035897435897435895, 'test_runtime': 1.2473, 'test_samples_per_second': 244.524, 'test_steps_per_second': 16.034, 'test_epoch': 2.0}
2025-05-16 12:09:48,820 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:09:48,828 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:09:49,503 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:09:49,503 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 12:09:49,503 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 12:09:49,697 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9008463621139526, 'eval_accuracy': 0.8355263157894737, 'eval_precision': 0.9081632653061225, 'eval_recall': 0.8476190476190476, 'eval_f1_score': 0.8768472906403941, 'eval_roc_auc': 0.9109422492401216, 'eval_false_positives_rate': 0.19148936170212766, 'eval_false_negatives_rate': 0.1523809523809524, 'eval_runtime': 1.2272, 'eval_samples_per_second': 247.728, 'eval_steps_per_second': 15.483, 'epoch': 4.0, 'step': 356}
2025-05-16 12:09:49,698 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 12:09:50,932 - Experiment - INFO - Test metrics: {'test_loss': 0.6106904745101929, 'test_accuracy': 0.8852459016393442, 'test_precision': 0.9301075268817204, 'test_recall': 0.8871794871794871, 'test_f1_score': 0.9081364829396326, 'test_roc_auc': 0.9518414918414918, 'test_false_positives_rate': 0.11818181818181818, 'test_false_negatives_rate': 0.11282051282051282, 'test_runtime': 1.2289, 'test_samples_per_second': 248.181, 'test_steps_per_second': 16.274, 'test_epoch': 4.0}
2025-05-16 12:09:50,961 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:09:50,969 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:09:51,679 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:09:51,679 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 12:09:51,679 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-178
2025-05-16 12:09:51,924 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.503424882888794, 'eval_accuracy': 0.8388157894736842, 'eval_precision': 0.8285714285714286, 'eval_recall': 0.9666666666666667, 'eval_f1_score': 0.8923076923076924, 'eval_roc_auc': 0.8977710233029381, 'eval_false_positives_rate': 0.44680851063829785, 'eval_false_negatives_rate': 0.03333333333333333, 'eval_runtime': 1.2319, 'eval_samples_per_second': 246.771, 'eval_steps_per_second': 15.423, 'epoch': 2.0, 'step': 178}
2025-05-16 12:09:51,925 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 12:09:53,180 - Experiment - INFO - Test metrics: {'test_loss': 0.5126537680625916, 'test_accuracy': 0.8426229508196721, 'test_precision': 0.8209606986899564, 'test_recall': 0.9641025641025641, 'test_f1_score': 0.8867924528301887, 'test_roc_auc': 0.933939393939394, 'test_false_positives_rate': 0.37272727272727274, 'test_false_negatives_rate': 0.035897435897435895, 'test_runtime': 1.2497, 'test_samples_per_second': 244.058, 'test_steps_per_second': 16.004, 'test_epoch': 2.0}
2025-05-16 12:09:53,203 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:09:53,210 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:09:53,922 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:09:53,922 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 12:09:53,922 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-356
2025-05-16 12:09:54,119 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9008463621139526, 'eval_accuracy': 0.8355263157894737, 'eval_precision': 0.9081632653061225, 'eval_recall': 0.8476190476190476, 'eval_f1_score': 0.8768472906403941, 'eval_roc_auc': 0.9109422492401216, 'eval_false_positives_rate': 0.19148936170212766, 'eval_false_negatives_rate': 0.1523809523809524, 'eval_runtime': 1.2272, 'eval_samples_per_second': 247.728, 'eval_steps_per_second': 15.483, 'epoch': 4.0, 'step': 356}
2025-05-16 12:09:54,120 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 12:09:55,380 - Experiment - INFO - Test metrics: {'test_loss': 0.6106904745101929, 'test_accuracy': 0.8852459016393442, 'test_precision': 0.9301075268817204, 'test_recall': 0.8871794871794871, 'test_f1_score': 0.9081364829396326, 'test_roc_auc': 0.9518414918414918, 'test_false_positives_rate': 0.11818181818181818, 'test_false_negatives_rate': 0.11282051282051282, 'test_runtime': 1.2534, 'test_samples_per_second': 243.344, 'test_steps_per_second': 15.957, 'test_epoch': 4.0}
2025-05-16 12:09:55,407 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:09:55,416 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:09:56,140 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:09:56,146 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 12:09:56,146 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-267
2025-05-16 12:09:56,373 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6023538708686829, 'eval_accuracy': 0.8388157894736842, 'eval_precision': 0.9045226130653267, 'eval_recall': 0.8571428571428571, 'eval_f1_score': 0.8801955990220048, 'eval_roc_auc': 0.9142857142857143, 'eval_false_positives_rate': 0.20212765957446807, 'eval_false_negatives_rate': 0.14285714285714285, 'eval_runtime': 1.2245, 'eval_samples_per_second': 248.259, 'eval_steps_per_second': 15.516, 'epoch': 3.0, 'step': 267}
2025-05-16 12:09:56,375 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 12:09:57,669 - Experiment - INFO - Test metrics: {'test_loss': 0.3808479905128479, 'test_accuracy': 0.8852459016393442, 'test_precision': 0.925531914893617, 'test_recall': 0.8923076923076924, 'test_f1_score': 0.9086161879895561, 'test_roc_auc': 0.9576689976689977, 'test_false_positives_rate': 0.12727272727272726, 'test_false_negatives_rate': 0.1076923076923077, 'test_runtime': 1.2874, 'test_samples_per_second': 236.916, 'test_steps_per_second': 15.536, 'test_epoch': 3.0}
2025-05-16 12:09:57,700 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:09:57,709 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:09:58,423 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:09:58,423 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 12:09:58,423 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-89
2025-05-16 12:09:58,686 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.412202388048172, 'eval_accuracy': 0.805921052631579, 'eval_precision': 0.8240343347639485, 'eval_recall': 0.9142857142857143, 'eval_f1_score': 0.8668171557562077, 'eval_roc_auc': 0.8747213779128672, 'eval_false_positives_rate': 0.43617021276595747, 'eval_false_negatives_rate': 0.08571428571428572, 'eval_runtime': 1.2191, 'eval_samples_per_second': 249.368, 'eval_steps_per_second': 15.585, 'epoch': 1.0, 'step': 89}
2025-05-16 12:09:58,687 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 12:09:59,952 - Experiment - INFO - Test metrics: {'test_loss': 0.3707558214664459, 'test_accuracy': 0.819672131147541, 'test_precision': 0.8097345132743363, 'test_recall': 0.9384615384615385, 'test_f1_score': 0.8693586698337292, 'test_roc_auc': 0.9338927738927739, 'test_false_positives_rate': 0.39090909090909093, 'test_false_negatives_rate': 0.06153846153846154, 'test_runtime': 1.2602, 'test_samples_per_second': 242.022, 'test_steps_per_second': 15.87, 'test_epoch': 1.0}
2025-05-16 12:09:59,977 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 12:09:59,984 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 12:10:00,741 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 12:10:00,742 - Experiment - INFO - Finished model evaluations stage.
2025-05-16 12:10:01,474 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
2025-05-16 12:10:01,474 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:10:01,474 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:10:01,474 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:10:02,354 - Experiment - INFO - Found existing run with signature model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 12:10:02,355 - Experiment - INFO - Existing run ID: b45a2f7bbfd640fcbc6ffb7a61f76392
2025-05-16 12:10:02,510 - Experiment - INFO - Pruning models artifacts to free space...
2025-05-16 12:10:02,903 - Experiment - INFO - Pruning models artifacts done...

### Run 3 of 8

2025-05-16 12:10:02,929 - Experiment - INFO - MLflow experiment initialized with ID: 580058141891138922
2025-05-16 12:10:02,930 - Experiment - INFO - Model signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 12:10:02,931 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:10:02,932 - Experiment - INFO - Run signature: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 12:10:03,138 - Experiment - INFO - Run ID: a8667e40ae5f4bd4850881a05c6a9417
2025-05-16 12:10:03,138 - Experiment - INFO - Run name: model(mn=distillibert,ti=distilbert-base-uncased,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),distilli_bert__encoder(t=distilbert-base-uncased,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_12-10-03;rs=1178019432
2025-05-16 12:10:03,151 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 12:10:03,197 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 12:10:03,372 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000011E77BFDDF0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000011E77BFEB40>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000011E77BFF3E0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.DistilliBERT_Encoder object at 0x0000011E77B92210>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 12:10:03,635 - Experiment - INFO - Preprocessing function 0: noise_reduction
2025-05-16 12:10:03,636 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 12:10:03,637 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:10:04,918 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 12:10:04,918 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:10:05,226 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 12:10:05,226 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 12:10:05,517 - Experiment - INFO - Preprocessing function 1: nltk_tokenizer
2025-05-16 12:10:05,517 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 12:10:05,518 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:10:09,131 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 12:10:09,131 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:10:09,934 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 12:10:09,934 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:10:10,658 - Experiment - INFO - Preprocessing function 2: lemmatization
2025-05-16 12:10:10,658 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 12:10:10,658 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:10:11,778 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 12:10:11,794 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:10:12,043 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 12:10:12,047 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 12:10:12,460 - Experiment - INFO - Preprocessing function 3: distilli_bert__encoder
2025-05-16 12:10:12,461 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 12:10:12,466 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/1420 [00:00<?, ? examples/s]

In [ ]:
%cd ../roberta
%run training.ipynb

In [ ]:
%cd ../openai_gpt1
%run training.ipynb

In [ ]:
%cd ../openai_gpt2
%run training.ipynb