In [1]:
from workspace.sources.local_datasets.preprocessing.tokenization import NLTKTokenizer
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction, Lemmatization, Stemming
from workspace.sources.experiments.metrics import Loss
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.utils import class_name_to_str
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.local_datasets.preprocessing.utils import truncate
from sklearn.model_selection import ParameterGrid
from IPython.display import display, Markdown

from workspace.sources.local_datasets.preprocessing.encoders.encoders import RoBERTaEncoder as Encoder
from workspace.sources.models.transformers.bert_based_models import RoBERTa as Model

import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [2]:
experiment_name = f'prefinal-{class_name_to_str(Model.__name__.lower())}-v2'
print('Experiment:', experiment_name)

Experiment: prefinal-ro_ber_ta-v2

In [3]:
def conduct_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid):
    total_runs = len(dataset_hparams_grid) * len(model_hparams_grid)
    for i, dataset_params in enumerate(dataset_hparams_grid):
        for j, model_hparams in enumerate(model_hparams_grid):
            run_number = i * len(model_hparams_grid) + j + 1
            display(Markdown(f'### Run {run_number} of {total_runs}'))
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = Model(train_best_model_metric=Loss,
                           training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            recovery_experiment.run()

In [4]:

# max_tokens_params = [128, 512]
max_tokens_params = [128]

pipelines = []

for max_tokens in max_tokens_params:
    pipelines.extend([PreprocessingPipeline(name='minimal',
                                            iterable=[Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction',
                                            iterable=[NoiseReduction(),
                                                      Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Lemmatization(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_stemming',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Stemming(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)])
                      ])
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(pipelines, fraction=0.05)

dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': pipelines})

print('Dataset Hyperparameters Grid Size: ', len(dataset_hparams_grid))

# model_hparams_grid = ParameterGrid({'epochs': [10],
#                                     'batch_size': [16],
#                                     'learning_rate': [1e-05, 5e-05],
#                                     'lr_scheduler': ['linear'],
#                                     'optimizer': ['adamw_torch'],
#                                     'weight_decay': [0.0, 1e-3],
#                                     'early_stopping_patience': [3],
#                                     'early_stopping_threshold': [0.01]})

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16],
                                    'learning_rate': [5e-05],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})

print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### ReCOVery Dataset

In [5]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 4

2025-05-16 02:14:30,089 - Experiment - INFO - MLflow experiment initialized with ID: 407824870238116211
2025-05-16 02:14:30,090 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 02:14:30,091 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:14:30,091 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:14:30,216 - Experiment - INFO - Found existing run with signature model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:14:30,216 - Experiment - INFO - Existing run ID: 78326fa052f945a283f99bb870442dc3
2025-05-16 02:14:30,217 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 2 of 4

2025-05-16 02:14:30,226 - Experiment - INFO - MLflow experiment initialized with ID: 407824870238116211
2025-05-16 02:14:30,227 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 02:14:30,227 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:14:30,228 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:14:30,347 - Experiment - INFO - Found existing run with signature model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:14:30,348 - Experiment - INFO - Existing run ID: 7cd707c13e9d41d8ba1f7450fbe82493
2025-05-16 02:14:30,348 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 3 of 4

2025-05-16 02:14:30,357 - Experiment - INFO - MLflow experiment initialized with ID: 407824870238116211
2025-05-16 02:14:30,358 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 02:14:30,359 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 02:14:30,359 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 02:14:30,812 - Experiment - INFO - Run ID: 0adf4d4676b54a559dd65e0042ef5706
2025-05-16 02:14:30,813 - Experiment - INFO - Run name: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_02-14-30;rs=266382915
2025-05-16 02:14:30,825 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:14:30,865 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:14:31,026 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000018B8D487440>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000018B8D486E10>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000018B8D486AB0>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000018B8D486C00>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.RoBERTaEncoder object at 0x0000018B8D486B10>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:14:31,652 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:14:31,652 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:14:31,652 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:31,682 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:14:31,684 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:31,699 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:14:31,701 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:31,715 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:14:31,716 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:14:31,719 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:31,782 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:14:31,784 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:31,804 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:14:31,805 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:14:31,825 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 02:14:31,826 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:14:31,826 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:32,024 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:14:32,025 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:32,067 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:14:32,067 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:32,106 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 02:14:32,108 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:14:32,109 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:32,249 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:14:32,251 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:32,278 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:14:32,280 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:14:32,612 - Experiment - INFO - Preprocessing function 4: ro_ber_ta_encoder
2025-05-16 02:14:32,613 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:14:32,615 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:14:33,417 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:14:33,419 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:14:33,817 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:14:33,818 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:14:34,594 - Experiment - INFO - Model name: RoBERTa
2025-05-16 02:14:34,600 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:15:08,170 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:15:08,170 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 02:15:08,594 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2626062035560608, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 0.9285714285714286, 'eval_recall': 1.0, 'eval_f1_score': 0.9629629629629629, 'eval_roc_auc': 0.9230769230769231, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1277, 'eval_samples_per_second': 117.449, 'eval_steps_per_second': 7.83, 'epoch': 4.0, 'step': 20}
2025-05-16 02:15:08,595 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:15:09,079 - Experiment - INFO - Test metrics: {'test_loss': 0.23504997789859772, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.4743, 'test_samples_per_second': 31.623, 'test_steps_per_second': 2.108, 'test_epoch': 4.0}
2025-05-16 02:15:09,191 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:15:09,201 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:15:09,469 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:15:09,473 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:15:09,477 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 02:15:11,022 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2626062035560608, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 0.9285714285714286, 'eval_recall': 1.0, 'eval_f1_score': 0.9629629629629629, 'eval_roc_auc': 0.9230769230769231, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1277, 'eval_samples_per_second': 117.449, 'eval_steps_per_second': 7.83, 'epoch': 4.0, 'step': 20}
2025-05-16 02:15:11,023 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:15:11,400 - Experiment - INFO - Test metrics: {'test_loss': 0.23504997789859772, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.3734, 'test_samples_per_second': 40.169, 'test_steps_per_second': 2.678, 'test_epoch': 4.0}
2025-05-16 02:15:11,421 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:15:11,422 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:15:11,461 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:15:11,462 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:15:11,462 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 02:15:11,923 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2626062035560608, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 0.9285714285714286, 'eval_recall': 1.0, 'eval_f1_score': 0.9629629629629629, 'eval_roc_auc': 0.9230769230769231, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1277, 'eval_samples_per_second': 117.449, 'eval_steps_per_second': 7.83, 'epoch': 4.0, 'step': 20}
2025-05-16 02:15:11,923 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:15:12,067 - Experiment - INFO - Test metrics: {'test_loss': 0.23504997789859772, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1315, 'test_samples_per_second': 114.094, 'test_steps_per_second': 7.606, 'test_epoch': 4.0}
2025-05-16 02:15:12,089 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:15:12,091 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:15:12,141 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:15:12,142 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:15:12,143 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 02:15:12,604 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3088720440864563, 'eval_accuracy': 0.8666666666666667, 'eval_precision': 0.8666666666666667, 'eval_recall': 1.0, 'eval_f1_score': 0.9285714285714286, 'eval_roc_auc': 0.9615384615384616, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.153, 'eval_samples_per_second': 98.057, 'eval_steps_per_second': 6.537, 'epoch': 3.0, 'step': 15}
2025-05-16 02:15:12,604 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:15:12,740 - Experiment - INFO - Test metrics: {'test_loss': 0.2772560715675354, 'test_accuracy': 0.8, 'test_precision': 0.8, 'test_recall': 1.0, 'test_f1_score': 0.8888888888888888, 'test_roc_auc': 1.0, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1358, 'test_samples_per_second': 110.455, 'test_steps_per_second': 7.364, 'test_epoch': 3.0}
2025-05-16 02:15:12,761 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:15:12,764 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:15:12,806 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:15:12,807 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:15:12,809 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 02:15:13,271 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.2626062035560608, 'eval_accuracy': 0.9333333333333333, 'eval_precision': 0.9285714285714286, 'eval_recall': 1.0, 'eval_f1_score': 0.9629629629629629, 'eval_roc_auc': 0.9230769230769231, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1277, 'eval_samples_per_second': 117.449, 'eval_steps_per_second': 7.83, 'epoch': 4.0, 'step': 20}
2025-05-16 02:15:13,286 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:15:13,419 - Experiment - INFO - Test metrics: {'test_loss': 0.23504997789859772, 'test_accuracy': 0.8666666666666667, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.6666666666666666, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1298, 'test_samples_per_second': 115.528, 'test_steps_per_second': 7.702, 'test_epoch': 4.0}
2025-05-16 02:15:13,441 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:15:13,442 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:15:13,482 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:15:13,482 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 02:15:14,237 - Experiment - INFO - MLflow experiment initialized with ID: 407824870238116211
2025-05-16 02:15:14,237 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 02:15:14,237 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 02:15:14,240 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 02:15:14,757 - Experiment - INFO - Run ID: 705b97a4338b4695a874b956d8836855
2025-05-16 02:15:14,757 - Experiment - INFO - Run name: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_02-15-14;rs=1327207743
2025-05-16 02:15:14,768 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:15:14,802 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:15:14,977 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000018B8D487470>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000018B8D486E70>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000018B8D4869C0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000018B8D487410>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.RoBERTaEncoder object at 0x0000018B8D486CC0>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:15:15,222 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:15:15,223 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:15:15,223 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:15,236 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:15:15,237 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:15,245 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:15:15,245 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:15,254 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:15:15,256 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:15:15,257 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:15,318 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:15:15,319 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:15,335 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:15:15,336 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:15:15,360 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 02:15:15,360 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:15:15,361 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:15,518 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:15:15,519 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:15,549 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:15:15,550 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:15,597 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 02:15:15,598 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:15:15,599 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:16,105 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:15:16,107 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:16,192 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:15:16,192 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:15:16,621 - Experiment - INFO - Preprocessing function 4: ro_ber_ta_encoder
2025-05-16 02:15:16,622 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:15:16,623 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:15:17,374 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:15:17,376 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:15:17,590 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:15:17,591 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:15:18,400 - Experiment - INFO - Model name: RoBERTa
2025-05-16 02:15:18,403 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:16:03,122 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:16:03,122 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-45
2025-05-16 02:16:03,573 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6796987056732178, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.7272727272727273, 'eval_recall': 0.8888888888888888, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.8333333333333333, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.1111111111111111, 'eval_runtime': 0.1387, 'eval_samples_per_second': 108.132, 'eval_steps_per_second': 7.209, 'epoch': 9.0, 'step': 45}
2025-05-16 02:16:03,573 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-16 02:16:03,763 - Experiment - INFO - Test metrics: {'test_loss': 1.4969736337661743, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.7222222222222222, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1716, 'test_samples_per_second': 87.401, 'test_steps_per_second': 5.827, 'test_epoch': 9.0}
2025-05-16 02:16:03,780 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:16:03,782 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:16:03,820 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:16:03,821 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:16:03,822 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 02:16:04,303 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.583891749382019, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.6923076923076923, 'eval_recall': 1.0, 'eval_f1_score': 0.8181818181818182, 'eval_roc_auc': 0.9259259259259259, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1548, 'eval_samples_per_second': 96.911, 'eval_steps_per_second': 6.461, 'epoch': 7.0, 'step': 35}
2025-05-16 02:16:04,304 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 02:16:04,442 - Experiment - INFO - Test metrics: {'test_loss': 1.502776861190796, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.6666666666666667, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1334, 'test_samples_per_second': 112.405, 'test_steps_per_second': 7.494, 'test_epoch': 7.0}
2025-05-16 02:16:04,461 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:16:04,463 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:16:04,503 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:16:04,503 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:16:04,504 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-45
2025-05-16 02:16:04,967 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6796987056732178, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.7272727272727273, 'eval_recall': 0.8888888888888888, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.8333333333333333, 'eval_false_positives_rate': 0.5, 'eval_false_negatives_rate': 0.1111111111111111, 'eval_runtime': 0.1387, 'eval_samples_per_second': 108.132, 'eval_steps_per_second': 7.209, 'epoch': 9.0, 'step': 45}
2025-05-16 02:16:04,968 - Experiment - INFO - Best model found at epoch 9.0.

2025-05-16 02:16:05,104 - Experiment - INFO - Test metrics: {'test_loss': 1.4969736337661743, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.7222222222222222, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1323, 'test_samples_per_second': 113.354, 'test_steps_per_second': 7.557, 'test_epoch': 9.0}
2025-05-16 02:16:05,122 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:16:05,126 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:16:05,166 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:16:05,167 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:16:05,169 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 02:16:05,711 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9430989027023315, 'eval_accuracy': 0.6, 'eval_precision': 0.6, 'eval_recall': 1.0, 'eval_f1_score': 0.75, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.1272, 'eval_samples_per_second': 117.945, 'eval_steps_per_second': 7.863, 'epoch': 4.0, 'step': 20}
2025-05-16 02:16:05,712 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:16:05,856 - Experiment - INFO - Test metrics: {'test_loss': 1.165282964706421, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.537037037037037, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1379, 'test_samples_per_second': 108.77, 'test_steps_per_second': 7.251, 'test_epoch': 4.0}
2025-05-16 02:16:05,885 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:16:05,888 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:16:05,940 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:16:05,942 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:16:05,942 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-30
2025-05-16 02:16:06,542 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5153636336326599, 'eval_accuracy': 0.6, 'eval_precision': 0.6363636363636364, 'eval_recall': 0.7777777777777778, 'eval_f1_score': 0.7, 'eval_roc_auc': 0.7592592592592592, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.2222222222222222, 'eval_runtime': 0.1357, 'eval_samples_per_second': 110.557, 'eval_steps_per_second': 7.37, 'epoch': 6.0, 'step': 30}
2025-05-16 02:16:06,543 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 02:16:06,679 - Experiment - INFO - Test metrics: {'test_loss': 0.852662980556488, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.6296296296296297, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1328, 'test_samples_per_second': 112.963, 'test_steps_per_second': 7.531, 'test_epoch': 6.0}
2025-05-16 02:16:06,698 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:16:06,701 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:16:06,744 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:16:06,745 - Experiment - INFO - Finished model evaluations stage.

### EUvsDisinfo Dataset

In [ ]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### ISOT Dataset

In [ ]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          dataset_hparams_grid,
                          model_hparams_grid)

### CZ Dataset

In [6]:
cz_pipelines = []

for max_tokens in max_tokens_params:
    cz_pipelines.extend([PreprocessingPipeline(name='minimal',
                                               iterable=[Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction',
                                               iterable=[NoiseReduction(),
                                                         Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Lemmatization(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_stemming',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Stemming(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)])
                         ])
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(cz_pipelines, fraction=0.15)

cz_dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': cz_pipelines})
print('Dataset Hyperparameters Grid Size: ', len(cz_dataset_hparams_grid))
print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(cz_dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

In [7]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_model_experiments(dataset_name,
                          dataset_path,
                          cz_dataset_hparams_grid,
                          model_hparams_grid)

### Run 1 of 4

2025-05-16 02:16:07,315 - Experiment - INFO - MLflow experiment initialized with ID: 407824870238116211
2025-05-16 02:16:07,316 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 02:16:07,317 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:16:07,317 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:16:08,531 - Experiment - INFO - Run ID: 607a37c07e7c404ba80bde99c82861a9
2025-05-16 02:16:08,532 - Experiment - INFO - Run name: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_02-16-08;rs=2180842552
2025-05-16 02:16:08,550 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:16:08,582 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:16:08,714 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000018B8E7D5AC0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.RoBERTaEncoder object at 0x0000018B8E7D5280>]>
2025-05-16 02:16:09,002 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:16:09,003 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:16:09,004 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:16:09,023 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:16:09,024 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:16:09,033 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:16:09,034 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:16:09,328 - Experiment - INFO - Preprocessing function 1: ro_ber_ta_encoder
2025-05-16 02:16:09,330 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:16:09,331 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:16:09,933 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:16:09,934 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:16:10,145 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:16:10,147 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:16:10,721 - Experiment - INFO - Model name: RoBERTa
2025-05-16 02:16:10,726 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:16:58,126 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:16:58,126 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 02:16:58,615 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.02285902388393879, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2125, 'eval_samples_per_second': 103.55, 'eval_steps_per_second': 9.414, 'epoch': 5.0, 'step': 35}
2025-05-16 02:16:58,615 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 02:16:58,840 - Experiment - INFO - Test metrics: {'test_loss': 0.5236748456954956, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.9285714285714286, 'test_roc_auc': 0.8205128205128205, 'test_false_positives_rate': 0.2222222222222222, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.2192, 'test_samples_per_second': 100.357, 'test_steps_per_second': 9.123, 'test_epoch': 5.0}
2025-05-16 02:16:58,864 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:16:58,867 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:16:58,927 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:16:58,929 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:16:58,930 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 02:16:59,376 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.02285902388393879, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2125, 'eval_samples_per_second': 103.55, 'eval_steps_per_second': 9.414, 'epoch': 5.0, 'step': 35}
2025-05-16 02:16:59,377 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 02:16:59,723 - Experiment - INFO - Test metrics: {'test_loss': 0.5236748456954956, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.9285714285714286, 'test_roc_auc': 0.8205128205128205, 'test_false_positives_rate': 0.2222222222222222, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.3383, 'test_samples_per_second': 65.039, 'test_steps_per_second': 5.913, 'test_epoch': 5.0}
2025-05-16 02:16:59,805 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:16:59,814 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:00,290 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:00,295 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:17:00,301 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 02:17:01,887 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.02285902388393879, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2125, 'eval_samples_per_second': 103.55, 'eval_steps_per_second': 9.414, 'epoch': 5.0, 'step': 35}
2025-05-16 02:17:01,888 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 02:17:02,308 - Experiment - INFO - Test metrics: {'test_loss': 0.5236748456954956, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.9285714285714286, 'test_roc_auc': 0.8205128205128205, 'test_false_positives_rate': 0.2222222222222222, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.4157, 'test_samples_per_second': 52.929, 'test_steps_per_second': 4.812, 'test_epoch': 5.0}
2025-05-16 02:17:02,329 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:17:02,331 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:02,386 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:02,387 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:17:02,388 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 02:17:02,859 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.02285902388393879, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2125, 'eval_samples_per_second': 103.55, 'eval_steps_per_second': 9.414, 'epoch': 5.0, 'step': 35}
2025-05-16 02:17:02,859 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 02:17:03,056 - Experiment - INFO - Test metrics: {'test_loss': 0.5236748456954956, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.9285714285714286, 'test_roc_auc': 0.8205128205128205, 'test_false_positives_rate': 0.2222222222222222, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.195, 'test_samples_per_second': 112.842, 'test_steps_per_second': 10.258, 'test_epoch': 5.0}
2025-05-16 02:17:03,076 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:17:03,078 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:03,140 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:03,141 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:17:03,141 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 02:17:03,594 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.02285902388393879, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1_score': 1.0, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2125, 'eval_samples_per_second': 103.55, 'eval_steps_per_second': 9.414, 'epoch': 5.0, 'step': 35}
2025-05-16 02:17:03,594 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 02:17:03,788 - Experiment - INFO - Test metrics: {'test_loss': 0.5236748456954956, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8666666666666667, 'test_recall': 1.0, 'test_f1_score': 0.9285714285714286, 'test_roc_auc': 0.8205128205128205, 'test_false_positives_rate': 0.2222222222222222, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1929, 'test_samples_per_second': 114.066, 'test_steps_per_second': 10.37, 'test_epoch': 5.0}
2025-05-16 02:17:03,810 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:17:03,812 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:03,873 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:03,874 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 4

2025-05-16 02:17:04,202 - Experiment - INFO - MLflow experiment initialized with ID: 407824870238116211
2025-05-16 02:17:04,203 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 02:17:04,204 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:17:04,204 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)])
2025-05-16 02:17:05,093 - Experiment - INFO - Run ID: 64f21176bd384b67a6d44ff7a8bd2711
2025-05-16 02:17:05,093 - Experiment - INFO - Run name: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=false)]);2025-05-16_02-17-05;rs=901513313
2025-05-16 02:17:05,106 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:17:05,133 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:17:05,238 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000018B8E7D4860>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000018B8E7D5880>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.RoBERTaEncoder object at 0x0000018B8E7D7410>]>
2025-05-16 02:17:05,478 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:17:05,479 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:17:05,480 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:05,492 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:17:05,492 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:05,504 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:17:05,505 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:05,516 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:17:05,517 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:17:05,518 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:05,592 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:17:05,594 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:05,620 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:17:05,621 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:06,236 - Experiment - INFO - Preprocessing function 2: ro_ber_ta_encoder
2025-05-16 02:17:06,236 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:17:06,237 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:17:06,883 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:17:06,884 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:17:07,090 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:17:07,092 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:17:07,661 - Experiment - INFO - Model name: RoBERTa
2025-05-16 02:17:07,665 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:17:38,283 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:17:38,284 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:17:38,790 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 1.0442763566970825, 'eval_accuracy': 0.7727272727272727, 'eval_precision': 1.0, 'eval_recall': 0.5833333333333334, 'eval_f1_score': 0.7368421052631579, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.4166666666666667, 'eval_runtime': 0.2104, 'eval_samples_per_second': 104.552, 'eval_steps_per_second': 9.505, 'epoch': 4.0, 'step': 28}
2025-05-16 02:17:38,791 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:17:39,034 - Experiment - INFO - Test metrics: {'test_loss': 1.0818850994110107, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.8888888888888888, 'test_recall': 0.6153846153846154, 'test_f1_score': 0.7272727272727273, 'test_roc_auc': 0.8974358974358976, 'test_false_positives_rate': 0.1111111111111111, 'test_false_negatives_rate': 0.38461538461538464, 'test_runtime': 0.2383, 'test_samples_per_second': 92.324, 'test_steps_per_second': 8.393, 'test_epoch': 4.0}
2025-05-16 02:17:39,057 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:17:39,060 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:39,125 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:39,126 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:17:39,127 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-21
2025-05-16 02:17:39,595 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3012712299823761, 'eval_accuracy': 0.9090909090909091, 'eval_precision': 0.8571428571428571, 'eval_recall': 1.0, 'eval_f1_score': 0.9230769230769231, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.2, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2074, 'eval_samples_per_second': 106.087, 'eval_steps_per_second': 9.644, 'epoch': 3.0, 'step': 21}
2025-05-16 02:17:39,597 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:17:39,783 - Experiment - INFO - Test metrics: {'test_loss': 0.6059758067131042, 'test_accuracy': 0.8181818181818182, 'test_precision': 0.8, 'test_recall': 0.9230769230769231, 'test_f1_score': 0.8571428571428571, 'test_roc_auc': 0.9145299145299146, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.07692307692307693, 'test_runtime': 0.1815, 'test_samples_per_second': 121.202, 'test_steps_per_second': 11.018, 'test_epoch': 3.0}
2025-05-16 02:17:39,802 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:17:39,804 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:39,862 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:39,863 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:17:39,864 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:17:40,330 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 1.0442763566970825, 'eval_accuracy': 0.7727272727272727, 'eval_precision': 1.0, 'eval_recall': 0.5833333333333334, 'eval_f1_score': 0.7368421052631579, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.4166666666666667, 'eval_runtime': 0.2104, 'eval_samples_per_second': 104.552, 'eval_steps_per_second': 9.505, 'epoch': 4.0, 'step': 28}
2025-05-16 02:17:40,331 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:17:40,522 - Experiment - INFO - Test metrics: {'test_loss': 1.0818850994110107, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.8888888888888888, 'test_recall': 0.6153846153846154, 'test_f1_score': 0.7272727272727273, 'test_roc_auc': 0.8974358974358976, 'test_false_positives_rate': 0.1111111111111111, 'test_false_negatives_rate': 0.38461538461538464, 'test_runtime': 0.1858, 'test_samples_per_second': 118.423, 'test_steps_per_second': 10.766, 'test_epoch': 4.0}
2025-05-16 02:17:40,540 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:17:40,542 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:40,599 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:40,600 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:17:40,600 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 02:17:41,075 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.23435594141483307, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.8, 'eval_recall': 1.0, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.3, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2144, 'eval_samples_per_second': 102.612, 'eval_steps_per_second': 9.328, 'epoch': 2.0, 'step': 14}
2025-05-16 02:17:41,076 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 02:17:41,280 - Experiment - INFO - Test metrics: {'test_loss': 0.5437412261962891, 'test_accuracy': 0.8636363636363636, 'test_precision': 0.8125, 'test_recall': 1.0, 'test_f1_score': 0.896551724137931, 'test_roc_auc': 0.9316239316239316, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1973, 'test_samples_per_second': 111.519, 'test_steps_per_second': 10.138, 'test_epoch': 2.0}
2025-05-16 02:17:41,305 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:17:41,308 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:41,371 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:41,372 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:17:41,373 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-14
2025-05-16 02:17:41,825 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.23435594141483307, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.8, 'eval_recall': 1.0, 'eval_f1_score': 0.8888888888888888, 'eval_roc_auc': 1.0, 'eval_false_positives_rate': 0.3, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2144, 'eval_samples_per_second': 102.612, 'eval_steps_per_second': 9.328, 'epoch': 2.0, 'step': 14}
2025-05-16 02:17:41,826 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 02:17:42,020 - Experiment - INFO - Test metrics: {'test_loss': 0.5437412261962891, 'test_accuracy': 0.8636363636363636, 'test_precision': 0.8125, 'test_recall': 1.0, 'test_f1_score': 0.896551724137931, 'test_roc_auc': 0.9316239316239316, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1894, 'test_samples_per_second': 116.126, 'test_steps_per_second': 10.557, 'test_epoch': 2.0}
2025-05-16 02:17:42,043 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:17:42,045 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:17:42,114 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:17:42,115 - Experiment - INFO - Finished model evaluations stage.

### Run 3 of 4

2025-05-16 02:17:42,363 - Experiment - INFO - MLflow experiment initialized with ID: 407824870238116211
2025-05-16 02:17:42,364 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 02:17:42,364 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 02:17:42,365 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 02:17:43,330 - Experiment - INFO - Run ID: 79695c039d4547f4b94224fc2d04cd3e
2025-05-16 02:17:43,331 - Experiment - INFO - Run name: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_02-17-43;rs=3678064787
2025-05-16 02:17:43,342 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:17:43,382 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:17:43,487 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000018B8E7D6600>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000018B8E7D5FD0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000018B8E7D7CB0>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x0000018B8E7D7020>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.RoBERTaEncoder object at 0x0000018B8E7D5160>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:17:43,755 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:17:43,755 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:17:43,756 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:43,776 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:17:43,777 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:43,786 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:17:43,787 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:43,796 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:17:43,796 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:17:43,797 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:43,877 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:17:43,879 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:43,905 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:17:43,906 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:17:43,928 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 02:17:43,929 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:17:43,930 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:44,206 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:17:44,207 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:44,245 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:17:44,247 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:44,287 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 02:17:44,288 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:17:44,289 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:44,595 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:17:44,597 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:44,626 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:17:44,628 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:17:45,021 - Experiment - INFO - Preprocessing function 4: ro_ber_ta_encoder
2025-05-16 02:17:45,022 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:17:45,024 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:17:45,959 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:17:45,960 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:17:46,212 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:17:46,213 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:17:46,916 - Experiment - INFO - Model name: RoBERTa
2025-05-16 02:17:46,921 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:18:30,893 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:18:30,894 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-42
2025-05-16 02:18:31,512 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7591434121131897, 'eval_accuracy': 0.7272727272727273, 'eval_precision': 0.9166666666666666, 'eval_recall': 0.6875, 'eval_f1_score': 0.7857142857142857, 'eval_roc_auc': 0.7708333333333334, 'eval_false_positives_rate': 0.16666666666666666, 'eval_false_negatives_rate': 0.3125, 'eval_runtime': 0.2102, 'eval_samples_per_second': 104.652, 'eval_steps_per_second': 9.514, 'epoch': 6.0, 'step': 42}
2025-05-16 02:18:31,513 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 02:18:31,755 - Experiment - INFO - Test metrics: {'test_loss': 1.153131127357483, 'test_accuracy': 0.5909090909090909, 'test_precision': 0.8571428571428571, 'test_recall': 0.42857142857142855, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.7321428571428572, 'test_false_positives_rate': 0.125, 'test_false_negatives_rate': 0.5714285714285714, 'test_runtime': 0.2389, 'test_samples_per_second': 92.091, 'test_steps_per_second': 8.372, 'test_epoch': 6.0}
2025-05-16 02:18:31,776 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:18:31,778 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:18:31,838 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:18:31,839 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:18:31,840 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-49
2025-05-16 02:18:32,277 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7007107734680176, 'eval_accuracy': 0.7727272727272727, 'eval_precision': 0.7619047619047619, 'eval_recall': 1.0, 'eval_f1_score': 0.8648648648648649, 'eval_roc_auc': 0.8125, 'eval_false_positives_rate': 0.8333333333333334, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2191, 'eval_samples_per_second': 100.416, 'eval_steps_per_second': 9.129, 'epoch': 7.0, 'step': 49}
2025-05-16 02:18:32,278 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 02:18:32,468 - Experiment - INFO - Test metrics: {'test_loss': 0.7974876761436462, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.7222222222222222, 'test_recall': 0.9285714285714286, 'test_f1_score': 0.8125, 'test_roc_auc': 0.8035714285714286, 'test_false_positives_rate': 0.625, 'test_false_negatives_rate': 0.07142857142857142, 'test_runtime': 0.1856, 'test_samples_per_second': 118.536, 'test_steps_per_second': 10.776, 'test_epoch': 7.0}
2025-05-16 02:18:32,486 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:18:32,489 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:18:32,559 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:18:32,559 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:18:32,560 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-42
2025-05-16 02:18:33,010 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7591434121131897, 'eval_accuracy': 0.7272727272727273, 'eval_precision': 0.9166666666666666, 'eval_recall': 0.6875, 'eval_f1_score': 0.7857142857142857, 'eval_roc_auc': 0.7708333333333334, 'eval_false_positives_rate': 0.16666666666666666, 'eval_false_negatives_rate': 0.3125, 'eval_runtime': 0.2102, 'eval_samples_per_second': 104.652, 'eval_steps_per_second': 9.514, 'epoch': 6.0, 'step': 42}
2025-05-16 02:18:33,010 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 02:18:33,196 - Experiment - INFO - Test metrics: {'test_loss': 1.153131127357483, 'test_accuracy': 0.5909090909090909, 'test_precision': 0.8571428571428571, 'test_recall': 0.42857142857142855, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.7321428571428572, 'test_false_positives_rate': 0.125, 'test_false_negatives_rate': 0.5714285714285714, 'test_runtime': 0.1825, 'test_samples_per_second': 120.535, 'test_steps_per_second': 10.958, 'test_epoch': 6.0}
2025-05-16 02:18:33,218 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:18:33,220 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:18:33,276 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:18:33,277 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:18:33,277 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-49
2025-05-16 02:18:33,749 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7007107734680176, 'eval_accuracy': 0.7727272727272727, 'eval_precision': 0.7619047619047619, 'eval_recall': 1.0, 'eval_f1_score': 0.8648648648648649, 'eval_roc_auc': 0.8125, 'eval_false_positives_rate': 0.8333333333333334, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2191, 'eval_samples_per_second': 100.416, 'eval_steps_per_second': 9.129, 'epoch': 7.0, 'step': 49}
2025-05-16 02:18:33,750 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 02:18:33,943 - Experiment - INFO - Test metrics: {'test_loss': 0.7974876761436462, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.7222222222222222, 'test_recall': 0.9285714285714286, 'test_f1_score': 0.8125, 'test_roc_auc': 0.8035714285714286, 'test_false_positives_rate': 0.625, 'test_false_negatives_rate': 0.07142857142857142, 'test_runtime': 0.1873, 'test_samples_per_second': 117.435, 'test_steps_per_second': 10.676, 'test_epoch': 7.0}
2025-05-16 02:18:33,960 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:18:33,962 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:18:34,026 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:18:34,027 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:18:34,027 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:18:34,511 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5547723174095154, 'eval_accuracy': 0.7272727272727273, 'eval_precision': 0.7272727272727273, 'eval_recall': 1.0, 'eval_f1_score': 0.8421052631578947, 'eval_roc_auc': 0.7916666666666666, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2064, 'eval_samples_per_second': 106.587, 'eval_steps_per_second': 9.69, 'epoch': 4.0, 'step': 28}
2025-05-16 02:18:34,512 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:18:34,699 - Experiment - INFO - Test metrics: {'test_loss': 0.6191278100013733, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.7222222222222222, 'test_recall': 0.9285714285714286, 'test_f1_score': 0.8125, 'test_roc_auc': 0.75, 'test_false_positives_rate': 0.625, 'test_false_negatives_rate': 0.07142857142857142, 'test_runtime': 0.1809, 'test_samples_per_second': 121.589, 'test_steps_per_second': 11.054, 'test_epoch': 4.0}
2025-05-16 02:18:34,719 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:18:34,721 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:18:34,781 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:18:34,782 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 02:18:34,949 - Experiment - INFO - MLflow experiment initialized with ID: 407824870238116211
2025-05-16 02:18:34,950 - Experiment - INFO - Model signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01)
2025-05-16 02:18:34,951 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 02:18:34,952 - Experiment - INFO - Run signature: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)])
2025-05-16 02:18:35,985 - Experiment - INFO - Run ID: c1bff05932834464aab83e1393aa3d9e
2025-05-16 02:18:35,985 - Experiment - INFO - Run name: model(mn=roberta,ti=roberta-base,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),ro_ber_ta_encoder(t=roberta-base,t=true,p=max_length,tml=128,isiw=true)]);2025-05-16_02-18-35;rs=12927438
2025-05-16 02:18:35,997 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:18:36,034 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:18:36,146 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x0000018B8E7D71D0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x0000018B8E7D7710>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x0000018B8E7D49E0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x0000018B8E7D64E0>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.RoBERTaEncoder object at 0x0000018B8E7D6720>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:18:36,430 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:18:36,431 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:18:36,432 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:18:36,450 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:18:36,451 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:18:36,468 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:18:36,470 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:18:36,487 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:18:36,489 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:18:36,490 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:18:36,582 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:18:36,583 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:18:36,610 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:18:36,611 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:18:36,638 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 02:18:36,639 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:18:36,640 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:18:36,851 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:18:36,852 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:18:36,907 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:18:36,907 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:18:36,962 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 02:18:36,963 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:18:36,964 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: QiMLlGBjz
warning: skipping word with mixed case: ProtiproudTV
warning: skipping word with mixed case: WAStáhnout
warning: skipping word with mixed case: kW
warning: skipping word with mixed case: EleZYZwTa
warning: skipping word with mixed case: LightRocket
warning: skipping word with mixed case: MUDr
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: ČEZu
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: iDnes
warning: skipping word with mixed case: LONGi
warning: skipping word with mixed case: JeZeĎáků
warning: skipping word with mixed case: JeZeDáků
warning: skipping word with mixed case: JeZeDák
warning: skipping word with mixed case: JeZeĎák
warning: skipping word with mixed case: JeZeĎáky
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: SudRadio
warning: skipping word with mixed case: SudRadia
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCaina
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: QsRsXmnJ
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: LeCarreho
warning: skipping word with mixed case: GAZPROMu
warning: skipping word with mixed case: iCloudu
warning: skipping word with mixed case: iPhonu
warning: skipping word with mixed case: iPhone
warning: skipping word with mixed case: iCloud
warning: skipping word with mixed case: iPhonu
warning: skipping word with mixed case: iCloud
warning: skipping word with mixed case: JPMorgan
warning: skipping word with mixed case: ProLibertate
warning: skipping word with mixed case: PolitNavigator
warning: skipping word with mixed case: uWGfbdcph
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: hzeEh
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: aJWmHMLT
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: antiRusko
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: kWh
warning: skipping word with mixed case: GRTgaz
2025-05-16 02:18:37,244 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:18:37,250 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: mSmlhLVUE
warning: skipping word with mixed case: JackPosobiec
warning: skipping word with mixed case: našÍ
2025-05-16 02:18:37,333 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:18:37,336 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: YouTube
warning: skipping word with mixed case: MiG
warning: skipping word with mixed case: MeToo
warning: skipping word with mixed case: ArmUkraineNow
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: sVDMmb
warning: skipping word with mixed case: StratcomCentre
warning: skipping word with mixed case: TOPky
warning: skipping word with mixed case: MafiánStan
warning: skipping word with mixed case: ViktoriaGruppe
2025-05-16 02:18:37,718 - Experiment - INFO - Preprocessing function 4: ro_ber_ta_encoder
2025-05-16 02:18:37,718 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:18:37,720 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:18:38,787 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:18:38,789 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:18:39,103 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:18:39,104 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:18:39,828 - Experiment - INFO - Model name: RoBERTa
2025-05-16 02:18:39,831 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-16 02:19:38,784 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:19:38,784 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-42
2025-05-16 02:19:39,246 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5725111961364746, 'eval_accuracy': 0.7272727272727273, 'eval_precision': 0.7692307692307693, 'eval_recall': 0.7692307692307693, 'eval_f1_score': 0.7692307692307693, 'eval_roc_auc': 0.8034188034188035, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 0.23076923076923078, 'eval_runtime': 0.2099, 'eval_samples_per_second': 104.822, 'eval_steps_per_second': 9.529, 'epoch': 6.0, 'step': 42}
2025-05-16 02:19:39,246 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 02:19:39,495 - Experiment - INFO - Test metrics: {'test_loss': 0.4660516679286957, 'test_accuracy': 0.8181818181818182, 'test_precision': 1.0, 'test_recall': 0.7333333333333333, 'test_f1_score': 0.8461538461538461, 'test_roc_auc': 0.9047619047619047, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.26666666666666666, 'test_runtime': 0.2448, 'test_samples_per_second': 89.873, 'test_steps_per_second': 8.17, 'test_epoch': 6.0}
2025-05-16 02:19:39,516 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:19:39,518 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:19:39,574 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:19:39,575 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:19:39,575 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-49
2025-05-16 02:19:40,093 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.710961639881134, 'eval_accuracy': 0.7272727272727273, 'eval_precision': 0.6842105263157895, 'eval_recall': 1.0, 'eval_f1_score': 0.8125, 'eval_roc_auc': 0.7350427350427351, 'eval_false_positives_rate': 0.6666666666666666, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2105, 'eval_samples_per_second': 104.535, 'eval_steps_per_second': 9.503, 'epoch': 7.0, 'step': 49}
2025-05-16 02:19:40,094 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 02:19:40,281 - Experiment - INFO - Test metrics: {'test_loss': 0.677480161190033, 'test_accuracy': 0.6818181818181818, 'test_precision': 0.75, 'test_recall': 0.8, 'test_f1_score': 0.7741935483870968, 'test_roc_auc': 0.7714285714285716, 'test_false_positives_rate': 0.5714285714285714, 'test_false_negatives_rate': 0.2, 'test_runtime': 0.1824, 'test_samples_per_second': 120.642, 'test_steps_per_second': 10.967, 'test_epoch': 7.0}
2025-05-16 02:19:40,303 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:19:40,305 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:19:40,368 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:19:40,369 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:19:40,370 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 02:19:40,883 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6988145112991333, 'eval_accuracy': 0.4090909090909091, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 0.7863247863247864, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.1997, 'eval_samples_per_second': 110.172, 'eval_steps_per_second': 10.016, 'epoch': 1.0, 'step': 7}
2025-05-16 02:19:40,884 - Experiment - INFO - Best model found at epoch 1.0.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-16 02:19:41,067 - Experiment - INFO - Test metrics: {'test_loss': 0.704379677772522, 'test_accuracy': 0.3181818181818182, 'test_precision': 0.0, 'test_recall': 0.0, 'test_f1_score': 0.0, 'test_roc_auc': 0.9523809523809524, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 1.0, 'test_runtime': 0.1797, 'test_samples_per_second': 122.414, 'test_steps_per_second': 11.129, 'test_epoch': 1.0}
2025-05-16 02:19:41,085 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:19:41,087 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:19:41,149 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:19:41,150 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:19:41,151 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:19:41,739 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6173588037490845, 'eval_accuracy': 0.5909090909090909, 'eval_precision': 0.5909090909090909, 'eval_recall': 1.0, 'eval_f1_score': 0.7428571428571429, 'eval_roc_auc': 0.8547008547008548, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.8464, 'eval_samples_per_second': 25.993, 'eval_steps_per_second': 2.363, 'epoch': 4.0, 'step': 28}
2025-05-16 02:19:41,741 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:19:41,950 - Experiment - INFO - Test metrics: {'test_loss': 0.5804975628852844, 'test_accuracy': 0.6818181818181818, 'test_precision': 0.6818181818181818, 'test_recall': 1.0, 'test_f1_score': 0.8108108108108109, 'test_roc_auc': 0.8857142857142857, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1996, 'test_samples_per_second': 110.241, 'test_steps_per_second': 10.022, 'test_epoch': 4.0}
2025-05-16 02:19:41,977 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:19:41,981 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:19:42,052 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:19:42,054 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:19:42,055 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-42
2025-05-16 02:19:42,588 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5725111961364746, 'eval_accuracy': 0.7272727272727273, 'eval_precision': 0.7692307692307693, 'eval_recall': 0.7692307692307693, 'eval_f1_score': 0.7692307692307693, 'eval_roc_auc': 0.8034188034188035, 'eval_false_positives_rate': 0.3333333333333333, 'eval_false_negatives_rate': 0.23076923076923078, 'eval_runtime': 0.2099, 'eval_samples_per_second': 104.822, 'eval_steps_per_second': 9.529, 'epoch': 6.0, 'step': 42}
2025-05-16 02:19:42,589 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 02:19:42,780 - Experiment - INFO - Test metrics: {'test_loss': 0.4660516679286957, 'test_accuracy': 0.8181818181818182, 'test_precision': 1.0, 'test_recall': 0.7333333333333333, 'test_f1_score': 0.8461538461538461, 'test_roc_auc': 0.9047619047619047, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.26666666666666666, 'test_runtime': 0.1864, 'test_samples_per_second': 118.029, 'test_steps_per_second': 10.73, 'test_epoch': 6.0}
2025-05-16 02:19:42,800 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:19:42,802 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:19:42,869 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:19:42,870 - Experiment - INFO - Finished model evaluations stage.