In [1]:
from workspace.sources.local_datasets.preprocessing.tokenization import NLTKTokenizer
from workspace.sources.local_datasets.preprocessing.cleaning import NoiseReduction, Lemmatization, Stemming
from workspace.sources.experiments.metrics import Loss
from workspace.sources.utils import class_name_to_str
from workspace.sources.experiments.experiment import Experiment
from workspace.sources.local_datasets.dataset import Dataset
from workspace.sources.local_datasets.preprocessing.pipelines import PreprocessingPipeline
from workspace.sources.local_datasets.preprocessing.utils import truncate
from sklearn.model_selection import ParameterGrid
from IPython.display import display, Markdown

from workspace.sources.local_datasets.preprocessing.encoders.encoders import GPT2_Encoder as Encoder
from workspace.sources.models.transformers.openai_gpt_models import GPT2 as Model


import mlflow

mlflow.set_tracking_uri('../../mlruns')

In [2]:
experiment_name = f'prefinal-{class_name_to_str(Model.__name__)}-v2'
print('Experiment:', experiment_name)

Experiment: prefinal-gpt2-v2

In [4]:
def conduct_gpt_model_experiments(dataset_name,
                                  dataset_path,
                                  dataset_hparams_grid,
                                  model_hparams_grid):
    total_runs = len(dataset_hparams_grid) * len(model_hparams_grid)
    for i, dataset_params in enumerate(dataset_hparams_grid):
        encoder = dataset_params['preprocessings_pipeline'][-1]
        for j, model_hparams in enumerate(model_hparams_grid):
            run_number = i * len(model_hparams_grid) + j + 1
            display(Markdown(f'### Run {run_number} of {total_runs}'))
            dataset = Dataset(dataset_name, dataset_path, **dataset_params)

            model = Model(gpt_encoder=encoder,
                           train_best_model_metric=Loss,
                           training_arguments=model_hparams)

            recovery_experiment = Experiment(
                name=experiment_name,
                dataset=dataset,
                model=model)
            recovery_experiment.run()

In [5]:

# max_tokens_params = [128, 512]
max_tokens_params = [128]

pipelines = []

for max_tokens in max_tokens_params:
    pipelines.extend([PreprocessingPipeline(name='minimal',
                                            iterable=[Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction',
                                            iterable=[NoiseReduction(),
                                                      Encoder(truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Lemmatization(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)]),
                      PreprocessingPipeline(name='noise_reduction_with_stemming',
                                            iterable=[NoiseReduction(), NLTKTokenizer(), Stemming(),
                                                      Encoder(is_split_into_words=True,
                                                              truncation_max_length=max_tokens)])
                      ])
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(pipelines, fraction=0.05)

dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': pipelines})

print('Dataset Hyperparameters Grid Size: ', len(dataset_hparams_grid))

# model_hparams_grid = ParameterGrid({'epochs': [10],
#                                     'batch_size': [16],
#                                     'learning_rate': [1e-05, 5e-05],
#                                     'lr_scheduler': ['linear'],
#                                     'optimizer': ['adamw_torch'],
#                                     'weight_decay': [0.0, 1e-3],
#                                     'early_stopping_patience': [3],
#                                     'early_stopping_threshold': [0.01]})

model_hparams_grid = ParameterGrid({'epochs': [10],
                                    'batch_size': [16],
                                    'learning_rate': [5e-05],
                                    'lr_scheduler': ['linear'],
                                    'optimizer': ['adamw_torch'],
                                    'weight_decay': [1e-3],
                                    'early_stopping_patience': [3],
                                    'early_stopping_threshold': [0.01]})

print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

### ReCOVery Dataset

In [6]:
dataset_name = 'ReCOVery'
dataset_path = '../../sources/local_datasets/data/ReCOVery/recovery.csv'

conduct_gpt_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid)

### Run 1 of 4

2025-05-16 02:05:34,818 - Experiment - INFO - MLflow experiment initialized with ID: 649077292658744800
2025-05-16 02:05:34,819 - Experiment - INFO - Model signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 02:05:34,820 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:05:34,820 - Experiment - INFO - Run signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:05:34,944 - Experiment - INFO - Found existing run with signature model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:05:34,945 - Experiment - INFO - Existing run ID: 51fcc03859b74aea916a2276875bdb7d
2025-05-16 02:05:34,946 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 2 of 4

2025-05-16 02:05:34,953 - Experiment - INFO - MLflow experiment initialized with ID: 649077292658744800
2025-05-16 02:05:34,954 - Experiment - INFO - Model signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 02:05:34,954 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:05:34,955 - Experiment - INFO - Run signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:05:35,072 - Experiment - INFO - Found existing run with signature model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:05:35,073 - Experiment - INFO - Existing run ID: 86c8caa8d0f44e739f4bf86300d04b97
2025-05-16 02:05:35,074 - Experiment - INFO - Skipping current experiment run, because run with same signature already exists.

### Run 3 of 4

2025-05-16 02:05:35,083 - Experiment - INFO - MLflow experiment initialized with ID: 649077292658744800
2025-05-16 02:05:35,083 - Experiment - INFO - Model signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 02:05:35,084 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 02:05:35,084 - Experiment - INFO - Run signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 02:05:35,463 - Experiment - INFO - Run ID: cdafeb450ad24e77bf108c000f6c19d4
2025-05-16 02:05:35,464 - Experiment - INFO - Run name: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),lemmatization(lc=en),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)]);2025-05-16_02-05-35;rs=3970646970
2025-05-16 02:05:35,475 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:05:35,513 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:05:35,656 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001F11477B6B0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001F11477B140>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x000001F11477B200>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x000001F11477B230>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT2_Encoder object at 0x000001F11477B2F0>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:05:36,056 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:05:36,057 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:05:36,058 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,080 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:05:36,081 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,094 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:05:36,095 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,107 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:05:36,108 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:05:36,110 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,174 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:05:36,176 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,196 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:05:36,197 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:05:36,222 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 02:05:36,222 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:05:36,223 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,398 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:05:36,398 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,444 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:05:36,446 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,499 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 02:05:36,500 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:05:36,501 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,652 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:05:36,654 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:36,676 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:05:36,678 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:05:37,068 - Experiment - INFO - Preprocessing function 4: gpt2__encoder
2025-05-16 02:05:37,068 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:05:37,070 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:05:37,892 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:05:37,894 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:05:38,161 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:05:38,162 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:05:39,031 - Experiment - INFO - Model name: GPT2
2025-05-16 02:05:39,037 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-16 02:06:15,590 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:06:15,590 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 02:06:16,175 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6158884763717651, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 1.0, 'eval_recall': 0.6363636363636364, 'eval_f1_score': 0.7777777777777778, 'eval_roc_auc': 0.8409090909090908, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.36363636363636365, 'eval_runtime': 0.601, 'eval_samples_per_second': 24.959, 'eval_steps_per_second': 1.664, 'epoch': 3.0, 'step': 15}
2025-05-16 02:06:16,176 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:06:16,379 - Experiment - INFO - Test metrics: {'test_loss': 1.1893900632858276, 'test_accuracy': 0.5333333333333333, 'test_precision': 1.0, 'test_recall': 0.4166666666666667, 'test_f1_score': 0.5882352941176471, 'test_roc_auc': 0.5833333333333334, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.5833333333333334, 'test_runtime': 0.199, 'test_samples_per_second': 75.376, 'test_steps_per_second': 5.025, 'test_epoch': 3.0}
2025-05-16 02:06:16,399 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:16,400 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:16,437 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:16,438 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:06:16,439 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 02:06:16,989 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7354328632354736, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 0.8888888888888888, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.8, 'eval_roc_auc': 0.75, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.1502, 'eval_samples_per_second': 99.867, 'eval_steps_per_second': 6.658, 'epoch': 7.0, 'step': 35}
2025-05-16 02:06:16,991 - Experiment - INFO - Best model found at epoch 7.0.

2025-05-16 02:06:17,133 - Experiment - INFO - Test metrics: {'test_loss': 1.0763776302337646, 'test_accuracy': 0.6, 'test_precision': 0.875, 'test_recall': 0.5833333333333334, 'test_f1_score': 0.7, 'test_roc_auc': 0.5833333333333334, 'test_false_positives_rate': 0.3333333333333333, 'test_false_negatives_rate': 0.4166666666666667, 'test_runtime': 0.1366, 'test_samples_per_second': 109.808, 'test_steps_per_second': 7.321, 'test_epoch': 7.0}
2025-05-16 02:06:17,164 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:17,167 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:17,227 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:17,229 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:06:17,230 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 02:06:17,781 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.6158884763717651, 'eval_accuracy': 0.7333333333333333, 'eval_precision': 1.0, 'eval_recall': 0.6363636363636364, 'eval_f1_score': 0.7777777777777778, 'eval_roc_auc': 0.8409090909090908, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 0.36363636363636365, 'eval_runtime': 0.601, 'eval_samples_per_second': 24.959, 'eval_steps_per_second': 1.664, 'epoch': 3.0, 'step': 15}
2025-05-16 02:06:17,781 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:06:17,913 - Experiment - INFO - Test metrics: {'test_loss': 1.1893900632858276, 'test_accuracy': 0.5333333333333333, 'test_precision': 1.0, 'test_recall': 0.4166666666666667, 'test_f1_score': 0.5882352941176471, 'test_roc_auc': 0.5833333333333334, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.5833333333333334, 'test_runtime': 0.1279, 'test_samples_per_second': 117.302, 'test_steps_per_second': 7.82, 'test_epoch': 3.0}
2025-05-16 02:06:17,932 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:17,935 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:17,976 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:17,978 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:06:17,979 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 02:06:18,542 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 1.6669695377349854, 'eval_accuracy': 0.26666666666666666, 'eval_precision': 0.0, 'eval_recall': 0.0, 'eval_f1_score': 0.0, 'eval_roc_auc': 0.9090909090909092, 'eval_false_positives_rate': 0.0, 'eval_false_negatives_rate': 1.0, 'eval_runtime': 0.119, 'eval_samples_per_second': 126.087, 'eval_steps_per_second': 8.406, 'epoch': 2.0, 'step': 10}
2025-05-16 02:06:18,543 - Experiment - INFO - Best model found at epoch 2.0.

C:\Users\nikita.bardatskii\git\bi-bap-2025-bardanik\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2025-05-16 02:06:18,672 - Experiment - INFO - Test metrics: {'test_loss': 2.4381749629974365, 'test_accuracy': 0.2, 'test_precision': 0.0, 'test_recall': 0.0, 'test_f1_score': 0.0, 'test_roc_auc': 0.5000000000000001, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 1.0, 'test_runtime': 0.1243, 'test_samples_per_second': 120.71, 'test_steps_per_second': 8.047, 'test_epoch': 2.0}
2025-05-16 02:06:18,689 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:18,691 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:18,732 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:18,733 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:06:18,734 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-20
2025-05-16 02:06:19,287 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.5517600774765015, 'eval_accuracy': 0.6666666666666666, 'eval_precision': 0.875, 'eval_recall': 0.6363636363636364, 'eval_f1_score': 0.7368421052631579, 'eval_roc_auc': 0.8181818181818181, 'eval_false_positives_rate': 0.25, 'eval_false_negatives_rate': 0.36363636363636365, 'eval_runtime': 0.1185, 'eval_samples_per_second': 126.618, 'eval_steps_per_second': 8.441, 'epoch': 4.0, 'step': 20}
2025-05-16 02:06:19,287 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:06:19,413 - Experiment - INFO - Test metrics: {'test_loss': 1.059842824935913, 'test_accuracy': 0.5333333333333333, 'test_precision': 1.0, 'test_recall': 0.4166666666666667, 'test_f1_score': 0.5882352941176471, 'test_roc_auc': 0.5833333333333334, 'test_false_positives_rate': 0.0, 'test_false_negatives_rate': 0.5833333333333334, 'test_runtime': 0.1221, 'test_samples_per_second': 122.838, 'test_steps_per_second': 8.189, 'test_epoch': 4.0}
2025-05-16 02:06:19,428 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:19,430 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:19,469 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:19,470 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 02:06:19,652 - Experiment - INFO - MLflow experiment initialized with ID: 649077292658744800
2025-05-16 02:06:19,653 - Experiment - INFO - Model signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 02:06:19,653 - Experiment - INFO - Dataset signature: dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 02:06:19,654 - Experiment - INFO - Run signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 02:06:20,264 - Experiment - INFO - Run ID: 8812f16ef6f548918a2ef001c7ca1ec2
2025-05-16 02:06:20,264 - Experiment - INFO - Run name: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=recovery,tp=0.7,vp=0.15);pipeline([truncation(f=0.05,tt=top),noise_reduction(),nltk_tokenizer(lc=en),stemming(st=snowball,lc=en),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)]);2025-05-16_02-06-20;rs=29062619
2025-05-16 02:06:20,275 - Experiment - INFO - {'dataset_name': 'recovery', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:06:20,311 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:06:20,477 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001F11477B3B0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001F11477AED0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x000001F11477B6E0>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x000001F11477B260>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT2_Encoder object at 0x000001F11477A960>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:06:20,734 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:06:20,734 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:06:20,735 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:20,751 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:06:20,752 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:20,763 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:06:20,764 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:20,773 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:06:20,773 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:06:20,774 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:20,840 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:06:20,841 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:20,864 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:06:20,865 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:06:20,887 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 02:06:20,888 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:06:20,888 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:21,038 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:06:21,039 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:21,088 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:06:21,090 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:21,141 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 02:06:21,142 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:06:21,143 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:21,615 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:06:21,616 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:21,744 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:06:21,745 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:22,159 - Experiment - INFO - Preprocessing function 4: gpt2__encoder
2025-05-16 02:06:22,159 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:06:22,159 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:06:22,815 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:06:22,817 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:06:23,066 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:06:23,068 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:06:23,838 - Experiment - INFO - Model name: GPT2
2025-05-16 02:06:23,843 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:06:43,805 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:06:43,806 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-5
2025-05-16 02:06:44,393 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7139406800270081, 'eval_accuracy': 0.6, 'eval_precision': 0.6428571428571429, 'eval_recall': 0.9, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.42000000000000004, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1675, 'eval_samples_per_second': 89.579, 'eval_steps_per_second': 5.972, 'epoch': 1.0, 'step': 5}
2025-05-16 02:06:44,408 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 02:06:44,594 - Experiment - INFO - Test metrics: {'test_loss': 0.6964749693870544, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.5185185185185185, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1819, 'test_samples_per_second': 82.448, 'test_steps_per_second': 5.497, 'test_epoch': 1.0}
2025-05-16 02:06:44,613 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:44,615 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:44,653 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:44,654 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:06:44,655 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-5
2025-05-16 02:06:45,169 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7139406800270081, 'eval_accuracy': 0.6, 'eval_precision': 0.6428571428571429, 'eval_recall': 0.9, 'eval_f1_score': 0.75, 'eval_roc_auc': 0.42000000000000004, 'eval_false_positives_rate': 1.0, 'eval_false_negatives_rate': 0.1, 'eval_runtime': 0.1675, 'eval_samples_per_second': 89.579, 'eval_steps_per_second': 5.972, 'epoch': 1.0, 'step': 5}
2025-05-16 02:06:45,169 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 02:06:45,297 - Experiment - INFO - Test metrics: {'test_loss': 0.6964749693870544, 'test_accuracy': 0.6, 'test_precision': 0.6, 'test_recall': 1.0, 'test_f1_score': 0.75, 'test_roc_auc': 0.5185185185185185, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1229, 'test_samples_per_second': 122.004, 'test_steps_per_second': 8.134, 'test_epoch': 1.0}
2025-05-16 02:06:45,569 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:45,572 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:45,650 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:45,653 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:06:45,654 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 02:06:46,511 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7120739817619324, 'eval_accuracy': 0.4666666666666667, 'eval_precision': 0.6, 'eval_recall': 0.6, 'eval_f1_score': 0.6, 'eval_roc_auc': 0.43999999999999995, 'eval_false_positives_rate': 0.8, 'eval_false_negatives_rate': 0.4, 'eval_runtime': 0.1213, 'eval_samples_per_second': 123.666, 'eval_steps_per_second': 8.244, 'epoch': 2.0, 'step': 10}
2025-05-16 02:06:46,512 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 02:06:46,639 - Experiment - INFO - Test metrics: {'test_loss': 0.6792124509811401, 'test_accuracy': 0.4, 'test_precision': 0.5, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.5740740740740741, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.122, 'test_samples_per_second': 122.985, 'test_steps_per_second': 8.199, 'test_epoch': 2.0}
2025-05-16 02:06:46,657 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:46,659 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:46,702 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:46,703 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:06:46,704 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-15
2025-05-16 02:06:47,329 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7155303359031677, 'eval_accuracy': 0.4666666666666667, 'eval_precision': 0.6, 'eval_recall': 0.6, 'eval_f1_score': 0.6, 'eval_roc_auc': 0.46, 'eval_false_positives_rate': 0.8, 'eval_false_negatives_rate': 0.4, 'eval_runtime': 0.1488, 'eval_samples_per_second': 100.821, 'eval_steps_per_second': 6.721, 'epoch': 3.0, 'step': 15}
2025-05-16 02:06:47,330 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:06:47,463 - Experiment - INFO - Test metrics: {'test_loss': 0.683748185634613, 'test_accuracy': 0.4, 'test_precision': 0.5, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.537037037037037, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.1285, 'test_samples_per_second': 116.75, 'test_steps_per_second': 7.783, 'test_epoch': 3.0}
2025-05-16 02:06:47,478 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:47,479 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:47,518 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:47,520 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:06:47,521 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-10
2025-05-16 02:06:48,013 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7120739817619324, 'eval_accuracy': 0.4666666666666667, 'eval_precision': 0.6, 'eval_recall': 0.6, 'eval_f1_score': 0.6, 'eval_roc_auc': 0.43999999999999995, 'eval_false_positives_rate': 0.8, 'eval_false_negatives_rate': 0.4, 'eval_runtime': 0.1213, 'eval_samples_per_second': 123.666, 'eval_steps_per_second': 8.244, 'epoch': 2.0, 'step': 10}
2025-05-16 02:06:48,014 - Experiment - INFO - Best model found at epoch 2.0.

2025-05-16 02:06:48,144 - Experiment - INFO - Test metrics: {'test_loss': 0.6792124509811401, 'test_accuracy': 0.4, 'test_precision': 0.5, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.5714285714285714, 'test_roc_auc': 0.5740740740740741, 'test_false_positives_rate': 1.0, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.1252, 'test_samples_per_second': 119.822, 'test_steps_per_second': 7.988, 'test_epoch': 2.0}
2025-05-16 02:06:48,165 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:06:48,168 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:06:48,210 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:06:48,212 - Experiment - INFO - Finished model evaluations stage.

### EUvsDisinfo Dataset

In [ ]:
dataset_name = 'EUvsDisinfo'
dataset_path = '../../sources/local_datasets/data/EUvsDisinfo/euvsdisinfo.csv'

conduct_gpt_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid)

### ISOT Dataset

In [ ]:
dataset_name = 'ISOT'
dataset_path = '../../sources/local_datasets/data/ISOT/isot.csv'

conduct_gpt_model_experiments(dataset_name,
                              dataset_path,
                              dataset_hparams_grid,
                              model_hparams_grid)

### CZ Dataset

In [7]:
cz_pipelines = []

for max_tokens in max_tokens_params:
    cz_pipelines.extend([PreprocessingPipeline(name='minimal',
                                               iterable=[Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction',
                                               iterable=[NoiseReduction(),
                                                         Encoder(truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_lemmatization',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Lemmatization(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)]),
                         PreprocessingPipeline(name='noise_reduction_with_stemming',
                                               iterable=[NoiseReduction(), NLTKTokenizer(language='czech'),
                                                         Stemming(language='czech'),
                                                         Encoder(is_split_into_words=True,
                                                                 truncation_max_length=max_tokens)])
                         ])
# optional - for testing purposes, if you want to run fast test on very small datasets
truncate(cz_pipelines, fraction=0.15)

cz_dataset_hparams_grid = ParameterGrid({'preprocessings_pipeline': cz_pipelines})
print('Dataset Hyperparameters Grid Size: ', len(cz_dataset_hparams_grid))
print('Model Hyperparameters Grid Size: ', len(model_hparams_grid))
print('Total Hyperparameter Combinations: ', len(cz_dataset_hparams_grid) * len(model_hparams_grid))

Dataset Hyperparameters Grid Size:  4
Model Hyperparameters Grid Size:  1
Total Hyperparameter Combinations:  4

In [8]:
dataset_name = 'cz_dataset'
dataset_path = '../../sources/local_datasets/data/cz_dataset/cz_dataset.csv'

conduct_gpt_model_experiments(dataset_name,
                              dataset_path,
                              cz_dataset_hparams_grid,
                              model_hparams_grid)

### Run 1 of 4

2025-05-16 02:06:56,742 - Experiment - INFO - MLflow experiment initialized with ID: 649077292658744800
2025-05-16 02:06:56,743 - Experiment - INFO - Model signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 02:06:56,744 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:06:56,744 - Experiment - INFO - Run signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:06:57,743 - Experiment - INFO - Run ID: 1816c3f5938941daaaf8a03c96e16c56
2025-05-16 02:06:57,744 - Experiment - INFO - Run name: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)]);2025-05-16_02-06-57;rs=2272126363
2025-05-16 02:06:57,757 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:06:57,786 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:06:57,897 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'minimal': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001F114B65910>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT2_Encoder object at 0x000001F1382B5610>]>
2025-05-16 02:06:58,315 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:06:58,315 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:06:58,315 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:58,343 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:06:58,345 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:58,361 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:06:58,363 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:06:58,677 - Experiment - INFO - Preprocessing function 1: gpt2__encoder
2025-05-16 02:06:58,678 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:06:58,679 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:06:59,568 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:06:59,569 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:06:59,787 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:06:59,788 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:07:00,408 - Experiment - INFO - Model name: GPT2
2025-05-16 02:07:00,416 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:07:36,648 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:07:36,648 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:07:37,192 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3772681951522827, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9173553719008264, 'eval_false_positives_rate': 0.2727272727272727, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.214, 'eval_samples_per_second': 102.803, 'eval_steps_per_second': 9.346, 'epoch': 4.0, 'step': 28}
2025-05-16 02:07:37,192 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:07:37,428 - Experiment - INFO - Test metrics: {'test_loss': 0.20516850054264069, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 0.9833333333333334, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.2319, 'test_samples_per_second': 94.86, 'test_steps_per_second': 8.624, 'test_epoch': 4.0}
2025-05-16 02:07:37,452 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:07:37,454 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:07:37,516 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:07:37,517 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:07:37,517 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:07:38,043 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3772681951522827, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9173553719008264, 'eval_false_positives_rate': 0.2727272727272727, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.214, 'eval_samples_per_second': 102.803, 'eval_steps_per_second': 9.346, 'epoch': 4.0, 'step': 28}
2025-05-16 02:07:38,043 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:07:38,235 - Experiment - INFO - Test metrics: {'test_loss': 0.20516850054264069, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 0.9833333333333334, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1863, 'test_samples_per_second': 118.109, 'test_steps_per_second': 10.737, 'test_epoch': 4.0}
2025-05-16 02:07:38,254 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:07:38,256 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:07:38,320 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:07:38,321 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:07:38,321 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:07:38,844 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3772681951522827, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9173553719008264, 'eval_false_positives_rate': 0.2727272727272727, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.214, 'eval_samples_per_second': 102.803, 'eval_steps_per_second': 9.346, 'epoch': 4.0, 'step': 28}
2025-05-16 02:07:38,845 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:07:39,034 - Experiment - INFO - Test metrics: {'test_loss': 0.20516850054264069, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 0.9833333333333334, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1857, 'test_samples_per_second': 118.494, 'test_steps_per_second': 10.772, 'test_epoch': 4.0}
2025-05-16 02:07:39,051 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:07:39,054 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:07:39,111 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:07:39,112 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:07:39,113 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-35
2025-05-16 02:07:39,621 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.4181590974330902, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9504132231404958, 'eval_false_positives_rate': 0.2727272727272727, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2232, 'eval_samples_per_second': 98.582, 'eval_steps_per_second': 8.962, 'epoch': 5.0, 'step': 35}
2025-05-16 02:07:39,622 - Experiment - INFO - Best model found at epoch 5.0.

2025-05-16 02:07:39,811 - Experiment - INFO - Test metrics: {'test_loss': 0.11860575526952744, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 1.0, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.1832, 'test_samples_per_second': 120.093, 'test_steps_per_second': 10.918, 'test_epoch': 5.0}
2025-05-16 02:07:39,827 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:07:39,829 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:07:39,894 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:07:39,895 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:07:39,896 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:07:40,460 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.3772681951522827, 'eval_accuracy': 0.8636363636363636, 'eval_precision': 0.7857142857142857, 'eval_recall': 1.0, 'eval_f1_score': 0.88, 'eval_roc_auc': 0.9173553719008264, 'eval_false_positives_rate': 0.2727272727272727, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.214, 'eval_samples_per_second': 102.803, 'eval_steps_per_second': 9.346, 'epoch': 4.0, 'step': 28}
2025-05-16 02:07:40,461 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:07:40,659 - Experiment - INFO - Test metrics: {'test_loss': 0.20516850054264069, 'test_accuracy': 0.9090909090909091, 'test_precision': 0.8571428571428571, 'test_recall': 1.0, 'test_f1_score': 0.9230769230769231, 'test_roc_auc': 0.9833333333333334, 'test_false_positives_rate': 0.2, 'test_false_negatives_rate': 0.0, 'test_runtime': 0.194, 'test_samples_per_second': 113.382, 'test_steps_per_second': 10.307, 'test_epoch': 4.0}
2025-05-16 02:07:40,682 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:07:40,685 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:07:40,766 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:07:40,767 - Experiment - INFO - Finished model evaluations stage.

### Run 2 of 4

2025-05-16 02:07:41,702 - Experiment - INFO - MLflow experiment initialized with ID: 649077292658744800
2025-05-16 02:07:41,703 - Experiment - INFO - Model signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 02:07:41,704 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:07:41,705 - Experiment - INFO - Run signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)])
2025-05-16 02:07:42,979 - Experiment - INFO - Run ID: 4a046f24730242bcb3f8afeca9c04bdf
2025-05-16 02:07:42,980 - Experiment - INFO - Run name: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=false,pt=none)]);2025-05-16_02-07-42;rs=3433694172
2025-05-16 02:07:42,995 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:07:43,034 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:07:43,145 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001F114B64DA0>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001F1382B4410>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT2_Encoder object at 0x000001F1382B5700>]>
2025-05-16 02:07:43,460 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:07:43,462 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:07:43,463 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:07:43,481 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:07:43,483 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:07:43,500 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:07:43,502 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:07:43,521 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:07:43,522 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:07:43,524 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:07:43,647 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:07:43,649 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:07:43,678 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:07:43,680 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:07:44,053 - Experiment - INFO - Preprocessing function 2: gpt2__encoder
2025-05-16 02:07:44,055 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:07:44,056 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:07:44,821 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:07:44,823 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:07:45,079 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:07:45,081 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:07:45,694 - Experiment - INFO - Model name: GPT2
2025-05-16 02:07:45,702 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:08:47,649 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:08:47,665 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-56
2025-05-16 02:08:48,416 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.12225854396820068, 'eval_accuracy': 0.9090909090909091, 'eval_precision': 0.9166666666666666, 'eval_recall': 0.9166666666666666, 'eval_f1_score': 0.9166666666666666, 'eval_roc_auc': 0.9916666666666667, 'eval_false_positives_rate': 0.1, 'eval_false_negatives_rate': 0.08333333333333333, 'eval_runtime': 0.2215, 'eval_samples_per_second': 99.307, 'eval_steps_per_second': 9.028, 'epoch': 8.0, 'step': 56}
2025-05-16 02:08:48,417 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 02:08:48,682 - Experiment - INFO - Test metrics: {'test_loss': 0.6583252549171448, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.6428571428571429, 'test_recall': 0.9, 'test_f1_score': 0.75, 'test_roc_auc': 0.9333333333333333, 'test_false_positives_rate': 0.4166666666666667, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.2604, 'test_samples_per_second': 84.485, 'test_steps_per_second': 7.68, 'test_epoch': 8.0}
2025-05-16 02:08:48,696 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:08:48,697 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:08:48,758 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:08:48,760 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:08:48,760 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-56
2025-05-16 02:08:49,390 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.12225854396820068, 'eval_accuracy': 0.9090909090909091, 'eval_precision': 0.9166666666666666, 'eval_recall': 0.9166666666666666, 'eval_f1_score': 0.9166666666666666, 'eval_roc_auc': 0.9916666666666667, 'eval_false_positives_rate': 0.1, 'eval_false_negatives_rate': 0.08333333333333333, 'eval_runtime': 0.2215, 'eval_samples_per_second': 99.307, 'eval_steps_per_second': 9.028, 'epoch': 8.0, 'step': 56}
2025-05-16 02:08:49,391 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 02:08:49,571 - Experiment - INFO - Test metrics: {'test_loss': 0.6583252549171448, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.6428571428571429, 'test_recall': 0.9, 'test_f1_score': 0.75, 'test_roc_auc': 0.9333333333333333, 'test_false_positives_rate': 0.4166666666666667, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.1755, 'test_samples_per_second': 125.371, 'test_steps_per_second': 11.397, 'test_epoch': 8.0}
2025-05-16 02:08:49,586 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:08:49,588 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:08:49,644 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:08:49,645 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:08:49,646 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-56
2025-05-16 02:08:50,199 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.12225854396820068, 'eval_accuracy': 0.9090909090909091, 'eval_precision': 0.9166666666666666, 'eval_recall': 0.9166666666666666, 'eval_f1_score': 0.9166666666666666, 'eval_roc_auc': 0.9916666666666667, 'eval_false_positives_rate': 0.1, 'eval_false_negatives_rate': 0.08333333333333333, 'eval_runtime': 0.2215, 'eval_samples_per_second': 99.307, 'eval_steps_per_second': 9.028, 'epoch': 8.0, 'step': 56}
2025-05-16 02:08:50,200 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 02:08:50,382 - Experiment - INFO - Test metrics: {'test_loss': 0.6583252549171448, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.6428571428571429, 'test_recall': 0.9, 'test_f1_score': 0.75, 'test_roc_auc': 0.9333333333333333, 'test_false_positives_rate': 0.4166666666666667, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.1777, 'test_samples_per_second': 123.801, 'test_steps_per_second': 11.255, 'test_epoch': 8.0}
2025-05-16 02:08:50,405 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:08:50,407 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:08:50,465 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:08:50,466 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:08:50,467 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-56
2025-05-16 02:08:50,947 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.12225854396820068, 'eval_accuracy': 0.9090909090909091, 'eval_precision': 0.9166666666666666, 'eval_recall': 0.9166666666666666, 'eval_f1_score': 0.9166666666666666, 'eval_roc_auc': 0.9916666666666667, 'eval_false_positives_rate': 0.1, 'eval_false_negatives_rate': 0.08333333333333333, 'eval_runtime': 0.2215, 'eval_samples_per_second': 99.307, 'eval_steps_per_second': 9.028, 'epoch': 8.0, 'step': 56}
2025-05-16 02:08:50,949 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 02:08:51,131 - Experiment - INFO - Test metrics: {'test_loss': 0.6583252549171448, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.6428571428571429, 'test_recall': 0.9, 'test_f1_score': 0.75, 'test_roc_auc': 0.9333333333333333, 'test_false_positives_rate': 0.4166666666666667, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.1785, 'test_samples_per_second': 123.281, 'test_steps_per_second': 11.207, 'test_epoch': 8.0}
2025-05-16 02:08:51,156 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:08:51,159 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:08:51,226 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:08:51,227 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:08:51,227 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-56
2025-05-16 02:08:51,724 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.12225854396820068, 'eval_accuracy': 0.9090909090909091, 'eval_precision': 0.9166666666666666, 'eval_recall': 0.9166666666666666, 'eval_f1_score': 0.9166666666666666, 'eval_roc_auc': 0.9916666666666667, 'eval_false_positives_rate': 0.1, 'eval_false_negatives_rate': 0.08333333333333333, 'eval_runtime': 0.2215, 'eval_samples_per_second': 99.307, 'eval_steps_per_second': 9.028, 'epoch': 8.0, 'step': 56}
2025-05-16 02:08:51,725 - Experiment - INFO - Best model found at epoch 8.0.

2025-05-16 02:08:51,904 - Experiment - INFO - Test metrics: {'test_loss': 0.6583252549171448, 'test_accuracy': 0.7272727272727273, 'test_precision': 0.6428571428571429, 'test_recall': 0.9, 'test_f1_score': 0.75, 'test_roc_auc': 0.9333333333333333, 'test_false_positives_rate': 0.4166666666666667, 'test_false_negatives_rate': 0.1, 'test_runtime': 0.1733, 'test_samples_per_second': 126.915, 'test_steps_per_second': 11.538, 'test_epoch': 8.0}
2025-05-16 02:08:51,923 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:08:51,925 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:08:51,987 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:08:51,988 - Experiment - INFO - Finished model evaluations stage.

### Run 3 of 4

2025-05-16 02:08:52,745 - Experiment - INFO - MLflow experiment initialized with ID: 649077292658744800
2025-05-16 02:08:52,746 - Experiment - INFO - Model signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 02:08:52,747 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 02:08:52,748 - Experiment - INFO - Run signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 02:08:53,929 - Experiment - INFO - Run ID: f0db6a2cc3a1406e983f7ba7fd91ed3c
2025-05-16 02:08:53,930 - Experiment - INFO - Run name: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),lemmatization(lc=cs),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)]);2025-05-16_02-08-53;rs=819188777
2025-05-16 02:08:53,945 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:08:53,989 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:08:54,114 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_lemmatization': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001F114B67320>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001F1382B5340>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x000001F1382B5580>, <workspace.sources.local_datasets.preprocessing.cleaning.Lemmatization object at 0x000001F115457A70>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT2_Encoder object at 0x000001F115457650>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:08:54,428 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:08:54,429 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:08:54,430 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:54,450 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:08:54,452 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:54,462 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:08:54,463 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:54,475 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:08:54,475 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:08:54,476 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:54,548 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:08:54,550 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:54,577 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:08:54,577 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:08:54,600 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 02:08:54,601 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:08:54,601 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:54,881 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:08:54,883 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:54,942 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:08:54,944 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:54,993 - Experiment - INFO - Preprocessing function 3: lemmatization
2025-05-16 02:08:54,993 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:08:54,995 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:55,351 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:08:55,354 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:55,418 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:08:55,421 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:08:55,827 - Experiment - INFO - Preprocessing function 4: gpt2__encoder
2025-05-16 02:08:55,828 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:08:55,829 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:08:56,771 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:08:56,772 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:08:57,094 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:08:57,095 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:08:57,795 - Experiment - INFO - Model name: GPT2
2025-05-16 02:08:57,799 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:09:24,790 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:09:24,792 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:09:25,464 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.8597242832183838, 'eval_accuracy': 0.5454545454545454, 'eval_precision': 0.5333333333333333, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.6153846153846154, 'eval_roc_auc': 0.5950413223140496, 'eval_false_positives_rate': 0.6363636363636364, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.9593, 'eval_samples_per_second': 22.933, 'eval_steps_per_second': 2.085, 'epoch': 4.0, 'step': 28}
2025-05-16 02:09:25,466 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:09:25,870 - Experiment - INFO - Test metrics: {'test_loss': 1.2497326135635376, 'test_accuracy': 0.4090909090909091, 'test_precision': 0.5714285714285714, 'test_recall': 0.2857142857142857, 'test_f1_score': 0.38095238095238093, 'test_roc_auc': 0.5, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.7142857142857143, 'test_runtime': 0.3963, 'test_samples_per_second': 55.518, 'test_steps_per_second': 5.047, 'test_epoch': 4.0}
2025-05-16 02:09:25,891 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:09:25,893 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:09:25,958 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:09:25,959 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:09:25,960 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-21
2025-05-16 02:09:26,629 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.80769944190979, 'eval_accuracy': 0.5454545454545454, 'eval_precision': 0.5294117647058824, 'eval_recall': 0.8181818181818182, 'eval_f1_score': 0.6428571428571429, 'eval_roc_auc': 0.578512396694215, 'eval_false_positives_rate': 0.7272727272727273, 'eval_false_negatives_rate': 0.18181818181818182, 'eval_runtime': 0.2173, 'eval_samples_per_second': 101.247, 'eval_steps_per_second': 9.204, 'epoch': 3.0, 'step': 21}
2025-05-16 02:09:26,629 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:09:26,813 - Experiment - INFO - Test metrics: {'test_loss': 0.8824541568756104, 'test_accuracy': 0.4090909090909091, 'test_precision': 0.5454545454545454, 'test_recall': 0.42857142857142855, 'test_f1_score': 0.48, 'test_roc_auc': 0.3660714285714286, 'test_false_positives_rate': 0.625, 'test_false_negatives_rate': 0.5714285714285714, 'test_runtime': 0.1793, 'test_samples_per_second': 122.673, 'test_steps_per_second': 11.152, 'test_epoch': 3.0}
2025-05-16 02:09:26,831 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:09:26,833 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:09:26,897 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:09:26,898 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:09:26,899 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:09:27,380 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.8597242832183838, 'eval_accuracy': 0.5454545454545454, 'eval_precision': 0.5333333333333333, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.6153846153846154, 'eval_roc_auc': 0.5950413223140496, 'eval_false_positives_rate': 0.6363636363636364, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.9593, 'eval_samples_per_second': 22.933, 'eval_steps_per_second': 2.085, 'epoch': 4.0, 'step': 28}
2025-05-16 02:09:27,381 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:09:27,562 - Experiment - INFO - Test metrics: {'test_loss': 1.2497326135635376, 'test_accuracy': 0.4090909090909091, 'test_precision': 0.5714285714285714, 'test_recall': 0.2857142857142857, 'test_f1_score': 0.38095238095238093, 'test_roc_auc': 0.5, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.7142857142857143, 'test_runtime': 0.1778, 'test_samples_per_second': 123.743, 'test_steps_per_second': 11.249, 'test_epoch': 4.0}
2025-05-16 02:09:27,584 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:09:27,586 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:09:27,644 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:09:27,645 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:09:27,646 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-28
2025-05-16 02:09:28,160 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.8597242832183838, 'eval_accuracy': 0.5454545454545454, 'eval_precision': 0.5333333333333333, 'eval_recall': 0.7272727272727273, 'eval_f1_score': 0.6153846153846154, 'eval_roc_auc': 0.5950413223140496, 'eval_false_positives_rate': 0.6363636363636364, 'eval_false_negatives_rate': 0.2727272727272727, 'eval_runtime': 0.9593, 'eval_samples_per_second': 22.933, 'eval_steps_per_second': 2.085, 'epoch': 4.0, 'step': 28}
2025-05-16 02:09:28,162 - Experiment - INFO - Best model found at epoch 4.0.

2025-05-16 02:09:28,342 - Experiment - INFO - Test metrics: {'test_loss': 1.2497326135635376, 'test_accuracy': 0.4090909090909091, 'test_precision': 0.5714285714285714, 'test_recall': 0.2857142857142857, 'test_f1_score': 0.38095238095238093, 'test_roc_auc': 0.5, 'test_false_positives_rate': 0.375, 'test_false_negatives_rate': 0.7142857142857143, 'test_runtime': 0.1763, 'test_samples_per_second': 124.805, 'test_steps_per_second': 11.346, 'test_epoch': 4.0}
2025-05-16 02:09:28,360 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:09:28,362 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:09:28,425 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:09:28,426 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:09:28,427 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-7
2025-05-16 02:09:28,894 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7651664614677429, 'eval_accuracy': 0.45454545454545453, 'eval_precision': 0.4666666666666667, 'eval_recall': 0.6363636363636364, 'eval_f1_score': 0.5384615384615384, 'eval_roc_auc': 0.4214876033057851, 'eval_false_positives_rate': 0.7272727272727273, 'eval_false_negatives_rate': 0.36363636363636365, 'eval_runtime': 0.2076, 'eval_samples_per_second': 105.962, 'eval_steps_per_second': 9.633, 'epoch': 1.0, 'step': 7}
2025-05-16 02:09:28,896 - Experiment - INFO - Best model found at epoch 1.0.

2025-05-16 02:09:29,078 - Experiment - INFO - Test metrics: {'test_loss': 0.8441355228424072, 'test_accuracy': 0.4090909090909091, 'test_precision': 0.5384615384615384, 'test_recall': 0.5, 'test_f1_score': 0.5185185185185185, 'test_roc_auc': 0.2946428571428571, 'test_false_positives_rate': 0.75, 'test_false_negatives_rate': 0.5, 'test_runtime': 0.1775, 'test_samples_per_second': 123.947, 'test_steps_per_second': 11.268, 'test_epoch': 1.0}
2025-05-16 02:09:29,098 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:09:29,099 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:09:29,158 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:09:29,159 - Experiment - INFO - Finished model evaluations stage.

### Run 4 of 4

2025-05-16 02:09:29,910 - Experiment - INFO - MLflow experiment initialized with ID: 649077292658744800
2025-05-16 02:09:29,911 - Experiment - INFO - Model signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none)
2025-05-16 02:09:29,911 - Experiment - INFO - Dataset signature: dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 02:09:29,912 - Experiment - INFO - Run signature: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)])
2025-05-16 02:09:31,116 - Experiment - INFO - Run ID: a5b643c9f57d4ea4ab9203bf3f3671fb
2025-05-16 02:09:31,117 - Experiment - INFO - Run name: model(mn=gpt2,ti=gpt2,mmn=loss,e=10,bs=16,ebs=16,lr=5e-05,ls=linear,wd=0.001,o=adamw_torch,esp=3,est=0.01,pt=none,pti=none);dataset(dn=cz_dataset,tp=0.7,vp=0.15);pipeline([truncation(f=0.15,tt=top),noise_reduction(),nltk_tokenizer(lc=cs),stemming(st=czech_stemmer,lc=cs),gpt2__encoder(t=gpt2,t=true,p=max_length,tml=128,isiw=true,pt=none)]);2025-05-16_02-09-31;rs=3110235756
2025-05-16 02:09:31,130 - Experiment - INFO - {'dataset_name': 'cz_dataset', 'train_pct': 0.7, 'val_pct': 0.15}
2025-05-16 02:09:31,171 - Experiment - INFO - Prepared dataset does not exist, computing from scratch.
2025-05-16 02:09:31,278 - Experiment - INFO - Initializing preprocessing pipeline: <PreprocessingPipeline 'noise_reduction_with_stemming': [<workspace.sources.local_datasets.preprocessing.transformations.Truncation object at 0x000001F114B64890>, <workspace.sources.local_datasets.preprocessing.cleaning.NoiseReduction object at 0x000001F115457CE0>, <workspace.sources.local_datasets.preprocessing.tokenization.NLTKTokenizer object at 0x000001F115457110>, <workspace.sources.local_datasets.preprocessing.cleaning.Stemming object at 0x000001F114B64470>, <workspace.sources.local_datasets.preprocessing.encoders.encoders.GPT2_Encoder object at 0x000001F114B64440>]>
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:09:31,646 - Experiment - INFO - Preprocessing function 0: truncation
2025-05-16 02:09:31,647 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:09:31,648 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:09:31,665 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:09:31,666 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:09:31,676 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:09:31,677 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:09:31,684 - Experiment - INFO - Preprocessing function 1: noise_reduction
2025-05-16 02:09:31,685 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:09:31,686 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:09:31,750 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:09:31,751 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:09:31,777 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:09:31,778 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
[nltk_data] Error loading punkt_pub: Package 'punkt_pub' not found in
[nltk_data]     index
2025-05-16 02:09:31,796 - Experiment - INFO - Preprocessing function 2: nltk_tokenizer
2025-05-16 02:09:31,796 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:09:31,797 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:09:31,962 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:09:31,963 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:09:32,014 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:09:32,014 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
2025-05-16 02:09:32,044 - Experiment - INFO - Preprocessing function 3: stemming
2025-05-16 02:09:32,045 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:09:32,047 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: oCxcRRwKl
warning: skipping word with mixed case: QUAcyLckUj
warning: skipping word with mixed case: GYFPXwFpsp
warning: skipping word with mixed case: UAarmy
warning: skipping word with mixed case: hzeEh
warning: skipping word with mixed case: JsmeArmada
warning: skipping word with mixed case: WeAreNATO
warning: skipping word with mixed case: StandWithUkraine
warning: skipping word with mixed case: uqYSNnbdbD
warning: skipping word with mixed case: ArmadaCR
warning: skipping word with mixed case: DeepL
warning: skipping word with mixed case: SAMů
warning: skipping word with mixed case: FEDu
warning: skipping word with mixed case: EURa
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: McCain
warning: skipping word with mixed case: antiRusko
warning: skipping word with mixed case: JeZeĎáků
warning: skipping word with mixed case: JeZeDáků
warning: skipping word with mixed case: JeZeDák
warning: skipping word with mixed case: JeZeĎák
warning: skipping word with mixed case: JeZeĎáky
warning: skipping word with mixed case: StB
warning: skipping word with mixed case: ZelenskyyUa
warning: skipping word with mixed case: HeidelbergCement
warning: skipping word with mixed case: TOSy
warning: skipping word with mixed case: NordStream
warning: skipping word with mixed case: NordStream
warning: skipping word with mixed case: NordStreamu
warning: skipping word with mixed case: AlJazeera
warning: skipping word with mixed case: PrisonPlanet
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
warning: skipping word with mixed case: JUDr
2025-05-16 02:09:32,199 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:09:32,202 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: xivAtTQk
warning: skipping word with mixed case: iLvIXZMBB
warning: skipping word with mixed case: CzechInvest
warning: skipping word with mixed case: CzechInvest
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: McGregor
warning: skipping word with mixed case: DMcuBPKUj
2025-05-16 02:09:32,251 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:09:32,253 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.
warning: skipping word with mixed case: zGrIFnzC
warning: skipping word with mixed case: McCarthy
warning: skipping word with mixed case: WatchAbrams
warning: skipping word with mixed case: jvbXUwDjc
warning: skipping word with mixed case: iZTdGDa
2025-05-16 02:09:32,616 - Experiment - INFO - Preprocessing function 4: gpt2__encoder
2025-05-16 02:09:32,617 - Experiment - INFO - Preprocessing split: train_set
2025-05-16 02:09:32,618 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:09:33,513 - Experiment - INFO - Preprocessing split: val_set
2025-05-16 02:09:33,516 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:09:33,835 - Experiment - INFO - Preprocessing split: test_set
2025-05-16 02:09:33,837 - Experiment - INFO - Preprocessed data does not exist, computing from scratch.

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

2025-05-16 02:09:34,493 - Experiment - INFO - Model name: GPT2
2025-05-16 02:09:34,497 - Experiment - INFO - Model input hyperparameters: {'epochs': 10, 'batch_size': 16, 'eval_batch_size': 16, 'learning_rate': 5e-05, 'lr_scheduler': 'linear', 'weight_decay': 0.001, 'optimizer': 'adamw_torch', 'early_stopping_patience': 3, 'early_stopping_threshold': 0.01}
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

2025-05-16 02:10:17,004 - Experiment - INFO - Evaluating model using precision metric...
2025-05-16 02:10:17,004 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-42
2025-05-16 02:10:17,620 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9180416464805603, 'eval_accuracy': 0.6363636363636364, 'eval_precision': 0.6, 'eval_recall': 0.8181818181818182, 'eval_f1_score': 0.6923076923076923, 'eval_roc_auc': 0.6363636363636364, 'eval_false_positives_rate': 0.5454545454545454, 'eval_false_negatives_rate': 0.18181818181818182, 'eval_runtime': 0.2105, 'eval_samples_per_second': 104.521, 'eval_steps_per_second': 9.502, 'epoch': 6.0, 'step': 42}
2025-05-16 02:10:17,621 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 02:10:17,878 - Experiment - INFO - Test metrics: {'test_loss': 0.7663020491600037, 'test_accuracy': 0.5, 'test_precision': 0.625, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.6451612903225806, 'test_roc_auc': 0.48571428571428577, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.2532, 'test_samples_per_second': 86.881, 'test_steps_per_second': 7.898, 'test_epoch': 6.0}
2025-05-16 02:10:17,898 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:10:17,901 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:10:17,958 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:10:17,959 - Experiment - INFO - Evaluating model using f1_score metric...
2025-05-16 02:10:17,960 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-21
2025-05-16 02:10:18,456 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7371377348899841, 'eval_accuracy': 0.6363636363636364, 'eval_precision': 0.5789473684210527, 'eval_recall': 1.0, 'eval_f1_score': 0.7333333333333333, 'eval_roc_auc': 0.8016528925619835, 'eval_false_positives_rate': 0.7272727272727273, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2029, 'eval_samples_per_second': 108.41, 'eval_steps_per_second': 9.855, 'epoch': 3.0, 'step': 21}
2025-05-16 02:10:18,457 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:10:18,638 - Experiment - INFO - Test metrics: {'test_loss': 0.7602422833442688, 'test_accuracy': 0.6363636363636364, 'test_precision': 0.6842105263157895, 'test_recall': 0.8666666666666667, 'test_f1_score': 0.7647058823529411, 'test_roc_auc': 0.4761904761904762, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.13333333333333333, 'test_runtime': 0.1757, 'test_samples_per_second': 125.205, 'test_steps_per_second': 11.382, 'test_epoch': 3.0}
2025-05-16 02:10:18,654 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:10:18,656 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:10:18,715 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:10:18,716 - Experiment - INFO - Evaluating model using false_positives_rate metric...
2025-05-16 02:10:18,717 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-42
2025-05-16 02:10:19,217 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.9180416464805603, 'eval_accuracy': 0.6363636363636364, 'eval_precision': 0.6, 'eval_recall': 0.8181818181818182, 'eval_f1_score': 0.6923076923076923, 'eval_roc_auc': 0.6363636363636364, 'eval_false_positives_rate': 0.5454545454545454, 'eval_false_negatives_rate': 0.18181818181818182, 'eval_runtime': 0.2105, 'eval_samples_per_second': 104.521, 'eval_steps_per_second': 9.502, 'epoch': 6.0, 'step': 42}
2025-05-16 02:10:19,218 - Experiment - INFO - Best model found at epoch 6.0.

2025-05-16 02:10:19,409 - Experiment - INFO - Test metrics: {'test_loss': 0.7663020491600037, 'test_accuracy': 0.5, 'test_precision': 0.625, 'test_recall': 0.6666666666666666, 'test_f1_score': 0.6451612903225806, 'test_roc_auc': 0.48571428571428577, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.3333333333333333, 'test_runtime': 0.1863, 'test_samples_per_second': 118.065, 'test_steps_per_second': 10.733, 'test_epoch': 6.0}
2025-05-16 02:10:19,424 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:10:19,426 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:10:19,483 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:10:19,484 - Experiment - INFO - Evaluating model using roc_auc metric...
2025-05-16 02:10:19,484 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-21
2025-05-16 02:10:20,005 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7371377348899841, 'eval_accuracy': 0.6363636363636364, 'eval_precision': 0.5789473684210527, 'eval_recall': 1.0, 'eval_f1_score': 0.7333333333333333, 'eval_roc_auc': 0.8016528925619835, 'eval_false_positives_rate': 0.7272727272727273, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2029, 'eval_samples_per_second': 108.41, 'eval_steps_per_second': 9.855, 'epoch': 3.0, 'step': 21}
2025-05-16 02:10:20,006 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:10:20,195 - Experiment - INFO - Test metrics: {'test_loss': 0.7602422833442688, 'test_accuracy': 0.6363636363636364, 'test_precision': 0.6842105263157895, 'test_recall': 0.8666666666666667, 'test_f1_score': 0.7647058823529411, 'test_roc_auc': 0.4761904761904762, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.13333333333333333, 'test_runtime': 0.1851, 'test_samples_per_second': 118.841, 'test_steps_per_second': 10.804, 'test_epoch': 3.0}
2025-05-16 02:10:20,214 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:10:20,216 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:10:20,271 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:10:20,272 - Experiment - INFO - Evaluating model using loss metric...
2025-05-16 02:10:20,273 - Experiment - INFO - Found checkpoint with best metrics at: checkpoint-21
2025-05-16 02:10:20,802 - Experiment - INFO - Best entry according to validation metrics: {'eval_loss': 0.7371377348899841, 'eval_accuracy': 0.6363636363636364, 'eval_precision': 0.5789473684210527, 'eval_recall': 1.0, 'eval_f1_score': 0.7333333333333333, 'eval_roc_auc': 0.8016528925619835, 'eval_false_positives_rate': 0.7272727272727273, 'eval_false_negatives_rate': 0.0, 'eval_runtime': 0.2029, 'eval_samples_per_second': 108.41, 'eval_steps_per_second': 9.855, 'epoch': 3.0, 'step': 21}
2025-05-16 02:10:20,804 - Experiment - INFO - Best model found at epoch 3.0.

2025-05-16 02:10:21,003 - Experiment - INFO - Test metrics: {'test_loss': 0.7602422833442688, 'test_accuracy': 0.6363636363636364, 'test_precision': 0.6842105263157895, 'test_recall': 0.8666666666666667, 'test_f1_score': 0.7647058823529411, 'test_roc_auc': 0.4761904761904762, 'test_false_positives_rate': 0.8571428571428571, 'test_false_negatives_rate': 0.13333333333333333, 'test_runtime': 0.1909, 'test_samples_per_second': 115.233, 'test_steps_per_second': 10.476, 'test_epoch': 3.0}
2025-05-16 02:10:21,030 - Experiment - INFO - Saving evaluation data in pickle...
2025-05-16 02:10:21,033 - Experiment - INFO - Saving evaluation data in json...
2025-05-16 02:10:21,109 - Experiment - INFO - Successfully saved evaluation data.
2025-05-16 02:10:21,114 - Experiment - INFO - Finished model evaluations stage.